### ISSUE TITLE
Docker socket is not readable by the www-data user.

### ISSUE THREAD

**Issue by pestotoast** [nextcloud/all-in-one#10]
The container does not start if the docker group does not have the expected group id. This is what I did:

```
sudo docker run -it --name nextcloud-aio-mastercontainer --restart always -p 80:80 -p 8080:8080 -p 8443:8443 --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock:ro nextcloud/all-in-one:latest
Unable to find image 'nextcloud/all-in-one:latest' locally
latest: Pulling from nextcloud/all-in-one
eff15d958d66: Pull complete 
933427dc39f7: Pull complete 
35bb08dc7ee2: Pull complete 
58a3f26800d7: Pull complete 
bba5c0e912ac: Pull complete 
62e5c0d120c5: Pull complete 
410a26230a3b: Pull complete 
cfd99187016c: Pull complete 
c32ab7d5171e: Pull complete 
0d32eb2980c3: Pull complete 
991f816a61cc: Pull complete 
c8667ca62702: Pull complete 
6405e507a13e: Pull complete 
108fd50a39c4: Pull complete 
a4802c6a0ae4: Pull complete 
4f4fb700ef54: Pull complete 
ed2a8c5d896a: Pull complete 
918f8b879784: Pull complete 
ef811a9a19da: Pull complete 
5957cd578fac: Pull complete 
16271f6bc746: Pull complete 
1fad265ca45b: Pull complete 
d3cff4a42d6b: Pull complete 
ed82917488d5: Pull complete 
e306f9b356b0: Pull complete 
71afc1271985: Pull complete 
0ec4a207d9fd: Pull complete 
891138b323b3: Pull complete 
9ba4b052261a: Pull complete 
df2f9d124a4f: Pull complete 
48b90860d7f8: Pull complete 
2ae887bcd224: Pull complete 
2283bd5bb2d5: Pull complete 
Digest: sha256:9a47ed4b666f74027d710490ae1fac5a078275d2516ce8e671046cb2337fb88b
Status: Downloaded newer image for nextcloud/all-in-one:latest
Docker socket is not readable by the www-data user. Cannot continue.
```
After checking out the source code I found that the docker group id is explicitly specified in the [Dockerfile](https://github.com/nextcloud/all-in-one/blob/3f672595ea8705d391aafcf78efe87bde991f45d/Containers/mastercontainer/Dockerfile#L79). This id has to match the docker group id of the host system otherwise we can't control the docker from with the container.

I was able to resolve the issue on my system by changing the id of my docker group with: `sudo groupmod -g 998 docker` but it probably should be fixed in the image.

**Comment by szaimen** [comment]
Thanks for your report!

So the problem here is that the docker groupid of the docker group inside the container needs to match the groupid of the docker group outside the container and that we don't run any script after the creation as root user which you can see here:
https://github.com/nextcloud/all-in-one/blob/3f672595ea8705d391aafcf78efe87bde991f45d/Containers/mastercontainer/Dockerfile#L85
hence we are not able to change the groupid of the docker group inside the container after its creation (during the entrypoint or afterwards). Hence this check ist correct.

Also in my testing it was always using the groupid 998 when installing docker via `curl -fsSL get.docker.com | sudo sh` so you probably installed docker a bit differently?

I'll leave this issue open for now so that we can see if other users experience this issue as well. If yes, we'll probably need to think about solutions to make this work also if the groupids don't match.

**Comment by majst01** [comment]
Same here, host ubuntu-21.10, docker installed as explained at docker.com

**Comment by szaimen** [comment]
Hi, as I've said there is not much we can do here but I improved the documentation in #13 so that the instructions are more clear.
See https://github.com/nextcloud/all-in-one/blob/fix/9%2Ffix-credential-screen/readme.md#how-to-use-this

**Comment by majst01** [comment]
OK, but this will make things hard to deploy it to kubernetes.

**Comment by thiphariel** [comment]
Hello. Got the same issue as @majst01, docker installed as explained on [docker.com](https://docs.docker.com/engine/install/debian), and use docker compose v2 (I'm on Debian 11).

If i look the ownership of the docker.sock, it seems owned by `root:docker` 

<img width="487" alt="image" src="https://user-images.githubusercontent.com/3125705/144205944-2c9d3cde-db52-4baf-9e57-ce046c8f92c3.png">

Is that ok ? I always installed docker like that so I'm little confused if I need to do something else ahah

Any clue of what's happening here ?

Thanks

**Comment by jakejoh** [comment]
unfortunately, this doesn't work on Synology. AFAIK there is no way to way to alter group ids, so you're stuck with whatever id you get when creating the docker group (it's not created automatically, see e.g. https://www.synoforum.com/threads/permissions-for-user-to-run-docker.3536/#post-16480)

**Comment by szaimen** [comment]
I'll reopen this to see if there are further users with permission problems

**Comment by CryoByte33** [comment]
I also have this issue running AlmaLinux (CentOS replacement). My docker group is GUID 990, not 998 and I'm getting the same "Docker socket is not readable by the www-data user. Cannot continue." error. Something of note is that I don't actually have the www-data user at all as this was a minimal install and I use Docker for all my services.

**Comment by szaimen** [comment]
Thanks for your feedback! We'll fix it with #13
For now you should be able to workaround this by running the following command:
`sudo groupmod -g 998 docker`

**Comment by gdiciancia** [comment]
It is good to have a workaround, but Fedora server already has a standard user with group 998, so changing the group ID is not working. The workaround also requires changing the group ownership of the docker socket to 998 (otherwise it keeps pointing to the original group ID)

**Comment by ThierryBegin** [comment]
Same issue here, Using Linux Mint. 
`sudo groupmod -g 998 docker`
gives me a  `groupmod: GID '998' already exists`

**Comment by CryoByte33** [comment]
Same here, I even attempted to change the existing user in 998 and put docker there, but it didn't work and gave me the same error.

**Comment by MikeK123** [comment]
Same here.

**Comment by Timmmy** [comment]
Same issue on synology

**Comment by szaimen** [comment]
> Same here on Synology

did you pull the latest image?

**Comment by szaimen** [comment]
sudo docker pull nextcloud/all-in-one:latest

**Comment by pestotoast** [comment]
> docker pull nextcloud/all-in-one:latest

The latest tag is not updated yet. Only `nextcloud/all-in-one:development` includes the fix at the moment.

**Comment by szaimen** [comment]
Are you sure? I actually updated the latest tag 6 hours ago and pushed the change to latest...
See https://hub.docker.com/r/nextcloud/all-in-one/tags

**Comment by pestotoast** [comment]
Oh my bad, I checked the wrong image..

**Comment by Timmmy** [comment]
Unfortunately still no luck on Synology (localhost works fine)
Image update: 2021-12-03 15:37:09 (CET)

```
sudo docker run -it --name nextcloud-aio-mastercontainer2 --restart always -p 81:80 -p 8080:8080 -p 84
43:8443 --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock
:ro nextcloud/all-in-one:latest
Trying to fix docker.sock permissions internally...
groupadd: GID '0' already exists
Docker socket is not readable by the www-data user. Cannot continue.
```

**Comment by szaimen** [comment]
I see. Thanks for the heads up!

**Comment by Timmmy** [comment]
Found a workaround for the Synology permission issue, added to FAQ in pull request: `https://github.com/nextcloud/all-in-one/pull/51`

**Comment by szaimen** [comment]
Hi, for all people that still had problems with this issue. It should be fixed now.
Please try to pull the latest image and run the `docker run ...` command aftewards again.
Feel free to report back if there are still issues with this. Thanks!
