### ISSUE TITLE
Add a texteditor into Nextcloud container

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#101]
How can the nextcloud config file be edited? or under which path is it located?

**Comment by szaimen** [comment]
Hello, it is by default stored here: https://github.com/nextcloud/all-in-one/blob/892590275f5822ba8ad394e463aef1fb5475256d/Containers/nextcloud/entrypoint.sh#L146

Do you think we should document this in the readme?

**Comment by R7JANV1** [comment]
That didn't work, I'm looking for a solution to edit the nextcloud config file using nono editor.

**Comment by szaimen** [comment]
oh, I didn't read the description properly. It is stored here: `/var/www/html/config/config.php`

**Comment by szaimen** [comment]
you can edit it using the vi editor: https://www.tutorialspoint.com/unix/unix-vi-editor.htm

**Comment by szaimen** [comment]
but better is using the occ command:
```
sudo docker exec -it nextcloud-aio-nextcloud php occ config:system:set configidentifier --value="yourvalue"
```

**Comment by R7JANV1** [comment]
When I enter this command (sudo docker exec -it nextcloud-aio-nextcloud vi /var/www/html/config/config.php), I get the following response: OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "vi": executable file not found in $PATH: unknown

**Comment by R7JANV1** [comment]
I need a simple solution to be able to edit the config of Nextcloud that would be great

**Comment by szaimen** [comment]
You are right. just tried to open a texteditor and seems like no one is installed in the container currently.
We are going to fix that soon.

For now you can use the following: 
```
sudo docker exec --user root -it nextcloud-aio-nextcloud bash
apt update && apt install nano
exit
sudo docker exec -it nextcloud-aio-nextcloud nano /var/www/html/config/config.php
```
