### ISSUE TITLE
Suggestion: Fallback to default port 3478 if TALK_PORT envvar is not set

### ISSUE THREAD

**Issue by flortsch** [nextcloud/all-in-one#1011]
Currently, the start.sh script in the Talk container generates an invalid janus config, if the TALK_PORT envvar is not set. This results in the janus process not starting within the container. I suggest to fallback to default port 3478, if this envvar is not set. This would also increase compatibility with older setups, where setting the TALK_PORT was not required.

Edit: the start.sh exits with error code 1 if e.g. NC_DOMAIN or other envvars are not set. If no default talk port is used, a check for TALK_PORT should also be included here.

**Comment by szaimen** [comment]
We actually have fallback in place: https://github.com/nextcloud/all-in-one/blob/177e115b2bc5d180a06cfcba2e82811ed1e0aed2/php/src/Data/ConfigurationManager.php#L398-L403

Why do you need a fallback inside the container?

**Comment by flortsch** [comment]
I have a setup of Nextcloud that I configured before the all-in-one suite existed. So I am using the official Docker Nextcloud container in combination with a standalone Talk container of the all-in-one-suite. The last update that added the TALK_PORT envvar broke my setup, because I didn't have it set and the container used a fixed port back then. This might not be a supported setup, but I thought I would report this here as a suggestion. Perhaps others have a similar setup, and when they update they will encounter the same problem.

**Comment by szaimen** [comment]
I see. This is indeed not a supported setup. However I am willing to accept a PR that adds this check if you create it.

**Comment by szaimen** [comment]
This is now fixed with v2.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
