### ISSUE TITLE
Improve update instructions

### ISSUE THREAD

**Issue by TheNomad11** [nextcloud/all-in-one#102]
In the readme it says:

> If we push new containers to latest, you will see in the AIO interface below the containers section that new container updates were found. In this case, just press Stop containers and Start containers in order to update the containers. 

In the AIO interface it also says:

> Updates are available. Stop your containers and restart them to apply the update.

But below there is also a button:

> A new mastercontainer is available. Please click on the button below to update it.

So what is the correct procedure here: Do  we need to press the button or not - and when? 

On the basis of what I have learned so far - I am no sysadmin - by logic the procedure would be:

1. Stop the containers
2. Press update button
3. Start the containers

Am I right? 

In any case, the instructions should be revised, I think

**Comment by szaimen** [comment]
No, the update instructions are correct. All containers except the mastercontainer get updated by simply clickling on `stop containers` and then `start containers`. The mastercontainer is updated with a different procedure though and has its own update button. 

What is your idea how we could improve the documentation regarding this?

**Comment by TheNomad11** [comment]
> No, the update instructions are correct. All containers except the mastercontainer get updated by simply clickling on `stop containers` and then `start containers`. The mastercontainer is updated with a different procedure though and has its own update button.
> 
> What is your idea how we could improve the documentation regarding this?

That was clearer. Thanks! That was a perfect explanation, maybe write something like this, especially in the AIO interface

**Comment by szaimen** [comment]
Thanks, I will have a look then how to improve this.
