### ISSUE TITLE
with NC25 it will be possible to add fonts to Nextcloud Office. Add a volume for this

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1032]
implemented by https://github.com/nextcloud/richdocuments/pull/2032,

a volume should be added to /opt/cool/systemplate/tmpfonts inside the collabora container

**Comment by karlemilnikka** [comment]
Do you, @szaimen, know if there are any similar plans regarding support for custom dictionaries? Currently, it seems like users cannot add new words to a dictionary of their own in Nextcloud Office.

**Comment by szaimen** [comment]
> Do you, @szaimen, know if there are any similar plans regarding support for custom dictionaries? Currently, it seems like users cannot add new words to a dictionary of their own in Nextcloud Office.

No idea, sry!

**Comment by szaimen** [comment]
> This will work with OnlyOffice too?

No

**Comment by szaimen** [comment]
This is now released with v4.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
