### ISSUE TITLE
Feature Req: Add Elasticsearch container for Full Text Search

### ISSUE THREAD

**Issue by revr3nd** [nextcloud/all-in-one#1036]
Elasticsearch is used by the Full Text Search addon and is extremely useful to provide content searching.
Given that Elastic search is already easily run within Docker, I think it's a fairly easy container app to add to the list for integration with Nextcloud AIO in single node setups.

The custom docker files make Elasticsearch deployment even easier as it does require an additional plugin to be installed, which requires an additional docker file command to run: '/usr/share/elasticsearch/bin/elasticsearch-plugin install --batch ingest-attachment'

I am currently running elasticsearch alongside the AIO deployment with:
1. docker run -d --name elasticsearch --net nextcloud-aio -p 9200:9200 -e "discovery.type=single-node" elasticsearch:7.17.5
2. docker exec -t elasticsearch /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch ingest-attachment
3. Open Nextcloud and install the Full text search - Elasticsearch Platform Addon
4. Open Nextcloud settings, under Full Test search, enable Elasticsearch as the search platform, servlet address, and index name

**Comment by szaimen** [comment]
Hey, thanks for the suggestion! 
Just two small questions:
- do you know if it works with elastisearch 8 as well?
- which directory contains the elastisearch cache and should be made persistant?

**Comment by Z0ey2022** [comment]
>     * do you know if it works with elastisearch 8 as well?

https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/178

**Comment by Z0ey2022** [comment]
>     * which directory contains the elastisearch cache and should be made persistant?

If I have read correctly, its `/usr/share/elasticsearch/data`

**Comment by revr3nd** [comment]
Ok, I had to go into the wayback on how this worked as it had been a long time since I had set this up. There actually does need to be a command that is run on startup every reboot in order to ensure the indexing continues indefinitely. The Fulltextsearch docs gives a better breakdown of what is required here: https://github.com/nextcloud/fulltextsearch/wiki/Basic-Installation

1. Create elasticsearch container: docker run -d --name elasticsearch --net nextcloud-aio -p 9200:9200 -e "discovery.type=single-node" -v esdata:/usr/share/elasticsearch/data elasticsearch:7.17.5
2. Install ingest plugin: docker exec -t elasticsearch /usr/share/elasticsearch/bin/elasticsearch-plugin install --batch ingest-attachment
3. Install the following addons in Nextcloud
    - Full text search
    - Full text search - Files
    - Full text search - Elasticsearch Platform
4. Setup Full text search in the Nextcloud Admin page
5. Run live indexer (normally a systemd service), must be run every reboot: docker exec -d --user www-data nextcloud-aio-nextcloud /usr/local/bin/php /var/www/html/occ fulltextsearch:live -q

The fulltextsearch addon can be configured via json string as well with the occ fulltextsearch:configure {$JSON} command, but I dont see what the syntax should be.

I'm sure some of this could be optimized to run better than by manual intervention, but I am sadly not that good at docker to figure it out. Items that would be optimized is host file references to the elasticsearch container, and auto configure the addon

**Comment by szaimen** [comment]
Thanks, we'll fogure it out!

**Comment by revr3nd** [comment]
Oh last comment, I did update my elasticsearch container run with a memory limit to prevent too much memory utilization. Mine runs with a 2GB limit with the '-m 2g' on the docker run command

**Comment by Z0ey2022** [comment]
Another question is `-p 9200:9200` needed? Since the cloud could connect internally to the elastic search container? Or does the web browser of the user also connect to elastic search?

**Comment by szaimen** [comment]
It is indeed not needed 👍

**Comment by revr3nd** [comment]
Correct, port 9200 is not needed for any reason outside the bridge. All communication is between the nextcloud and the elasticsearch containers

**Comment by Z0ey2022** [comment]
But just a small question, what is the different between these three apps:
- Full text search
- Full text search - Files
- Full text search - Elasticsearch Platform

And this app: https://github.com/nextcloud/files_fulltextsearch_tesseract ?

**Comment by revr3nd** [comment]
See below for more context of each addon, based on the wiki here: https://github.com/nextcloud/fulltextsearch/wiki
- Full text search - Base addon providing the settings page and search function integration
- Full text search - Files - Provider app that identifies files to be fed to the indexer
- Full text search - Elasticsearch Platform - Platform app that performs the indexing

Regarding tesseract, it looks like this provides OCR functionality to provide reading of text within an image. Examples here would be scanned documents stored as a jpg or image-based pdf. I honestly haven't used it.
Looking at the nextcloud addon documentation and some container images, tesseract doesn't run as a daemon with a socket or network port, and is instead an executable called on demand by nextcloud's php when it sees a file it wants to OCR. I'm not sure tesseract would be an easy option to integrate unless you maintain tesseract as a built in app on the nextcloud container.

**Comment by szaimen** [comment]
We will not add the OCR functionality in the first implementation.

**Comment by szaimen** [comment]
This is now released with v2.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by Aceriz** [comment]
very excited to see this come to the stable branch in the future :)
