### ISSUE TITLE
Collabora issue with IPv6

### ISSUE THREAD

**Issue by karlemilnikka** [nextcloud/all-in-one#1047]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

1. Install Nextcloud AIO on an x86 Ubuntu 22.04 VPS according to the official documentation.  
2. Enable IPv6 support by editing the daemon.json file.
3. Select Collabora as the office suite when asked. 
4. Finish setting up an admin account. Shutdown the containers and restart the server. 
5. Start the containers, log in as admin and try to open a document in Collabora (e.g., the Welcome to Nextcloud Hub document). 

### Expected behavior 

Collabora should load the document. 

### Actual behavior 

When I install Nextcloud AIO on a demo VPS without enabling IPv6 support for Docker, everything works fine. When I do exactly the same install with IPv6 support enabled for Docker, Nextcloud AIO installs without errors, and I can edit documents in Collabora for a while. As soon as I restart the server for the first time however, Collabora stops working. 

This is not an issue when choosing OnlyOffice instead of Collabora. The OnlyOffice server works as intended, even after restarting the server, regardless of whether or not IPv6 support is enabled.

### Host OS 
Ubuntu 22.04 x86

#### Nextcloud AIO version 

Tested on Nextcloud AIO 1.7.0 and Nextcloud AIO 1.7.1.

#### Current channel 

Latest channel.

#### Other valuable info 

I have attached two log files from the Collabora container. The first one is from Collabora starting up after a server reboot. The second one is from trying to open a document after server reboot. The demo server which the logs are from is no longer running. 

[collabora-log-01-start-after-reboot.txt](https://github.com/nextcloud/all-in-one/files/9396992/collabora-log-01-start-after-reboot.txt)

[collabora-log-02-open-document-after-reboo.txt](https://github.com/nextcloud/all-in-one/files/9396991/collabora-log-02-open-document-after-reboo.txt)

<img width="1339" alt="Nextcloud says that document loading failed." src="https://user-images.githubusercontent.com/20514810/186000689-adb55c01-8b32-4f4f-bdea-9e91772c3f07.png">

**Comment by szaimen** [comment]
I fear this needs to be reported to the collabora repo. Can you please open an issue here: https://github.com/CollaboraOnline/online/issues
Thank you!

**Comment by karlemilnikka** [comment]
I retested the install today using Nextcloud AIO 2.0.1. Everything works as intended now.
