### ISSUE TITLE
Feature Request: Add path Volume possibility

### ISSUE THREAD

**Issue by david-steg** [nextcloud/all-in-one#105]
Hello
By creating a aio Docker-compose instance I have found that local Volume like "./data" doesn't work properly on the Container. Ich will receive this Error: https://github.com/nextcloud/all-in-one/issues/100.
But if I use the Docker Volumes, it work just fine.

I would find usefull to have a better controll about the config, db files.

Thanks

**Comment by szaimen** [comment]
Sry but we are not going to add this functionality. 
You can move the docker library to a custom path, though. See https://github.com/nextcloud/all-in-one#how-to-store-the-filesinstallation-on-a-separate-drive
