### ISSUE TITLE
Outdated disclaimer

### ISSUE THREAD

**Issue by bottycode** [nextcloud/all-in-one#1054]
https://github.com/nextcloud/all-in-one/blob/7af4c3a2ecc7955082ddaab60ed3413c62eeb62f/reverse-proxy.md?plain=1#L144

Since all of the three issues are closed (and fixed as it looks like), could you remove this disclaimer?

**Comment by szaimen** [comment]
Hey, feel free to submit to do the changes on https://github.com/nextcloud/all-in-one/edit/main/reverse-proxy.md and submit a PR. Thanks!

**Comment by szaimen** [comment]
done with https://github.com/nextcloud/all-in-one/commit/ed82a41bc1ce5caeeb979fe752addd4e478fff86
