### ISSUE TITLE
Triggering the daily backup from a script externally does not work

### ISSUE THREAD

**Issue by gadric** [nextcloud/all-in-one#1067]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Connect to server via ssh
2. in bash use `sudo docker exec -it nextcloud-aio-mastercontainer DAILY_BACKUP=1 /daily-backup.sh`

### Expected behavior 

Backup should start und backup everything

### Actual behavior 

Bash output gives the following error: 

```
OCI runtime exec failed: exec failed: unable to start container process: exec: "DAILY_BACKUP=1": executable file not found in $PATH: unknown
```

I also tried: `root@styx:/srv# docker exec -it nextcloud-aio-mastercontainer /daily-backup.sh DAILY_BACKUP=1`
It shows that the backup has started, however it finishs after 1 sec. and the backup is not created. 

### Host OS 
Debian 11.4

#### Nextcloud AIO version 
1.7.1

#### Current channel 
latest channel

**Comment by Zoey2936** [comment]
Try 
`sudo docker exec -it -e DAILY_BACKUP=1nextcloud-aio-mastercontainer /daily-backup.sh`

**Comment by szaimen** [comment]
Thanks, yes that is the correct syntax. will correct this.

**Comment by szaimen** [comment]
fixed with https://github.com/nextcloud/all-in-one/commit/34d5ee62989c33e9c241b0b58fe3c0c41999db04

**Comment by gadric** [comment]
that works. 

However, although the backup finishs, in the middle there is the following error: 

```
# docker exec -it -e DAILY_BACKUP=1 -e START_CONTAINERS=1 nextcloud-aio-mastercontainer /daily-backup.sh
Daily backup has started
Not pulling the latest database image because the container was not correctly shut down.
Waiting for the Nextcloud container to start
Waiting for the Nextcloud container to start
Daily backup has finished
```

**Comment by szaimen** [comment]
Thanks for reporting. Will be fixed with https://github.com/nextcloud/all-in-one/pull/1069

**Comment by gadric** [comment]
Nice thanks. 

one more thing, if starting the command from a remote machine, the command needs to be slightly changed: 

```
docker exec -i -e DAILY_BACKUP=1 -e START_CONTAINERS=1 nextcloud-aio-mastercontainer /daily-backup.sh
```

the `t` needs to be removed from the `-it`. Otherwise it ends with `the input device is not a TTY`
