### ISSUE TITLE
Containers fail on starting v1.7.1

### ISSUE THREAD

**Issue by willyamcts** [nextcloud/all-in-one#1070]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Follow steps in README this repository, run "docker run ..."
2. Visit page starting in port 8080 to the containers status page

### Expected behavior 
Containers installed successfuly and page status all containers "OK"

### Actual behavior 
In page status container Apache and Nextcloud stay status "Starting"

In container nextcloud-aio-nextcloud:
```
Next OC\DB\Exceptions\DbalException: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "nextcloud-aio-database" (172.19.0.5), port 5432 failed: FATAL:  password authentication failed for user "oc_nextcloud" in /var/www/html/lib/private/DB/Exceptions/DbalException.php:71
Stack trace:
#0 /var/www/html/lib/private/DB/ConnectionAdapter.php(59): OC\DB\Exceptions\DbalException::wrap(Object(Doctrine\DBAL\Exception))
#1 /var/www/html/lib/private/legacy/OC_DB.php(55): OC\DB\ConnectionAdapter->prepare('SHOW SERVER_VER...', NULL, NULL)
#2 /var/www/html/lib/private/legacy/OC_DB.php(128): OC_DB::prepare('SHOW SERVER_VER...', NULL, NULL)
#3 /var/www/html/lib/private/legacy/OC_Util.php(759): OC_DB::executeAudited(Array)
#4 /var/www/html/lib/private/legacy/OC_Util.php(739): OC_Util::checkDatabaseVersion()
#5 /var/www/html/lib/private/Console/Application.php(157): OC_Util::checkServer(Object(OC\SystemConfig))
#6 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/occ(11): require_once('/var/www/html/c...')
#8 {main}installing of nextcloud failed!
Waiting for the database to start...
psql: error: connection to server at "nextcloud-aio-database" (172.19.0.5), port 5432 failed: FATAL:  password authentication failed for user "oc_nextcloud"
Waiting for the database to start...
```

in container nextcloud-aio-database:
```
2022-08-25 23:42:33.359 UTC [38] FATAL:  password authentication failed for user "oc_nextcloud"
2022-08-25 23:42:33.359 UTC [38] DETAIL:  Role "oc_nextcloud" does not exist.
        Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
```

### Host OS 
Debian 11

#### Nextcloud AIO version 
Last release 1.7.1

#### Current channel 
Latest

#### Others
Same problem reported in issue #1000

**Comment by szaimen** [comment]
Sorry but I cannot reproduce this. Please reset your instance properly by following https://github.com/nextcloud/all-in-one#how-to-properly-reset-the-instance and try again.
