### ISSUE TITLE
AIO version id

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#108]
I find that a version number for AIO would be useful to know if the version is up to date.

**Comment by szaimen** [comment]
Hi, where should we add that version number in your opinion? in the AIO interface or elsewhere? 
Honestly, I am  a bit unsure about this because as written in the readme, all Nextcloud admins get a notification as soon as a new update is found. Otherwise just open the interface regularly which will also tell if an update is available.

**Comment by marcatsmci** [comment]
Any piece of software need an version id, I think. It's a comforting point when you can see the current version at a glance and without deep finding.
On my point of view, Nextcloud version is different from AIO version and need to remain different.
As an admin, I get Nextcloud updates notification, so no need to open the interface periodically to know the status of my installation. Would be nice if AOI acts the same way, based upon version id.

**Comment by szaimen** [comment]
We actually send a notification to all nextcloud admins if a new container or mastercontainer was found. See https://github.com/nextcloud/all-in-one/blob/ca5da1c5bbefc94fc289afa3a0d9e98c251e29e9/php/src/Cron/cron.php#L24-L29
Is this not enough?

Additionally, we show it in the aio interface. See https://github.com/nextcloud/all-in-one#how-to-update-the-containers or https://github.com/nextcloud/all-in-one/issues/102#issuecomment-1007969901

**Comment by marcatsmci** [comment]
Just to finish this discussion, after you do as you want ;-)

- Nextcloud : 23.0.1
- Nextcloud Desktop : 3.4.1
- Gitea : 1.18.9
- Linux kernel : 5.15.13-arch-1
- PHP : 8.1
- MariaDB : 10.6.5
- LibreOffice : 7.2.5-4
- AIO : ???????

**Comment by szaimen** [comment]
Fine by me then. Will have a look how to implement this.

**Comment by marcatsmci** [comment]
One more idea : when a mastercomnainer update is available, put the version # in the message

**Mastercontainer update**
⚠ A mastercontainer update is available (new version : v0.3.0). Please click on the button below to update it. All other containers get updated independently from the mastercontainer by simply clicking on `Stop containers` and clicking on `Start containers` if a new update is available.

**Comment by marcatsmci** [comment]
Same proposition for the notifications
