### ISSUE TITLE
Maintenance mode after PHP memory exhausted

### ISSUE THREAD

**Issue by aleliga** [nextcloud/all-in-one#1090]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Deployed by DigitalOcean marketplace
2. Upload a file of 1 GB
3. Exhaustion in `/var/lib/docker/volumes/nextcloud_aio_nextcloud/_data/data/nextcloud.log`
    ```yaml
    {"reqId":"Ekx1b4vlVyT9t9QlICY4","level":3,"time":"2022-08-10T00:01:47+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 400564224 bytes) at /var/www/html/3rdparty/guzzlehttp/psr7/src/Stream.php#247","userAgent":"--","version":"24.0.3.2","data":{"app":"PHP"}}
    ```
4. Interface show `Errore durante l'assemblaggio dei blocchi, codice di stato 500`

### Host OS 

- Ubuntu 20.04.4 LTS
- Docker version 20.10.17, build 100c701
- Docker images
    ```bash
    # docker images
    REPOSITORY                  TAG       IMAGE ID       CREATED        SIZE
    nextcloud/aio-nextcloud     latest    b73fc7d592a8   12 days ago    1.13GB
    nextcloud/all-in-one        latest    179703f14c67   12 days ago    688MB
    nextcloud/aio-talk          latest    b1f702716475   12 days ago    494MB
    nextcloud/aio-collabora     latest    7e015eb19abe   12 days ago    1.53GB
    nextcloud/aio-apache        latest    1450639e0b5d   12 days ago    262MB
    nextcloud/aio-redis         latest    0b765682118c   12 days ago    28.4MB
    nextcloud/aio-watchtower    latest    07f93392c805   12 days ago    23.3MB
    nextcloud/aio-postgresql    latest    7be223dfd807   12 days ago    220MB
    nextcloud/aio-borgbackup    latest    8ccd87cf4986   12 days ago    116MB
    nextcloud/aio-domaincheck   latest    7030bbf08ea9   3 months ago   12.2MB
    ```
- [docker inspect container](https://github.com/nextcloud/all-in-one/files/9451044/docker-inspect-container-nextcloud-aio-nextcloud.txt)
- [docker inspect image](https://github.com/nextcloud/all-in-one/files/9451048/docker-inspect-image-nextcloud_all-in-one.txt)

#### Nextcloud AIO version 

Nextcloud AIO v1.7.1

#### Current channel 

Latest

#### Other valuable info 

- DigitalOcean Object storage

    ```yaml
     array (
         'class' => '\\OC\\Files\\ObjectStore\\S3',
         'arguments' => 
         array (
           'bucket' => '',
           'key' => '',
           'secret' => '',
           'hostname' => 'ams3.digitaloceanspaces.com',
           'region' => 'ams3',
           'port' => 443,
           'use_ssl' => true,
           'use_path_style' => true,
         ),
     ),
   ```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
