### ISSUE TITLE
latest-arm64 cant't boot up! encountering with nextcloud container cant not access database because password wrong!

### ISSUE THREAD

**Issue by IceDerce** [nextcloud/all-in-one#1122]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. docker info 20.10.7
2. linux version ubuntu 20.04 with kernetl 5.15
3. arm64 arch (spec Oracle Armpre virtual machine!)

### Expected behavior 

using ofiicical guide to boot exectly like below:

`sudo docker run \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 80:80 \
--publish 19080:8080 \
--publish 8443:8443 \
--volume nextcloud_aio_mastercontainer:/etc/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
nextcloud/all-in-one:latest-arm64`

### Actual behavior 

can acess the controll web interface, but cant boot up completely!

container nextcloud went wrong! it cant access the database, password auth wrong! 
![image](https://user-images.githubusercontent.com/37328400/188598632-8568f254-1178-4ca2-83eb-90e1b5fe35c9.png)

### Host OS 
1. docker info 20.10.7
2. linux version ubuntu 20.04 with kernetl 5.15
3. arm64 arch (spec Oracle Armpre virtual machine!)

#### Nextcloud AIO version 
1.7.1

#### Current channel 
stable lastes

#### Other valuable info 
install version
![image](https://user-images.githubusercontent.com/37328400/188598743-73b11d92-6b62-40ec-b43a-8436f856e49e.png)

container database logs
![image](https://user-images.githubusercontent.com/37328400/188598808-667f35b9-25e9-40a5-9dd8-11b63ca61a39.png)

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/all-in-one/discussions/1073#discussioncomment-3547961
