### ISSUE TITLE
nextcloud-aio-apache uses hardcoded containername instead of env variable 

### ISSUE THREAD

**Issue by mustaphazorgati** [nextcloud/all-in-one#1173]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install aio manually
2. Rename the container name of `nextcloud-aio-nextcloud`
3. Adjust the new container name in the given docker-compose file
4. start nextcloud aio

### Expected behavior 
nextcloud starts properly

### Actual behavior 
the container nextcloud-aio-apache can't find the nextcloud container since the apache configuation uses a hardcoded `nextcloud-aio-nextcloud` hostname.

### Host OS 
Linux

#### Nextcloud AIO version 
24.0.0.5

#### Current channel 
stable

#### Other valuable info 
I created a PR which resolves this issue. 
Apache is able to use env variables in its configuration. Since the env variable `NEXTCLOUD_HOST` is passed into the container anyway I replaced the hardcoded hostname with this variable, built the image locally and verified that it is indeed working.

Since I've manually changed all container names I can verify that everything else regarding the container names is working properly.

**Comment by szaimen** [comment]
This is now fixed with v2.0.3 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
