### ISSUE TITLE
OnlyOffice install without AIO

### ISSUE THREAD

**Issue by Un1QExit** [nextcloud/all-in-one#1183]
After install OnlyOffice manualy and connect to AIO in Web I noticed an oddity. 
If restart my AIO, application OnlyOffice disappears and need to install and setup again.

Nextcloud AIO v2.0.2 
nextcloud/all-in-one:latest

**Comment by Zoey2936** [comment]
Can confirm, it gets removed in this line if OnlyOffice is not enabled:
https://github.com/nextcloud/all-in-one/blob/e0a52df781ab6261790926e45a9b2c71ac109744/Containers/nextcloud/entrypoint.sh#L386

**Comment by Un1QExit** [comment]
how to change this file?
I didn't find...

**Comment by szaimen** [comment]
I'll fix it in the next version...

**Comment by szaimen** [comment]
fixed with https://github.com/nextcloud/all-in-one/commit/8889e92a649bc5bbbc08ae13ef71a9675ab2c62d

will inform you as soon as a beta release that contains this fix is released

**Comment by szaimen** [comment]
This is now fixed with v2.0.4 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by szaimen** [comment]
Can you modify the jwt_secret in your config.php and try again?

**Comment by Zoey2936** [comment]
The problem was that I reused the same jwt_secret, after creating a new one, it works, sorry for this, I misunderstood the check for a jwt secret
