### ISSUE TITLE
Maintenance mode android app/Cron job not working

### ISSUE THREAD

**Issue by joaoferreira-git** [nextcloud/all-in-one#1186]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.Followed the AIO install with NPM
2.Logged in on the phone and uploaded one image to test and it worked.

Not sure if this might have to do with anything but after testing it i installed photoprism docker and pointed it to the photos folder inside nextcloud and it detected the photo i had uploaded previously, as i type this i realized it stopped working after this, could it be a simple permissions problem?

### Actual behavior 
Getting a error about cron not working.
```
It was not possible to execute the cron job via CLI. The following technical errors have appeared:
Your data directory is readable by other users. Please change the permissions to 0770 so that the directory cannot be listed by other users.
```
The android app says that the server is in maintenance mode, i was unable to upload anything and after logging out im unable to log back on in the android app.

Nextcloud still works fine in the browser since i can still upload files to it.

### Host OS 
Unraid with portainer

#### Nextcloud AIO version 
Nextcloud AIO v2.0.2
#### Current channel 
latest
#### Other valuable info 
Theres this in the logs
![log](https://user-images.githubusercontent.com/19786598/191880460-ed22e077-6f95-4ac3-b255-1a5eb4bc8604.jpg)

nextcloud data dir permissions
```
root@UNRAID-Server:~# sudo ls -la /mnt/user/nextcloud/
total 4
drwxrwxrwx 1 nobody users   6 Sep 23 02:29 .
drwxrwxr-x 1 nobody users 103 Sep 23 01:01 ..
-rw-r--r-- 1 sshd   sshd  635 Sep 23 01:54 .htaccess
-rw-rw---- 1 sshd   sshd    0 Sep 22 20:41 .ocdata
drwxr-xr-x 1 sshd   sshd  115 Sep 22 23:19 Toino
drwxr-xr-x 1 sshd   sshd   32 Sep 22 22:03 admin
drwxr-xr-x 1 sshd   sshd  156 Sep 22 22:45 appdata_oc9axajdhd9a
-rw-r--r-- 1 sshd   sshd    0 Sep 22 20:41 audit.log
drwxr-xr-x 1 sshd   sshd   35 Sep 22 20:41 files_external
-rw-r--r-- 1 sshd   sshd    0 Sep 22 22:00 fts-index.done
-rw-r--r-- 1 sshd   sshd    0 Sep 22 20:41 index.html
-rw-r--r-- 1 sshd   sshd    0 Sep 22 20:41 nextcloud.log
drwxr-xr-x 1 sshd   sshd    6 Sep 23 01:45 tmp
root@UNRAID-Server:~# 
```

**Comment by szaimen** [comment]
Hi, please ask this question in the forum. 
https://help.nextcloud.com
Thank you!
