### ISSUE TITLE
Two containers missing when installing AIO from scratch

### ISSUE THREAD

**Issue by michaelfuckner** [nextcloud/all-in-one#1265]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install VM with portainer
2. redirect Ports to this VM: 80,443,3478,8443 (TCP) and 3478 (UDP)
3. use the docker compose file for [portainer](https://github.com/nextcloud/all-in-one/blob/main/docker-compose.yml)
4. log in to http://vm100:8080

### Expected behavior 
be able to acces AIO after clicking start container

### Actual behavior 
two containers are not started

### Host OS 
Fedora 36

#### Nextcloud AIO version 
2.0.4

#### Current channel 
latest

#### Other valuable info 
from apache: Message: Client error: `GET http://localhost/v1.41/containers/nextcloud-aio-apache/logs?stdout=true&stderr=true` resulted in a `404 Not Found` response: {"message":"No such container: nextcloud-aio-apache"}
from nextcloud: Message: Client error: `GET http://localhost/v1.41/containers/nextcloud-aio-apache/logs?stdout=true&stderr=true` resulted in a `404 Not Found` response: {"message":"No such container: nextcloud-aio-apache"}
![containers](https://user-images.githubusercontent.com/64693420/195975019-596baede-7e12-47dd-b352-ce78fdb230e0.png)

**Comment by szaimen** [comment]
Hi, thanks for your report! 

Can you please stop and start the containers again from the AIO interface and if the issue should persist, post the complete mastercontainer logs here?

Thank you!

**Comment by michaelfuckner** [comment]
Hi, does not work, here are the logs,
 Michael!

[nextcloud-aio-mastercontailer_logs.txt](https://github.com/nextcloud/all-in-one/files/9791633/nextcloud-aio-mastercontailer_logs.txt)

**Comment by gphinol** [comment]
Same Issue here, any solution?

**Comment by szaimen** [comment]
Can you run `sudo docker exec -it docker pull nextcloud/aio-nextcloud:latest` ? What does it return?

**Comment by gphinol** [comment]
Error: No such container: docker

**Comment by szaimen** [comment]
My fault. Please try this one: ``sudo docker exec -it nextcloud-aio-mastercontainer docker pull nextcloud/aio-nextcloud:latest`

**Comment by gphinol** [comment]
same issue

**Comment by szaimen** [comment]
How did you name the mastercontainer then?

**Comment by gphinol** [comment]
From my log: 
nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9000: Name or service not known
Waiting for Nextcloud to start...

**Comment by szaimen** [comment]
So the apache container is started?

**Comment by szaimen** [comment]
Can you post the output of `sudo docker ps`?

**Comment by gphinol** [comment]
![image](https://user-images.githubusercontent.com/79718703/195981911-43afa34f-8800-4214-bbfc-510aa2c0e2d3.png)

**Comment by szaimen** [comment]
Seems like you have a different problem then. Can you post the logs of `nextcloud-aio-nextcloud` here?

**Comment by gphinol** [comment]
-------------------------------
 2022-10-15 11:52:37.057389+01
(1 row)

Configuring Redis as session handler...
Setting php max children...
The last Nextcloud update failed.
Please restore from backup and try again!
If you do not have a backup in place, you can simply delete the update.failed file in the datadir which will allow the container to start again.
              now
-------------------------------
 2022-10-15 11:53:39.775959+01
(1 row)

Configuring Redis as session handler...
Setting php max children...
The last Nextcloud update failed.
Please restore from backup and try again!
If you do not have a backup in place, you can simply delete the update.failed file in the datadir which will allow the container to start again.
              now
-------------------------------
 2022-10-15 11:54:42.422139+01
(1 row)

Configuring Redis as session handler...
Setting php max children...
The last Nextcloud update failed.
Please restore from backup and try again!
If you do not have a backup in place, you can simply delete the update.failed file in the datadir which will allow the container to start again.

**Comment by gphinol** [comment]
-------------------------------
 2022-10-15 11:52:37.057389+01
(1 row)

Configuring Redis as session handler...
Setting php max children...
The last Nextcloud update failed.
Please restore from backup and try again!
If you do not have a backup in place, you can simply delete the update.failed file in the datadir which will allow the container to start again.
              now
-------------------------------
 2022-10-15 11:53:39.775959+01
(1 row)

Configuring Redis as session handler...
Setting php max children...
The last Nextcloud update failed.
Please restore from backup and try again!
If you do not have a backup in place, you can simply delete the update.failed file in the datadir which will allow the container to start again.
              now
-------------------------------
 2022-10-15 11:54:42.422139+01
(1 row)

Configuring Redis as session handler...
Setting php max children...
The last Nextcloud update failed.
Please restore from backup and try again!
If you do not have a backup in place, you can simply delete the update.failed file in the datadir which will allow the container to start again.

**Comment by szaimen** [comment]
> The last Nextcloud update failed.
> Please restore from backup and try again!

Please do exactly this then.

**Comment by michaelfuckner** [comment]
I started again from the very beginning- deinstall docker, remove every file/ directory named docker, install docker, install portainer, nextcloud and now it seems to find the missing containers- I can't explain, why.

Is it correct the domaincheck container just runs shortly and exits? Then the nextcloud container starts and the last one is the apache one?

**Comment by szaimen** [comment]
As for @michaelfuckner , can you run this and report the outcome?

>  `sudo docker exec -it nextcloud-aio-mastercontainer docker pull nextcloud/aio-nextcloud:latest`

**Comment by michaelfuckner** [comment]
[root@vm100 ~]# sudo  docker exec -it nextcloud-aio-mastercontainer docker pull nextcloud/aio-nextcloud:latest
latest: Pulling from nextcloud/aio-nextcloud
Digest: sha256:22e566a1bdb84a521e0f1dae39ffaae463f74e6a5a5ebd6bfc7bc2e1521bcc1b
Status: Image is up to date for nextcloud/aio-nextcloud:latest
docker.io/nextcloud/aio-nextcloud:latest
[root@vm100 ~]#

**Comment by szaimen** [comment]
> [root@vm100 ~]# sudo docker exec -it nextcloud-aio-mastercontainer docker pull nextcloud/aio-nextcloud:latest latest: Pulling from nextcloud/aio-nextcloud Digest: sha256:22e566a1bdb84a521e0f1dae39ffaae463f74e6a5a5ebd6bfc7bc2e1521bcc1b Status: Image is up to date for nextcloud/aio-nextcloud:latest docker.io/nextcloud/aio-nextcloud:latest [root@vm100 ~]#

Interesting! That is very strange! Does starting the containers still not work?

I was asking because of this issue in the logs 
`Client error: `POST http://localhost/v1.41/containers/create?name=nextcloud-aio-nextcloud` resulted in a `404 Not Found` response:\n{&quot;message&quot;:&quot;No such image: nextcloud/aio-nextcloud:latest&quot;}`

Can you run `sudo docker image inspect nextcloud/aio-nextcloud:latest`?

**Comment by michaelfuckner** [comment]
sorry, did not try before wiping and reinstalling, that;s how it looks now:

[root@vm100 ~]# sudo docker image inspect nextcloud/aio-nextcloud:latest
[
    {
        "Id": "sha256:f4abd46e462970fe4e040806bddf59480548ae06622f5f5eaadb853a5cc2f93a",
        "RepoTags": [
            "nextcloud/aio-nextcloud:latest"
        ],
        "RepoDigests": [
            "nextcloud/aio-nextcloud@sha256:22e566a1bdb84a521e0f1dae39ffaae463f74e6a5a5ebd6bfc7bc2e1521bcc1b"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2022-10-06T21:33:49.379089298Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "www-data",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHPIZE_DEPS=autoconf \t\tdpkg-dev dpkg \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkgconf \t\tre2c",
                "PHP_INI_DIR=/usr/local/etc/php",
                "PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
                "PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
                "PHP_LDFLAGS=-Wl,-O1 -pie",
                "GPG_KEYS=1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F",
                "PHP_VERSION=8.0.24",
                "PHP_URL=https://www.php.net/distributions/php-8.0.24.tar.xz",
                "PHP_ASC_URL=https://www.php.net/distributions/php-8.0.24.tar.xz.asc",
                "PHP_SHA256=8e6a63ac9cdabe4c345b32a54b18f348d9e50a1decda217faf2d61278d22f08b",
                "PHP_MEMORY_LIMIT=512M",
                "PHP_UPLOAD_LIMIT=10G",
                "PHP_MAX_TIME=3600",
                "NEXTCLOUD_VERSION=24.0.6",
                "NEXTCLOUD_UPDATE=1"
            ],
            "Cmd": [
                "/usr/bin/supervisord",
                "-c",
                "/supervisord.conf"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "(nc -z localhost 9000 && nc -z localhost 7867) || exit 1"
                ]
            },
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": {
                "/mnt/ncdata": {},
                "/var/www/html": {}
            },
            "WorkingDir": "/var/www/html",
            "Entrypoint": [
                "/start.sh"
            ],
            "OnBuild": null,
            "Labels": null,
            "StopSignal": "SIGQUIT"
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 1134384496,
        "VirtualSize": 1134384496,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/d7d742a09933e67c0775c516564cd9bac4bca095220ad94d48b11d78e3c0ef01/diff:/var/lib/docker/overlay2/519222ee531b5f1fe5ec43ff02859a77c2071690c66ffc81dedbe9d13b7e1a93/diff:/var/lib/docker/overlay2/5840c1723cf1726df73d9f43123a7429389653a677c7fbcbc815c88adb5df366/diff:/var/lib/docker/overlay2/0b35c2a2e0a80b166607f6a0387b3f9d8d80c140a552e7f7313ce434db79f28a/diff:/var/lib/docker/overlay2/8afbc176c13bd6c72332682aead2d41558e58280c3233f3fb5ba40469a890e49/diff:/var/lib/docker/overlay2/2d9ad997a261008221b0829272ffa702c3d811a2b3631ad06ce912a65c1caca3/diff:/var/lib/docker/overlay2/1b214a6515d78b1ee8cd09f3ffc03dfad54e7aca7babcb8a3467b7877a7d76d8/diff:/var/lib/docker/overlay2/ea1f9af69cba1098eeb8dd4e90d0d3aa7b259c17452b8dad048353eb56004781/diff:/var/lib/docker/overlay2/724461b12443927f8fcff3f40689951fb7f8955c1ed386f03003baa7f32114cc/diff:/var/lib/docker/overlay2/a40f1cbd40e6e357014f97e890cdd0d995e6d6dcec0f22d7e4910e9237510767/diff:/var/lib/docker/overlay2/818a327dcb5402e3c79eb06e3244addc324ae4e86c307ea85bf9f31bede3bfb2/diff:/var/lib/docker/overlay2/85bc0657181ff5f047fa241e29a64ab023def70cbe3583c3720293483c067e27/diff:/var/lib/docker/overlay2/d03426b4be91409c449e8e734a6f8f9596c6ae9aefdd5f007f082f11d8c41481/diff:/var/lib/docker/overlay2/9d5eaa9253e5bacddab24e9c526a8eec47918e8bd0b3a61e8cefbe036ba7a9e0/diff:/var/lib/docker/overlay2/6bf222ae19b82077031f69ff7f79b4435b811be5b8b9a68309516190f87fcb47/diff:/var/lib/docker/overlay2/e97046c8af849bcf74933026a63d89e78ebfca773ffa73a087853e6214febe9d/diff:/var/lib/docker/overlay2/c38ca1fa61e04b290d20ae725d8bb333b8141a3c7e30c34fd5575d781eca9be3/diff:/var/lib/docker/overlay2/61f2a967d21b8a23b63934cee88e4fd2ac9b44fed17652599bc739f0de98b7ef/diff:/var/lib/docker/overlay2/b352ceb43a0de3472f8c2ff5aba3e700563d8dbb6345456ea031fee4b1737457/diff:/var/lib/docker/overlay2/818bc64d00c3ea26471934d38bf21ff9156e0950254b9c63dc053ea1a26fca83/diff:/var/lib/docker/overlay2/ccdffac10e8f64cdba5420f3ae5f6520b2499ef1f2dede0fa4e8c95f80088126/diff:/var/lib/docker/overlay2/56973a0e826b4492994e81ea0663abcb8bbe30539ea28b32fcc37e6efc5c1d10/diff:/var/lib/docker/overlay2/0f168b7af73d12511ddd34af8e3812f7ad218cbddb840ad103a33b47ddd344c0/diff:/var/lib/docker/overlay2/91913f84d1700e457a2b7254d334c85d3c290266702f3307a29d1cf0aed32450/diff:/var/lib/docker/overlay2/880fac4da870b9a34f6734217d46ff1bd7b6e12cafbac532bd612a935d563052/diff:/var/lib/docker/overlay2/0462cf36979a95f1a792734023dd6dff4c2459cc0a92e59716b7c9ba0fc89aea/diff:/var/lib/docker/overlay2/822800b0fa98ac8b443be480b5365a2dafa2a2dcd241e9604b97065df5d4fc3a/diff:/var/lib/docker/overlay2/d68b661b155f9d5eb863f66e71956db80d6171c70a419eeecc00bdd227a7cd11/diff:/var/lib/docker/overlay2/f2f53e55969349194cfab475f812be8a976cc955cde899248514487cd04bfb1f/diff",
                "MergedDir": "/var/lib/docker/overlay2/c94b2108c40f4b24619e9bca5984fa830a7d21defbf1ec47107bb6eafb847e6e/merged",
                "UpperDir": "/var/lib/docker/overlay2/c94b2108c40f4b24619e9bca5984fa830a7d21defbf1ec47107bb6eafb847e6e/diff",
                "WorkDir": "/var/lib/docker/overlay2/c94b2108c40f4b24619e9bca5984fa830a7d21defbf1ec47107bb6eafb847e6e/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:994393dc58e7931862558d06e46aa2bb17487044f670f310dffe1d24e4d1eec7",
                "sha256:cd3f5d78e589ec1ee4f39079b6dafab03ed380a3a329b172fad36a8b46b7fc90",
                "sha256:49a1a2a80ba6a929497c64f271c34d292ac1e20d1e5be045be78b38bb9d781e3",
                "sha256:744437e91ddbdb0d9b7a557e0c347ffa0aa0990c27775079ddb638762de9b6c8",
                "sha256:b5ddaa9e9c6fe6ab6fe77fe595dbd3007deb4b84c937ae041dd831653ab91085",
                "sha256:e8a1531411ad8c4c94c671afe869abe875ab983e9fdcf4a3ece623f5a939e8aa",
                "sha256:a3bb4600fe1324d87752d29a13245ea3eadf1c4ee7f217705ad57ba94f0fada0",
                "sha256:a5c285b523a144e76a291eadada440e9dee41977e13981dec5610d944329b43e",
                "sha256:a796b0dabc599aadc779c7ddbc3b751b3031e06d6c58a55c0b475bee45e7c42a",
                "sha256:ba931dfecebc85210614f11fc2c5ac816442397cb08eb40a4fcae218536f9818",
                "sha256:008f63b958952270c4fafc0de311bd9f105056b9511c4f0f200b5eec39efb255",
                "sha256:a98c60959f19e0f824c8f3c7fcf2b427322fcadaa3dda8ac0b844083562e5452",
                "sha256:9f96978dec444d53d3cdc64555e7ad049b34757e329cb06d5ea433070b0a8bc4",
                "sha256:9b0df28ca2f4712e1d27211ef8aa55c105540adfbe36df65f03a2d0e6a6b8956",
                "sha256:3c75b87cc2e7359875b3e9cc11e8d61ebdb1658f6a7039cbd608455144d0ec8e",
                "sha256:bbf7f44db4fabd9f782810f527dab02279ccd7daf55b66ca68b6ba970faa1a91",
                "sha256:a64b0f74dae43db955528a494c07e8a8daef937ec77d12cba00952de99dbe759",
                "sha256:8d0d25bbe3e5689a86954f0572bb9e18555cd7daf439c2bdd9a88a3fa7bd47b6",
                "sha256:c33130703ba1a48e87966f7923e7bf0bc70c80d4f5e1659219b20a59197d5f7a",
                "sha256:7100bec5d635cb79753b84ff2edc895cfa96600ae14a05a8998b66d87e301b31",
                "sha256:232bff0361d9c2e6ff03e732b91036f029ac509683af42e4e737d1573bf7c132",
                "sha256:1a322eb89a4aa18c60988f56a70e8a55828ebdc95e95ae513193b11ce5fc1a2d",
                "sha256:f11fdda1e09c9c21d4b26055c26d02f4e4df35427e97013782322aa82fc572c2",
                "sha256:32e7eed7df9ac1087dfd1a34e33ce2529765db359ea0bc551769855dd03e378a",
                "sha256:27b5168b5841036f837660dbd63fa6e82e1d20ae8ed4132d25bcf908d953392d",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:0ca5dfbc34a45cb1c0bea30d9de723eec17856a248c047b6c0837ef4891f441c",
                "sha256:1b1149e902336249250b880463eb2b4b77c5649aa2362e8a0ac45424548aae25",
                "sha256:b2ee751b3325b48f814acd23dc3de9e1402fd7ce0506026a6fce6e22db8e8beb"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
[root@vm100 ~]#

**Comment by szaimen** [comment]
I had a look at the logs again and reduced them to these ones:
```
Client error: `POST http://localhost/v1.41/containers/create?name=nextcloud-aio-nextcloud` resulted in a `404 Not Found` response:\n{&quot;message&quot;:&quot;No such image: nextcloud/aio-nextcloud:latest&quot;}
Client error: `DELETE http://localhost/v1.41/containers/nextcloud-aio-collabora?v=true` resulted in a `409 Conflict` response:\n{&quot;message&quot;:&quot;You cannot remove a running container 59a3daf89ac3aaab63e1c771f59d69cf0b1979ab43c6f56e712621a6f1f390ae. Stop (truncated...)
Client error: `POST http://localhost/v1.41/containers/create?name=nextcloud-aio-nextcloud` resulted in a `404 Not Found` response:\n{&quot;message&quot;:&quot;No such image: nextcloud/aio-nextcloud:latest&quot;}
Client error: `DELETE http://localhost/v1.41/containers/nextcloud-aio-collabora?v=true` resulted in a `409 Conflict` response:\n{&quot;message&quot;:&quot;You cannot remove a running container d17622f65481aabbf345f838888723922539167d6a2802bbc2431cea62ee48de. Stop (truncated...)
Client error: `POST http://localhost/v1.41/containers/create?name=nextcloud-aio-nextcloud` resulted in a `404 Not Found` response:\n{&quot;message&quot;:&quot;No such image: nextcloud/aio-nextcloud:latest&quot;}

```

**Comment by szaimen** [comment]
As for the Nextcloud issue, it basically looks like it tries to create the Nextcloud container but the image is somehow not present even though it seems to be present which is really strange.

As for the collabora issue here, that happens if the side does not reload and you click the start container again. It the fails to start them because the containers are still running and not stopped yet.

---

Since I cannot reproduce this issue, can you please try to reset the instance again by following https://github.com/nextcloud/all-in-one#how-to-properly-reset-the-instance and try again?

**Comment by michaelfuckner** [comment]
followed your guide and now NC comes up as expected.
If I ran into docker pull limit, there would have been another error message?

**Comment by szaimen** [comment]
> If I ran into docker pull limit, there would have been another error message?

yes. then `sudo docker exec -it nextcloud-aio-mastercontainer docker pull nextcloud/aio-nextcloud:latest` should have shown something.
