### ISSUE TITLE
missing things for stable release

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#127]
## Required:
- [x] https://github.com/nextcloud/all-in-one/issues/28
- [x] https://github.com/nextcloud/all-in-one/issues/38
- [x] https://github.com/nextcloud/all-in-one/issues/39
- [x] https://github.com/nextcloud/all-in-one/issues/47
- [x] https://github.com/nextcloud/all-in-one/issues/72
- [x] https://github.com/nextcloud/all-in-one/issues/76
- [x] https://github.com/nextcloud/all-in-one/issues/185
- [x] https://github.com/nextcloud/all-in-one/issues/131
- [x] https://github.com/nextcloud/all-in-one/issues/476

## Not necessarily required:

- [x] ~~migrate borgbackup to alpine?~~ did not work, hence reverted the change
- [x] #272
- [x] https://github.com/nextcloud/all-in-one/issues/271
- [x] https://github.com/nextcloud/all-in-one/issues/276
- [x] https://github.com/nextcloud/all-in-one/issues/265
- [x] https://github.com/nextcloud/all-in-one/issues/55
- [x] https://github.com/nextcloud/all-in-one/issues/340
- [x] https://github.com/nextcloud/all-in-one/issues/345

### Options:
- [x] add an optional section for later (requirement for thr options below) https://github.com/nextcloud/all-in-one/pull/330
- [x] https://github.com/nextcloud/all-in-one/issues/376
- [x] https://github.com/nextcloud/all-in-one/issues/382
- [x] https://github.com/nextcloud/all-in-one/issues/383

### Help wanted:
- [x] ~~Make the AIO interface a bit prettier?~~
- [x] https://github.com/nextcloud/all-in-one/issues/341

### Before stable release:
- [x] ~~after all above is done, remove all beta status hints and add a `What is the status of this project?` to the readme.~~

### After that
- [ ] https://github.com/nextcloud/all-in-one/discussions/361
- [ ] https://github.com/nextcloud/all-in-one/discussions/358
- [ ] https://github.com/nextcloud/all-in-one/discussions/452

**Comment by sim-san** [comment]
What is the release plan for the first stable version ? Is there some rough plan ?

**Comment by szaimen** [comment]
The current plan is to release the stable version when NC24 comes out.

**Comment by R7JANV1** [comment]
Approximately when can we expect a stable Nextcloud 24 release?

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule#nextcloud-24
