### ISSUE TITLE
Borg backups : allow `/var/backups` as backup target

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#128]
As stated in the doc. : Backups get created in the following directory on the host: /mnt/backup/borg 

Why do you force this dir ? Any reason ?

In my case, because I have standardised scripts on my servers where the backups dirs are not in the /mnt dir, I prefer to have the choice.

I needed to create a sym link to put the files elsewhere but it's a workaround.

**Comment by szaimen** [comment]
> Why do you force this dir ? Any reason ?

We don't force it. You choose it by yourself. see https://pifferi.info/content/images/2021/12/Bildschirmfoto-2021-12-05-um-11.54.42.png

**Comment by marcatsmci** [comment]
My bad : the title is wrong... I corrected it

**Comment by marcatsmci** [comment]
I think it could be reopened?

**Comment by szaimen** [comment]
Not sure if we wanna allow this. Where are your backups usually stored?

**Comment by marcatsmci** [comment]
First answer : where I want ;-)
Second one : on a server, /mnt is traditionnaly reserved for mount points and /media is dedicated to laptops for usb etc...

I manage many servers for customers and the location relays on their particular backups configurations/tools.

Why do you want to force something ? It's up to the admin because there are as many destinations/situations as admin...

**Comment by marcatsmci** [comment]
Maybe related to #76 ?

**Comment by szaimen** [comment]
We simply want to allow only specific, feasible directories here as it potentially prevents some bugs from happening.
You would help if you would list some of those custom backup directories in this thread that we could think about allowing as well.

> Maybe related to #76 ?

No, it isn't.

**Comment by marcatsmci** [comment]
> We simply want to allow only specific, feasible directories here as it potentially prevents some bugs from happening.

I agree ;-)

In fact, the main root I need is **/var**

**Comment by szaimen** [comment]
I discussed this with a collegue and we agreed that `/var` is not suitable. What would be possible though is `/var/backups`. Would that work?

**Comment by marcatsmci** [comment]
Great for me ! 

Le 13 janvier 2022 17:51:33 GMT+01:00, "Simon L." ***@***.***> a écrit :
>I discussed this with a collegue and we agreed that `/var` is not suitable. What would be possible though is `/var/backups`. Would that work?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/all-in-one/issues/128#issuecomment-1012319354
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail.

**Comment by marcatsmci** [comment]
One more question : after complete installation, any way to change the borg dest dir ?

**Comment by szaimen** [comment]
Okay, will allow /var/backups then 👍

**Comment by szaimen** [comment]
> after complete installation, any way to change the borg dest dir ?

No, no official one but you might be able to adjust the `borg_backup_host_location` in `/var/lib/docker/volumes/nextcloud_aio_mastercontainer/_data/data/configuration.json` but no guarantee that you don't run into issues.

**Comment by marcatsmci** [comment]
Needed to remove `backup_archives.list` and `borg.config` and all is ok.

Thanks !
