### ISSUE TITLE
AIO Interface: self signed certificate

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#130]
Trying to access to AIO Interface with **https://xxxx:8080/containers** and get a security message from the browser : 

xxxx:8080 uses an invalid security certificate.
The certificate is not trusted because it is self-signed.
Error code: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT

The certificate used is selfsigned with **nextcloud.local** as common name.

Did I a wrong configuration ? 
If it's not the case, any way to use the same cert as the one generated with Letsencrypt's ?

Last AIO version on Debian 11

**Comment by szaimen** [comment]
simply open the aio interface on port 8443 or is that not possible?

**Comment by marcatsmci** [comment]
Yes, it's ok but needed to coy the full url .../api/auth/getlogin?token=xxx...

**Comment by szaimen** [comment]
> Yes, it's ok but needed to coy the full url .../api/auth/getlogin?token=xxx...

What do you mean?

**Comment by marcatsmci** [comment]
Forget it, it's ok, probably a bad manipulation ;-(

**Comment by szaimen** [comment]
Thanks for the answer

**Comment by marcatsmci** [comment]
Any way to change the url in the button to get the url with the Let's Encrypt cert ?

**Comment by szaimen** [comment]
> Any way to change the url in the button to get the url with the Let's Encrypt cert ?

Yes, access the aio interface from port 8443, click on `stop containers`, click on `start containers` -> done.

**Comment by marcatsmci** [comment]
> Yes, access the aio interface from port 8443, click on stop containers, click on start containers -> done.

Definitely magical !
Thanks
