### ISSUE TITLE
Active ports : question

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#134]
My installation is up and running behind a firewall, with only these ports : 80, 443, 8443, 3478 and all runs smoothly.

I blocked the 8080.

My question : any necessity to run with 8080 open after a complete installation ?

**Comment by szaimen** [comment]
> My installation is up and running behind a firewall, with only these ports : 80, 443, 8443, 3478 and all runs smoothly.
> 
> I blocked the 8080.
>
> My question : any necessity to run with 8080 open after a complete installation ?

If the server is running on your local network, you have the choice to either access the interface only from inside via port 8080 with self-signed certificate or forward 80 and 8443 to open it with valid certificate on port 8443.

So no, If port 8443 works for your, port 8080 can be closed. 👍
