### ISSUE TITLE
Make Nextclouds Backup app work

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#135]
I try the Backup App as proposed in the README (Note that this implementation does not provide remote backups, for this you can use the Backup App.)

The first problem is the backups locations : 
`/var/lib/docker/volumes/nextcloud_aio_nextcloud_data/_data/appdata_xxxxxxxxx/backup`
Was not possible to set any other location.

The second problem is the missing of "pg_programs" : `pg_dump` for example...

Anybody tried to use this app successfully ?

**Comment by szaimen** [comment]
I must admit: I didn't test the Nextcloud Backup app yet.

---

> The second problem is the missing of "pg_programs" : pg_dump for example...

This is happening because the used library uses pg_dump internally:
https://github.com/spatie/db-dumper

We could think about adding postgresql-client into the container in order to fix this on our side:
https://askubuntu.com/a/501130

---

> The first problem is the backups locations :
> `/var/lib/docker/volumes/nextcloud_aio_nextcloud_data/_data/appdata_xxxxxxxxx/backup`
> Was not possible to set any other location.

Why do you need to set it to a different location?

**Comment by marcatsmci** [comment]
> Why do you need to set it to a different location?

I like to have choice on my servers, something like `/var/backups`;-)

**Comment by szaimen** [comment]
> > Why do you need to set it to a different location?
> 
> I like to have choice on my servers, something like `/var/backups`;-)

Fine by me but for local backups you can use the built-in borg solution, no?

**Comment by marcatsmci** [comment]
The main advantage with the backup app is the separated parts of the backup : 
- DB
- datas
- apps
- ...

**Comment by szaimen** [comment]
I don't wanna start a discussion now so I only mention that you are probably looking for this: https://github.com/nextcloud/all-in-one/issues/76 ;)

**Comment by marcatsmci** [comment]
Nice !

**Comment by szaimen** [comment]
Another possibility is backing up `/var/lib/docker/volumes` with the program of your choice after you clicked on `Stop containers`.
(which has the data seperated as well)
