### ISSUE TITLE
Access Nextcloud AIO on Port 8443 dont work

### ISSUE THREAD

**Issue by Supergamerx3000** [nextcloud/all-in-one#14]
I installed the nextcloud aio container. I get on port 8080 but not on port 8443 how do I tell the docker which host name it should listen to?

**Comment by szaimen** [comment]
Hi, it is as simple as described in the readme :)
> If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatially by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443

It gets the domain via SNI and automatically generates a certificate for you :)
