### ISSUE TITLE
Think about making update process more stable

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1400]
Enabled apps can have an influence on if the update pocess fails. (It is indeed the main source why an update fails).

We should think about making it more stable. 

One solution would be disabling all apps before the update, then updating, then enabing them again with the correct group values. If re-enabling fails, dont restore the group values and simply leave it disabled but send a notification in that case. This might break some apps, but is still better than failing the updatee process altogether which would bring down the whole instance. (Obviously only do this for apps in the custom_apps dir).

Maybe also create an update log and store that somewhere permanently.

**Comment by szaimen** [comment]
@Zoey2936 WDYT?

**Comment by Zoey2936** [comment]
I think this could work and would be a better solution then the current way
