### ISSUE TITLE
Question : where are the server logs ?

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#141]
All in the title ;-)

**Comment by szaimen** [comment]
Which logs exactly? Nextcloud logs?

**Comment by marcatsmci** [comment]
Yes
![Screenshot_2022-01-17_22-33-51](https://user-images.githubusercontent.com/47881838/149839225-15dba054-7ae2-4bc5-9573-6d30ee9ad917.png)

**Comment by szaimen** [comment]
here: https://github.com/nextcloud/all-in-one/blob/20d02fb83f4ffab8938420868d09d021f4ae95af/Containers/nextcloud/entrypoint.sh#L146

**Comment by szaimen** [comment]
Does this answer your question?

**Comment by marcatsmci** [comment]
Now I have some entries in the log, so the message "Everything is working fine" was a real message ;-)
Thanks !

**Comment by szaimen** [comment]
Okay great!
