### ISSUE TITLE
built-in LDAP server

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#144]
built-in LDAP server.  Nextcloud's LDAP app is an important part of the cloud and is especially important for companies or small organizations.  In my opinion, the built-in LDAP server would be interesting for many, possibly as an extension.  would definitely offer many possibilities

**Comment by szaimen** [comment]
I am sorry but this is out of scope for this project. You should be able to use an external LDAP server together with this project, though.
