### ISSUE TITLE
A shared folder is visible but (recently became) not traversable by (pre-upgrade) users

### ISSUE THREAD

**Issue by r-hmn** [nextcloud/all-in-one#1442]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have 3 folders shared with user-groups since AIO v1.x. Follow all updates/upgrades.
2. Upgrade to AIO v3.0.0 Now traversing those folders using the browser seems broken (for pre-existing users only..)
3. From the browser folder view, under 'shares', click the shared folder
4. The folder view doesn't show the shared folder'content, but (falsly) shows the personal root content.
5. Also, From the browser folder view, under 'shares', click '... > details' on the shared folder, it (falsly) shows an error in the details pane.
6. 'internal links' to files in a shared folder(which i email to them) don't work. the browser shows a loading pane indefinitely when users click the link.
7. The 'owner user' of the shared folder, who is part of the same group, is the able to traverse the shared folder via 'shares'.(so sees no problem)
8. A newly created user in v3.0.0 who is part of the same group is also able to traverse the shared folder via 'shares'.(so sees no problem)
9. 'old users' aren't able to traverse the shared folders.(sees the problem)
10. unshare a folder, and share it again with the same settings(allow:edit,create,download / disallow: delete, share again), and the folder reappears for all users. but the same behaviour persists.
11. A user who sees the problem in the browser, has reported that the files ARE available on her iPhone which are synched with the 'nextcloud' app, and that edits i make are coming through(confirmed). i have no info of Android users.

### Expected behavior 
For all users in the group with whom the folder is shared:
The shared folder should be traversable form the browser gui.
The internal-links to content in a shared folder should enable opening the file in the browser.

### Actual behavior 
*For users pre-existing v3.0.0:*
When traversing the shared folder, it shows the person's private root content intead. 
Also for the shared folders the details-pane isn't working. 
Also 'internal links' which point to files in a shared folder doesn't work. it shows a page which stays 'loading'.
The iPhone nextcloud sync app does function and keeps the files in the shared folder up-to-date.
*For users created after v3.0.0 upgrade:*
They do have acccess to the shared folder in the browser, and internal links can be followed.

### Host OS 
Lubuntu 22.04

#### Nextcloud AIO version 
v3.0.0

#### Current channel 
it says 'you are running the "lates" channel' 

#### Other valuable info 
https://help.nextcloud.com/t/a-shared-folder-is-visible-but-recently-became-not-clickable-traversable-by-multiple-users/150562

**Comment by szaimen** [comment]
This will be fixed with 24.0.8 or 25.0.2. 

Also see https://github.com/nextcloud/all-in-one/discussions/1434#discussioncomment-4203779
