### ISSUE TITLE
wrong admin password

### ISSUE THREAD

**Issue by HedgeShot** [nextcloud/all-in-one#149]
I couldn't log into nextcloud using the given credentials (admin / some random password) after a clean install. I had to change it using this occ command:

```
docker exec -it nextcloud-aio-nextcloud php occ user:resetpassword admin
```

Also, `docker-compose up -d --build` raised an issue: `volumes.nextcloud_aio_mastercontainer value Additional properties are not allowed ('name' was unexpected)`bumping the version to 3.8 solved the issue. It seems `name` is supported only from `docker-compose` 3.4

**Comment by szaimen** [comment]
> Also, `docker-compose up -d --build` raised an issue: `volumes.nextcloud_aio_mastercontainer value Additional properties are not allowed ('name' was unexpected)`bumping the version to 3.8 solved the issue. It seems `name` is supported only from `docker-compose` 3.4

What do you expect? Bumping this version to at least 3.4?
https://github.com/nextcloud/all-in-one/blob/dadbc4d43db0499cf29ae41223af3cfa92c45e69/docker-compose.yml#L1

**Comment by HedgeShot** [comment]
I expect the docker-compose file provided on this repo to work, which was not the case until I bumped the version on the docker-compose file to 3.8. I haven't tried below 3.8 but according to docker-compose docs, `name` is supported since 3.4 for volumes. I am assuming you tried it before pushing the version on Github with version 3.1 so I am not sure how you made it work.

**Comment by szaimen** [comment]
Thanks, will bump the version then :)
