### ISSUE TITLE
Disable auto SSL cert generation

### ISSUE THREAD

**Issue by iWangJiaxiang** [nextcloud/all-in-one#15]
Hi, according to README, this image will auto get SSL cert from letsencrypt.
Is there any way to disable auto SSL cert generation because I have an external reverse proxy for SSL termination.

**Comment by szaimen** [comment]
Sry but we will not make it possible to disable ssl generation and since we cannot make sure that everything works then.

**Comment by AlexanderProd** [comment]
@szaimen Is there any way of running it behind a reverse proxy then? I want to run `nextcloud-aio` on a server where many apps run so I need to run it behind a reverse proxy.

**Comment by szaimen** [comment]
Hi, reverse proxies are currently not supported.
You might investigate yourself though how it could made work behind reverse proxies. If you open a PR with that we might consider it then :)
