### ISSUE TITLE
add docker cp command documentation for migration.md

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1522]
See https://docs.docker.com/engine/reference/commandline/cp/

**Comment by ManOki** [comment]
@szaimen for clarification: you refer to [migration.md](https://github.com/nextcloud/all-in-one/blob/main/migration.md) and want to improve lines/paths like:

> Restore the datadirectory of your former instance into the following directory: <ins>**/var/lib/docker/volumes**</ins>/nextcloud_aio_nextcloud_data/_data/
> Next, run sudo chown -R 33:0 <ins>**/var/lib/docker/volumes**</ins>/nextcloud_aio_nextcloud_data/_data/* and sudo chmod -R 750 <ins>**/var/lib/docker/volumes**</ins>/nextcloud_aio_nextcloud_data/_data/* to apply the correct permissions

?

**Comment by szaimen** [comment]
Yes, indeed since absolute paths don't work e.g. on Windows and using docker cp for this also feels less hacky. Additionally, I read that docker cp even works when the container is stopped which we need here...

**Comment by ManOki** [comment]
see #1773
