### ISSUE TITLE
Nextcloud AIO v4.0.0 - Talk - Turnserver

### ISSUE THREAD

**Issue by martin-77** [nextcloud/all-in-one#1547]
Thanks for the new beta!

Here a little bug:

On a fresh install the Turn-Server is missing in the config of Nextcloud Talk.
Turnserver was installed inside the talk container - simply had to add the missing entrys in the config of Nextcloud.

On the stable Version, the entry is done automatic.
When updating from stable to beta4 the entry persists. 

Installing from beta without any previous installation, the config-entry in administrative settings/talk is missing for turn.

Once again, thank you for your incredible job!

**Comment by szaimen** [comment]
Hi, thanks for testing and your report! I'll have a look soon and will probably fix this in AIO v4.0.1.

**Comment by szaimen** [comment]
This is now released with v4.0.1 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
