### ISSUE TITLE
Setting upload max size

### ISSUE THREAD

**Issue by Tomptez** [nextcloud/all-in-one#16]
I really would like to use the nextcloud all-in-one image since I do not need a lot of control or special requirements regarding my nextcloud instance.
However, I do need to be able to change the maximum upload size. Since I couldn't find any information on this:
**Is there a way to manually set the maximum upload size using the all-in-one container?**

**Comment by szaimen** [comment]
@Tomptez thanks for your request! I don't think that we will make it possible to change the maximum upload size but we are open to adjust it to a sane value. Would e.g. 10GB be enough for your usecase?
