### ISSUE TITLE
NC Office WOPI Whitelist blocking access to open documents

### ISSUE THREAD

**Issue by frederikb96** [nextcloud/all-in-one#1610]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a new document online in the file view
1. Open the document online, which will launch Nextcloud Office

### Expected behavior 
It opens the document

### Actual behavior 
It fails, since the WOPI Whitelist not allows the access

### What I already tried
If I delete the entries in the Whitelist, it works, but they get recreated with every new container startup.
I already tried stopping all containers, disabling Nextcloud Office, deleting the old container and volume, starting again, stopping again, enabling Nextcloud Office again and starting again.
Is there a way I can debug this further?

### Host OS 
Ubuntu 22.04 server

#### Nextcloud AIO version 
v4.0.1

#### Current channel 
Beta

**Comment by szaimen** [comment]
Hi, you would need to find out which ip-address it is trying to use (maybe check the collabora logs for ip-addresses) and put that additionally into the wopi allowlist.

**Comment by frederikb96** [comment]
Ok thanks, I had to additionally set the ip address of the docker network my caddy container is part of, which I use as a reverse proxy for the Nextcloud Apache container.

**Comment by szaimen** [comment]
> I had to additionally set the ip address of the docker network my caddy container is part of,

is that an internal ip-address or a public one?

**Comment by szaimen** [comment]
Can you share the ip-address?
