### ISSUE TITLE
Avatar Generation does not work of single letter users

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#1628]
Already tried a lot of things but nothing did make it work:
- https://github.com/nextcloud/all-in-one/pull/1624 
- https://github.com/nextcloud/all-in-one/pull/1626
- https://github.com/nextcloud/all-in-one/pull/1627
- https://github.com/nextcloud/all-in-one/commit/7a6f35024822c29d79899945fdd66bcaf298c9f6
- https://github.com/nextcloud/all-in-one/commit/d06b3a7b19d30fa28144abda5f5d616ca3d67edd
- https://github.com/nextcloud/all-in-one/commit/810094daa3d88c08e5a4a43da69873f74ca286ae
- [ ] todo: check if it works with php8.1

**Comment by szaimen** [comment]
Maybe it has to do with imagemagicks policy.xml but I tried to modify that and it still didnt work so out of ideas again...

**Comment by ManOki** [comment]
does not work even with long user names

<img width="146" alt="avatars" src="https://user-images.githubusercontent.com/1769457/212986685-3b040423-e34d-431f-80be-9dc18280e7b6.png">

**Comment by szaimen** [comment]
Interesting! So yeah, I tried my best but didn't find a solution. Help on this is appreciated! My last thought was that it might be the policy.xml from imaginary but even adjusting that didn't made it work...

**Comment by Zoey2936** [comment]
Does this error only exist under some conditions? Since on my AIO Instance it is working... (v4.2.0)
![grafik](https://user-images.githubusercontent.com/75573284/212992528-e225646a-6d6d-46ee-9926-877434ad95e8.png)

**Comment by szaimen** [comment]
> Does this error only exist under some conditions? Since on my AIO Instance it is working... (v4.2.0)
> ![grafik](https://user-images.githubusercontent.com/75573284/212992528-e225646a-6d6d-46ee-9926-877434ad95e8.png)

do you have imagick installed and enabled?

**Comment by Zoey2936** [comment]
> > Does this error only exist under some conditions? Since on my AIO Instance it is working... (v4.2.0)
> > ![grafik](https://user-images.githubusercontent.com/75573284/212992528-e225646a-6d6d-46ee-9926-877434ad95e8.png)
> 
> do you have imagick installed and enabled?

![grafik](https://user-images.githubusercontent.com/75573284/212993891-b90599b8-fc97-4aaf-8994-8a3abf0ba3d3.png)
I would say yes and in my config.php is set:
```php
  'enabledPreviewProviders' => 
  array (
    1 => 'OC\\Preview\\Image',
    2 => 'OC\\Preview\\MarkDown',
    3 => 'OC\\Preview\\MP3',
    4 => 'OC\\Preview\\TXT',
    5 => 'OC\\Preview\\OpenDocument',
    6 => 'OC\\Preview\\Movie',
    0 => 'OC\\Preview\\Imaginary',
  ),
  'enable_previews' => true,
  'preview_imaginary_url' => 'http://nextcloud-aio-imaginary:9000',
```

**Comment by szaimen** [comment]
> do you have imagick installed and enabled?

You can check it here: `https://yourdomain.com/settings/admin/overview`. If it is not enabled it should show a warning.

**Comment by Zoey2936** [comment]
![grafik](https://user-images.githubusercontent.com/75573284/212994800-1ec54a5f-a76c-4941-b336-8707bc545c59.png)

**Comment by szaimen** [comment]
> ![grafik](https://user-images.githubusercontent.com/75573284/212994800-1ec54a5f-a76c-4941-b336-8707bc545c59.png)

hm, okay then no idea why it works for you. Maybe some difference between arm64 and amd64? But yeah, really no clue.

**Comment by szaimen** [comment]
btw, one workaround that I've found is disabling imagemagick but this will show a warning in the admin overview so is really only a workaround.

**Comment by EgonHeuson** [comment]
Hello! I did some quick behavior tests and here are the results (on my amd64 config).
When I add an avatar to a user, its avatar is generated correctly, and it can see the avatars of the users that added avatars to themselves before him somehow. 
I noticed I had this problem too this evening, then to test I added a Dog avatar to a test account just to see if it was only coming from the letters avatar or from all. Strangely it seems to propagate as it can be seen below.
Here is what I see if I connect to my account:
<img width="315" alt="2023-01-24_23-40-37" src="https://user-images.githubusercontent.com/32910291/214437503-5700e563-2fa9-4fd5-8f41-35f75d7c01dd.png">
Then I tested the same with the admin account to check, and I get this when I'm connected with this account:
<img width="43" alt="2023-01-24_23-44-13" src="https://user-images.githubusercontent.com/32910291/214437723-32d759de-bd2b-4586-af96-148eeb1cc1bb.png">
So it seems to see all the avatars. But when I come back to my account, I still cannot see the one of my admin account: 
<img width="43" alt="2023-01-24_23-45-41" src="https://user-images.githubusercontent.com/32910291/214437949-08b819b4-c9cd-429e-a550-cc962b7d72ae.png">
Same for a 4th account I tested, but this time it can see its own avatar, but not the one of my account like the Admin account.
I don't know if this might help you or not? I can do some more testing if you like :-)

**Comment by EgonHeuson** [comment]
Samll update on this :-) This morning, I just reconnected to my nextcloud account and now I can see the avatar of my admin account :-) However, it is not the good one showing 😅. Here is what I get from my user account: 
![2023-01-25_10-07-07](https://user-images.githubusercontent.com/32910291/214523355-8e84a276-8827-44f1-ae95-c33af2690995.png)
And here is what I get from my admin account (when I go to "users"):
![2023-01-25_10-09-49](https://user-images.githubusercontent.com/32910291/214523473-8f569832-0d85-46dd-9518-bf13a5b49f06.png)
The second image is the actual one. The first one is one image I first uploaded yesterday evening to see it it worked, and then I uploaded the second one. Strange no?
Also, I asked a friend of mine who has an account to add a picture. And 1) it could yesterday see all of the ones that where already uploaded to my user accounts and my admin account, and 2) I now can see his avatar while I could not see it yesterday evening just after it uploaded it.
I have to precise that I execute this command every night at 3am via a Cron job: `docker exec --user www-data nextcloud-aio-nextcloud /var/www/html/occ files:scan --all`
It is to update the files that I may have manually added in my Nextcloud folder on my NAS. But maybe it refreshes something else? 
One last thought, I feel like when somebody adds up a new avatar, the people who does it sees the ones of the people that already uploaded their avatar before him, but not those who did it after. And more that it might get reseted on specific action/command/event, or maybe it just take some time to propagate to the other users? 
You didn't propose a mastercontainer update the last night, right?

**Comment by szaimen** [comment]
Thanks for your posts @EgonHeuson! However the more I think about your findings, the more I think that this is a different bug than the one that this issue is about. The bug which this issue is about is only about the default avatars not getting generated correctly.

**Comment by EgonHeuson** [comment]
Argh damned! 😅 I also have the issue with default avatars generation but hard to distinguish if it is link to the other issue in my case or not... 😥

**Comment by VitaleyUsa** [comment]
Sorry for the long reply.
Just did a quick test with profile avatars when i'm not logged in: i can see generated avatar picture (but with one letter instead of two)
for example: when i'm already logged in, only background shown with no letters
when i'm logged out and just checking profile link of the same user: i can see letter on profile pic:
![image](https://user-images.githubusercontent.com/36405102/215278122-1d4b13ff-0a40-4b6a-9d6d-1a776e192b8c.png)

or maybe i not properly cleaned avatar cache?

**Comment by szaimen** [comment]
> or maybe i not properly cleaned avatar cache?

Can you clear the browser cache ans check if it still works?

**Comment by VitaleyUsa** [comment]
> > or maybe i not properly cleaned avatar cache?
> 
> Can you clear the browser cache ans check if it still works?

it works, i'm testing in incognito to remove cache factor :)

**Comment by szaimen** [comment]
All right. Just tried on my test instance and avatar generation of single name users does not work even in incognito tab. Are you on arm64?

**Comment by VitaleyUsa** [comment]
> All right. Just tried on my test instance and avatar generation of single name users does not work even in incognito tab. Are you on arm64?

`Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         40 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  2
  On-line CPU(s) list:   0,1
Vendor ID:               AuthenticAMD
  Model name:            Common KVM processor
    CPU family:          15
    Model:               6
    Thread(s) per core:  1
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            1
    BogoMIPS:            4599.99
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx lm
                         rep_good nopl cpuid extd_apicid tsc_known_freq pni cx16 x2apic hypervisor cmp_legacy 3dnowprefetch vmmcall
Virtualization features:
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   128 KiB (2 instances)
  L1i:                   128 KiB (2 instances)
  L2:                    1 MiB (2 instances)
  L3:                    32 MiB (2 instances)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0,1
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Not affected
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, STIBP disabled, RSB filling
  Srbds:                 Not affected
  Tsx async abort:       Not affected
`

i'm noticed that in incognito mode i have dif. language: 
![image](https://user-images.githubusercontent.com/36405102/215278122-1d4b13ff-0a40-4b6a-9d6d-1a776e192b8c.png)

when i'm logged in: 
![image](https://user-images.githubusercontent.com/36405102/215282186-872f32bc-1c15-4de2-9c5f-84480e74b942.png)

**Comment by szaimen** [comment]
So it seems to work for you correctly on x64. Now I am even more clueless...

**Comment by VitaleyUsa** [comment]
> So it seems to work for you correctly on x64. Now I am even more clueless...

no! sorry, deleted my upd: it's what i have when i'm using ur hack from another thread

**Comment by VitaleyUsa** [comment]
Sorry for misunderstand.
I did last screen (with ur fix from another thread) only to show u that i have dif. language.
But when i have no fix enabled, it shows letters only when i'm not logged in.

**Comment by szaimen** [comment]
> But when i have no fix enabled, it shows letters only when i'm not logged in.

Which fix? you mean disabling imagemagick?

**Comment by VitaleyUsa** [comment]
> > But when i have no fix enabled, it shows letters only when i'm not logged in.
> 
> Which fix? you mean disabling imagemagick?

https://github.com/nextcloud/server/issues/34755#issuecomment-1402444083

**Comment by szaimen** [comment]
This comment is not made by me.

**Comment by VitaleyUsa** [comment]
Ooooooh, all this time i thought it was yours :(
sorry!

**Comment by szaimen** [comment]
All good!

**Comment by VitaleyUsa** [comment]
Just did another test with no fix:
1. That's what i have when i'm logged in:
![image](https://user-images.githubusercontent.com/36405102/215316624-259c3887-6e64-4e07-aab9-d2377c1fbe25.png)

2. That's what i have when i'm not logged in (no cache):
![image](https://user-images.githubusercontent.com/36405102/215316641-89fc0fea-3984-477b-95d4-279f87a92e1e.png)

Also, i decide to check what happening when i'm cleaning avatar folder:
1. When i'm logged in:
![image](https://user-images.githubusercontent.com/36405102/215316754-abb111f7-9eba-4790-b338-1ded7091bda9.png)

2. When i'm not logged in:
![image](https://user-images.githubusercontent.com/36405102/215316779-e8a91715-56ae-439e-89be-a62293dee309.png)

Seems like, when i'm not logged in profile pictures generating in some other place (not in data/appdata_xxxxx/avatar):
![image](https://user-images.githubusercontent.com/36405102/215316911-b0c95f66-9b9a-47ac-a045-cb51827dfa7e.png)

So.. when you not logged in, nextcloud uses different way yo show profile picture, it's not generated then. I checked source code of the page (changed name to "Test"):
![image](https://user-images.githubusercontent.com/36405102/215317751-15205037-6c57-440d-9d52-bb7776fcf803.png)

the result:
![image](https://user-images.githubusercontent.com/36405102/215317767-2b221a1f-1457-45d2-ac62-1bae0e076100.png)

probably, no point to search in this way, cuz it has dif. way of profile pic. generation

**Comment by VitaleyUsa** [comment]
@szaimen 

i'm not a programmist, so don't know, how it should be right

https://github.com/nextcloud/server/blob/v25.0.0/lib/private/Avatar/Avatar.php#L142

is it right that this line looks like this: catch (\Exception $e)
because if i changing it to: catch (Exception $e)
(removing escape symbol before Exception)
it starts working as expected

so in summary:
1. remove avatar cache from nc folder and from browser
2. only remove escape symbol in Avatar.php in 142 line "catch (Exception $e)"
3. generate avatars by php occ files:scan-app-data avatar 
4. it works like a charm now

**Comment by szaimen** [comment]
Sorry, I have also already played with this a lot and no changes i catching the exception make any difference on my test instance. So it should work since now error is thrown but it doesnt generate the avatar. As you, I am out of ideas but thanks for your attempt!

**Comment by szaimen** [comment]
Cross-linking https://github.com/nextcloud/server/issues/36607 here. However I'll hope that we find a solution to this sooner.

**Comment by spss20** [comment]
I've been following this issue for a long time. Why is there no solution yet for a simple thing? It's been months.

**Comment by szaimen** [comment]
> Why is there no solution yet for a simple thing? It's been months.

Because we didnt found a solution yet. See our investigations and attempts above. 

If you have further ideas on a technical solution, feel free to post them here.

**Comment by spss20** [comment]
@szaimen Thanks for updating. However i would like to bring the fact that there is no such issue in the docker standalone version of nextcloud. The problem exists only in all-in-one installation of nextcloud. Just curious.

**Comment by szaimen** [comment]
> However i would like to bring the fact that there is no such issue in the docker standalone version of nextcloud.

did you use the fpm-alpine image or the apache version?

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/issues/34755#issuecomment-1488363838

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/pull/37378
