### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#164]
Internal server error

The server could not complete the request.

If this happens again, please send the technical details below to your server administrator.

More details can be found in the server log.

Appears when I try to configure the Gestion app or the user defined menu app in the admin settings.

**Comment by szaimen** [comment]
Hi, thanks for your report! are there any error messages regarding this in your logs? 
You should find them in `https://your-nextcloud-domain.com/settings/admin/logging` (use an admin account for that)

**Comment by R7JANV1** [comment]
Error index Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing a query: SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "id" of relation "oc_gestion_configuration" violates not-null constraint DETAIL: Failing row contains (null, Your company name, Your company contact first name, Your company contact name, Your limited liability company, Your company unique identifier, Your company email, Your company phone number, Your company address, /, Any legal notices, disclaimers, or anything that . .., 0, 0, EUR, 1).	
2022-01-23T15:17:24+0100
Error PHP Error: Undefined variable $mailer at /var/www/html/custom_apps/gestion/lib/Controller/PageController.php#42	
2022-01-23T15:17:24+0100
PHP Error: Undefined variable $mailer at /var/www/html/custom_apps/gestion/lib/Controller/PageController.php#42

**Comment by szaimen** [comment]
Thanks for the log! I fear this is an issue of the gestion app with postgresql so nothing we can fix here. Please report this to https://github.com/baimard/gestion Thanks!
