### ISSUE TITLE
document cannot be exported

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#165]
The following error message appears when I try to print a file in Nextcloud Office.
The document cannot be exported. Contact the administrator of the storage server.

**Comment by szaimen** [comment]
Hi, thanks for your report! are there any error messages regarding this in your logs? 
You should find them in `https://your-nextcloud-domain.com/settings/admin/logging` (use an admin account for that)

**Comment by R7JANV1** [comment]
No error is output.

**Comment by szaimen** [comment]
Also, please open the logs of collabora in the aio interface which are probably useful as well :)

**Comment by szaimen** [comment]
It should be this button: 
![image](https://user-images.githubusercontent.com/42591237/150683432-76a37fab-a31d-4da4-b995-d6201b5611ff.png)

**Comment by szaimen** [comment]
@R7JANV1 could you please post some steps how to reproduce the issue?

**Comment by R7JANV1** [comment]
Yes, of course, I have not yet found the time to view the logs of the container. The NC runs on Ubuntu 20.4 LTS and a simple Nextcloud AIO installation. Create a new document (with Nextcloud Office suit) then click on print and then the error should show up.

**Comment by szaimen** [comment]
I fear there is nothing we can do here as we simply reuse the collabora container and follow the documentation for connecting it. So i either suspect an issue with the nextcloud connector app or collabora itself.

**Comment by R7JANV1** [comment]
The problem persists, what to do? Maybe make Nextcloud or Collabora aware of the problem?

**Comment by szaimen** [comment]
I fear either the problem was not reported yet or they weren't able to fix it until now. Feel free to open a new issue about this in the correct repo. Thank you!
