### ISSUE TITLE
Talk HPB doesn't seem to work on arm64 

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#169]
No connection possible; Error message:

```
[31m[ERR][0m [dtls.c:janusdtlssrtpincomingmsg:869] [3054062946470231] Oops, error creating inbound SRTP session for component 1 in stream 1??
```

**Comment by szaimen** [comment]
Here is potential solution: https://help.nextcloud.com/t/janus-libsrtp-2-3-oops-error-creating-inbound-srtp-session-for-component-1-in-stream-1/86962/5?u=szaimen

**Comment by MariusQuabeck** [comment]
happy to help debugging this further on my arm64 install. just ping me :)

**Comment by szaimen** [comment]
Thanks, will do :)

**Comment by szaimen** [comment]
linked to https://gitlab.com/packaging/janus/-/issues/4#note_822681648

**Comment by szaimen** [comment]
Hi @MariusQuabeck please update your containers and check if it solves the issue that you've experience. Thanks! :)

**Comment by MariusQuabeck** [comment]
Hi,
I've updated the containers and mastercontainer but no luck. I've tried it using Safari and Firefox.
Safari: I see my preview but the call gets disconnected after a few seconds
Firefox: apparently stays in the call but never displays any feeds from participants

please find log attached
https://cloud.nft-gebrauchtwarenhandel.de/s/ePAwEWikBwgL8wj

**Comment by MariusQuabeck** [comment]
It seems to work now after the latest container update! More testing on my end needed tho

**Comment by szaimen** [comment]
> It seems to work now after the latest container update! 

Very nice! Thanks for testing :)

> More testing on my end needed tho

Let me know if there are further problems.

**Comment by MariusQuabeck** [comment]
after some more testing with up to 6 people using different operating systems and browsers, I think we're good here! no issues, logs look normal and load is as expected.
thank you for solving this so quickly!

**Comment by szaimen** [comment]
Great to hear! Thanks for letting me know!
