### ISSUE TITLE
Avatar is coming black by default

### ISSUE THREAD

**Issue by spss20** [nextcloud/all-in-one#1703]
# Avatar not working as expected
Hello All,

I am new to the community. First of all, I would like to take time to thank each and every engineer working on this for their hard work and dedication. 

Recently I did a fresh installation of nextcloud using this repository. I noticed that the profile images for users' admin and other users which I've just created are coming to pitch black which I think might not be a default behaviour in such big project.

### Expected Behaviour:  I think it should automatically make an avatar pick up the first letter of the user's name or it should just choose any random picture for every user. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/29224720/211336277-059eb4b2-d831-4e75-9b8e-5debac21e375.png">

**Comment by szaimen** [comment]
Hi, this is already tracked in https://github.com/nextcloud/all-in-one/issues/1628
