### ISSUE TITLE
Traefik documentation references an unknown middleware

### ISSUE THREAD

**Issue by hunhejj** [nextcloud/all-in-one#1720]
In the Traefik reverse proxy example `middlewares-rate-limit` is referenced, however that middleware is not described. Either it's definition should be added to the middleware examples or it shold be removed from the middleware chain (or converted to a comment instead telling that you could have your additional middlewares here).

**Comment by szaimen** [comment]
Hi, unfortunately I dont know much about Treafik. Would it be fine to simply remove the middelware?

**Comment by hunhejj** [comment]
Sure

**Comment by szaimen** [comment]
Yes, please do. Thanks a lot! :)

**Comment by hunhejj** [comment]
Here you are @szaimen https://github.com/nextcloud/all-in-one/pull/1726
