### ISSUE TITLE
Nextcloud AIO doesn't set 'default_phone_region'

### ISSUE THREAD

**Issue by nuschpl** [nextcloud/all-in-one#1779]
### Steps to reproduce
1. Install Nexcloud All-in-One
2. Set all available configuration available via UI
3. In the overwiev configuration issues within admin panel get informationGet warning that you need to manually set 'default_phone_region' 

### Expected behavior 
Have the possibility to set the option as part of install process or withing the admin panel

### Actual behavior 
User need to be aware about AIO architecture and probably manually change on of the containers configuration. The panel points user to installation instructions while setting this specific variable is not part of the process.

### Host OS 
not relevant

#### Nextcloud AIO version 
[Nextcloud Hub 3](https://nextcloud.com/) (25.0.2)

**Comment by szaimen** [comment]
There should be a UI optionn in server that allows to set this directly - nothing we will built into AIO.

However see this: https://github.com/nextcloud/all-in-one#how-to-resolve-security--setup-warnings-displays-the-missing-default-phone-region-after-initial-install
