### ISSUE TITLE
Restoring backup from non-Arm server to Arm server causes issues when clamAV was enabled

### ISSUE THREAD

**Issue by RikkiBC** [nextcloud/all-in-one#1783]
Steps to reproduce:

1. On non-Arm server, have clamAV as one of the selected Docker containers.
2. Take backup.
3. Move backup to server with Arm architecture 
4. Install Arm version of AIO.
5. Restore From Backup.

Issue encountered:

1. ClamAV container is marked as unselectable due to it not running on Arm server, however because it was on/checked in the previous setup/backup, it's unselectable as checked, not unchecked. So you can't un-check it.
2. This also means it's waiting to turn on with the rest of the containers.
3. Trying to turn on the containers inevitably fails, as ClamAV encounters errors.

Workaround:

Turning one of the other containers off and hitting Save Changes also turns off the unselectable ClamAV container. You can then turn back on the container you'd turned off.

Better fix:

When restoring from backup on the Arm version of AIO, immediately disable ClamAV container (perhaps with a message explaining why?) if it was enabled in the backup, rather than restoring into a semi-broken state.

**Comment by szaimen** [comment]
Thanks for the report! I'll have a look soon.

**Comment by szaimen** [comment]
Fix is in https://github.com/nextcloud/all-in-one/pull/1785

**Comment by szaimen** [comment]
This is now released with v4.3.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
