### ISSUE TITLE
After upgrade to 0.2.1 stuck in maintenance mode: Upgrade needed

### ISSUE THREAD

**Issue by TheNomad11** [nextcloud/all-in-one#182]
I updated from 0.2.0 to 0.2.1 and it failed :(

First after upgrading the "maintence mode" message appeared. Then I run the command 

`sudo docker exec -it nextcloud-aio-nextcloud php occ maintenance:mode --off` 

The terminal answered:

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
```

Nextcloud's maintenance message disappeared and was replaced by 

```
Update needed
Please use the command line updater because automatic updating is disabled in the config.php
```

Running 

`sudo docker exec -it nextcloud-aio-nextcloud php occ upgrade`

results in following answer:

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
UnexpectedValueException: The files of the app "updatenotification" were not correctly replaced before running the update
Update failed
Maintenance mode is kept active
Resetting log level
```

I will try to restore from backup now

**Comment by szaimen** [comment]
Hi there 👋

Thanks for your report! This should already be fixed with https://github.com/nextcloud/all-in-one/commit/20d631b600e6eb59146d3b71e85c974348709dbe and I also already updated the nextcloud container with the fix. 

So it should already be fixed since saturday evening :)

**Comment by TheNomad11** [comment]
Thanks so much! Upgrade went fine now :)

**Comment by szaimen** [comment]
> Thanks so much! Upgrade went fine now :)

Great! Thanks for the feedback :)
