### ISSUE TITLE
Migration steps do not copy data folder to the correct place

### ISSUE THREAD

**Issue by tyleraharrison** [nextcloud/all-in-one#1842]
### Steps to reproduce
Follow migration instructions here: https://github.com/nextcloud/all-in-one/blob/main/migration.md
1. Run `sudo docker cp --follow-link /path/to/nextcloud/data/ nextcloud-aio-nextcloud:/mnt/ncdata/`
2. Wonder why data folder is in the data folder
3. Cry?

### Expected behavior
The data folder should have unpacked into the destination Docker data folder, instead 
```
.
├── data
│   └── (all of the users/database/external files/etc.)
```

### Actual behavior
It nests a new data folder inside of the existing one.
```
.
├── data
│   └── data
```

### Host OS 
Alpine LXC with Docker in Proxmox w/ nested virtualization enabled. Everything is fine, just a documentation issue I believe.

#### Nextcloud AIO version 
`25.0.3`

#### Current channel 
`stable`

#### Other valuable info 
(Original comment here: https://github.com/nextcloud/all-in-one/pull/1839#issuecomment-1405772049)
I noticed this docker cp command actually puts the data folder inside the data folder. Maybe it needs to be a data/* or something along those lines. I had to manually move all of the data folder to .. to fix it.

**Comment by szaimen** [comment]
I'll take a look at this later. Maybe @ManOki can help? :)

**Comment by szaimen** [comment]
I just tested and cannot reproduce this. If you make sure that you have a trailing slash here: `/path/to/nextcloud/data/` it should work correctly. Make sure that this is the folder containing your former datadir.
