### ISSUE TITLE
error code antivirus app

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#186]
The following error code is displayed. Error due to NC AIO or the antivirus app

<html><body>

Fehler | files_antivirus | RuntimeException: The antivirus executable could not be found at /usr/bin/clamscan<<closure>>OCA\Files_Antivirus\Scanner\LocalClam->__construct(OCA\Files_An ... {}, OC\Log {}, OCA\Files_An ... {})/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 106: ReflectionClass->newInstanceArgs([ OCA\Files_ ... }])/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 114: OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionCl ... "})/var/www/html/custom_apps/files_antivirus/lib/Scanner/ScannerFactory.php - line 45: OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Files_ ... m")/var/www/html/custom_apps/files_antivirus/lib/BackgroundJob/BackgroundScanner.php - line 335: OCA\Files_Antivirus\Scanner\ScannerFactory->getScanner()/var/www/html/custom_apps/files_antivirus/lib/BackgroundJob/BackgroundScanner.php - line 122: OCA\Files_Antivirus\BackgroundJob\BackgroundScanner->scanOneFile(OC\Files\Node\File {})/var/www/html/lib/private/BackgroundJob/Job.php - line 51: OCA\Files_Antivirus\BackgroundJob\BackgroundScanner->run(null)/var/www/html/lib/private/BackgroundJob/TimedJob.php - line 58: OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})/var/www/html/cron.php - line 128: OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
-- | -- | --

</body>
</html>

**Comment by szaimen** [comment]
Hi, you need to make sure that nextcloud is able to talk to clamav. the best way is to add a clamav container and add it to the nextcloud-aio network. Then nextcloud should be able to talk to clamav using the correct port. 

But honestly I will not help further here as clamav is planned here: https://github.com/nextcloud/all-in-one/issues/78

**Comment by R7JANV1** [comment]
oh sorry! Thank you that was helpful
