### ISSUE TITLE
Error: disk_free_space(): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#381

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#187]
This problem occurs when I open an dir but I still can access the files...
Only showing in the log, no problem using NC.

[nc-err.pdf](https://github.com/nextcloud/all-in-one/files/7978874/nc-err.pdf)

AIO 0.2.1 
Nextcloud 23.0.1
Debian 11
Docker version 20.10.5+dfsg1, build 55c4c88
Let's Encrypt

Not a physical disk problem : 

[nc-err-disk.pdf](https://github.com/nextcloud/all-in-one/files/7978912/nc-err-disk.pdf)

What can I provide to help solving this problem ?

**Comment by szaimen** [comment]
Hi, it seems like somehow the database got out of sync with the files. Did you maybe changed the files externally? 
Can you please try to run `sudo docker exec -it nextcloud-aio-nextcloud php occ files:scan --all` and report back if it fixes the issue? Thanks!

**Comment by szaimen** [comment]
Hm... Maybe another idea: `sudo docker exec -it nextcloud-aio-nextcloud php occ files:scan-app-data`

Otherwise looking at the nextcloud logs should be sufficient. Please share the raw log. That should help. Thanks!

**Comment by marcatsmci** [comment]
Done

**Comment by marcatsmci** [comment]
I think it's ok now. No more message after `files:scan-app-data`
Bravo !

**Comment by szaimen** [comment]
Seems like this is actually a bug...
https://github.com/nextcloud/server/issues/30992

**Comment by marcatsmci** [comment]
I confirm, the message came back ;-(
