### ISSUE TITLE
Host 10.0.17.6 was not connected to because it violates local access rules

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#188]
This ip is the server's ip behind my vpn : 

`[no app in context] Warning: Host 10.0.17.6 was not connected to because it violates local access rules
GET /core/preview?fileId=11436&c=aceb6a0c5957df016e3c081536f8a2d7&x=250&y=250&forceIcon=0&a=0
from 10.3.17.2 by f3nix at 2022-02-01T13:32:29+00:00`

`{"reqId":"x7xjPnEzno9pfCRIQaAA","level":2,"time":"2022-02-01T13:32:29+00:00","remoteAddr":"10.3.17.2","user":"f3nix","app":"no app in context","method":"GET","url":"/core/preview?fileId=11436&c=aceb6a0c5957df016e3c081536f8a2d7&x=250&y=250&forceIcon=0&a=0","message":"Host 10.0.17.6 was not connected to because it violates local access rules","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0","version":"23.0.1.2","id":"61f9366dd3abc"}`

I added the ip in the config file as a `trusted_domains` : 

1. is this the good way ?
2. Is the config file automatically taken into account or do I have to restart the containers?

**Comment by szaimen** [comment]
Hi, I am honestly not sure what you did. Can you please add some steps how to reproduce this issue? Thanks!

**Comment by marcatsmci** [comment]
I don't know how this happens: I just noticed the ip... But I don't do any specific action...
To try to correct I inserted the ip in the `trusted_domains` constant.

[ip.pdf](https://github.com/nextcloud/all-in-one/files/7979205/ip.pdf)

**Comment by szaimen** [comment]
Hm... Maybe you could try to add this to the config.php and report back if it fixes the issue:

`'allow_local_remote_servers' => true,`

**Comment by marcatsmci** [comment]
OK, added...
Is the config file automatically taken into account or do I have to restart the containers?

**Comment by szaimen** [comment]
It should be automatically taken into account.

**Comment by marcatsmci** [comment]
No more messages => ok !
Thanks !

**Comment by szaimen** [comment]
Thanks for testing! This needs to be solved for everyone so I am reopening this.
