### ISSUE TITLE
Huge logs

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#193]
After a few days, the Nextcloud log become very large, 233'000 lines from last restart.

Is something like logrotate active ?

**Comment by szaimen** [comment]
> After a few days, the Nextcloud log become very large, 233'000 lines from last restart.

That is strange. Did you maybe changed the loglevel to 0 or 1? (It should be at 2)

> Is something like logrotate active ?

Yes, see https://github.com/nextcloud/all-in-one/blob/3041e51b047b74d6a5224df3f7cebd77948e2a3f/Containers/nextcloud/entrypoint.sh#L153

**Comment by marcatsmci** [comment]
> Did you maybe changed the loglevel to 0 or 1? (It should be at 2)

No it's 2, with logrorate at 10485760

**Comment by szaimen** [comment]
Do you have repeating lines that get triggered continuosly?

**Comment by szaimen** [comment]
Could you maybe run the following command and report the output? 
`docker exec -it nextcloud-aio-nextcloud ls -l /var/log/nextcloud/nextcloud.log`

**Comment by marcatsmci** [comment]
`-rw-r----- 1 www-data www-data 862339 Feb  3 17:25 /var/log/nextcloud/nextcloud.log`

Strange : wc -l says 442 lines...

When I dump log from AIO interfacce > Nextcloud I get a 233'000 lines response, with many repetitions : 


172.19.0.8 -  04/Feb/2022:09:34:59 +0000 "GET /index.php" 200
172.19.0.8 -  04/Feb/2022:09:34:59 +0000 "GET /index.php" 200
172.19.0.8 -  04/Feb/2022:09:34:59 +0000 "GET /ocs/v2.php" 200
172.19.0.8 -  04/Feb/2022:09:34:59 +0000 "GET /ocs/v2.php" 200
172.19.0.8 -  04/Feb/2022:09:35:00 +0000 "GET /index.php" 200
172.19.0.8 -  04/Feb/2022:09:35:06 +0000 "GET /index.php" 200
172.19.0.8 -  04/Feb/2022:09:35:06 +0000 "PUT /index.php" 200
172.19.0.8 -  04/Feb/2022:09:35:06 +0000 "GET /index.php" 200
172.19.0.8 -  04/Feb/2022:09:35:06 +0000 "GET /index.php" 304
172.19.0.8 -  04/Feb/2022:09:35:06 +0000 "POST /index.php" 200
172.19.0.8 -  04/Feb/2022:09:35:06 +0000 "GET /ocs/v2.php" 200
172.19.0.8 -  04/Feb/2022:09:35:06 +0000 "GET /index.php" 200
172.19.0.8 -  04/Feb/2022:09:35:06 +0000 "PUT /index.php" 200
172.19.0.8 -  04/Feb/2022:09:35:06 +0000 "GET /ocs/v2.php" 200
172.19.0.8 -  04/Feb/2022:09:35:06 +0000 "GET /ocs/v2.php" 200
172.19.0.8 -  04/Feb/2022:09:35:07 +0000 "GET /index.php" 304
172.19.0.8 -  04/Feb/2022:09:35:07 +0000 "GET /index.php" 200
172.19.0.8 -  04/Feb/2022:09:35:07 +0000 "GET /index.php" 304
172.19.0.8 -  04/Feb/2022:09:35:07 +0000 "POST /index.php" 302

**Comment by szaimen** [comment]
> `-rw-r----- 1 www-data www-data 862339 Feb 3 17:25 /var/log/nextcloud/nextcloud.log`
> 
> Strange : wc -l says 442 lines...

That one is the nextcloud log that you can see in the admin interface in the loggin section.

> When I dump log from AIO interfacce > Nextcloud I get a 233'000 lines response, with many repetitions :
>
> 172.19.0.8 - 04/Feb/2022:09:34:59 +0000 "GET /index.php" 200 172.19.0.8 - 04/Feb/2022:09:34:59 +0000 "GET /index.php" 200 172.19.0.8 - 04/Feb/2022:09:34:59 +0000 "GET /ocs/v2.php" 200 172.19.0.8 - 04/Feb/2022:09:34:59 +0000 "GET /ocs/v2.php" 200 172.19.0.8 - 04/Feb/2022:09:35:00 +0000 "GET /index.php" 200 172.19.0.8 - 04/Feb/2022:09:35:06 +0000 "GET /index.php" 200 172.19.0.8 - 04/Feb/2022:09:35:06 +0000 "PUT /index.php" 200 172.19.0.8 - 04/Feb/2022:09:35:06 +0000 "GET /index.php" 200 172.19.0.8 - 04/Feb/2022:09:35:06 +0000 "GET /index.php" 304 172.19.0.8 - 04/Feb/2022:09:35:06 +0000 "POST /index.php" 200 172.19.0.8 - 04/Feb/2022:09:35:06 +0000 "GET /ocs/v2.php" 200 172.19.0.8 - 04/Feb/2022:09:35:06 +0000 "GET /index.php" 200 172.19.0.8 - 04/Feb/2022:09:35:06 +0000 "PUT /index.php" 200 172.19.0.8 - 04/Feb/2022:09:35:06 +0000 "GET /ocs/v2.php" 200 172.19.0.8 - 04/Feb/2022:09:35:06 +0000 "GET /ocs/v2.php" 200 172.19.0.8 - 04/Feb/2022:09:35:07 +0000 "GET /index.php" 304 172.19.0.8 - 04/Feb/2022:09:35:07 +0000 "GET /index.php" 200 172.19.0.8 - 04/Feb/2022:09:35:07 +0000 "GET /index.php" 304 172.19.0.8 - 04/Feb/2022:09:35:07 +0000 "POST /index.php" 302

That one is the docker log and it has indeed no logrotation. I also wouldn't know how to activate something like that...

We could maybe try to load only the latest 500 lines or so. What do you think about that idea?

**Comment by marcatsmci** [comment]
`172.19.0.8` is an internal address used by NC-AIO ?

**Comment by szaimen** [comment]
> `172.19.0.8` is an internal address used by NC-AIO ?

that is probably the internal ip address of the apache container...

**Comment by marcatsmci** [comment]
> > `172.19.0.8` is an internal address used by NC-AIO ?
> 
> that is probably the internal ip address of the apache container...

okay

**Comment by marcatsmci** [comment]
> That one is the docker log and it has indeed no logrotation. I also wouldn't know how to activate something like that...
> 
> We could maybe try to load only the latest 500 lines or so. What do you think about that idea?

[https://sandro-keil.de/blog/logrotate-for-docker-container/](https://sandro-keil.de/blog/logrotate-for-docker-container/)

I try this and all seems to be ok : newly created *.log.1

**Comment by szaimen** [comment]
Okay sounds great but I guess this is nothing we can do feom inside a docker container?

**Comment by szaimen** [comment]
What I head in mind was somehow limiting the output here: https://github.com/nextcloud/all-in-one/blob/3041e51b047b74d6a5224df3f7cebd77948e2a3f/php/src/Docker/DockerActionManager.php#L123-L143 or doesn't that make sense?

**Comment by marcatsmci** [comment]
> Okay sounds great but I guess this is nothing we can do from inside a docker container?

No idea ;-(

At least an entry in the documentation - README

**Comment by marcatsmci** [comment]
> or doesn't that make sense?

When you make an update, if the log is too short, maybe you will miss something...

Proposition : show the list of logs and the 100 last lines of the current log. 

Maybe the ability to clic on the list tou open the corresponging log ?

**Comment by szaimen** [comment]
Hm... What do you think about an option to specifiy the max number of lines that get shown to you?
(Would be at infinite by default)

**Comment by marcatsmci** [comment]
> Hm... What do you think about an option to specifiy the max number of lines that get shown to you? (Would be at infinite by default)

The problem is not the # of lines to show but the lack of logrotate, I think. So for me the # is up to you...

**Comment by szaimen** [comment]
Okay, then I'll add a point to the readme. Thanks for the reply!
