### ISSUE TITLE
improve readme and .md files for better readability

### ISSUE THREAD

**Issue by privatemaker** [nextcloud/all-in-one#1945]
### Is your feature request related to a problem? Please describe. 

While manageable, the existing `readme.md` at 682 lines is getting a bit long and less than ideal to find what one is looking for quickly.

### Describe the solution you'd like

I can think of three solutions:

1. Tuck more information into `<details><summary>...` collapsible sections
2. Split up `readme.md` and migrate along with other `.md` files to static site like [docs.nextcloud.com](https://docs.nextcloud.com)
3. Use Github Wiki feature

### Describe alternatives you've considered

Personally, I think option 2. is better fitting as it allows nicer styling and attention to various things. Followed by option 3. 

### Additional context

I am happy to contribute either solution if it well received.

**Comment by DenuxPlays** [comment]
Can't we use the github wiki feature?
Would be a good option too I guess.

**Comment by privatemaker** [comment]
@DenuxPlays true. updated my issue
