### ISSUE TITLE
Question (I could not find a concrete answer)

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#197]
Are backups to an externally connected hard drive already possible or is this coming or will this be added at all?

**Comment by szaimen** [comment]
Hi, it is already possible. See https://github.com/nextcloud/all-in-one#backup-solution

> If you connect an external drive to your host, and choose the backup directory to be on that drive, you are also kind of save against drive failures of the drive where the docker volumes are stored on.

**Comment by R7JANV1** [comment]
is the complete instance backed up with all content and settings or just the containers?

**Comment by szaimen** [comment]
The complete instance. But you should have https://github.com/nextcloud/all-in-one/issues/38 in mind which is not yet implemented

**Comment by R7JANV1** [comment]
Great, very helpful, thank you
