### ISSUE TITLE
NC AIO crashes when generating photo previews

### ISSUE THREAD

**Issue by monsieurhannes** [nextcloud/all-in-one#1988]
Hi,

I recently switched from NextcloudPi to AIO to have a more integrated Docker solution. NCP is more focused on an complete solution running the whole system.
Unfortunately I have some problems with the preview generator and I don't know why - as it was working in NCP, on the same hardware.

I installed Preview Generator and run it in the CLI, but after a while it takes the whole system down. I don't really know if it's due to the image size, but I already saw that the PHP-MEMORY-LIMIT is 512MB, which sounds more than the standard setting at 128MB, it should probably manage my 33 megapixel images, right?
It also doesn't necessarily seem to be the image size.

I'm currently on the beta-channel due to this issue: #1873 , could it be because of that? When I change to `latest`, the containers won't start...

## Server
Odroid N2 4GB RAM
Armbian Bullseye
Docker with Portainer
Nextcloud AIO v4.3.4

If you need any more information, I'm happy to provide it, but I'm not so experienced where to find things in the AIO-universe...

**Comment by szaimen** [comment]
Hi, this will be resolved with the update to nc26. You can follow https://github.com/nextcloud/all-in-one/issues/1846.
