### ISSUE TITLE
Finish Talk migration to alpine

### ISSUE THREAD

**Issue by Zoey2936** [nextcloud/all-in-one#1992]
Things that should be done after #1583 is finished

coturn:
- [x] https://github.com/coturn/coturn/pull/1156 to be merged
- [x] new coturn image release (https://github.com/coturn/coturn/releases)
- [x] change `FROM alpine:3.17.x` to latest `FROM coturn/cotrun:x.x.x-rx-alpine` (https://hub.docker.com/layers/coturn/coturn/4.6.2-alpine/images/sha256-52c5e7ec35da4f20b434883909fcafb30a4aa0c7de2f7112836e22eb33a04e58?context=explore)
- [x] remove coturn from normal `apk add` line

janus-gateway:
- [ ] alpine v3.18.1 release
- [ ] [coturn](https://github.com/coturn/coturn/blob/master/docker/coturn/alpine/Dockerfile) image updated to v3.18.1
- [ ] move janus gateway to normal `apk add` line and remove `apk add repository edge/community` line
- [ ] upgrade luarocks / lua-dev to 5.4
- [ ] wget needs to be tmp added and can be removed after luarocks installed everything

**Comment by Zoey2936** [comment]
maybe we could ask here; https://gitlab.alpinelinux.org/alpine/aports/-/issues what is missing that janus-gateway becomes available outside testing?

**Comment by szaimen** [comment]
Sounds good to me 👍

**Comment by Zoey2936** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/issues/14661

**Comment by Zoey2936** [comment]
that was a fast awnser (https://gitlab.alpinelinux.org/alpine/aports/-/issues/14661#note_293079)

**Comment by szaimen** [comment]
Oh wow!

**Comment by Zoey2936** [comment]
There is already a PR: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/44537

**Comment by szaimen** [comment]
Nice 🚀

**Comment by Zoey2936** [comment]
If they continue with this speed, janus-gateway is faster inside v3.17 then signaling is released and coturn is based on alpine 3.17

**Comment by Zoey2936** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/issues/14661#note_293460

**Comment by szaimen** [comment]
Wow, that was really fast! Okay, so it will be included in alpine 3.18, nice🎉

**Comment by Zoey2936** [comment]
@szaimen do you want to use the 4.6.2-r0-alpine or 4.6.2-alpine docker tag of coturn? and can you please create the PR?

**Comment by Zoey2936** [comment]
I've creted #2328

**Comment by Zoey2936** [comment]
Coturn got upgraded to alpine v3.18: https://github.com/coturn/coturn/commit/d526e7afcc2607d8f9206711dd2fe76208de1a09

**Comment by Zoey2936** [comment]
since we don't stick to reversions of the builds the next AIO build will container talk based on alpine 3.18, so we could move janus-gateway to the normal install line

**Comment by szaimen** [comment]
Oh really? I think we should actually pin the r0 version then for now. I'd like to wait for 3.18.1...

**Comment by Zoey2936** [comment]
yes
