### ISSUE TITLE
After Update of containers, the database wont start. Fails with import of database failed

### ISSUE THREAD

**Issue by ChojinDSL** [nextcloud/all-in-one#2008]
### Steps to reproduce
1. Stopped all the containers 
2. Updated master container
3. Updated all the containers
4. Try to start the containers

### Expected behavior 
It should work

### Actual behavior 
The nextcloud-aio-database container keeps crashing, with an error message in the container logs saying the database import failed and that I should restore from backup. 
I also tried to restore from backup, but it still keeps crashing and producing the same error.
### Host OS
Debian Bullseye 

#### Nextcloud AIO version
Nextcloud AIO v4.3.4
#### Current channel 
Latest
#### Other valuable info 
023-02-17 10:42:18.578 CET [12] LOG:  starting PostgreSQL 15.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-02-17 10:42:18.578 CET [12] LOG:  listening on IPv4 address "0.0.0.0", port 11000
2023-02-17 10:42:18.578 CET [12] LOG:  listening on IPv6 address "::", port 11000
2023-02-17 10:42:18.685 CET [12] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.11000"
2023-02-17 10:42:18.760 CET [109] LOG:  database system was shut down at 2023-02-17 10:42:18 CET
+ nc -z localhost 11000
+ GREP_STRING='Name: oc_appconfig; Type: TABLE; Schema: public; Owner:'
+ grep -q 'Name: oc_appconfig; Type: TABLE; Schema: public; Owner:' /mnt/data/database-dump.sql
++ grep 'Name: oc_appconfig; Type: TABLE; Schema: public; Owner:' /mnt/data/database-dump.sql
++ grep -oP 'Owner:.*$'
++ sed 's|Owner:||;s| ||g'
+ DB_OWNER=oc_nextcloud
+ '[' oc_nextcloud = nextcloud ']'
+ '[' oc_nextcloud '!=' oc_nextcloud ']'
+ echo 'Restoring the database from database dump'
Restoring the database from database dump
+ psql nextcloud_database -U nextcloud
2023-02-17 10:42:22.184 CET [118] FATAL:  the database system is starting up
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.11000" failed: FATAL:  the database system is starting up
The database import failed. Please restore a backup and try again.
For further clues on what went wrong, look at the logs above.

**Comment by szaimen** [comment]
Hi, thanks for the report. I've tested the migration around 10 times and it worked all the time. I also did not get any reports about this while it was in the beta channel.

This is likely caused by a overall slow system. I'll try to fix the migration for slow systems soon.

**Comment by ChojinDSL** [comment]
Thanks. Is there anything I can do for the time being? Rebuild a docker container, or setup some env vars?

**Comment by szaimen** [comment]
No, you need to wait for now. I'll create a new beta release with the fix soon.

**Comment by szaimen** [comment]
This is now released with v4.4.1 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel. After you switched the channel, restore a backup from before the broken update and start the containers again. Then it should hopefully work.
