### ISSUE TITLE
Manual installation fails if S3 primary storage is used

### ISSUE THREAD

**Issue by dhelonious** [nextcloud/all-in-one#2057]
When I use manual installation with the OBJECTSTORE_S3_* environment variables (see #1807), the setup fails because no appdata directores are created in the data directory. I think #1918 breaks S3 support and there should be an exception when OBJECTSTORE_S3_BUCKET is defined.

The object storage seems to be working since the bucket and objects inside of it are created by nextcloud during the setup process.

**Comment by szaimen** [comment]
This is now fixed with v4.5.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
