### ISSUE TITLE
Update Nextcloud AIO v4.3.4 - Database error

### ISSUE THREAD

**Issue by alenobad** [nextcloud/all-in-one#2060]
Hi,

I was updated to new version 4.3.4 from web. After update my container nextcloud-aio-database can't start. 
Logs of container: 
The database import failed. Please restore a backup and try again.
For further clues on what went wrong, look at the logs above.

**Comment by szaimen** [comment]
Hi, can you post the complete database logs here?

**Comment by alenobad** [comment]
Hi,

That is only logs from  nextcloud-aio-database:
The database import failed. Please restore a backup and try again.
For further clues on what went wrong, look at the logs above.

**Comment by szaimen** [comment]
Can you post the output of 
```
# Go into the container
sudo docker exec -it nextcloud-aio-database bash
```
```
# Get the import logs
cat $DUMP_DIR/database-import.log
exit
```

**Comment by alenobad** [comment]
Error response from daemon: Container nextcloud-aio-databaseis restarting, wait until the container is running

**Comment by alenobad** [comment]
Restoring from database dump.
+ rm -rf /var/lib/postgresql/data/PG_VERSION /var/lib/postgresql/data/base /var/lib/postgresql/data/global /var/lib/postgresql/data/pg_commit_ts /var/lib/postgresql/data/pg_dynshmem /var/lib/postgresql/data/pg_hba.conf /var/lib/postgresql/data/pg_ident.conf /var/lib/postgresql/data/pg_logical /var/lib/postgresql/data/pg_multixact /var/lib/postgresql/data/pg_notify /var/lib/postgresql/data/pg_replslot /var/lib/postgresql/data/pg_serial /var/lib/postgresql/data/pg_snapshots /var/lib/postgresql/data/pg_stat /var/lib/postgresql/data/pg_stat_tmp /var/lib/postgresql/data/pg_subtrans /var/lib/postgresql/data/pg_tblspc /var/lib/postgresql/data/pg_twophase /var/lib/postgresql/data/pg_wal /var/lib/postgresql/data/pg_xact /var/lib/postgresql/data/postgresql.auto.conf /var/lib/postgresql/data/postgresql.conf /var/lib/postgresql/data/postmaster.opts
+ export PGPORT=11000
+ PGPORT=11000
+ nc -z localhost 11000
+ exec docker-entrypoint.sh postgres
+ echo 'Waiting for the database to start.'
Waiting for the database to start.
+ sleep 5
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... sh: locale: not found
2023-02-20 22:14:43.294 UTC [30] WARNING:  no usable system locales were found
ok
syncing data to disk ... + nc -z localhost 11000
+ echo 'Waiting for the database to start.'
Waiting for the database to start.
+ sleep 5
ok

initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2023-02-20 22:14:47.353 UTC [38] LOG:  starting PostgreSQL 15.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-02-20 22:14:47.357 UTC [38] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.11000"
2023-02-20 22:14:47.373 UTC [41] LOG:  database system was shut down at 2023-02-20 22:14:44 UTC
2023-02-20 22:14:47.388 UTC [38] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-user-db.sh
+ touch /mnt/data/initialization.failed
+ psql -v ON_ERROR_STOP=1 --username nextcloud --dbname nextcloud_database
CREATE ROLE
ALTER DATABASE
GRANT
GRANT
+ rm /mnt/data/initialization.failed
+ set +ex

waiting for server to shut down...2023-02-20 22:14:48.265 UTC [38] LOG:  received fast shutdown request
.2023-02-20 22:14:48.270 UTC [38] LOG:  aborting any active transactions
2023-02-20 22:14:48.276 UTC [38] LOG:  background worker "logical replication launcher" (PID 44) exited with exit code 1
2023-02-20 22:14:48.277 UTC [39] LOG:  shutting down
2023-02-20 22:14:48.477 UTC [39] LOG:  checkpoint starting: shutdown immediate
..2023-02-20 22:14:50.544 UTC [39] LOG:  checkpoint complete: wrote 927 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.049 s, sync=0.224 s, total=2.267 s; sync files=257, longest=0.221 s, average=0.001 s; distance=4227 kB, estimate=4227 kB
2023-02-20 22:14:50.579 UTC [38] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2023-02-20 22:14:50.764 UTC [12] LOG:  starting PostgreSQL 15.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
2023-02-20 22:14:50.764 UTC [12] LOG:  listening on IPv4 address "0.0.0.0", port 11000
2023-02-20 22:14:50.764 UTC [12] LOG:  listening on IPv6 address "::", port 11000
2023-02-20 22:14:50.977 UTC [12] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.11000"
2023-02-20 22:14:50.988 UTC [59] LOG:  database system was shut down at 2023-02-20 22:14:50 UTC
+ nc -z localhost 11000
+ GREP_STRING='Name: oc_appconfig; Type: TABLE; Schema: public; Owner:'
+ grep -q 'Name: oc_appconfig; Type: TABLE; Schema: public; Owner:' /mnt/data/database-dump.sql
++ grep 'Name: oc_appconfig; Type: TABLE; Schema: public; Owner:' /mnt/data/database-dump.sql
++ grep -oP 'Owner:.*$'
++ sed 's|Owner:||;s| ||g'
+ DB_OWNER=oc_nextcloud
+ '[' oc_nextcloud = nextcloud ']'
+ '[' oc_nextcloud '!=' oc_nextcloud ']'
+ echo 'Restoring the database from database dump'
Restoring the database from database dump
+ psql nextcloud_database -U nextcloud
2023-02-20 22:14:51.470 UTC [68] FATAL:  the database system is starting up
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.11000" failed: FATAL:  the database system is starting up

**Comment by szaimen** [comment]
I see. This should already be resolved with AIO v4.4.1.

Please do the following steps:
1. Restore a backup from before the failed update via the AIO interface.
2. run `sudo docker rm nextcloud-aio-database` while the containers are still stopped
3. start the containers via the AIO interface again.

Let me know if that works!

**Comment by alenobad** [comment]
which is the best way to restore a backup?

**Comment by szaimen** [comment]
from the AIO interface or did you not create a backup before upgrading?

**Comment by alenobad** [comment]
I didn't create backup before upgrading

**Comment by szaimen** [comment]
Then I fear there is no way to fix this for you.

**Comment by alenobad** [comment]
Thanks for your time
