### ISSUE TITLE
postgresql version mismatch

### ISSUE THREAD

**Issue by mnaiman** [nextcloud/all-in-one#2101]
### Steps to reproduce
1. nextcloud container is based on alpine 3.16 and contain postgresql 14.7
2. postgresql container is based on postgres:15.2-alpine which is based on alpine 3.17 and contains postgresql 15.2

therefore postgresql commands like pg_dump not working across containers
possible other impacts too

### Expected behavior
same versions of postgres across containers

**Comment by szaimen** [comment]
Hi, the upgrade to 3.17 is tracked in https://github.com/nextcloud/all-in-one/issues/1782
