### ISSUE TITLE
AIO - Install - Behind NPM - No Connectivity w. Nextcloud Talk

### ISSUE THREAD

**Issue by geoff-scott** [nextcloud/all-in-one#2111]
### Discussed in https://github.com/nextcloud/all-in-one/discussions/2110

<div type='discussions-op-text'>

<sup>Originally posted by **geoff-scott** March  5, 2023</sup>
Hello everyone, perhaps you guys can help me.

I have a nextcloud aio installation behind a NPM  (NGINX Proxy Manager) install pointing at port 11000 (as per documentation). Everything works respectively well except nextcloud talk.  It has never has been able to connect two people together in a call ever since day one of install. I would like to know why, and how to fix it...as I am assuming that this is a heavily used feature that should work out of the box...since it was shipped with it.

Text chat works fine, just not video or audio.

Some info about system setup.

VPS - Contabo
Spec: 4 Core - 8GB RAM
800GB SSD
Nextcloud AIO - 4.5.0
Nextcloud Install 25.0.4
UFW enabled with 3478, 80, 443, 11000 allowed through.

I am a novice when it comes to configuring nextcloud aio or anything inside a docker system.

I will need some serious step by step instructions if you ask me to do something for diagnostics etc.
</div>

**Comment by Zoey2936** [comment]
I think the discussion is enough: #2110
