### ISSUE TITLE
Upload of larger files stuck after upload the first chunk

### ISSUE THREAD

**Issue by gadric** [nextcloud/all-in-one#2147]
I am trying to upload different larger files to my Nextcloud AIO but they stuck in the upload via WebGUI and also via Nextcloud Desktop App. It seems that for files larger than 20 mb, the ends in a connection timeout. I have than to restart the app to upload the next chunk. 

The smallest file that shows this kind of behaviour is 25mb, the biggest 1GB. 

My setup is behind a nginx reverse proxy and is setup extractly as described in the tutorial here. 

### Steps to reproduce
1. add files >20mb for upload. 
2. wait for upload
3. upload failes with connection timeout. 

### Expected behavior 
If file is too large, then it will be divided into multiple chunks and than uploaded in sequence

### Actual behavior 
Upload stops after upload of 1 chunk (at least this is what I assume). 

### Host OS 
Debian 11

#### Nextcloud AIO version 
4.5.0

#### Current channel 
stable
#### Other valuable info 

logs of the Nginx Proxy manager: 
`2023/03/12 13:14:33 [warn] 541#541: *2148 a client request body is buffered to a temporary file /var/tmp/nginx/body/2/03/0000000032, client: <ip>, server: XXXXXXXXXXXXXXXXX, request: "PROPFIND /remote.php/dav/files/******************/ HTTP/1.1", host: "xxxxxxxxxxxx"`

Setup of my Nginx Proxy Manager:
![NPM_1](https://user-images.githubusercontent.com/19403905/224548279-157def0f-6b42-46b9-a9ba-ca6a84cdf4f1.png)
![NPM_2](https://user-images.githubusercontent.com/19403905/224548280-2fcdeb3a-baf6-44ae-a2b2-2b4af3ccd091.png)

**Comment by szaimen** [comment]
Hi, this is caused by the recognize app. Disabling that should fix the issue. Also see https://github.com/nextcloud/recognize/issues

**Comment by gadric** [comment]
can confirm. disabling recognize app works.
