### ISSUE TITLE
Database issues after update to 0.3.0

### ISSUE THREAD

**Issue by OliverPifferi** [nextcloud/all-in-one#217]
Hey everyone,

apparently, users lose the group membership after updating to 0.3.0 (update of the master container and the single containers went fine). After logging in, I couldn't visit the app store nor the settings. Checking my group membership via occ, I saw my Administrator-login not belonging to the admin-group anymore. Manually adding it via CLI seemed be okay but didn't succeed in the web interface.

I had to create a new admin to get into my installation again with access to all settings. Putting back, for example, my daughter's login into the "familie"-group didn't succeed either so there must be something messed up with this latest version.

The log states

```
[no app in context] Fehler: An exception occurred while executing a query: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "oc_group_user_pkey"
DETAIL:  Key (gid, uid)=(familie, emilia) already exists.

POST /ocs/v2.php/cloud/users/emilia/groups
from XXX.XXX.XXX.XXX by admin at 2022-02-11T20:50:52+00:00
```

Any ideas on that?

Best regards,

Oliver

**Comment by szaimen** [comment]
Thank for your report! Did you try to restore from backup? Does that solve the issue?

**Comment by szaimen** [comment]
And could you maybe also post the loga of the database cpntainer here? Thanks!

**Comment by szaimen** [comment]
The bug might be happening because we switched to alpine as base which comes with improved security and decreased size.

I already have a fix ready but while testing the fix I discovered a more tremendous bug that needs to be fixed in server first. Here is my bugfix for aio: https://github.com/nextcloud/all-in-one/pull/218

---

In any case please try to restore from backup and report back if it already fixes your issue. (also please send your logfiles from the first start of the database after restoring from backup)

BTW: I tested the switch from debian to alpine so not sure why this is happening now to you.

**Comment by OliverPifferi** [comment]
> And could you maybe also post the logs of the database container here? Thanks!

Sure.

```
2022-02-11 20:10:52.949 UTC [10] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2022-02-11 20:10:52.950 UTC [10] LOG:  listening on IPv6 address "::", port 5432
2022-02-11 20:10:52.959 UTC [10] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2022-02-11 20:10:52.970 UTC [17] LOG:  database system was shut down at 2022-02-11 20:10:25 UTC
2022-02-11 20:10:53.015 UTC [10] LOG:  database system is ready to accept connections
2022-02-11 20:26:34.631 UTC [282] ERROR:  duplicate key value violates unique constraint "oc_group_user_pkey"
2022-02-11 20:26:34.631 UTC [282] DETAIL:  Key (gid, uid)=(admin, XXX) already exists.
2022-02-11 20:26:34.631 UTC [282] STATEMENT:  INSERT INTO "oc_group_user" ("uid", "gid") VALUES($1, $2)
2022-02-11 20:28:12.303 UTC [296] ERROR:  duplicate key value violates unique constraint "oc_group_user_pkey"
2022-02-11 20:28:12.303 UTC [296] DETAIL:  Key (gid, uid)=(admin, XXX) already exists.
2022-02-11 20:28:12.303 UTC [296] STATEMENT:  INSERT INTO "oc_group_user" ("uid", "gid") VALUES($1, $2)
2022-02-11 20:29:04.245 UTC [306] ERROR:  duplicate key value violates unique constraint "oc_group_user_pkey"
2022-02-11 20:29:04.245 UTC [306] DETAIL:  Key (gid, uid)=(admin, XXX) already exists.
2022-02-11 20:29:04.245 UTC [306] STATEMENT:  INSERT INTO "oc_group_user" ("uid", "gid") VALUES($1, $2)
2022-02-11 20:29:14.568 UTC [308] ERROR:  duplicate key value violates unique constraint "oc_group_user_pkey"
2022-02-11 20:29:14.568 UTC [308] DETAIL:  Key (gid, uid)=(admin, XXX) already exists.
2022-02-11 20:29:14.568 UTC [308] STATEMENT:  INSERT INTO "oc_group_user" ("uid", "gid") VALUES($1, $2)
2022-02-11 20:30:31.945 UTC [313] ERROR:  duplicate key value violates unique constraint "oc_group_user_pkey"
2022-02-11 20:30:31.945 UTC [313] DETAIL:  Key (gid, uid)=(admin, XXX) already exists.
2022-02-11 20:30:31.945 UTC [313] STATEMENT:  INSERT INTO "oc_group_user" ("uid", "gid") VALUES($1, $2)
2022-02-11 20:32:46.778 UTC [335] ERROR:  duplicate key value violates unique constraint "oc_group_user_pkey"
2022-02-11 20:32:46.778 UTC [335] DETAIL:  Key (gid, uid)=(admin, XXX) already exists.
2022-02-11 20:32:46.778 UTC [335] STATEMENT:  INSERT INTO "oc_group_user" ("uid", "gid") VALUES($1, $2)
2022-02-11 20:38:55.571 UTC [462] ERROR:  relation "oc_circle_circles" does not exist at character 15
2022-02-11 20:38:55.571 UTC [462] STATEMENT:  SELECT * FROM "oc_circle_circles"
2022-02-11 20:38:55.574 UTC [462] ERROR:  relation "oc_circle_members" does not exist at character 15
2022-02-11 20:38:55.574 UTC [462] STATEMENT:  SELECT * FROM "oc_circle_members"
2022-02-11 20:38:55.663 UTC [462] ERROR:  relation "oc_circle_tokens" does not exist at character 15
2022-02-11 20:38:55.663 UTC [462] STATEMENT:  SELECT * FROM "oc_circle_tokens"
2022-02-11 20:50:52.143 UTC [572] ERROR:  duplicate key value violates unique constraint "oc_group_user_pkey"
2022-02-11 20:50:52.143 UTC [572] DETAIL:  Key (gid, uid)=(familie, emilia) already exists.
2022-02-11 20:50:52.143 UTC [572] STATEMENT:  INSERT INTO "oc_group_user" ("uid", "gid") VALUES($1, $2)
2022-02-11 20:58:25.918 UTC [665] ERROR:  duplicate key value violates unique constraint "oc_twofactor_providers_pkey"
2022-02-11 20:58:25.918 UTC [665] DETAIL:  Key (provider_id, uid)=(backup_codes, admin) already exists.
```

**Comment by OliverPifferi** [comment]
> Thank for your report! Did you try to restore from backup? Does that solve the issue?

Didn't use the backup here but used my system's snapshot, reverting back to 0.2.1.

Maybe this isn't of any interest, but I used to go with another dedicated admin-user, deleting the initial one after installing?

Thanks for your thought in that case!

BR,

Oliver

Waiting for any updates on that here.

**Comment by szaimen** [comment]
Thanks for the logs!

So do I understand correctly that after restoring your instance from the snapshot it is still broken?

Could you please add the steps what you exaxtly did before the error occured?

So e.g.:
1. used the aio interface to stop the containers
2. created a system snapshot
3. started and updated the the containers from the aio interface by using the "start and update containers" button
4. the database error occured

Also interesting would be what were the exact steps you took to restore your instance from the snapshot.

So e.g.:
1. used the aio interface to stop the containers
2. restored the system snapshot
3. started and updated the the containers from the aio interface by using the "start and update containers" button
4. the database error occured again

Thanks for your effort!

**Comment by OliverPifferi** [comment]
> Thanks for the logs!
> 
> So do I understand correctly that after restoring your instance from the snapshot it is still broken?
> 
> Could you please also add the steps what you exaxtly did before the error occured?
> 
> So e.g.:
> 
> 1. created a system snapshot
> 2. used the aio interface to stop the containers
> 3. started and updated the the containers from the aio interface by using the "start and update containers" button
> 4. the database error occured
> 
> Also interesting would be what were the exact steps you took to restore your instance from the snapshot.
> 
> So e.g.:
> 
> 1. restored the system snapshot
> 2. used the aio interface to stop the containers
> 3. started and updated the the containers from the aio interface by using the "start and update containers" button
> 4. the database error occured again
> 
> Thanks for your effort!

Okay, before the error, I made an hypervisor-based snapshot. After doing this, I updated the master container then (0.3.0) and, after this has been done, the single containers by the official procedure, starting the stopped containers once again. Everything was started with the logged in, specific non-standard-admin using the Nextcloud AIO Login-backend like I have done it from the initial release weeks ago without any hassle.

The restore procedure simply was restoring the snapshot on hypervisor-level and, with staying on 0.2.1, everything worked as usual. Don't know whether to update to 0.3.0 now or better not at the time of writing.

Hope this help a little bit to clarify some steps I have made here. Thanks for your help!

BR,

Oliver

**Comment by OliverPifferi** [comment]
A clean and fresh install of 0.3.0 (just FYI) works well and as expected without any hassle - just mentioning!

**Comment by szaimen** [comment]
> Okay, before the error, I made an hypervisor-based snapshot. After doing this, I updated the master container then (0.3.0) and, after this has been done, the single containers by the official procedure, starting the stopped containers once again. Everything was started with the logged in, specific non-standard-admin using the Nextcloud AIO Login-backend like I have done it from the initial release weeks ago without any hassle.
> 
> The restore procedure simply was restoring the snapshot on hypervisor-level and, with staying on 0.2.1, everything worked as usual. Don't know whether to update to 0.3.0 now or better not at the time of writing.
> 
> Hope this help a little bit to clarify some steps I have made here. Thanks for your help!

Thanks, looks fine to me.

> Maybe this isn't of any interest, but I used to go with another dedicated admin-user, deleting the initial one after installing?

No, that should not have any effect except if an app broke the process when you were doing that initially.

> A clean and fresh install of 0.3.0 (just FYI) works well and as expected without any hassle - just mentioning!

Thanks for testing that out. I already verified that too.

---

So no idea here why the change from debian to alpine worked in my testing but not on your instance but let's see if the issue gets reported by more users.

---

Apart from that I'll probably work on https://github.com/nextcloud/all-in-one/pull/218 on monday which will fix any possible problem that comes through the change from debian to alpine.

**Comment by OliverPifferi** [comment]
Thanks for the update. Maybe I just had bad luck as everything ran smoothly from the initial release on but anyway - backup early, backup often - until now, AIO worked like a charm and considering it's still entitled as "beta" in version 0.3.0 the whole solution is just great. Great to see this activity here, keep it up!

**Comment by TheNomad11** [comment]
The update went fine for me, thanks a lot!

**Comment by szaimen** [comment]
Thanks for the feedback @OliverPifferi @TheNomad11 and @happyreacer! Also a colleague of mine updated without any problem. So it looks like @OliverPifferi you simply had bad luck... I still keep this open for a while.

**Comment by OliverPifferi** [comment]
> So it looks like @OliverPifferi you simply had bad luck... (luckily for those cases we have the build in backup solution).
> I still keep this open for a while.

Just my luck! Anyway, thanks for clarifying 🥇

**Comment by bpcrocke** [comment]
Same issue like the OP in my install. Restoring backup didn't change anything. Seems database broke after update, this is bad because admin is thrown out of admin group (and users out of their groups). I'm waiting for an update which can fix this. Will report back if update exists.

**Comment by szaimen** [comment]
Thanks for your report! I am on it and will publish an update soon that hopefully fixes this.
@bpcrocke did you install your instance before or after v0.3.0 was released?

**Comment by bpcrocke** [comment]
@szaimen before 0.3.0, started at 0.1.0

**Comment by szaimen** [comment]
Okay thanks!

**Comment by szaimen** [comment]
Hello, 

I just published `v0.4.0` which makes it possible to recover from this bug by following these steps:
(Unfortunatley if you already updated your containers after the release of `v0.3.0` you will likely loose all changes that were made to your Nextcloud instance between the release of `v0.3.0` and `v0.4.0` but I currently don't see a way around.)

Here is how to fix your instance:
1. Update your Mastercontainer to `0.4.0`
2. Click on `Create backup` to save the current state in a backup archive
3. Select a backup from before you updated your containers after the release of `v0.3.0` so e.g. a backup from `11-02-2022 16:00:00` or before that time should be sufficient.
4. Click on `Restore selected backup` to restore the selected backup.
5. Click on `Start and update containers` to Restore your instance from that backup archive
6. Stop your instance by clicking on `Stop containers`
7. Start your instance by clicking on `Start containers` in order to upgrade to 23.0.2

I hope it fixes this problem and I am very sorry for the sideffects and problems this issue caused!

Please report back if the provided steps work for you! Thank you!

**Comment by szaimen** [comment]
> Hey,
> 
> > I hope it fixes this problem and I am very sorry for the sideffects and problems this issue caused!
> 
> Well, we're here for testing, aren't we :-) ?

I guess so but still: this issue shouldn't have happened in the first place!

> > Please report back if the provided steps work for you! Thank you!
> 
> Worked like a charm - I can verify this, also going with a clean 0.3.0 (installed on a different system) being updated to 0.4.0 worked flawlessly, now running 23.0.2 as Nextcloud-base.
> 
> Great work here, thanks for your support and efforts in this rare case!

Thanks for verifying! 

I'll leave this open for two more confirmations.

**Comment by szaimen** [comment]
Thanks for the feedback @bpcrocke !

> I had to update the master container, then the other containers and then restore the backup

Wasn't that the exact order I recommended?

**Comment by MariusQuabeck** [comment]
I've only updated the containers & mastercontainer since I had no backup (I know) and that fixed all the issues on my instance regarding editing, sharing etc.

thanks @szaimen!

**Comment by szaimen** [comment]
Interesting! So it seems like the changed we made to the database container already fixed the issue. Anyone up for trying that out?

0. back up the current state by clicking on thr `Create backup` button
1. restore the formerly broken state from backup using the aio interface
2. start the containers
3. is it still broken?

Please report back everyone!

(If yes, you can easily revert to the working state by choossing the latest backup archive.)

**Comment by szaimen** [comment]
Either way seems like everything works again with v0.4.0 so closing.
