### ISSUE TITLE
vm image not being updated on website

### ISSUE THREAD

**Issue by thibaultmol** [nextcloud/all-in-one#2186]
Just letting you know that the link on this page:
https://nextcloud.com/install/#instructions-server
Which goes to https://download.nextcloud.com/aio-vm/
seems to have an old version from last year instead of the up to date aio vm image

**Comment by szaimen** [comment]
Thanks! However AIO updates itself after you open the aio interface the first time. So this is not really. We'll only update the image once the base-OS is oudated, e.g. when Ubuntu 24.02 LTS is out or if there is some other change that cannot be handled internally.
