### ISSUE TITLE
LDAP broken

### ISSUE THREAD

**Issue by DrZoidberg09** [nextcloud/all-in-one#223]
Hi there,

since the newest update LDAP seems to be broken. I cannot enter anything and hence it does not work, obviously.

I have the same issue in my Kubernetes instance and I have to fix it by changing the nginx.conf adding/changing the following:

> location ~ \.php(?:$|/) {
    # Required for legacy support
    **rewrite ^/(?!index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+|.+\/richdocumentscode\/proxy) /index.php$request_uri;**

However, in this case it is Apache based, right? So, I guess to needs to adapted to Apache.

As it happens here and in the nginx based Docker image, I guess it is a general issue?!?

Thanks a lot!

**Comment by szaimen** [comment]
Yes, I think LDAP might be broken on 23.0.1 currently. Apart from that did you see this documentation on ldap https://github.com/nextcloud/all-in-one#ldap ?

**Comment by szaimen** [comment]
23.0.2 should be released soon, btw

**Comment by szaimen** [comment]
> Do understand this correctly? It is known that LDAP is broken and will be fixed in 23.0.2?

Yes, LDAP broke on some setups on 23.0.1 and will hopefully be fixed with 23.0.2 which should be released soon.

**Comment by DrZoidberg09** [comment]
Nice. Thanks a lot! Then I will wait and see if it is fixed then. If not, I will come back and complain ;)

**Comment by szaimen** [comment]
Hello, if your created your instance before the release of v0.3.0 there might be a bug due to the switch from debian to alpine for the database container. So if your instance is older than v0.3.0 you should better play safe by following these steps:
https://github.com/nextcloud/all-in-one/issues/217#issuecomment-1041873234
Thanks again for your report!
