### ISSUE TITLE
text file preview/editor stays blank

### ISSUE THREAD

**Issue by MariusQuabeck** [nextcloud/all-in-one#224]
Hi,

opening .md files in nextcloud no longer works, page stays blank and no editor chrome appears.
I've downloaded the file and opened it locally and its contents are still there.
Also no new .md files can get created.

Please let me know how/what logs to provide to help debug this.
I just tried to share the log via link and there was an error there as well.

[logs.txt](https://github.com/nextcloud/all-in-one/files/8068500/logs.txt)

**Comment by szaimen** [comment]
Thanks for the report! 

Hm... strange. It works with my account on your instance...
Could you maybe try another browser or incognito mode?

**Comment by szaimen** [comment]
I see this error in the logs:

```
{
  "reqId": "07oeq28X8rxIFS72uWbw",
  "level": 3,
  "time": "2022-02-15T11:03:19+00:00",
  "remoteAddr": "91.18.250.141",
  "user": "Marius",
  "app": "text",
  "method": "PUT",
  "url": "/apps/text/session/create",
  "message": "",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36",
  "version": "23.0.1.2",
  "exception": {
    "Exception": "OCP\\Files\\NotFoundException",
    "Message": "",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/apps/text/lib/Service/ApiService.php",
        "line": 81,
        "function": "getFileById",
        "class": "OCA\\Text\\Service\\DocumentService",
        "type": "->",
        "args": [
          1429
        ]
      },
      {
        "file": "/var/www/html/apps/text/lib/Controller/SessionController.php",
        "line": 50,
        "function": "create",
        "class": "OCA\\Text\\Service\\ApiService",
        "type": "->",
        "args": [
          1429,
          null,
          null,
          null,
          false
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 217,
        "function": "create",
        "class": "OCA\\Text\\Controller\\SessionController",
        "type": "->",
        "args": [
          1429,
          null,
          false
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 126,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Text\\Controller\\SessionController"
          },
          "create"
        ]
      },
      {
        "file": "/var/www/html/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Text\\Controller\\SessionController"
          },
          "create"
        ]
      },
      {
        "file": "/var/www/html/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Text\\Controller\\SessionController",
          "create",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "_route": "text.Session.create"
          }
        ]
      },
      {
        "file": "/var/www/html/lib/base.php",
        "line": 1006,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/apps/text/session/create"
        ]
      },
      {
        "file": "/var/www/html/index.php",
        "line": 36,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/html/apps/text/lib/Service/DocumentService.php",
    "Line": 409,
    "CustomMessage": "--"
  },
  "id": "620b8a043add8"
}
```

**Comment by szaimen** [comment]
Could you maybe try to recreate the file? Does that work?

**Comment by MariusQuabeck** [comment]
hmm try creating a new .md file or try open the Baden-Baden one I've just shared with you (never mind "Error creating the share")
Doesn't work on any of my browsers and also didn't work for someone else last night.

I did recreate the file and that one also didn't open.

Since it also didn't work for my friend yesterday, I'm not sure if the problem is entirely on my end.

**Comment by szaimen** [comment]
works for me:
![image](https://user-images.githubusercontent.com/42591237/154051709-d0df234e-083c-4cbe-808e-545a2686395c.png)

**Comment by szaimen** [comment]
Could you try to clear your browser cache once?

**Comment by MariusQuabeck** [comment]
I just did that, also doesn't work.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17063564/154052163-09a37489-4144-44d6-896b-46d61de70be5.png">

**Comment by szaimen** [comment]
okay, maybe you coulld try a `sudo docker exec -it nextcloud-aio-nextcloud php occ files:scan --all` then?

**Comment by szaimen** [comment]
> I've just logged in with your user and it works from there!

yes for me too

**Comment by szaimen** [comment]
> okay, maybe you coulld try a `sudo docker exec -it nextcloud-aio-nextcloud php occ files:scan --all` then?

please try that and report back if it fixes the issue

**Comment by MariusQuabeck** [comment]
It scanned 41 folders and 138 files but that didn't fix the issue. would it help you to verify the issue if I give you temporary access to my user?

**Comment by szaimen** [comment]
> would it help you to verify the issue if I give you temporary access to my user?

if that is okay for you, I can try to find out what is wrong, yes 👍

**Comment by MariusQuabeck** [comment]
thank you, see c.nc.c talk :)

**Comment by szaimen** [comment]
Hello, this should be fixable by following these steps: https://github.com/nextcloud/all-in-one/issues/217#issuecomment-1041873234
Lets track all follow ups there. Thanks again for the report!
