### ISSUE TITLE
Restore Backup from an normal Necloud Instance

### ISSUE THREAD

**Issue by sim-san** [nextcloud/all-in-one#225]
Is it possible to restore the backup (backup app) of a normal Nextcloud instance in the backup app of the Nextcloud AIO ?
Or do I have to take the fiddly way over [migration](https://github.com/nextcloud/all-in-one/blob/main/migration.md)

**Comment by szaimen** [comment]
Yes, you should be able to restore a backup that you took with the backup app like on any other nextcloud instance. But I haven't tried it so I cannot confirm if it really works. If it doesn't work you can still choose to go the migration path.
