### ISSUE TITLE
containers won't start after manual backup removal

### ISSUE THREAD

**Issue by MariusQuabeck** [nextcloud/all-in-one#2274]
I regularly have to remove old backups to free up disk space.
This usually leads to my containers not starting up again until I manually remove the database lock file.

db container:
`Waiting for backup container to finish...
If this is incorrect because the backup container is not running anymore (because it was forcefully killed), you might delete the lock file:
sudo docker exec --user root nextcloud-aio-database rm /mnt/data/backup-is-running`

I assume this file is being placed there when I'm trying to verify backup integrity to remove old entries in the list, as stated by the readme section about backup removal.

backup container:
`Performing backup...
Starting the backup...
Creating archive at "/mnt/borgbackup/borg::20230404_160614-nextcloud-aio"
Synchronizing chunks cache...
Archives: 0, w/ cached Idx: 0, w/ outdated Idx: 0, w/o cached Idx: 0.
Done.
`

steps to reproduce:
create a backup from AIO page, remove backup as stated in readme section, try emptying the backup list on AIO page by verifying, get stuck and manually reboot host or restart containers, database not starting because of lock file, remove lock file

**Comment by szaimen** [comment]
Hi, thanks for the report!

> I regularly have to remove old backups to free up disk space.

Did you know that this is done automatically? See https://github.com/nextcloud/all-in-one/discussions/1675

> I assume this file is being placed there when I'm trying to verify backup

Indeed and we are going to improve this as it is not really needed in the case of verifying a backup.

> get stuck and manually reboot host or restart containers, database not starting because of lock file

I don't think that it gets stuck, the integrity check just can take up to a few hours depending on the backup archive.

However rebooting the machine in that case actually make it get stuck then.

> also subsequently backups break `Performing backup... Starting the backup... Failed to create/acquire the lock /root/.cache/borg/5bb3af51325768c0c5779cb3349f08b520a324d67e5de1d5f35b21bb813f1e16/lock.exclusive (timeout). Deleting the failed backup archive... Failed to create/acquire the lock /root/.cache/borg/5bb3af51325768c0c5779cb3349f08b520a324d67e5de1d5f35b21bb813f1e16/lock.exclusive (timeout). Backup failed!`

I fear you will need to run `sudo borg break-lock /mnt/backup/borg` then since you basically interrupted borg from doing its thing which brog doesnt really like. See https://borgbackup.readthedocs.io/en/stable/usage/lock.html

**Comment by MariusQuabeck** [comment]
Hmm for me it never removed old backups, recently even Nextcloud Office stopped working because it run out of disk space, that's why I manually removed old backups.

I had to reboot since the backup verifying was stuck after removing old backups.

I did run the break-lock command but backups still wont work
`Performing backup...
Starting the backup...
Failed to create/acquire the lock /root/.cache/borg/5bb3af51325768c0c5779cb3349f08b520a324d67e5de1d5f35b21bb813f1e16/lock.exclusive (timeout).
Deleting the failed backup archive...
Failed to create/acquire the lock /root/.cache/borg/5bb3af51325768c0c5779cb3349f08b520a324d67e5de1d5f35b21bb813f1e16/lock.exclusive (timeout).
Backup failed!
`

**Comment by szaimen** [comment]
Maybe I wasnt vlear enough. Only creating a new backup will remove old ones based on the linked prune policy. So if you are already out of space it will not be able to prune old ones.

**Comment by szaimen** [comment]
> I did run the break-lock command but backups still wont work
> `Performing backup... Starting the backup... Failed to create/acquire the lock /root/.cache/borg/5bb3af51325768c0c5779cb3349f08b520a324d67e5de1d5f35b21bb813f1e16/lock.exclusive (timeout). Deleting the failed backup archive... Failed to create/acquire the lock /root/.cache/borg/5bb3af51325768c0c5779cb3349f08b520a324d67e5de1d5f35b21bb813f1e16/lock.exclusive (timeout). Backup failed! `

Regarding that issue I am not completely sure how to resolve that ad it seems that possibly the out of space issue created issues with the borg cache. You could try to clear that by clearing the borg cache, stored in /var/lib/docker/volumes/nextcloud_aio_backup_cache/_data but I never tried that and it is possible that you would break things more by doing so.

**Comment by szaimen** [comment]
> yea that is what I mean, it created daily backups until it ran out of disk space and Nextcloud Office started complaining which is why I then had to remove backups manually.
> So maybe it does work but the quota/rentention policy needs adjusting,

I guess the best advice would be moving the borg repository to a different drive then.

**Comment by MariusQuabeck** [comment]
thank you, I'll give this a try over the weekend

**Comment by szaimen** [comment]
Hi Marius, did it work? :)
