### ISSUE TITLE
Feature: Ability to remove default example files and folders upon nextcloud user creation

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/all-in-one#231]
I'm always finding myself having to login to the user to remove the default files and folders Nextcloud creates. This would be nice to have an option to not have skeleton files in Nextcloud AIO.

**Comment by szaimen** [comment]
hello, you can already do that by setting skeletondirectory to an empty string: https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=skeleton#:~:text='skeletondirectory'%20%3D%3E%20'%2Fpath%2Fto%2Fnextcloud%2Fcore%2Fskeleton'%2C

e.g. `sudo docker exec -it nextcloud-aio-nextcloud php occ config:system:set skeletondirectory --value=""`

**Comment by johnnyq** [comment]
oh wow I didn't know that Thank you!

**Comment by szaimen** [comment]
I just found this bug so it might be possible that this feature doesn't work currently:
https://github.com/nextcloud/server/issues/27890#issuecomment-901855503
