### ISSUE TITLE
NPM documentation needs changes

### ISSUE THREAD

**Issue by Zoey2936** [nextcloud/all-in-one#2319]
with NPM v2.10.x nginx runs now without root permission, this causes that in network mode host it can't bind privileged ports...
Workarround (Use v2.9.x, use a fork that runs as root, set apache_ip_binding to private/public ip of server (or 0.0.0.0) and use this ip inside the npm)

**Comment by szaimen** [comment]
Do you have a link to the discussion?

Reading https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2750 it might was a bug in NPM?

**Comment by szaimen** [comment]
Apparently it was fixed with https://github.com/NginxProxyManager/nginx-proxy-manager/commit/56a92e5c0e7643eaed0ed6b1ce74295912eeeff2 in 2.10.2?

**Comment by Zoey2936** [comment]
network mode host only works with unset ids/root ids... this should be mentioned in the reverse proxy docs. can you please do this?

**Comment by szaimen** [comment]
@Zoey2936 is this the PUID and PGID setting of NPM? Where in the documentation should I add this? At the very top of the NPM section?

**Comment by Zoey2936** [comment]
PUID / PGID are envs of the npm, they need to be set to 0 or be unset
