### ISSUE TITLE
Question : best way to update

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#233]
If we have both Containers and Mastercontainer to update, what is the best way : 

1. Stop Containers > Backup > update Containers > wait until up and running > update Mastercontainer
2. Stop Containers > Backup > update Mastercontainer > update Containers
3. Update Mastercontainer > stop Containers > Backup > update Containers
3. ???

For me, the AIO doc is not clear enough about that...

It seems to me that the AIO interface should be clearer and force  or at least drive the best sequence.

**Comment by szaimen** [comment]
Hello, either order that you've noted down here is valid. Most importantly is to create a backup before pressing the `Start and update containers` button which we make pretty clear, imo.

**Comment by marcatsmci** [comment]
Ok, thanks !
