### ISSUE TITLE
IPv6 not enabled for the custom nextcloud-aio network when ipv6 is enabled for the global network

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#2348]
It Seems like ipv6 need to be enabled manually, however I have not yet found a way to get a working subnet...

**Comment by szaimen** [comment]
@Zoey2936 apparently https://github.com/nextcloud/all-in-one/issues/2041#issuecomment-1438692762 was needed as well to make ipv6 support work in any way. However we would need to add the subnet and gateway manually which I was not able to. 

So honestly after checking this a bit, it feels much safer to just use the default bridge network which enables the things automatically but of course does not allow to configure things anymore and the containers would not be separated form other containers running in the bridge network anymore

**Comment by szaimen** [comment]
I'll tackle this by allowing to define a custom network name. WIP here: https://github.com/nextcloud/all-in-one/pull/2349

Also the ipv6 instructions will get adjusted.

**Comment by Zoey2936** [comment]
one question: what is the goal?  I thought enabling ipv6 inside the deamon.json would be enough to make port 443 accessable over ipv6?

**Comment by Zoey2936** [comment]
why do we need internal ipv6 support in docker?

**Comment by szaimen** [comment]
> I thought enabling ipv6 inside the deamon.json would be enough to make port 443 accessable over ipv6?

Is that so? Let me check this.

**Comment by Zoey2936** [comment]
btw. you could have a lock at the mailcow compose file since this works in combination with the changed deamon.json

**Comment by szaimen** [comment]
> > I thought enabling ipv6 inside the deamon.json would be enough to make port 443 accessable over ipv6?
> 
> Is that so? Let me check this...

It actually works! Really glad that internal ipv6 support is apparently not needed 😅 

So https://github.com/nextcloud/all-in-one/blob/main/docker-ipv6-support.md was all which made it work
