### ISSUE TITLE
Issues after upgrade from v0.3.0 to v0.4.0 

### ISSUE THREAD

**Issue by r-hmn** [nextcloud/all-in-one#235]
Hi,

Yesterday(17th) i tried an upgrade from 0.3.0 to 0.4.0, but i ran in some issues.
i installed using the github readme, (didn't do any of the special mentioned later in the document)
OS: `Lubuntu, `
Docker version: `Docker-ce*/impish,now 5:20.10.12~3-0~ubuntu-impish amd64`
Using portainer.io container to see container details.

First i made a backup via the nextcloud admin console at https://localhost:8080/containers
Then i did both upgrades of container and mastercontainer via nextcloud admin console (didn't do it separately..🙈)
Then at first start; other containers didn't see the database. and database itself also had issues in the log (seen by clicking on the status of the container as shown in nextcloud admin console).
Then something went wrong(cant recall) and the backups dropdown was empty?
Then i decided to backup the all-in-one-docker-volume folders and the borg folder myself.
Then i checked what would happen if i'd perform a backup again. Backing-up seemed to work. The backup log showed no error.
Then i checked the contents of the backup/borg folder but it looked like it wasn't touched, looking at timestamp.(i could be wrong) 
(i didn't do a file-by-file binary compare my backup of /borg and the new contents of /borg though)
but the dropdownbox did have an entry again, but the time of backup (i'm at GMT+1) looked like it was the old time of 1st backup (but i don't know if it shows LCT or GMT)?
Now, the database log says authentication fails for oc_admin and oc_nextcloud.
i reported on the support forum https://help.nextcloud.com/t/all-in-one-container-fails-to-start-after-upgrading-v0-3-0-to-v0-4-0-issues-with-the-database/134071
Please advise what details/logs to add to this item here.
Regards

**Comment by szaimen** [comment]
Hello, thanks for your report!

Do I understand correctly that you don't have a working backup now that you could restore to?

I fear if that is the case there is not much I can do to help you.

Btw: do you have javascript enabled in your browser for the aio interface?

**Comment by r-hmn** [comment]
Hi, thanks
Well, i did use the backup interface before letting it do the container update. so i do have a /borg folder.
i tarred it (and also tarred the docker volumes folders) before performing another backup attempt.
My browser is firefox, i think everything is enabled. All html5 pages work fine.

**Comment by szaimen** [comment]
Thanks! Please first create an additional backup now from the aio interface. Is it successful? If yes, does the new backup show up in the dropdown then?If not, please send the logs from the borgbackup container! If is is successfuly and does show up, please restore the old backup that was shown. If the restore is successful, please click on `start containers` and see if that works. Thank you!

**Comment by r-hmn** [comment]
From the admin console, i did 'stop containers', pressed 'create backup'. 
it reported 'last backup failed' within a minute. Pressing 'backup' a 2nd time with same result.
Attached is the backup container log of 1st click(same as 2nd), and my database log(just in case). 
[logs_nextcloud-aio-database.txt](https://github.com/nextcloud/all-in-one/files/8096286/logs_nextcloud-aio-database.txt)
[logs_nextcloud-aio-borgbackup.txt](https://github.com/nextcloud/all-in-one/files/8096289/logs_nextcloud-aio-borgbackup.txt)

**Comment by szaimen** [comment]
I see! in this case please directly restore the old backup that gets shown in the dropdown. If the restore is successful, please click on start containers and see if that works. If it doesnt work please send the logs from the database container. Thank you!

**Comment by r-hmn** [comment]
i restored that backup and that succeeded.
i clicked 'start containers', then after a few seconds the admin interface showed in the right top "failed to talk to server" very briefly.
The admin page seems not updating again, so i pressed F5 to see all containers running. But db has same error as i sae before:
[logs_1-successfully_restored_backup__nextcloud-aio-borgbackup.txt](https://github.com/nextcloud/all-in-one/files/8096381/logs_1-successfully_restored_backup__nextcloud-aio-borgbackup.txt)
[logs_2-started_containers-all_running, but db log shows error__nextcloud-aio-database.txt](https://github.com/nextcloud/all-in-one/files/8096380/logs_2-started_containers-all_running.but.db.log.shows.error__nextcloud-aio-database.txt)

**Comment by szaimen** [comment]
Hello, I just published a new database container with the fix. Please try again the following and report back if it works! Thank you!

>  Please directly restore the old backup that gets shown in the dropdown. If the restore is successful, please click on start containers (or start and update containers) and see if that works. If it doesnt work please send the logs from the database container. Thank you!

**Comment by r-hmn** [comment]
thanks! You mean, 'stop containers', then 'restore backup', then 'start and update containers'?
During auto refresh it reported 'failed to talk to server'. i manually refreshed 'admin console' with F5.
Redis,Collabora,Talk are 'Running'
Apache,Database,Nexcloud are 'Starting'   
(database log contained lot of Alter tables, and ended with "ready to accept connections")
After a few minutes it now says 'Running' 😎 and data and users are there🎉🎊
Thanks!

**Comment by szaimen** [comment]
Great that it solved the issue for you! I think it failed for you in the beginning because we only waited 10 seconds for the database to start. Seems like you have a pretty slow server 😅 but great that it works for you now :)

**Comment by r-hmn** [comment]
Actually i don't even have SDD, its a 1TB HDD. 
We're only planning to use if for occasional collaboration for sharing files and ideas with maybe 20 people. But haven't done video/audio-chat, only texting. If we agree to use this platform, then we'll upgrade a bit.
I'd say speed is kind fine for home use. Sometimes the file list is populated a bit slow, so as you think you click one file, it just added the last one somewhere in the middle, so you end up clicking the wrong file 😀 Maybe that becomes better when some caches are filled more. But running Lubuntu leaves quite some memory free. i'm now using 2.8G RAM of 7.5G total.
Thanks for the speedy support!
