### ISSUE TITLE
Error when trying to save API-URL and API-KEY on BBB App

### ISSUE THREAD

**Issue by sheyk87** [nextcloud/all-in-one#2386]
### Steps to reproduce
1. https://DOMAIN/settings/admin/additional
2. BigBlueButton
3. I complete data, but nothing happen.

![4](https://user-images.githubusercontent.com/86056803/232841236-0b6ae926-36fe-4341-9aca-11e28e1af646.png)

#### Nextcloud AIO version [Nextcloud Hub 3] (https://nextcloud.com/) (25.0.5)

![1](https://user-images.githubusercontent.com/86056803/232840968-2999df15-a7bf-4165-adcf-6f0a5277356a.png)

![2](https://user-images.githubusercontent.com/86056803/232840967-2115ed04-566e-46c1-b0a2-77ca5ee65ea1.png)

![3](https://user-images.githubusercontent.com/86056803/232840963-b1588dfa-fe64-46bf-aa70-287eea993a4e.png)

**Comment by Zoey2936** [comment]
works for me

**Comment by Zoey2936** [comment]
and should be reported more to the bbb app

**Comment by sheyk87** [comment]
> and should be reported more to the bbb app

BBB its working fine. Ive moodle linked and its works

**Comment by Zoey2936** [comment]
I don`t mean bbb itself, I mean the bbb nextcloud app

**Comment by szaimen** [comment]
> and should be reported more to the bbb app

yes
