### ISSUE TITLE
remove banner

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#239]
Please remove this banner when creating a document from Nextcloud Office.
Benefit from the latest developments in online productivity. Nutzen Sie die Möglichkeiten kostenlos mit anderen im Browser. Apps are also available for Android and iOS. 21.11.1.3 brings major improvements in usability, visual presentation, and performance.

**Comment by johnnyq** [comment]
Yes please do.

![image](https://user-images.githubusercontent.com/1812594/154820172-48807e4a-728b-4e72-8610-d25c4b4e6d89.png)

**Comment by johnnyq** [comment]
Also remove

This

![image](https://user-images.githubusercontent.com/1812594/154820224-a4e163c7-da85-467a-8deb-de1326ee5880.png)


It appears on the login page and when I share files

**Comment by R7JANV1** [comment]
@johnnyq You can change the slogan with the Theming App, if that helps you out

**Comment by szaimen** [comment]
> Also remove
> 
> This
> 
> ![image](https://user-images.githubusercontent.com/1812594/154820224-a4e163c7-da85-467a-8deb-de1326ee5880.png)
> 
> It appears on the login page and when I share files

Yes, you can change/remove that yourself in the theming app

**Comment by szaimen** [comment]
Will have a look how to remove the banner.

**Comment by jakobroehrl** [comment]
https://github.com/nextcloud/richdocuments/issues/1902

**Comment by szaimen** [comment]
> [nextcloud/richdocuments#1902](https://github.com/nextcloud/richdocuments/issues/1902)

Thanks! So this option does not work currently?

**Comment by jakobroehrl** [comment]
> Thanks! So this option does not work currently?

Right, has no effect currently

**Comment by szaimen** [comment]
> Yes please do.
> 
> ![image](https://user-images.githubusercontent.com/1812594/154820172-48807e4a-728b-4e72-8610-d25c4b4e6d89.png)

We will not remove the dialog but it will likely be enhanced in the future. See https://github.com/nextcloud/richdocuments/issues/1902#issuecomment-1057087256
