### ISSUE TITLE
Think over project considering people dont read the documentation

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#2402]
So only things in the aio interface get recognized. If we dont want to add options for all things to the aio interface, we at least want to show the current config (or some of it) in a details tag and post a link how to adjust that. Also e.g. where the config.php is stored and to adjust it and how to run occ commands (only after initial setup is done) and more... Also asd link for further docs and env here.

Need to list really important stff here. Less important stuff might not get listed here.

At the bottom we could add where to find further documentation (and say how to search it)...and also where firther options.

**Comment by johnnyq** [comment]
I Like your idea @szaimen , I also like the idea of only showing the settings with detailed descriptions that pertain to the Nextcloud instance itself.
I'm guessing you will have it in a separate page which may be clickable from the main AIO Page.
I think this will deff limit the amount of support questions

**Comment by martin-77** [comment]
Good point! Maybe an implementation like the "update to 26" thing would work. Just link the most important faqs.

**Comment by szaimen** [comment]
This is now released with v5.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
