### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by sergiorgb** [nextcloud/all-in-one#241]
It does get to the aio dashboard but i cant open nextcloud itself 
![image](https://user-images.githubusercontent.com/59933966/154874598-f8b10f82-b502-4f9f-895b-0ded86f25abc.png)
![image](https://user-images.githubusercontent.com/59933966/154874619-51fd34a8-3f18-48f9-8e55-adaa57842df3.png)
as you see it doesnt connect in any way

**Comment by sergiorgb** [comment]
I tried reinstalling didnt work tho

**Comment by R7JANV1** [comment]
If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatially by opening the Nextcloud AIO Interface via:
https://your-domain-that-points-to-this-server.tld:8443

**Comment by szaimen** [comment]
Hello @sergiorgb ,

please click on `Running` next to `Apache` and post the logs here. Thanks!

**Comment by sergiorgb** [comment]
ok i will send info later

**Comment by sergiorgb** [comment]
Logs are here
`nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9000: Name or service not known
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.8. Set the 'ServerName' directive globally to suppress this message
{"level":"info","ts":1645476969.6358109,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
{"level":"warn","ts":1645476969.6394832,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/Caddyfile","line":2}
{"level":"info","ts":1645476969.6409762,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
{"level":"info","ts":1645476969.6412656,"logger":"http","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}
{"level":"info","ts":1645476969.641299,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00011ae00"}
{"level":"info","ts":1645476969.6421478,"logger":"http","msg":"enabling automatic TLS certificate management","domains":["192.168.0.10"]}
{"level":"info","ts":1645476969.6421711,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/data/caddy"}
{"level":"info","ts":1645476969.6421993,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1645476969.6423035,"msg":"autosaved config (load with --resume flag)","file":"/var/www/.config/caddy/autosave.json"}
{"level":"info","ts":1645476969.642311,"msg":"serving initial configuration"}
{"level":"info","ts":1645476969.6425157,"logger":"tls.obtain","msg":"acquiring lock","identifier":"192.168.0.10"}
{"level":"info","ts":1645476969.643885,"logger":"tls.obtain","msg":"lock acquired","identifier":"192.168.0.10"}
{"level":"error","ts":1645476969.6442194,"logger":"tls.obtain","msg":"will retry","error":"[192.168.0.10] Obtain: subject does not qualify for a public certificate: 192.168.0.10","attempt":1,"retrying_in":60,"elapsed":0.000326591,"max_duration":2592000}
`
these are the apache ones

**Comment by sergiorgb** [comment]
looks like i  cant get a cert
since im using a private ip
i do have a domain but i cant open ports 
what do i do then

**Comment by szaimen** [comment]
> looks like i cant get a cert
> since im using a private ip

yes, that is the problem here.

I wonder though how you managed to enter the ip-address in the domain field?

**Comment by sergiorgb** [comment]
> > looks like i cant get a cert
> > since im using a private ip
> 
> yes, that is the problem here.
> 
> I wonder though how you managed to enter the ip-address in the domain field?

yeah i did put my local ip when configuring it can i edit the caddyfile or smth?

**Comment by HritwikSinghal** [comment]
> > looks like i cant get a cert
> > since im using a private ip
> 
> yes, that is the problem here.
> 
> I wonder though how you managed to enter the ip-address in the domain field?

You can put ip address in the domain field and it will take it as a valid input. i also have the same issue. Is there any way we can use an automatically generated self signed cert or use it with HTTP since those who are behind NAT or cant do port forward will not be able to use this setup.

**Comment by sergiorgb** [comment]
yep

**Comment by szaimen** [comment]
Sry to say but ip-addresses are not and will not be supported.

**Comment by HritwikSinghal** [comment]
> Sry to say but ip-addresses are not and will not be supported.

can we get an http option with it or an automatically self signed https certificate ?

**Comment by szaimen** [comment]
> can we get an http option with it or an automatically self signed https certificate ?

No. But you might be interested in this: https://github.com/nextcloud/all-in-one/issues/72

**Comment by sergiorgb** [comment]
Ok
