### ISSUE TITLE
Document how to mount hard disk and backup to that

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#242]
If I want to make backups to my second connected hard disk, which path do I have to enter in the AIO interface?

Second hard disk: /dev/sdb

**Comment by szaimen** [comment]
Hello, first you need to mount the partition to your linux distribution. E.g. you can follow this video: https://youtu.be/2lSyX4D3v_s and enter the path where the drive gets mounted in the aio interface.

**Comment by R7JANV1** [comment]
Would it be possible to write a tutorial and include it in the documentation? I think there are more people with the same problem as me.

**Comment by szaimen** [comment]
I won't do it but will reopen for someone to take this task over.

**Comment by DrShivang** [comment]
How to mount external hard disk and backup using borg :

1) Mount Ext / Backup HDD to Host OS using inbuilt functionality or Udev Rules or whatever way you prefer.
2) Ensure that the mount point remains fixed through reboots if it's meant to sustain.
3) Modify Docker Compose To Mount Host Directory To Mastercontainer Docker, Say For Example, If You Have Mounted An External Disk at  **/mnt/media/My_Passport** , Then Add These Lines To Your Docker Compose :
`NEXTCLOUD_MOUNT=/mnt/media/My_Passport`
4) Fire Up The Docker And Setup Nextcloud As Per The Guide.
5) Ensure Correct Permissions Are Set. Please Refer #https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host by running
`sudo chown -R 33:0 /mnt/media/My_Passport` on Host OS
6) In Your Nextcloud Admin System Settings Page, Check your mount point location under disk `https://yournextcloud domain/settings/admin/serverinfo` if it's mounted and showing up correctly.
7) Now Visit Nextcloud AIO Interface from Admin Overview Settings.
8) Under Backup Section Add Your External Disk Mountpoint As Backup Directory, In Our Example 
`/mnt/media/My_Passport`
9) Ensure The Backup Directory is Empty, Else Backup May Run Into Errors, You May Also Create or Use A Folder with Correct Permissions by running : 
`sudo chown -R 33:0 /mnt/media/My_Passport/mynextcloudaiobackup` on host OS
then add this folder as a backup directory as mentioned in point 8
`/mnt/media/My_Passport/mynextcloudaiobackup`
10) Run Backup

**Comment by szaimen** [comment]
@DrShivang thanks for this bjut the following steps should actually not needed for the backup container:

> * Modify Docker Compose To Mount Host Directory To Mastercontainer Docker, Say For Example, If You Have Mounted An External Disk at  **/mnt/media/My_Passport** , Then Add These Lines To Your Docker Compose :
>   `NEXTCLOUD_MOUNT=/mnt/media/My_Passport`
> * Ensure Correct Permissions Are Set. Please Refer #https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
>   `sudo chown -R 33:0 /mnt/media/My_Passport` by running on Host OS
> * In Your Nextcloud Admin System Settings Page, Check your mount point location under disk `https://yournextcloud domain/settings/admin/serverinfo` if it's mounted and showing up correctly.
> * Now Visit Nextcloud AIO Interface from Admin Overview Settings. Refer https://github.com/nextcloud/all-in-one#how-to-easily-log-in-to-the-aio-interface
> * You May Also Create or Use A Folder with Correct Permissions by running :
>   `sudo chown -R 33:0 /mnt/media/My_Passport/mynextcloudaiobackup` on host OS
>   then add this folder as a backup directory as mentioned in point 8
>   `/mnt/media/My_Passport/mynextcloudaiobackup`

**Comment by szaimen** [comment]
This should be enough:


> 1. Mount Ext / Backup HDD to Host OS using inbuilt functionality or Udev Rules or whatever way you prefer.
> 2. Ensure that the mount point remains fixed through reboots if it's meant to sustain.
> 4\. Fire Up The Docker And Setup Nextcloud As Per The Guide. And visit the AIO interface.
> 8. Under Backup Section Add Your External Disk Mountpoint As Backup Directory, In Our Example
>   `/mnt/media/My_Passport`
> 9. Ensure The Backup Directory is Empty, Else Backup May Run Into Errors
> 10\. Run Backup

**Comment by DrShivang** [comment]
How to mount external hard disk and backup using borg :

1. Mount Ext / Backup HDD to Host OS using inbuilt functionality or Udev Rules or whatever way you prefer.
2. Ensure that the mount point remains fixed through reboots if it's meant to sustain.
3. If not already done, Fire Up The Docker And Setup Nextcloud As Per The Guide.
4. Now open the AIO interface.
5. Under Backup Section Add Your External Disk Mountpoint As Backup Directory, Example
`/mnt/media/My_Passport`
6. Run Backup

**Comment by szaimen** [comment]
Thanks! Looks good to me! Will add this to the readme going forward.
(Though I will adjust some small things)
(Path and add a link to the youtube video)
