### ISSUE TITLE
windows 10 1809 LTSC - not working

### ISSUE THREAD

**Issue by VitaliyAT** [nextcloud/all-in-one#243]
8443 calling:
![image](https://user-images.githubusercontent.com/1639608/154913516-50a80dc1-fdf5-49e3-9b1a-955a78fbb012.png)

8080 caling:
![image](https://user-images.githubusercontent.com/1639608/154913639-8a29f7f5-fa04-4cc6-91ec-fae158bd2fda.png)

> $ docker pull nextcloud/all-in-one:latest
> latest: Pulling from nextcloud/all-in-one
> 5eb5b503b376: Already exists
> 8b1ad84cf101: Already exists
> 38c937dadeb7: Already exists
> 6a2f1dc96e59: Already exists
> f8c3f82c39d4: Already exists
> 90fc6462bd8e: Already exists
> c670d99116c9: Already exists
> 268554d6fe96: Already exists
> 6c29fa0d4492: Already exists
> 73e23c50a259: Already exists
> 81ac13c96fc2: Already exists
> b60a3e623949: Already exists
> dac5dd67fd59: Already exists
> f004b617f760: Pull complete
> 66c68c9a61d1: Pull complete
> 83b505933678: Pull complete
> b2aefdb706b8: Pull complete
> 2fa32216a6d8: Pull complete
> d892ae51dc39: Pull complete
> 1b2512d89701: Pull complete
> b413efaee42c: Pull complete
> a24fb47214e4: Pull complete
> 70fc624b9c8a: Pull complete
> a8ba1ba1ce72: Pull complete
> 88c3ea02adbf: Pull complete
> c592aeb16d6d: Pull complete
> 6af844b7611a: Pull complete
> 9e9b81dde74a: Pull complete
> 07479ca8c0ee: Pull complete
> d79d61e6796a: Pull complete
> 4a31881c3218: Pull complete
> Digest: sha256:e4a1ccb313c5dbda5d63791070deaa5d2a93af1e31245b5c6f254f208b2f2c75
> Status: Downloaded newer image for nextcloud/all-in-one:latest
> docker.io/nextcloud/all-in-one:latest

> $ docker run -it --name nextcloud-aio-mastercontainer --restart always -p 80:80 -p 8080:8080 -p 8443:8443 --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock:ro nextcloud/all-in-one:latest
> Generating a RSA private key
> ..........................................................................................................................................................................................................................................................................................................................................++++
> ..............................................................................................................................................................................................................................++++
> writing new private key to './ssl.key'
> -----
> Initial startup of Nextcloud All In One complete!
> You should be able to open the Nextcloud AIO Interface now on port 8080 of this server!
> E.g. https://internal.ip.of.this.server:8080
> 
> If your server has port 80 and 8443 open and you point a domain to your server, you can get a valid certificate automatially by opening the Nextcloud AIO Interface via:
> https://your-domain-that-points-to-this-server.tld:8443
> 2022-02-21 08:01:55,106 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
> + true
> + sudo -u www-data php /var/www/docker-aio/php/src/Cron/cron.php
> {"level":"info","ts":1645430516.153837,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
> {"level":"warn","ts":1645430516.1566577,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/Caddyfile","line":2}
> {"level":"info","ts":1645430516.157713,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["127.0.0.1:2019","localhost:2019","[::1]:2019"]}
> {"level":"warn","ts":1645430516.1580455,"logger":"tls","msg":"YOUR SERVER MAY BE VULNERABLE TO ABUSE: on-demand TLS is enabled, but no protections are in place","docs":"https://caddyserver.com/docs/automatic-https#on-demand-tls"}
> {"level":"info","ts":1645430516.1581082,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0003467e0"}
> {"level":"info","ts":1645430516.1582167,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/docker-aio-config/caddy/"}
> {"level":"info","ts":1645430516.1582654,"logger":"tls","msg":"finished cleaning storage units"}
> {"level":"info","ts":1645430516.1585534,"msg":"autosaved config (load with --resume flag)","file":"/root/.config/caddy/autosave.json"}
> {"level":"info","ts":1645430516.1585631,"msg":"serving initial configuration"}
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
> [Mon Feb 21 08:01:56.229961 2022] [ssl:warn] [pid 64] AH01906: 172.17.0.2:8080:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
> [Mon Feb 21 08:01:56.230034 2022] [ssl:warn] [pid 64] AH01909: 172.17.0.2:8080:0 server certificate does NOT include an ID which matches the server name
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
> 
> Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/v1.41/containers/nextcloud-aio-borgbackup/json in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
> Stack trace:
> #0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
> #1 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #2 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #3 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #4 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #5 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #6 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #7 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #8 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #9 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #10 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #11 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
> #12 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array)
> #13 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request('GET', 'http://localhos...', Array)
> #14 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(56): GuzzleHttp\Client->get('http://localhos...')
> #15 /var/www/docker-aio/php/src/Container/Container.php(91): AIO\Docker\DockerActionManager->GetContainerRunningState(Object(AIO\Container\Container))
> #16 /var/www/docker-aio/php/src/ContainerDefinitionFetcher.php(117): AIO\Container\Container->GetRunningState()
> #17 /var/www/docker-aio/php/src/ContainerDefinitionFetcher.php(32): AIO\ContainerDefinitionFetcher->FetchDefinition()
> #18 /var/www/docker-aio/php/src/Cron/cron.php(19): AIO\ContainerDefinitionFetcher->GetContainerById('nextcloud-aio-n...')
> #19 {main}
>   thrown in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210
> [Mon Feb 21 08:01:56.271396 2022] [ssl:warn] [pid 64] AH01906: 172.17.0.2:8080:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
> [Mon Feb 21 08:01:56.271445 2022] [ssl:warn] [pid 64] AH01909: 172.17.0.2:8080:0 server certificate does NOT include an ID which matches the server name
> [Mon Feb 21 08:01:56.275731 2022] [mpm_prefork:notice] [pid 64] AH00163: Apache/2.4.52 (Debian) PHP/8.0.15 OpenSSL/1.1.1k configured -- resuming normal operations
> [Mon Feb 21 08:01:56.275776 2022] [core:notice] [pid 64] AH00094: Command line: 'apache2 -D FOREGROUND'
> + true
> + sudo -u www-data php /var/www/docker-aio/php/src/Cron/cron.php
> 
> Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/v1.41/containers/nextcloud-aio-borgbackup/json in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
> Stack trace:
> #0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
> #1 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #2 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #3 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #4 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #5 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #6 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #7 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #8 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #9 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #10 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #11 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
> #12 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array)
> #13 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request('GET', 'http://localhos...', Array)
> #14 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(56): GuzzleHttp\Client->get('http://localhos...')
> #15 /var/www/docker-aio/php/src/Container/Container.php(91): AIO\Docker\DockerActionManager->GetContainerRunningState(Object(AIO\Container\Container))
> #16 /var/www/docker-aio/php/src/ContainerDefinitionFetcher.php(117): AIO\Container\Container->GetRunningState()
> #17 /var/www/docker-aio/php/src/ContainerDefinitionFetcher.php(32): AIO\ContainerDefinitionFetcher->FetchDefinition()
> #18 /var/www/docker-aio/php/src/Cron/cron.php(19): AIO\ContainerDefinitionFetcher->GetContainerById('nextcloud-aio-n...')
> #19 {main}
>   thrown in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210
> + true
> + sudo -u www-data php /var/www/docker-aio/php/src/Cron/cron.php
> 
> Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/v1.41/containers/nextcloud-aio-borgbackup/json in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
> Stack trace:
> #0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
> #1 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #2 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #3 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #4 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #5 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #6 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #7 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #8 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #9 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #10 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #11 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
> #12 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array)
> #13 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request('GET', 'http://localhos...', Array)
> #14 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(56): GuzzleHttp\Client->get('http://localhos...')
> #15 /var/www/docker-aio/php/src/Container/Container.php(91): AIO\Docker\DockerActionManager->GetContainerRunningState(Object(AIO\Container\Container))
> #16 /var/www/docker-aio/php/src/ContainerDefinitionFetcher.php(117): AIO\Container\Container->GetRunningState()
> #17 /var/www/docker-aio/php/src/ContainerDefinitionFetcher.php(32): AIO\ContainerDefinitionFetcher->FetchDefinition()
> #18 /var/www/docker-aio/php/src/Cron/cron.php(19): AIO\ContainerDefinitionFetcher->GetContainerById('nextcloud-aio-n...')
> #19 {main}
>   thrown in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210
> + true
> + sudo -u www-data php /var/www/docker-aio/php/src/Cron/cron.php
> 
> Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/v1.41/containers/nextcloud-aio-borgbackup/json in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
> Stack trace:
> #0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
> #1 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #2 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
> #3 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #4 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #5 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #6 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #7 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #8 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #9 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
> #10 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
> #11 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
> #12 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array)
> #13 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request('GET', 'http://localhos...', Array)
> #14 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(56): GuzzleHttp\Client->get('http://localhos...')
> #15 /var/www/docker-aio/php/src/Container/Container.php(91): AIO\Docker\DockerActionManager->GetContainerRunningState(Object(AIO\Container\Container))
> #16 /var/www/docker-aio/php/src/ContainerDefinitionFetcher.php(117): AIO\Container\Container->GetRunningState()
> #17 /var/www/docker-aio/php/src/ContainerDefinitionFetcher.php(32): AIO\ContainerDefinitionFetcher->FetchDefinition()
> #18 /var/www/docker-aio/php/src/Cron/cron.php(19): AIO\ContainerDefinitionFetcher->GetContainerById('nextcloud-aio-n...')
> #19 {main}
>   thrown in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 210
> 172.17.0.2:8080 172.17.0.1 - - [21/Feb/2022:08:02:54 +0000] "GET / HTTP/1.0" 400 622 "-" "-"
> 172.17.0.1 - - [21/Feb/2022:08:02:54 +0000] "GET / HTTP/1.0" 400 622 "-" "-"
> 172.17.0.2:8080 172.17.0.1 - - [21/Feb/2022:08:02:54 +0000] "GET / HTTP/1.0" 400 622 "-" "-"
> 172.17.0.1 - - [21/Feb/2022:08:02:54 +0000] "GET / HTTP/1.0" 400 622 "-" "-"

**Comment by szaimen** [comment]
Hi, did you try `https://localhost:8080` ?

**Comment by szaimen** [comment]
I'll close this in favor of https://github.com/nextcloud/all-in-one/issues/161 since AIO doesn't work currently on Docker Desktop.
