### ISSUE TITLE
MacOS - "Cannot connect to the docker socket. Cannot proceed." 

### ISSUE THREAD

**Issue by Anendil** [nextcloud/all-in-one#2443]
### Steps to reproduce
1. Install Docker desktop for Apple chip from offical website 
2. Run docker command ajusted for mac usage : 
```
# For Linux and without a web server or reverse proxy (like Apache, Nginx and else) already in place:
sudo docker run \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 80:80 \
--publish 8080:8080 \
--publish 8443:8443 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock.raw:/var/run/docker.sock:ro \
-e DOCKER_SOCKET_PATH=/var/run/docker.sock \
nextcloud/all-in-one:latest
```
3. "Cannot connect to the docker socket. Cannot proceed." message loop after restart

### Expected behavior 

I expect to have correct creation of the container

### Actual behavior 

The container always restart and show "Cannot connect to the docker socket. Cannot proceed."

### Host OS 
MacOS 13.3.1 (22E261)

#### Nextcloud AIO version 
latest

#### Current channel 
cannot access to AIO interface

#### Other valuable info 
I tried many potential solutions but nothing work has expected. Tried different installation of docker and with and without special ajustment for macOS. I also tried with docker compose.

Please ask me if more information is needed and what exactly because i am still a beginner with docker :)

**Comment by Roeda** [comment]
I have the exact same issue with the latest docker 4.19 for macos. My otherwise running AIO mater-container stop working after the update and got stuck in "connect to docker.sock".
I (fully) removed docker desktop and did a fresh install. but couldn't make it work no matter the combination I try ( docker.sock, docker.sock.raw ...). I receive the same issue : "Cannot connect to the docker socket. Cannot proceed."

**Comment by Roeda** [comment]
why is this issue closed ?

**Comment by Anendil** [comment]
I closed it because i tought it was in the wrong channel so i move the issue in chat. I do not know if i have to reopen it.
