### ISSUE TITLE
timeout issue

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#245]
is it intentional that when port 8443 is called with https:// a timeout is issued? Or must the port be open outside the network? If this is intentional and the port does not need to be open outside the network, could there be a response created with SSL certificate?

**Comment by szaimen** [comment]
Hello, please read and follow 
![image](https://user-images.githubusercontent.com/42591237/154953922-77b5931f-f7e5-43bb-9dd7-bb92c7707c36.png)

**Comment by R7JANV1** [comment]
I have a Lets Encrypt certificate for the Nextcloud but none for the AIO interface. is this intentional?

**Comment by szaimen** [comment]
> I have a Lets Encrypt certificate for the Nextcloud but none for the AIO interface. is this intentional?

yes since the aio interface is independent from nextcloud. But we have documented how you can get a valid certificate for the aio interface. So simply follow the provided steps.

**Comment by R7JANV1** [comment]
Can I also get a Lets encrypt certificate for the AIO interface? Or only a self-signed one?

**Comment by szaimen** [comment]
> Can I also get a Lets encrypt certificate for the AIO interface?

You can get a lets encrypt certificate for the aio interface by following these steps:
![image](https://user-images.githubusercontent.com/42591237/154960539-ba849830-84d3-4beb-af1e-eed5e5728e42.png)

**Comment by szaimen** [comment]
I am unsubscribing now.

**Comment by R7JANV1** [comment]
I have tried but it does not work
