### ISSUE TITLE
typo readme.md

### ISSUE THREAD

**Issue by jungmin-lim** [nextcloud/all-in-one#249]
https://github.com/nextcloud/all-in-one/blob/ac3b8bc963fce906ce477f187e0db2d529aaec8f/readme.md?plain=1#L84

Shouldn't it be `3478/UDP` instead of `3478/UPD`?

**Comment by szaimen** [comment]
Oh yes, thanks!

**Comment by szaimen** [comment]
fixed with https://github.com/nextcloud/all-in-one/commit/30e2c6be251776bcfb72737afd131e37361ff0bd
