### ISSUE TITLE
Update Nextcloud to php8.2 with Nextcloud 28

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#2534]
- add ftp back manually? https://github.com/docker-library/php/issues/1488#issuecomment-1906738878 and https://github.com/nextcloud/docker/issues/2152#issue-2103576478

**Comment by DenuxPlays** [comment]
What is the reason for waiting until nextcloud 28?

**Comment by szaimen** [comment]
> What is the reason for waiting until nextcloud 28?

Waiting for community apps to become slowly compatible with php 8.2 and ironing out of some remaining compatibility issues in core apps.

**Comment by szaimen** [comment]
This is now released with v8.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
