### ISSUE TITLE
Error in document print function 

### ISSUE THREAD

**Issue by lukaspavelka** [nextcloud/all-in-one#2559]
### Steps to reproduce
1. Open any document on last version of All-in-one
2. File / Print 
3. Error show up: 

![image](https://github.com/nextcloud/all-in-one/assets/48788338/abe809ff-4e2a-4b1e-92a3-f1d471a67740)

Maybe important : server is behind: nginx proxy manager . 

### Expected behavior 
It should print document :)

### Actual behavior 
Just error pop up

### Host OS 
proxmox in CT, ubuntu 22.04

#### Nextcloud AIO version 
Nextcloud AIO - 26.0.1

#### Current channel 
Channel STABLE

#### Other valuable info 
screenshots in the post

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/CollaboraOnline/online/issues
