### ISSUE TITLE
apache does not start after v5.2.0 Update

### ISSUE THREAD

**Issue by gerhard-thompson** [nextcloud/all-in-one#2566]
### Steps to reproduce
1. upgrade from v5.1.0 to v5.2.0 with APACHE_PORT different than 443

### Expected behavior 
apache should start

### Actual behavior 
apache does not start

### Host OS 
Ubuntu 22.04

#### Nextcloud AIO version 
v5.2.0

#### Current channel 
beta

#### Other valuable info 
Error Message:
`Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
{"level":"info","ts":1684516223.1517866,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /Caddyfile:9 - Error during parsing: getting module named 'http.ip_sources.private_ranges': module not registered: http.ip_sources.private_ranges
[Fri May 19 17:10:23.161254 2023] [mpm_event:notice] [pid 37:tid 139855306758984] AH00489: Apache/2.4.57 (Unix) configured -- resuming normal operations
[Fri May 19 17:10:23.161281 2023] [core:notice] [pid 37:tid 139855306758984] AH00094: Command line: '/usr/local/apache2/bin/httpd -D FOREGROUND'
{"level":"info","ts":1684516224.19098,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /Caddyfile:9 - Error during parsing: getting module named 'http.ip_sources.private_ranges': module not registered: http.ip_sources.private_ranges
{"level":"info","ts":1684516226.2237773,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /Caddyfile:9 - Error during parsing: getting module named 'http.ip_sources.private_ranges': module not registered: http.ip_sources.private_ranges
{"level":"info","ts":1684516229.2550886,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
Error: adapting config using caddyfile: parsing caddyfile tokens for 'servers': /Caddyfile:9 - Error during parsing: getting module named 'http.ip_sources.private_ranges': module not registered: http.ip_sources.private_ranges
`

my startup command:
`docker run --sig-proxy=false --name nextcloud-aio-mastercontainer --restart always --publish 8080:8080 -e APACHE_PORT=11000 -e APACHE_IP_BINDING=0.0.0.0 --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock:ro nextcloud/all-in-one:beta`

with [this commit](https://github.com/nextcloud/all-in-one/commit/48e70e2b00093210183d40c2c4912c6354788f12#diff-feba2bfdff2f11db21fa6cfc5e5674666dc8c183c9f4d340c9d93239882f775d) the Caddyfile got a Server Block with an comment line.
if APACHE_PORT != 443, [start.sh](https://github.com/nextcloud/all-in-one/blob/main/Containers/apache/start.sh#L42) will replace this with "trusted_proxies private_ranges" which leads to this error

**Comment by DO6FP** [comment]
I have the exact same issue on Debian 11 with v.5.2 on the beta channel.
(Publishing on Port 1100)

With the following startup command:
`sudo docker run --sig-proxy=false --name nextcloud-aio-mastercontainer --restart always --publish 8080:8080 -e APACHE_PORT=11000 -e SKIP_DOMAIN_VALIDATION=true --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock:ro nextcloud/all-in-one:beta`

**Comment by szaimen** [comment]
This is now released with v5.2.1 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by gerhard-thompson** [comment]
apache is green again :)
