### ISSUE TITLE
add imaginary_key with the update to 28

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#2591]
See https://github.com/nextcloud/server/pull/38365 and 
![image](https://github.com/nextcloud/all-in-one/assets/42591237/c612e9a7-9848-478d-9130-8f17b29d36cc)

**Comment by Rish-P** [comment]
Can I try and solve this issue, would be great if you could assign this to me.

**Comment by szaimen** [comment]
I can assign it to you but since NC28 is not out yet it probably does not make much sense to do this now :)

**Comment by Rish-P** [comment]
Okay, but I'll try to come up with something anyways... could you give me a rough idea on how to start with this problem? Maybe which directory or file I should be looking through to find the error...

**Comment by szaimen** [comment]
It is not an error but an enhancement :)

You would probably need to adjust these places:
https://github.com/nextcloud/all-in-one/blob/1771a72c0e5a37d43356c4d3e6c657dc5d4a0990/Containers/imaginary/Dockerfile#L35
https://github.com/nextcloud/all-in-one/blob/1771a72c0e5a37d43356c4d3e6c657dc5d4a0990/Containers/nextcloud/entrypoint.sh#L667-L669
And add the imaginary secret as environmental variable to the imaginary and nextcloud container in https://github.com/nextcloud/all-in-one/blob/main/php/containers.json

**Comment by Rish-P** [comment]
Alright thank you so much, will get on this

**Comment by szaimen** [comment]
This is now released with v8.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
