### ISSUE TITLE
Question: Backup Types

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/all-in-one#264]
We currently use Proxmox as a hypervisor for Nextcloud AIO as a VM. We use Proxmox backup server to make nightly backups of the VM, which appears to do the same as the builtin BORG backup system . Should I continue using the proxmox backups and not use Borg or should I use the Builtin Borg Backups?

**Comment by szaimen** [comment]
Feel free to use either backup solution. the built-in is especially meant for folks that don't have another backup possibility. Using the built-in one will likely become more attractive though when those two missing features are implemented: https://github.com/nextcloud/all-in-one/issues/38 and https://github.com/nextcloud/all-in-one/issues/47
