### ISSUE TITLE
Feature: Upgrade to PostgreSQL 14

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/all-in-one#265]
Upgrade from PostgreSQL 13 to 14.2. PostgreSQL 14.x is supposed to be a huge performance boost and may help with Nextcloud at a performance level.

**Comment by johnnyq** [comment]
Docker image: **14.2-alpine3.15**

**Comment by szaimen** [comment]
Thanks for the idea but I honestly wanted to wait for Nextcloud to become officially compatible with that version...

**Comment by johnnyq** [comment]
I did not know that it was not compatible. However I know it works, We have been running it on our platform and we have noticed a noticeable improvement moving to 14 from 13.

**Comment by szaimen** [comment]
I changed my mind a bit: in the past there were never troubles with Postgres updates so I trust @johnnyq that Nextcloud works with version. We can like this also test the built-in upgrade procedure before AIO gets released as stable.

**Comment by johnnyq** [comment]
Thats @szaimen  I upgraded Nextcloud and it went smooth and deff notice a speed difference. I didn't measure anything, it just feels alot snapper.

**Comment by szaimen** [comment]
> Thats @szaimen I upgraded Nextcloud and it went smooth and deff notice a speed difference. I didn't measure anything, it just feels alot snapper.

Great to hear, thanks for the feedback!
