### ISSUE TITLE
Login page doesn't load remotely on iPhone

### ISSUE THREAD

**Issue by gokou340** [nextcloud/all-in-one#2659]
Using Cloudflare, but not proxy or tunnel

### Steps to reproduce
1. Turn off WiFi and use cellular data on iPhone
2. Browse to Nextcloud URL on Safari
3. Nextcloud takes forever to load, and never loads the login screen
4. Connect to local WiFi, login loads

### Expected behavior 
Login page should load completely, regardless of being remotely connected or local

### Actual behavior 
Login page never loads remotely on iPhone

### Host OS 
Ubuntu/Portainer

#### Nextcloud AIO version 
v5.2.2

#### Current channel 
Latest Channel

#### Other valuable info 
Running behind Nginx Proxy Manager on another machine

**Comment by szaimen** [comment]
Hi, this is a bug in nextcloud/server. Please fill out the template here: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&projects=&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
