### ISSUE TITLE
domain does not point to this server

### ISSUE THREAD

**Issue by shumancw** [nextcloud/all-in-one#27]
Containers are all coming up ok, admin login works fine. When I get to the "Please type in the domain that will be used for Nextcloud:" portion, I input my domain name and get the error "domain does not point to this server". I'm able to ping the domain and in fact have pulled up the admin login using my domain, but I still get the error message.

Debian 10.11 w/current docker install based off of AIO instructions. NGINX proxy manager is forwarding cloud.xxxx.xyz using https to 192.168.1.82:8080.

Ideas?

**Comment by szaimen** [comment]
Hi, please see https://github.com/nextcloud/all-in-one/issues/15#issuecomment-983971267

**Comment by szaimen** [comment]
I changed my mind. Sry for the harsh answer!

Does it work if you change the `http://` in this line to `https://` ?

https://github.com/nextcloud/all-in-one/blob/13360b176e58deca026e8a190ab221131ac96549/php/src/Data/ConfigurationManager.php#L126

The file should be located inside the container here: `/var/www/docker-aio/php/src/Data/ConfigurationManager.php`

I wonder especially if Nextcloud and all plugins work like Office, Talk & Co.?
If yes, I would accept a PR that allows `https://`, too.

**Comment by shumancw** [comment]
> I changed my mind. Sry for the harsh answer!
> 
> Does it work if you change the `http://` in this line to `https://` ?
> 
> https://github.com/nextcloud/all-in-one/blob/13360b176e58deca026e8a190ab221131ac96549/php/src/Data/ConfigurationManager.php#L126
> 
> The file should be located inside the mastercontainer here: `/var/www/docker-aio/php/src/Data/ConfigurationManager.php`
> 
> I wonder especially if Nextcloud and all plugins like Office, Talk & Co. work afterwards and if you are able to log in with the android and desktop clients on your new Nextcloud instance?
> 
> If yes, I would accept a PR that allows `https://`, too.

No problem whatsoever. I'm sure you've just been hammered with requests and a lot of them regarding this subject. Thanks for responding back and thank you for your work on this project!
