### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#272]
add the function that the AIO interface password can be changed. So that if there is a password leak, the password can be changed. A nice optional feature would be to log into the nextcloud AIO interface with the nextcloud admin account, so that nextcloud admins can log into the AIO interface and change their password.

**Comment by R7JANV1** [comment]
The function that special characters are allowed would increase security significantly.

**Comment by szaimen** [comment]
For the moment feel free to just enter a very long password.
