### ISSUE TITLE
Option for ClamAV or Kaspersky?

### ISSUE THREAD

**Issue by OliverPifferi** [nextcloud/all-in-one#277]
Hey folks,

as I did just read that ClamAV-Support will come with [#78](https://github.com/nextcloud/all-in-one/issues/78), I was just wondering if the support for commercial Kaspersky-engine may be implemented as well, "reaching" outside the container using the Antivirus-app?

Thanks and have a nice weekend,

O.

**Comment by szaimen** [comment]
Hi, you should actually already be able to add Kaspersky as external engine to your Nextcloud. As with any other external application you need to make sure that the Nextcloud container can access the service and then configure the antivirus app as usual.

As this is not possible to automate for us, I'll close this issue.

**Comment by OliverPifferi** [comment]
Sorry for asking again but how do I exactly configure the container to access the service "underneath", running on the same host? Checked this with ClamAV running without success (couldn't fetch neither the socket nor the /var/run-file).

Any hints on that :-) ?

Thanks in advance,

Oliver

**Comment by szaimen** [comment]
See https://github.com/nextcloud/all-in-one/issues/186#issuecomment-1026901269

**Comment by szaimen** [comment]
You might be interested in this: https://www.zeit.de/digital/2022-03/kaspersky-virenschutz-software-bsi-cyberangriffe-risiko-russland

**Comment by OliverPifferi** [comment]
Well, it's the expected bullsh*it-progress that was nearly overdue - apart from my wish to implement it in Nextcloud. Reminds me on 2017.
