### ISSUE TITLE
Run borg compact after pruning archives with borg 1.2.0

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#279]
https://borgbackup.readthedocs.io/en/stable/usage/compact.html?highlight=compact#

(Borg 1.2.0 required)

(Will be available with debian-bookworm)

---

~~also add this to the readme docs on how to delete archives manually (if already part of ubuntu 22.04)~~ done with https://github.com/nextcloud/all-in-one/commit/9d4c591f1afa5b67ed64aaf7bf2517b2a95ce2b4

**Comment by gadric** [comment]
FYI: borgbackup 1.2.2 is also available in `debian bullseye-backports`

https://packages.debian.org/bullseye-backports/borgbackup

**Comment by szaimen** [comment]
That is an interesting idea! Not sure though if we should go this route.

**Comment by Zoey2936** [comment]
> That is an interesting idea! Not sure though if we should go this route as I don't want it to become unstable by doing so.

I think the backports are very stable, I use them everywhere for some years and had no problems so far

**Comment by szaimen** [comment]
I just also asked a colleague of mine regarding this and he agreed that using the backports for borg makes sense. Will do this then 👍

**Comment by szaimen** [comment]
This is now released with v2.1.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
