### ISSUE TITLE
Nextcloud Office Default Option

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/all-in-one#280]
I think it would be good to enable the following option by default

![image](https://user-images.githubusercontent.com/1812594/155902926-234d3252-dadc-4b84-80f6-ecf416ebf647.png)

as this will save Documents and such in Microsoft Office formats

We in live in such a Microsoft Office Oriented world that this will make the most sense to help bridge that gap

**Comment by szaimen** [comment]
Interesting idea but we will not change the default here. You can though ask for this feature here: https://github.com/nextcloud/richdocuments

**Comment by johnnyq** [comment]
okay will do thank you @szaimen
