### ISSUE TITLE
Default Apps to Install / Remove - Disable

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/all-in-one#281]
Install Following by default:

- Group folders - as Nextcloud is normally used amongst groups
- Impersonate - Allow an admin easy access to other users for delegation purposes
- Mail

Disable Following Apps by default

I think most admins disable them anyway and can always be re-enabled if need be

- Dashboard
- First run wizard
- Support
- Weather
- Usage Survey
- Nextcloud announcements

**Comment by szaimen** [comment]
Hello, thanks for your ideas but we considered the default apps carefully and will not change what is currently installed and enabled by default.

Luckily is adding, disabling and removing apps pretty easy and fast using Nextclouds interface. 

If you need to automate this I'd recommend that you write your own script that can run manually on your server after the first installation of aio.
