### ISSUE TITLE
Previews not working with Nextcloud AIO v 6.2.1 with Nextcloud 27.0.0

### ISSUE THREAD

**Issue by Byter3** [nextcloud/all-in-one#2908]
Previews not working with Nextcloud AIO v 6.2.1 with Nextcloud 27.0.0
preview generator app version: 5.3.0
Preview generator seems not working, thumbnails gets generated on the fly and when clicked it's loading the original file.
Heic thumbnails not showing in browser and in the Talk IOS app, but working in the Android Talk app and the Nextcloud app on both platforms, but if I click it it will load the entire heic file at least..

**Comment by dantefromhell** [comment]
I'm having a similar issue (although slightly different nextcloud versions) when opening the photos app previews are not shown, while clicking on the image itself opens and displays the image correctly.

According to my developer tools, the HTTP request for the previews (e.g. `https://<SERVER_FQDN>/apps/photos/api/v1/preview/39443?etag=a74042ef82bb9733b5d2fbc3f41ee1e3&x=512&y=512` fail with `HTTP/404`.

The server log file contains a few errors, but nothing directly related to photos or previews app.

I tried re-creating the previews with all `php occ preview:` commands to no success.

Versions
nextcloud-aio: 6.2.1
nextcloud: 26.0.3
preview generator: 5.3.0
photos: 2.2.0

**Comment by Byter3** [comment]
`{"reqId":"VRbK0hT5IWOJ8TtrqSCP","level":3,"time":"2023-07-09T22:55:06+00:00","remoteAddr":"192.168.1.1","user":"Amir","app":"no app in context","method":"GET","url":"/core/preview?fileId=188335&x=250&y=250","message":"Imaginary preview generation failed: Client error: `POST http://nextcloud-aio-imaginary:9000/pipeline?operations=%5B%7B%22operation%22%3A%22autorotate%22%7D%2C%7B%22operation%22%3A%22fit%22%2C%22params%22%3A%7B%22width%22%3A256%2C%22height%22%3A256%2C%22stripmeta%22%3A%22true%22%2C%22type%22%3A%22jpeg%22%2C%22norotation%22%3A%22true%22%2C%22quality%22%3A%2260%22%7D%7D%5D` resulted in a `400 Bad Request` response:\n{\"message\":\"Empty or unreadable image\",\"status\":400}\n","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67","version":"27.0.0.8","exception":{"Exception":"GuzzleHttp\\Exception\\ClientException","Message":"Client error: `POST http://nextcloud-aio-imaginary:9000/pipeline?operations=%5B%7B%22operation%22%3A%22autorotate%22%7D%2C%7B%22operation%22%3A%22fit%22%2C%22params%22%3A%7B%22width%22%3A256%2C%22height%22%3A256%2C%22stripmeta%22%3A%22true%22%2C%22type%22%3A%22jpeg%22%2C%22norotation%22%3A%22true%22%2C%22quality%22%3A%2260%22%7D%7D%5D` resulted in a `400 Bad Request` response:\n{\"message\":\"Empty or unreadable image\",\"status\":400}\n","Code":400,"Trace":[{"file":"/var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/guzzle/src/Middleware.php","line":72,"function":"create","class":"GuzzleHttp\\Exception\\RequestException","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/promises/src/Promise.php","line":209,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/promises/src/Promise.php","line":158,"function":"callHandler","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":[1,"*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/promises/src/TaskQueue.php","line":52,"function":"GuzzleHttp\\Promise\\{closure}","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/promises/src/Promise.php","line":251,"function":"run","class":"GuzzleHttp\\Promise\\TaskQueue","type":"->","args":[true]},{"file":"/var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/promises/src/Promise.php","line":227,"function":"invokeWaitFn","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/promises/src/Promise.php","line":272,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/promises/src/Promise.php","line":229,"function":"invokeWaitList","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/promises/src/Promise.php","line":69,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/guzzle/src/Client.php","line":189,"function":"wait","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/var/www/html/lib/private/Http/Client/Client.php","line":297,"function":"request","class":"GuzzleHttp\\Client","type":"->","args":["post","http://nextcloud-aio-imaginary:9000/pipeline",["/mnt/ncdata/files_external/rootcerts.crt",120,["[{\"operation\":\"autorotate\"},{\"operation\":\"fit\",\"params\":{\"width\":256,\"height\":256,\"stripmeta\":\"true\",\"type\":\"jpeg\",\"norotation\":\"true\",\"quality\":\"60\"}}]"],true,"image/jpeg","And 5 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/private/Preview/Imaginary.php","line":147,"function":"post","class":"OC\\Http\\Client\\Client","type":"->","args":["http://nextcloud-aio-imaginary:9000/pipeline",[["[{\"operation\":\"autorotate\"},{\"operation\":\"fit\",\"params\":{\"width\":256,\"height\":256,\"stripmeta\":\"true\",\"type\":\"jpeg\",\"norotation\":\"true\",\"quality\":\"60\"}}]"],true,"image/jpeg",null,[true],"And 2 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/private/Preview/GeneratorHelper.php","line":62,"function":"getCroppedThumbnail","class":"OC\\Preview\\Imaginary","type":"->","args":[["OC\\Files\\Node\\File"],256,256,false]},{"file":"/var/www/html/lib/private/Preview/Generator.php","line":397,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->","args":[["OC\\Preview\\Imaginary"],["OC\\Files\\Node\\File"],256,256]},{"file":"/var/www/html/lib/private/Preview/Generator.php","line":255,"function":"generateProviderPreview","class":"OC\\Preview\\Generator","type":"->","args":[["OC\\Files\\SimpleFS\\SimpleFolder"],["OC\\Files\\Node\\File"],256,256,true,false,"image/jpeg",""]},{"file":"/var/www/html/lib/private/Preview/Generator.php","line":155,"function":"getSmallImagePreview","class":"OC\\Preview\\Generator","type":"->","args":[["OC\\Files\\SimpleFS\\SimpleFolder"],[["OC\\Files\\SimpleFS\\SimpleFile"]],["OC\\Files\\Node\\File"],"image/jpeg","",true]},{"file":"/var/www/html/lib/private/Preview/Generator.php","line":116,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->","args":[["OC\\Files\\Node\\File"],[[250,250,true,"fill"]],"image/jpeg"]},{"file":"/var/www/html/lib/private/PreviewManager.php","line":192,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->","args":[["OC\\Files\\Node\\File"],250,250,true,"fill","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/core/Controller/PreviewController.php","line":144,"function":"getPreview","class":"OC\\PreviewManager","type":"->","args":[["OC\\Files\\Node\\File"],250,250,true,"fill"]},{"file":"/var/www/html/core/Controller/PreviewController.php","line":113,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[["OC\\Files\\Node\\File"],250,250,false,true,"fill"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->","args":[188335,250,250,false,true,"fill"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OC\\Core\\Controller\\PreviewController"],"getPreviewByFileId"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OC\\Core\\Controller\\PreviewController"],"getPreviewByFileId"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\PreviewController","getPreviewByFileId",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["core.Preview.getPreviewByFileId"]]},{"file":"/var/www/html/lib/base.php","line":1064,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/core/preview"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php","Line":113,"message":"Imaginary preview generation failed: Client error: `POST http://nextcloud-aio-imaginary:9000/pipeline?operations=%5B%7B%22operation%22%3A%22autorotate%22%7D%2C%7B%22operation%22%3A%22fit%22%2C%22params%22%3A%7B%22width%22%3A256%2C%22height%22%3A256%2C%22stripmeta%22%3A%22true%22%2C%22type%22%3A%22jpeg%22%2C%22norotation%22%3A%22true%22%2C%22quality%22%3A%2260%22%7D%7D%5D` resulted in a `400 Bad Request` response:\n{\"message\":\"Empty or unreadable image\",\"status\":400}\n","exception":[],"CustomMessage":"Imaginary preview generation failed: Client error: `POST http://nextcloud-aio-imaginary:9000/pipeline?operations=%5B%7B%22operation%22%3A%22autorotate%22%7D%2C%7B%22operation%22%3A%22fit%22%2C%22params%22%3A%7B%22width%22%3A256%2C%22height%22%3A256%2C%22stripmeta%22%3A%22true%22%2C%22type%22%3A%22jpeg%22%2C%22norotation%22%3A%22true%22%2C%22quality%22%3A%2260%22%7D%7D%5D` resulted in a `400 Bad Request` response:\n{\"message\":\"Empty or unreadable image\",\"status\":400}\n"},"id":"64ab424556d8d"}`

**Comment by kaibagley** [comment]
I'm also having this issue, previews don't get generated, clicking an image just has a loading circle, but can still download quickly

**Comment by dantefromhell** [comment]
I've been having quite some issues with preview generation, especially with PDF larger than 100MB. I ended up disabling the imaginary container on nextcloud-aio 6.2.1 and reset the preview generation as documented in the `previewgenerator` repo README
https://github.com/nextcloud/previewgenerator#i-want-to-resetregenerate-all-previews
