### ISSUE TITLE
Failed to update: TOOMANYREQUESTS

### ISSUE THREAD

**Issue by NiciTheNici** [nextcloud/all-in-one#2910]
### Steps to reproduce
1. Stop running containers in webui
2. Click "Start and update containers"

### Expected behavior 
The containers start normally and dont throw any errors
### Actual behavior 
I get "Server error. Please check the #mastercontainer logs for details."

### Host OS 
Im using Arch Linux

#### Nextcloud AIO version 
Nextcloud AIO v6.2.1

#### Current channel 
Latest channel
#### Other valuable info 
[mastercontainer logs.txt](https://github.com/nextcloud/all-in-one/files/11971136/mastercontainer.logs.txt)

**Comment by Zoey2936** [comment]
at the moment just wait, docker resets the rate limit once a day. Relates to https://github.com/nextcloud/all-in-one/discussions/2667

**Comment by NiciTheNici** [comment]
Thing is I've been having this issue for 4 days already. See the attached files I commented in issue #2889

**Comment by Zoey2936** [comment]
The issue you mention, is different one, not?

**Comment by NiciTheNici** [comment]
Yes, it is. I'm not sure how related it is to the problem I'm having now but I wanted to show with the logs I commented there that this has been an ongoing issue for 4 days now and that waiting 24 hasnt fixed it for me.

[Here is a direct link to said commemt. ](https://github.com/nextcloud/all-in-one/issues/2889#issuecomment-1616735787)

**Comment by NiciTheNici** [comment]
Welp, I tried again just to be sure today and it worked. This happily also fixed #2889 for me :)
