### ISSUE TITLE
Wrong cp command in migration.md

### ISSUE THREAD

**Issue by notEvil** [nextcloud/all-in-one#2921]
### Steps to reproduce
1. Migrate from another instance
2. Use the command to copy datadir

### Expected behavior

Everything in `/path/to/nextcloud/data` ends up in `nextcloud-aio-nextcloud:/mnt/ncdata`

### Actual behavior

Everything ends up in `nextcloud-aio-nextcloud:/mnt/ncdata/data` (leading to "Appdata is not present...")

### Host OS

Arch Linux

#### Nextcloud AIO version

6.2.1

#### Current channel

latest

#### Other valuable info

Command must use `/path/to/nextcloud/data/.`, see https://docs.docker.com/engine/reference/commandline/cp/

**Comment by szaimen** [comment]
Hi, can you edit https://github.com/nextcloud/all-in-one/edit/main/migration.md and adjust the command in there? Thanks!
