### ISSUE TITLE
dbpasword error on fresh install

### ISSUE THREAD

**Issue by burnclouds** [nextcloud/all-in-one#2954]
### Steps to reproduce
1. Fresh install Debian stable and update fully
2. Install docker
3. Install nextcloud-aio
4. Attempt initial setup

### Expected behavior 
System starts and runs after initial setup

### Actual behavior
dbpasword error

### Host OS
Debian

#### Nextcloud AIO version
Docker latest

#### Current channel
26

#### Other valuable info
docker run --sig-proxy=false --name nextcloud-aio-mastercontainer --restart unless-stopped --publish 8080:8080 --publish 8443:8443 --publish 80:80 --volume /media/nc/nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock:ro nextcloud/all-in-one:latest

use all defaults and enter my domain name... then:

![image](https://github.com/nextcloud/all-in-one/assets/9850267/e54db383-1b9a-4e6c-84b4-75bbf0a702d4)

"https://nc.domain.tld:8443/api/docker/logs?id=nextcloud-aio-nextcloud"
```
psql: error: connection to server at "nextcloud-aio-database" (172.18.0.4), port 5432 failed: FATAL:  password authentication failed for user "oc_nextcloud"
Waiting for the database to start...
psql: error: connection to server at "nextcloud-aio-database" (172.18.0.4), port 5432 failed: FATAL:  password authentication failed for user "oc_nextcloud"
Waiting for the database to start...

```

$ sudo docker exec nextcloud-aio-nextcloud grep dbpassword config/config.php
$ 

I presume the lack of a response means that the config file doesn't define the password properly (or at all) but I'm not a dbadmin. suggestions and Ideas are welcome.

**Comment by szaimen** [comment]
Will be answered in https://github.com/nextcloud/all-in-one/discussions/2953
