### ISSUE TITLE
Backups to multiple disks

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#299]
Is that already possible?  If not, will this feature be added?  Personally, I always like to have a data carrier on the server on which weekly or daily backups are stored and every month an external hard drive is connected to save the monthly backup on another data carrier, which is separated from the server again after the backup.

**Comment by szaimen** [comment]
This make sense in general but I fear it is also out of scope for AIO. Do you think we should add some docs on this though?

**Comment by R7JANV1** [comment]
I don't think I'm the only one facing this problem so I would say that documentation would be very helpful.

**Comment by szaimen** [comment]
will do
