### ISSUE TITLE
No incoming video in Talk on Android

### ISSUE THREAD

**Issue by Byter3** [nextcloud/all-in-one#2996]
This:

https://github.com/nextcloud/talk-android/issues/2704

The solution for now seems to roll back the janus server, if you eant to use Talk on Android, what is to be frank a core feature of Talk.

So can we have a roll back of Janus in the AIO container?

**Comment by szaimen** [comment]
Hi, the fix is in https://github.com/nextcloud/all-in-one/pull/2886 and is scheduled for the next release.

**Comment by Byter3** [comment]
> Hi, the fix is in https://github.com/nextcloud/all-in-one/pull/2886 and is scheduled for the next release.

Thank, you!
I must have missed this!

**Comment by Byter3** [comment]
> Hi, the fix is in #2886 and is scheduled for the next release.

Hi updated AIO to v6.3.0. Still not working.

**Comment by szaimen** [comment]
This is now released with v6.4.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
