### ISSUE TITLE
Summary of changes when an update is proposed

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#303]
> An update of mastercontainer is available. Please click...

Where can I find a summary of the changes? How do I know if the changes should be applied quickly (big bug...) or if I can wait until next weekend (not urgent update...)?

It would be nice to have a summary (not the complete list of PR or bugs, just a sentence...).

And it would be nice if the message was, in case of a new version: 

> An update of mastercontainer to **v0.18.3** is available. Please click...

What do you think ?

**Comment by szaimen** [comment]
You can find the changes here: https://github.com/nextcloud/all-in-one/releases so simply follow the releases to get to know all new changes/fixes.
In general you should always update as soon as possible.

**Comment by szaimen** [comment]
> OK, thanks !
> Maybe a link to github on the AIO interface ?

Good idea! will add this

**Comment by szaimen** [comment]
will track this in https://github.com/nextcloud/all-in-one/issues/276#issue-1150711968
