### ISSUE TITLE
Login issues with Firefox

### ISSUE THREAD

**Issue by DrZoidberg09** [nextcloud/all-in-one#304]
I just have updated to v0.6 and now I cannot login in my Firefox browser. It just reloads the login page without any error message. 
This is a behavior I encounter also in my Kubernetes deployment of Nextcloud.

Any suggestions from your side? Maybe even to get a proper error message or log to understand the issue?

**Comment by szaimen** [comment]
Hello, where can't you log in using Firefox? In the aio interface or in Nextcloud itself?

**Comment by DrZoidberg09** [comment]
Just Nextcloud itself. The AIO interface is fine. With Chromium based browsers everything is fine.

**Comment by szaimen** [comment]
I fear this is most likely a Nextcloud bug then (since you also have this problem on your kubernetes installation). So nothing we can do here. Feel free to open a new issue in the server repository if it wasn't alread reported. Thanks!
