### ISSUE TITLE
Apache not starting in Nextcloud All-in-One Docker setup

### ISSUE THREAD

**Issue by MightyMirko** [nextcloud/all-in-one#3066]
### Discussed in https://github.com/nextcloud/all-in-one/discussions/3062

<div type='discussions-op-text'>

<sup>Originally posted by **MightyMirko** July 31, 2023</sup>
Hello Folks,

Description of the Issue:
I have followed the instructions provided in the repository's README to set up Nextcloud using the Docker Compose file. However, I am encountering an issue where Apache is not starting.

Error Message:
Upon inspecting the logs, I noticed the following error related to Apache:

![grafik](https://github.com/nextcloud/all-in-one/assets/23053791/b1ff0be2-e71c-4528-bce0-8d0e954234cf)

Setup Details:

    Operating System: LXC Container (fuse enabled)
    Docker Version: Docker version 20.10.24, build 297e1284d3bd092e9bc96076c3ddc4bb33f8c7ab
    Docker Compose Version: docker-compose version 1.29.2, build unknown

Steps Taken:
   
    I modified the Docker Compose file to customize the setup according to my requirements.
    I executed the Docker Compose command to bring up the containers.
    I set up my reverse proxy on another host, also containered, to point to hostname:11000

Expected Outcome:
I expected Apache to start successfully, and the Nextcloud instance to be accessible at the specified URL.

Troubleshooting Attempts:
I have reviewed the logs and attempted to identify the cause of the issue, but I haven't been able to resolve it.

Attachments:
[Nextcloud log](https://pastebin.com/k7ZbaNCp)
[Database](https://pastebin.com/Wa50RsZ8)
[reverse proxy](https://pastebin.com/4rAxkNQd)
https://pastebin.com/ffHaXmyQ

![grafik](https://github.com/nextcloud/all-in-one/assets/23053791/729f00de-038f-4fe1-a4d3-e2672a3eb6cf)

`> nmap -Pn c117-nextcloud -p80,443,8000-9000,11000
Starting Nmap 7.70 ( https://nmap.org ) at 2023-07-31 22:51 CEST
Nmap scan report for c117-nextcloud (10.163.25.208)
Host is up (0.00083s latency).
rDNS record for 10.163.25.208: c117-nextcloud.mydomain.loc
Not shown: 1003 closed ports
PORT     STATE SERVICE
8080/tcp open  http-proxy
MAC Address: 1E:F2:7F:DB:F7:9B (Unknown)

Nmap done: 1 IP address (1 host up) scanned in 3.39 seconds
`

I would greatly appreciate it if you could assist me in resolving this issue with Apache. I am open to providing any additional information or logs that might be necessary for troubleshooting.</div>

**Comment by MightyMirko** [comment]
```
{
  "aio_services_v1": [
    {
      "container_name": "nextcloud-aio-apache",
      "depends_on": [
        "nextcloud-aio-onlyoffice",
        "nextcloud-aio-collabora",
        "nextcloud-aio-talk",
        "nextcloud-aio-nextcloud",
        "nextcloud-aio-notify-push"
      ],
      "display_name": "Apache",
      "image": "nextcloud/aio-apache",
      "ports": [
        {
          "ip_binding": "%APACHE_IP_BINDING%",
          "port_number": "%APACHE_PORT%",
          "protocol": "tcp"
        },
        {
          "ip_binding": "%APACHE_IP_BINDING%",
          "port_number": "%APACHE_PORT%",
          "protocol": "udp"
        }
      ],
      "internal_port": "%APACHE_PORT%",
      "environment": [
        "NC_DOMAIN=%NC_DOMAIN%",
        "NEXTCLOUD_HOST=nextcloud-aio-nextcloud",
        "COLLABORA_HOST=nextcloud-aio-collabora",
        "TALK_HOST=nextcloud-aio-talk",
        "APACHE_PORT=%APACHE_PORT%",
        "ONLYOFFICE_HOST=nextcloud-aio-onlyoffice",
        "TZ=%TIMEZONE%",
        "APACHE_MAX_SIZE=%APACHE_MAX_SIZE%",
        "APACHE_MAX_TIME=%NEXTCLOUD_MAX_TIME%",
        "NOTIFY_PUSH_HOST=nextcloud-aio-notify-push"
      ],
      "volumes": [
        {
          "source": "nextcloud_aio_nextcloud",
          "destination": "/var/www/html",
          "writeable": false
        },
        {
          "source": "nextcloud_aio_apache",
          "destination": "/mnt/data",
          "writeable": true
        }
      ],
      "restart": "unless-stopped",
      "backup_volumes": [
        "nextcloud_aio_nextcloud",
        "nextcloud_aio_apache"
      ],
      "networks": [
        "nextcloud-aio"
      ],
      "read_only": true,
      "tmpfs": [
        "/var/log/supervisord",
        "/var/run/supervisord",
        "/usr/local/apache2/logs",
        "/tmp",
        "/home/www-data"
      ]
    }
```

should it work if i install OnlyOffice, Collabora, Talk?

**Comment by MightyMirko** [comment]
Any ideas anyone?

**Comment by szaimen** [comment]
See https://github.com/nextcloud/all-in-one/discussions/3062
