### ISSUE TITLE
Random issue on thumbnails and photos after AIO fresh install

### ISSUE THREAD

**Issue by mangabs** [nextcloud/all-in-one#3078]
### Steps to reproduce
1. Setup Nextcloud AIO on latest version with default options (Collabora + Imaginary + Nextcloud Talk).
2. Go to /apps/photos/ or go to /apps/files/ in the "Photos" folder.

### Expected behavior 
Photos thumbnails are displayed in /apps/photos/ and each photo can be opened by clicking on it.
Photos thumbnails are displayed in /apps/files/ in the "Photos" folder.

### Actual behavior 
No photos thumbnails in /apps/photos/ and it's not possible to open it. 
No photos thumbnails in /apps/files/ in the "Photos" folder.
I can add new photos in the web interface but there are no thumbnails and it's not possible to open them.
If I try to open photos, Web Interface become available with this message:
"Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log."

### Host OS 
Debian 12 VMware VM (2vCPU - 4Go RAM).
Latest Docker version (24.0.5) installed as indicated here: https://docs.docker.com/engine/install/debian/.
Docker running in the default Context (not rootless).
 
#### Nextcloud AIO version 
Nextcloud AIO v6.4.0

#### Current channel 
"You are running the latest channel."

#### Other valuable info 

I've done lot of new AIO install after reset the instance as indicated here: https://github.com/nextcloud/all-in-one#how-to-properly-reset-the-instance. Sometimes it works well (thumbnails works and I can open photos), sometimes not: it seems to be a random behavior.

On a buggy AIO instance, the steps below can solve the problem:
1. In the AIO Panel, stop containers
2. Uncheck the Collabora box
3. Start containers ==> photos and thumbnails works as expected.
4. Stop containers
5. Check again the collabora box
6. Start containers ==> photos and thumbnails always works as expected.

In /settings/admin/richdocuments, i always have "Collabora Online server is reachable."
https://github.com/nextcloud/all-in-one/discussions/1358 doesn't help me.

AIO Instances are created on a VM behind firewall and without reverse proxy, with the command:
docker run \
--sig-proxy=false \
--name nextcloud-aio-mastercontainer \
--restart always \
--publish 8080:8080 \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
--env NEXTCLOUD_DATADIR="/mnt/nextcloud-data" \
--env SKIP_DOMAIN_VALIDATION=true \
nextcloud/all-in-one:latest

See attached logs of a buggy instance.
[nextcloud-aio-collabora.log](https://github.com/nextcloud/all-in-one/files/12260161/nextcloud-aio-collabora.log)
[nextcloud-aio-nextcloud.log](https://github.com/nextcloud/all-in-one/files/12260162/nextcloud-aio-nextcloud.log)
[nextcloud-aio-database.log](https://github.com/nextcloud/all-in-one/files/12260163/nextcloud-aio-database.log)
[nextcloud-aio-apache.log](https://github.com/nextcloud/all-in-one/files/12260164/nextcloud-aio-apache.log)

**Comment by szaimen** [comment]
Hi, can you upgrade to v7.0.0 Beta and check if that resolves things? See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by proudhon** [comment]
I can confirm switching to the beta channel solved the issue for me.

**Comment by mangabs** [comment]
Hi, I always have the same problem with Nextcloud AIO v7.0.0 and Nextcloud 27.0.2.
The workaround describe above still works.
Is there a way to find what's wrong with the logs?

**Comment by mangabs** [comment]
I created today 2 new users and they are affected by this problem. If I work without collabora container, it seems that there is no problem. Without Collabora container, I can create new users and there are not affected by this problem.
