### ISSUE TITLE
Feature: nginx instead of Apache

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/all-in-one#308]
Im just throwing the idea out there.

Use nginx instead of Apache for performance reasons. This should dramatically increase performance and handoff to PHP FPM processes extremely fast and keep everything lightweight. This is how I ran Nextcloud instance before Nextcloud AIO

**Comment by szaimen** [comment]
Hey, thanks for the idea but we will not do this because of maintenance reasons: I don't want to get into a situation where I need to keep track of Nextclouds nginx documentation.
