### ISSUE TITLE
publish to marketplaces

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#31]
- [ ] **Google Cloud**
- https://cloud.google.com/build/docs/building/build-vm-images-with-packer
- https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/packer/examples/gce
- https://cloud.google.com/marketplace/docs/partners/get-started
- https://cloud.google.com/marketplace/docs/partners/vm

---

- [x] **AWS**
- https://docs.aws.amazon.com/cli/latest/userguide/cli-services-ec2-instances.html#launching-instances
- https://www.ipswitch.com/blog/import-machine-images-into-aws-with-packer
- https://docs.aws.amazon.com/marketplace/latest/userguide/product-submission.html
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-ebs.html
- https://learn.hashicorp.com/collections/packer/aws-get-started

---

- [x] **Digitalocean**
- https://docs.digitalocean.com/products/images/custom-images/how-to/upload/
- https://marketplace.digitalocean.com/vendors
- https://github.com/digitalocean/marketplace-partners#digitalocean-marketplace-partner-tools

---

- [x] **Microsoft Azure**
- https://docs.microsoft.com/en-us/azure/marketplace/marketplace-virtual-machines
- https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-manage-vm
- https://docs.microsoft.com/en-us/azure/marketplace/azure-vm-use-approved-base
- https://github.com/Azure/azvmimagebuilder/tree/main/quickquickstarts/0_Creating_a_Custom_Linux_Managed_Image

---

- [x] **IONOS** didn't find docs about how to do that.

---

- [x] **Linode**
- https://www.linode.com/marketplace/app-partners/
- https://www.linode.com/docs/guides/how-to-deploy-a-new-linode-using-a-stackscript/

---

- [x] ~~**OVH**~~

**Comment by sim-san** [comment]
Has the plan to release Nextcloud AIO via Azure Marketplace been scrapped ?

**Comment by szaimen** [comment]
For now we'll focus on https://github.com/nextcloud/all-in-one/issues/476 :)

However it may be added after the stable release in a follow-up.
