### ISSUE TITLE
Reverse proxy documentation using nginx

### ISSUE THREAD

**Issue by rallisf1** [nextcloud/all-in-one#315]
I understand caddy is a better fit for this but since I already use [nginx](https://nginxproxymanager.com/) for all my other containers, I'd appreciate an nginx section in the reverse-proxy documentation, preferabbly with TLS offloading (you'll need to share the certs between the containers).

Cheers!

**Comment by szaimen** [comment]
Hey, feel free to investigate yourself how it could work behind nginx. I'll gladly add it to the reverse proxy documentation then.

As a starting point should probably simply translating the caddy config into nginx syntax work:
![image](https://user-images.githubusercontent.com/42591237/156889462-760a9a09-675a-4dac-bd9c-d768adda44f0.png)
(of course you need to provide your own certificates in the config for nginx which is not necessary using caddy as reverse proxy)

**Comment by twwd** [comment]
At the first glance, my Nginx config seems to work. I've startet the AIO container with the custom `APACHE_PORT=11000` and then used the following config in my server block (besides the TLS stuff etc.):

```
location / {
    proxy_pass http://localhost:11000;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

# Websockets for Push
location /push/ {
    proxy_pass http://localhost:11000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}

# Websockets for Collabora
location /cool/ {
    proxy_pass http://localhost:11000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}
```

**Comment by szaimen** [comment]
Thanks @twwd !

Are you sure that the block below is really neded though? (Doesn't it work without?)
Or maybe aren't you able to enable websocket connections for the whole domain? This would eliminate the need to configure every endpoint manually...

```
# Websockets for Push
location /push/ {
    proxy_pass http://localhost:11000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}

# Websockets for Collabora
location /cool/ {
    proxy_pass http://localhost:11000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
}
```

**Comment by twwd** [comment]
My first config was without these parts and it didn't work. I'm not a Nginx pro, but I'm not aware of a method to combine all three blocks.

**Comment by szaimen** [comment]
Thanks! So I guess enabling websocket connections for the whole domain does not work?

**Comment by twwd** [comment]
Regarding to [SO](https://stackoverflow.com/a/39216976), it might work. I'll try in the next days and give an update here.

**Comment by twwd** [comment]
At the first glance, the combined config seems to work:

```
location / {
        proxy_pass http://localhost:11000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
```

**Comment by szaimen** [comment]
Nice!

**Comment by happyreacer** [comment]
I used the 
```
location / {
        proxy_pass http://localhost:11000;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
```


but no notifications in my apps work

**Comment by szaimen** [comment]
Are you sure that this is not due to https://github.com/nextcloud/android/issues/8684?

**Comment by happyreacer** [comment]
@szaimen  No, unfortunately it is not. I have taken other parameters. However, this has gone through trying. Unfortunately, I do not know what the individual values have for effects. But it worked as follows

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name www.*;

    include /config/nginx/ssl.conf;
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomians; preload;";
    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app nextcloud-aio-apache;
        set $upstream_port 11000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_max_temp_file_size 2048m;
    }
}
```
