### ISSUE TITLE
Database Restore Failure during Migration

### ISSUE THREAD

**Issue by captaindyson** [nextcloud/all-in-one#3166]
### Steps to reproduce
1. Follow AIO Migraiton Guide
2. Reach step 12 - Starting Containers
3.

### Expected behavior 
Containers all start ... Happy days!
### Actual behavior 
containers start appart from those waiting on the Database. In looking at the DB container logs, i find the following:

````
+ GREP_STRING='Name: oc_appconfig; Type: TABLE; Schema: public; Owner:'
+ grep -q 'Name: oc_appconfig; Type: TABLE; Schema: public; Owner:' /mnt/data/database-dump.sql
++ grep 'Name: oc_appconfig; Type: TABLE; Schema: public; Owner:' /mnt/data/database-dump.sql
++ grep -oP 'Owner:.*$'
++ sed 's|Owner:||;s| ||g'
grep: /mnt/data/database-dump.sql: binary file matches
+ DB_OWNER=
+ '[' '' = nextcloud ']'
+ '[' '' '!=' oc_nextcloud ']'
+ DIFFERENT_DB_OWNER=1
+ psql -v ON_ERROR_STOP=1 --username nextcloud --dbname nextcloud_database
2023-08-15 19:53:45.825 BST [74] ERROR:  zero-length delimited identifier at or near """" at character 13
2023-08-15 19:53:45.825 BST [74] STATEMENT:  CREATE USER "" WITH PASSWORD '<omitted out of caution>' CREATEDB;
ERROR:  zero-length delimited identifier at or near """"
LINE 1: CREATE USER "" WITH PASSWORD '<omitted out of caution>...
                    ^
The database import failed. Please restore a backup and try again.
For further clues on what went wrong, look at the logs above.
````

### Host OS 
Unraid 6.12.3

#### Nextcloud AIO version 
6.4.0
#### Current channel 
Latest
#### Other valuable info 
Thanks for any help in advance!

**Comment by szaimen** [comment]
Hi, it looks like the grep string is not found. What does `grep 'Name: oc_appconfig; Type: TABLE' /mnt/data/database-dump.sql` return?

**Comment by szaimen** [comment]
This is weird, never seen this problem coming up but I agree, we could add the -a flag to the command...

**Comment by captaindyson** [comment]
Just to be clear (in case it helps) the above results were when running grep from the unraid shell on the file. If i use the following:
`sudo docker run --rm --volume nextcloud_aio_database_dump:/mnt/data:rw alpine grep 'Name: oc_appconfig; Type: TABLE' /mnt/data/database-dump.sql`
Which i believe would run the grep insude the dump container?
I get this again:
```
-- Name: oc_appconfig; Type: TABLE; Schema: public; Owner: ncadmin
-- Data for Name: oc_appconfig; Type: TABLE DATA; Schema: public; Owner: ncadmin
```
without the need for -a

**Comment by szaimen** [comment]
So what is the problem then?

**Comment by captaindyson** [comment]
The import still fails as in the original post.

**Comment by szaimen** [comment]
So as I said it is weird but we can try to fix this by adding the -a flag.

**Comment by captaindyson** [comment]
I have been testing the Beta today. This does not seem to have soved the issue, though i am no longer getting logs, so it is hard to tell exactly what is going on.
Upon start, the DB container starts outputting the lines:
```
The database import failed. Please restore a backup and try again.
For further clues on what went wrong, look at the logs above.
```
but now with no error above it, where before there was detailed error info as in my original post.
I have stopped and restarted the container with log time stamps to chow the absence of anything informative:
```
2023-09-03T08:47:38.385719143Z The database import failed. Please restore a backup and try again.
2023-09-03T08:47:38.385743338Z For further clues on what went wrong, look at the logs above.
2023-09-03T08:47:38.835123925Z The database import failed. Please restore a backup and try again.
2023-09-03T08:47:38.835139755Z For further clues on what went wrong, look at the logs above.
2023-09-03T08:47:39.413723002Z The database import failed. Please restore a backup and try again.
2023-09-03T08:47:39.413740074Z For further clues on what went wrong, look at the logs above.
2023-09-03T08:47:40.567816928Z The database import failed. Please restore a backup and try again.
2023-09-03T08:47:40.567847976Z For further clues on what went wrong, look at the logs above.
2023-09-03T08:47:42.193694908Z The database import failed. Please restore a backup and try again.
```
It just keeps sending those error lines every second. If this should be a new bug report, just let me know and i can open a new one.

**Comment by szaimen** [comment]
You probably want to reset the instance properly by following https://github.com/nextcloud/all-in-one#how-to-properly-reset-the-instance and then try the steps again that you did to migrate to AIO.

**Comment by captaindyson** [comment]
I can confirm that this has fixed the issue. Thankyou for your hard work!
