### ISSUE TITLE
Your Collabora Online server needs updating

### ISSUE THREAD

**Issue by MariusQuabeck** [nextcloud/all-in-one#3175]
![image](https://github.com/nextcloud/all-in-one/assets/17063564/8ee3d01b-ac5e-4ab7-9bf4-47afdb08e3f1)

AIO v6.4.0
Nextcloud Office 8.0.3

**Comment by szaimen** [comment]
You can switch to beta if you dont want to wait:
https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
