### ISSUE TITLE
Cron job does not work correctly

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#318]
![grafik](https://user-images.githubusercontent.com/90777102/156997486-ac28d1e2-843f-407d-bc15-4e50a9638830.png)

**Comment by R7JANV1** [comment]
{"reqId":"TiiFRxjdWKYXLYXFukqi","level":3,"time":"2022-03-07T09:17:14+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Unsupported operand types: int * string","userAgent":"--","version":"23.0.2.1","exception":{"Exception":"TypeError","Message":"Unsupported operand types: int * string","Code":0,"Trace":[{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelCanonMakerNotes.php","line":215,"function":"loadSingleValue","class":"lsolesen\\pel\\PelIfd","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"},4828,0,256]},{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php","line":406,"function":"load","class":"lsolesen\\pel\\PelCanonMakerNotes","type":"->","args":[]},{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelTiff.php","line":159,"function":"load","class":"lsolesen\\pel\\PelIfd","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"},10]},{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelExif.php","line":108,"function":"load","class":"lsolesen\\pel\\PelTiff","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"}]},{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php","line":216,"function":"load","class":"lsolesen\\pel\\PelExif","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"}]},{"file":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelJpeg.php","line":126,"function":"load","class":"lsolesen\\pel\\PelJpeg","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"}]},{"file":"/var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php","line":442,"function":"__construct","class":"lsolesen\\pel\\PelJpeg","type":"->","args":[{"__class__":"lsolesen\\pel\\PelDataWindow"}]},{"file":"/var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php","line":384,"function":"getExifPelBackup","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"}]},{"file":"/var/www/html/custom_apps/maps/lib/Service/PhotofilesService.php","line":264,"function":"getExif","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"}]},{"file":"/var/www/html/custom_apps/maps/lib/BackgroundJob/AddPhotoJob.php","line":56,"function":"addPhotoNow","class":"OCA\\Maps\\Service\\PhotofilesService","type":"->","args":[{"__class__":"OC\\Files\\Node\\File"},"User"]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":79,"function":"run","class":"OCA\\Maps\\BackgroundJob\\AddPhotoJob","type":"->","args":[{"photoId":40267,"userId":"User"}]},{"file":"/var/www/html/lib/public/BackgroundJob/QueuedJob.php","line":47,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/html/cron.php","line":128,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/html/custom_apps/maps/vendor/lsolesen/pel/src/PelIfd.php","Line":447,"CustomMessage":"--"},"id":"6225cd9b53db6"}

**Comment by szaimen** [comment]
Thanks! So it is most likely an issue with the maps app.
Feel free to disable the app to solve this problem.

**Comment by R7JANV1** [comment]
I could imagine that it may have something to do with the duplicate finder. I activated this app and after the app did not work I deactivated it again and removed it. This could be from the time from about this time the cron no longer worked.

**Comment by R7JANV1** [comment]
For all with the same problem:
If the Maps app is deactivated and reactivated, the problem is also solved.
