### ISSUE TITLE
use oci manifests in the future 

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#3182]
- [x] wait a few months, e.g. until january 2024 so that we are sure everyone updated to https://github.com/nextcloud/all-in-one/commit/2469461a3cc07c5a6a6e965c9c3c17a018d6fd9b in the meantime.

https://github.com/nextcloud-releases/all-in-one/blob/7cff84a6f95365a3295d0e7e987c69b30612729a/.github/workflows/build_images.yml#L75
maybe then https://docs.docker.com/engine/reference/commandline/buildx_imagetools_create could be used inside the push beta workflow

Was initially discussed in https://github.com/nextcloud/all-in-one/discussions/2903

**Comment by Zoey2936** [comment]
The push beta workflow still nerds changes

**Comment by szaimen** [comment]
> The push beta workflow still nerds changes

Oh, I forgt. Would you mind creating a PR for that? :)

**Comment by Zoey2936** [comment]
sorry, but I currently have not much time for this
