### ISSUE TITLE
What can be done against this warning in the logs?

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#319]
{"reqId":"EIeATMES0ctPOpBTGz9y","level":2,"time":"2022-03-07T10:14:16+00:00","remoteAddr":"","user":"--","app":"OC\\Log\\Rotate","method":"","url":"--","message":"Log file \"/var/log/nextcloud/nextcloud.log\" was over 10485760 bytes, moved to \"/var/log/nextcloud/nextcloud.log.1\"","userAgent":"--","version":"23.0.2.1","id":"6225dbd259ce2"}

**Comment by szaimen** [comment]
> {"reqId":"EIeATMES0ctPOpBTGz9y","level":2,"time":"2022-03-07T10:14:16+00:00","remoteAddr":"","user":"--","app":"OC\Log\Rotate","method":"","url":"--","message":"Log file "/var/log/nextcloud/nextcloud.log" was over 10485760 bytes, moved to "/var/log/nextcloud/nextcloud.log.1"","userAgent":"--","version":"23.0.2.1","id":"6225dbd259ce2"}

This is a simple warning that the log was rotated. You can ignore it.

> {"reqId":"FubUdtOkIsl5V8xnXLd7","level":3,"time":"2022-03-07T10:32:30+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 5568488 bytes) at /var/www/html/lib/private/Files/Storage/Local.php#277","userAgent":"--","version":"23.0.2.1","id":"6225dfab07be9"}

Seems like you don't have enough memory for some operations. Please increase the available memory for your system.

**Comment by R7JANV1** [comment]
RAM or ROM?

Both are more than enough so I don't understand this log.

**Comment by szaimen** [comment]
Maybe it has to do with the maps app so please monitor if this error happens to appear after you disabled the maps app.
