### ISSUE TITLE
backup disk to the monitoring app

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#323]
Adding the backup disk to the monitoring app to see how much disk space is available.
Possibly include in the documentation?

**Comment by szaimen** [comment]
Hi you should already be able to make it show up in the serverinfo app by using this option: https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
But I think the usecase of this is pretty limited so I will not document this.
