### ISSUE TITLE
New item button

### ISSUE THREAD

**Issue by foxhoundv** [nextcloud/all-in-one#3374]
### Steps to reproduce
1. Update to Nextcloud AIO v7.2.1

### Expected behavior 
Display button correctly
### Actual behavior 
View is different.

### Host OS 
Ubuntu 20.04.06

#### Nextcloud AIO version 
v7.2.1
#### Current channel 
latest
#### Other valuable info 
All browsers are updated to latest.

It show up fine in Microsoft Edge Browser
![image](https://github.com/nextcloud/all-in-one/assets/16512250/0dbad3e3-f2c6-49e4-92b0-0cda2acaebbd)

Not in Chrome...
![image](https://github.com/nextcloud/all-in-one/assets/16512250/4e161c04-cdbf-406b-9a42-88454e093b32)

Not in Firefox...
![image](https://github.com/nextcloud/all-in-one/assets/16512250/9d67c850-ef53-4f78-82da-df16f3a20f8b)

Not in Brave...
![image](https://github.com/nextcloud/all-in-one/assets/16512250/6f72603e-40ab-4e37-bfd0-95f5ed523865)

**Comment by szaimen** [comment]
Hi, you need to clear the browser cache.
