### ISSUE TITLE
Optimisations of the installation description for AIO with Docker rootless and Nginx proxy manager

### ISSUE THREAD

**Issue by MarvvanPal** [nextcloud/all-in-one#3399]
### Is your feature request related to a problem? Please describe. 

While installing along the given instruction of how to install Nextcloud AIO [with rootless ](https://github.com/nextcloud/all-in-one/blob/main/docker-rootless.md)and behind a [Nginx Proxy Manager](https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#1-add-this-to-your-reverse-proxy-config) I stumbled across different questions. This includes a few minor points before deploying AIO and one bigger issue after the deployment (see #3396) .

### Describe the solution you'd like

- If using Portainer to deploy the AIO the variable $XDG_RUNTIME_DIR is not available. In this case it is necessary to insert the path (e.g. /run/user/1000/docker.sock) directly into the [Docker compose file](https://github.com/nextcloud/all-in-one/blob/main/compose.yaml). If you are not sure how to retrieve the path, you can run on the host: `echo $XDG_RUNTIME_DIR`
- Extend the (Nginx) proxy manager config to avoid triggering brute force prevention like mentioned in #2968 AND/OR
- ...explain how to change parameter like trusted_proxies mentioned in #3396 
- Differentiate more between `localhost` and `ip-address of the host` [in this section](https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#nginx-proxy-manager). Example: 

> Of course you need to modify <your-nc-domain> to the domain on which you want to run Nextcloud.
> 
> **Please note**
> _Running the Proxy Manager on the host_
> The above configuration will only work if your reverse proxy is running directly on the host that is running the docker daemon. If the reverse proxy is running in a docker container, you can use the --network host when starting the reverse proxy container in order to connect the reverse proxy container to the host network. 
> 
> _Running the Proxy Manager in a Docker container_
> If that is not an option or not possible for you (like e.g. on Windows or if the reverse proxy is running on a different host), you can alternatively instead of localhost use the private ip-address of the host that is running the docker daemon. If you are not sure how to retrieve that, you can run: ip a | grep "scope global" | head -1 | awk '{print $2}' | sed 's|/.*||'. If the command returns a public ip-address, use ip a | grep "scope global" | grep docker0 | awk '{print $2}' | sed 's|/.*||' instead (the commands only work on Linux)

### Describe alternatives you've considered

none

### Additional context

none

**Comment by szaimen** [comment]
Hi, thanks a lot for your recommendations! All of them make sense! A PR that improves the docs would be very welcome!
