### ISSUE TITLE
Raspberry Pi 4 – docker: no matching manifest for linux/arm/v8 in the manifest list entries.

### ISSUE THREAD

**Issue by terraboss** [nextcloud/all-in-one#3407]
Again and again. 

I don't understand why I can't just install Nextcloud AIO! Such errors should be caught. Or at least for popular platforms, like the Raspberry Pi, there should be at least installation instructions that address these kind of problems and offer solution steps.

**docker: no matching manifest for linux/arm/v8 in the manifest list entries.**

Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default

Kernel Version: 6.1.21-v8+
 Operating System: Raspbian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64

**Comment by szaimen** [comment]
Hi, AIO needs a 64-bit OS in order to work.
