### ISSUE TITLE
Apache IP Binding with IPv6

### ISSUE THREAD

**Issue by PlayerSchark** [nextcloud/all-in-one#3441]
### Steps to reproduce
1. Setup a reverse Proxy by following the steps on https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
2. in docker set the environment variable APACHE_IP_BINDING=[::]
3. Start the AIO

### Expected behavior 
Apache should bind to [::]
### Actual behavior 
Error message:
You provided an ip-address for the apache container's ip-binding but it was not a valid ip-address.
It is set to '[::]'.

### Host OS 
Alpine Linux v3.13

#### Nextcloud AIO version 
nextcloud/all-in-one:latest

#### Current channel 
You are running the [latest](https://github.com/nextcloud/all-in-one#how-to-switch-the-channel) channel

#### Other valuable info 
The host runs behind a reverse proxy

**Comment by szaimen** [comment]
Hi, may I ask why 127.0.0.1 is not sufficient for you?

**Comment by PlayerSchark** [comment]
Thanks for your reply.

Well, there are two main reasons for that.
1. it's Ipv4 and I think [::1] won't work either. This is the main reason. Since multiple years Ipv4 should be replaced with Ipv6. And this topic becomes more important these days.
2. 
> This is only recommended to be set if you use localhost in your reverse proxy config to connect to your AIO instance. If you use an ip-address instead of localhost, you should set it to 0.0.0.0.
https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md

As per documentation, if you run behind a reverse proxy and nextcloud is being targeted by an IP you should use 0.0.0.0

Nextcloud AIO in general seems to support IPv6 https://github.com/nextcloud/all-in-one/blob/main/docker-ipv6-support.md

**Comment by Zoey2936** [comment]
https://github.com/nextcloud/all-in-one/blob/9d640fa9d678c2b522ef069abafa5bc66651014a/Containers/mastercontainer/start.sh#L182 would changing this regex not be enough to fix it?

**Comment by szaimen** [comment]
> would changing this regex not be enough to fix it?

We would need to make sure that the `[]` are not given to docker because it will bug out IIRC...

**Comment by Zoey2936** [comment]
compose supports [], so you mean that they need to be escaped?
```
    ports:
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
      - "[::1]:53:53/tcp"
      - "[::1]:53:53/udp"
      - "192.168.168.3:53:53/tcp"
      - "192.168.168.3:53:53/udp"
```

**Comment by szaimen** [comment]
```
# docker run --name test -p [::]:81:80 alpine
# docker inspect test
...
            "PortBindings": {
                "80/tcp": [
                    {
                        "HostIp": "::",
                        "HostPort": "81"
                    }
                ]
            },
...
```

**Comment by PlayerSchark** [comment]
As per [RFC-5952](https://www.rfc-editor.org/rfc/rfc5952) (update of [RFC-4291](https://www.rfc-editor.org/rfc/rfc4291))It seems to be enough without `[]` as long as you don't use a Port. So what about rejection of the `[]` format?

**Comment by Zoey2936** [comment]
> https://github.com/nextcloud/all-in-one/blob/9d640fa9d678c2b522ef069abafa5bc66651014a/Containers/mastercontainer/start.sh#L182
> would changing this regex not be enough to fix it?

I've added : to the regex, and set "APACHE_IP_BINDING=::1", restarted the containers and:
![grafik](https://github.com/nextcloud/all-in-one/assets/75573284/eb0ffb77-b993-420b-94bf-a61df7aa35ff)

**Comment by szaimen** [comment]
> > https://github.com/nextcloud/all-in-one/blob/9d640fa9d678c2b522ef069abafa5bc66651014a/Containers/mastercontainer/start.sh#L182
> > 
> > would changing this regex not be enough to fix it?
> 
> I've added : to the regex, and set "APACHE_IP_BINDING=::1", restarted the containers and: ![grafik](https://user-images.githubusercontent.com/75573284/271642775-eb0ffb77-b993-420b-94bf-a61df7aa35ff.png)

All right! Would someone be able to adjust the regex then? :)

**Comment by PlayerSchark** [comment]
Everything seems to work fine.

![image](https://github.com/nextcloud/all-in-one/assets/37115511/a4643475-f6a6-41f2-8e0d-e8bcaaca2a0e)

I may mention that it wasn't enough to set APACHE_IP_BINDING to IPv6 to fully support IPv6.
I also had to follow the steps on https://github.com/nextcloud/all-in-one/blob/main/docker-ipv6-support.md because i ran into the following error. But because of good documentation it was easy to solve the problem.
```
NOTICE: PHP message: Could not get digest of container nextcloud/aio-postgresql:beta cURL error 6: Could not resolve host: auth.docker.io (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://auth.docker.io/token?service=registry.docker.io&scope=repository:nextcloud/aio-postgresql:pull
```
I looking forward to see it on the latest channel.
