### ISSUE TITLE
AIO behind caddy still rewrite to 443 port instead of the port I use

### ISSUE THREAD

**Issue by lianqi1998** [nextcloud/all-in-one#3473]
### Steps to reproduce
1. My ISP block 80, 443 port
2. Add caddy reverse proxy config [with ACME DNS-challenge](https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#caddy-with-acme-dns-challenge) and open 20000 to replace 443. Caddy  can get cert and run well.
3. Use AIO behind caddy with --env SKIP_DOMAIN_VALIDATION=true
4. Open https://my.domain:20000 Nextcloud will rewrite to https://my.domain/login 
5. I can enter Nextcloud panel after I add port manually. And after login the matter disappeared.
6. After I modified "domain": "my.domain:20000" in configuration.json as folder nextcloud_aio_mastercontainer/_data/data/  It seems fixed (I'm not sure, I changed a lot)
### Expected behavior 
After acess Nextcloud with specific port I think AIO should not rewrite adress to 443
### Actual behavior 
With right reverse proxy config, Nextcloud still rewrite adress as default (443).
After login the matter disappeared, so I guess it's a bug
### Host OS 

debian 11
#### Nextcloud AIO version 
AIO v7.2.1
#### Current channel 
[latest](https://github.com/nextcloud/all-in-one#how-to-switch-the-channel) channel
#### Other valuable info 
By the way, I wonder to know if I modified "domain": "my.domain:20000" in configuration.json with port information directly, it will produce other problem?
Thank You for Your Patience.

**Comment by Zoey2936** [comment]
https://github.com/nextcloud/all-in-one#are-other-ports-than-the-default-443-for-nextcloud-supported - also the :2000 could cause problems

**Comment by lianqi1998** [comment]
> If port 443 and/or 80 is blocked for you, you may use the ACME DNS-challenge or a Cloudflare Tunnel
I think perhaps AIO support other port, by get cert by ACME DNS-challenge? 

> https://github.com/nextcloud/all-in-one#are-other-ports-than-the-default-443-for-nextcloud-supported - also the :2000 could cause problems↳
**So that means AIO can only run on 443 ?**

But what confuses me is AIO will work after login. It seems like it is a bug happens on login. 
And could I know why abandon other port support, it looks as if once solve the problem while login, AIO will run other port behind reverse proxy.
