### ISSUE TITLE
The configuration of the mastercontainer is not stored in the volume

### ISSUE THREAD

**Issue by pestotoast** [nextcloud/all-in-one#35]
I was testing the backups and my backup-container exited with `configuration.json not present. Cannot perform the backup!`

After some investigation I noticed that  the `configuration.json` of the mastercontainer is no longer saved to `/mnt/docker-aio-config/data/configuration.json`

```
root@ubuntu-2gb-fsn1-2:~/all-in-one# docker exec -it nextcloud-aio-mastercontainer ls -la /mnt/docker-aio-config/data/
total 8
drwxrwx--- 2 www-data www-data 4096 Dec  3 12:20 .
drwxrwx--- 6 root     root     4096 Dec  3 12:20 ..
```
I tested with the nextcloud/all-in-one:develop image.

**Comment by szaimen** [comment]
Thanks for the heads up! Should be fixed with https://github.com/nextcloud/all-in-one/commit/7c8b134e8d9e54e7768a406cd0eeafb5c71dd77e and I made sure that this doesn't happen again with https://github.com/nextcloud/all-in-one/pull/37

**Comment by HedgeShot** [comment]
Installed AIO yesterday and got the same error message in the logs when trying to perform a backup:

```
configuration.json not present. Cannot perform the backup!
 ```

How did you fix this?

**Comment by szaimen** [comment]
Hello, please post the exact command that you used to create the container in a new issue. Thanks! If you don't have it anymore, posting the output of `sudo docker inspect nextcloud-aio-mastercontainer` should work as well.

**Comment by HedgeShot** [comment]
hi, I started the container from the `docker-compose` file that you provide on this repo. `docker-compose up -d --build`

**Comment by szaimen** [comment]
Hm... no idea then :/

**Comment by HedgeShot** [comment]
I actually changed something before doing `docker-compose up`... I removed `name` from the docker-compose file as it was throwing an error (`name` is not supported in docker-compose 3.1). It automatically created a name `user_nextcloud_aio_mastercontainer` instead of `nextcloud_aio_mastercontainer`. Bumping to a version higher than 3.1 in the docker-compose file solved the issue.
