### ISSUE TITLE
Allow Creation Without Domain

### ISSUE THREAD

**Issue by JohnDHowell54** [nextcloud/all-in-one#351]
Hello, I have looked around for this but saw no answer.

I want to create an image with no domain name, just access via IP only and only on LAN. Is there anyway this can be done?

As of now I am stuck on this screen and cannot continue with the setup.

![image](https://user-images.githubusercontent.com/22427799/157976186-08ab0ae7-0f0f-462d-b820-98d6fe0c298e.png)

**Comment by szaimen** [comment]
No, this is not possible and will not be implemented.

**Comment by JohnDHowell54** [comment]
Darn. Thank you for your quick reply, have a nice day.

**Comment by szaimen** [comment]
Have a nice day, too!
