### ISSUE TITLE
Consider renaming mastercontainer?

### ISSUE THREAD

**Issue by ya-d** [nextcloud/all-in-one#354]
Many projects are currently trying to use more sensible language and avoid naming things master/slave. 

As this project is in its early stages maybe you should consider renaming `mastercontainer` to `maincontainer`, `primarycontainer` or something similar.

But English is not my primary language nor am I into this debate. Using `master` on its own might be ok, some projects are keeping that and only change the more obviously offensive part `slave`.

**Comment by szaimen** [comment]
Hi, thanks for the idea but I fear it is already to late for that because we internally rely on that name.
I hope it is fine to keep this name because of this.
Also, we don't use the word `slave` anywhere so I hope the decision is fine.
