### ISSUE TITLE
Unable to save when adding a directory to backup list

### ISSUE THREAD

**Issue by BigMichi1** [nextcloud/all-in-one#3544]
### Steps to reproduce
1. open Backup and Restore section
2. enter a local filesystem path and try to submit

### Expected behavior 

no failure when adding a local filesystem directory to the backup list

### Actual behavior 
unable to add a local filesystem directory to the backup list, manually changing the config file and entering the directory at least works

### Host OS 
Ubuntu 20.10

#### Nextcloud AIO version 
7.4.1

#### Current channel 
latest

#### Other valuable info 
![image](https://github.com/nextcloud/all-in-one/assets/91786/d5cc2980-aaf7-47e7-a5d3-4b7bcb438407)
![image](https://github.com/nextcloud/all-in-one/assets/91786/87bb150e-1e9a-4899-93f0-dc89b4c2cc28)

**Comment by szaimen** [comment]
This is now fixed with v7.5.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
