### ISSUE TITLE
Missing .ocdata file

### ISSUE THREAD

**Issue by david-steg** [nextcloud/all-in-one#355]
Hello

It seems that by using the "NEXTCLOUD_DATADIR" Env. Variable the ".ocdata" will be missing and the following error will be prompt:
```
#2 {main}Your data directory is invalid
Ensure there is a file called ".ocdata" in the root of the data directory.
```
I had to create the file manualy. Now it works.

P.S. the Directory Permission was right: "-rw-r--r-- 1 www-data root"

**Comment by szaimen** [comment]
I cannot reproduce that. It worked in my testing without any problem.

**Comment by david-steg** [comment]
I tried it again and it work... I don't know i might had a special case. Sorry for the inconvenience...

**Comment by szaimen** [comment]
No problem!
