### ISSUE TITLE
Docker Socket Proxy fails to start.

### ISSUE THREAD

**Issue by ShapeShifter499** [nextcloud/all-in-one#3566]
### Steps to reproduce
Install the docker, see log. 

### Expected behavior 
Docker socket proxy should load and work. 

### Actual behavior 
AIO settings webpage states "starting" but it never appears to actually start. I see errors in the log for nextcloud-aio-docker-socket-proxy, log attached at the bottom.

### Host OS 
Manjaro x86_64

#### Current channel 
Nextcloud AIO v7.4.1

#### Other valuable info 
[nextcloud-aio-docker-socket-proxy_log.txt](https://github.com/nextcloud/all-in-one/files/13045687/nextcloud-aio-docker-socket-proxy_log.txt)

**Comment by szaimen** [comment]
This is the issue apparently:
```
[ALERT]    (23) : Not enough memory to allocate 1073741815 entries for fdtab!
[ALERT]    (23) : No polling mechanism available.
  This may happen when using thread-groups with old pollers (poll/select), or
  it is possible that haproxy was built with TARGET=generic and that FD_SETSIZE
  is too low on this platform to support maxconn and the number of listeners
  and servers. You should rebuild haproxy specifying your system using TARGET=
  in order to support other polling systems (poll, epoll, kqueue) or reduce the
  global maxconn setting to accommodate the system's limitation. For reference,
  FD_SETSIZE=1024 on this system, global.maxconn=536870896 resulting in a maximum of
  1073741815 file descriptors. You should thus reduce global.maxconn by 536870396. Also,
  check build settings using 'haproxy -vv'.
```

**Comment by szaimen** [comment]
https://github.com/haproxy/haproxy/issues/2043

**Comment by szaimen** [comment]
Possible fix: https://github.com/matrix-org/sytest/commit/a42e75a3845f339ad41aac9b3cf5fef820c0f7fc

**Comment by ShapeShifter499** [comment]
> Possible fix: [matrix-org/sytest@a42e75a](https://github.com/matrix-org/sytest/commit/a42e75a3845f339ad41aac9b3cf5fef820c0f7fc)

so this would be added to the haproxy used inside the AIO?

**Comment by szaimen** [comment]
> > Possible fix: [matrix-org/sytest@a42e75a](https://github.com/matrix-org/sytest/commit/a42e75a3845f339ad41aac9b3cf5fef820c0f7fc)
> 
> so this would be added to the haproxy used inside the AIO?

yes

**Comment by sol8712** [comment]
Will adding maxconn to the haproxy config directly be removed on a restart of the container?


You could attempt setting a higher limit for all of docker as in this Q/A:
https://stackoverflow.com/questions/71828013/docker-container-has-a-too-large-file-descriptor-limit-ulimit-n

Or try this only on your AIO docker file as shown by the OP here:
https://www.reddit.com/r/EndeavourOS/comments/u9cpb7/docker_and_limitsconf/?rdt=64474

**IF** these work these are temporary fixes. Also maybe usefull for debugging.

**Comment by szaimen** [comment]
This is now fixed with v7.5.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by ShapeShifter499** [comment]
@szaimen I have pulled the latest beta and the nextcloud-aio-docker-socket-proxy now loads properly. Thank you for the help.

**Comment by ShapeShifter499** [comment]
@szaimen One more related concern, while the container doesn't throw errors anymore. I do see this in Nextcloud for the App API. I'm guessing I ignore the fact it cannot access the socket since it's getting a proxy?   It does return a message that it connected successfully.  Does this screenshot look correct to you?

I edited out my domain name.
![Screenshot from 2023-10-22 04-44-39](https://github.com/nextcloud/all-in-one/assets/388665/64af3450-5f01-470d-9518-990c6c038c5d)

**Comment by szaimen** [comment]
This looks like something that should get reported to https://github.com/cloud-py-api/app_api/issues

**Comment by ShapeShifter499** [comment]
@szaimen ```--volume /var/run/docker.sock:/var/run/docker.sock:ro```  should still work if I set it up like this?  or should the 'ro' be 'rw' to use this?  the documentation is a little unclear to me.

**Comment by szaimen** [comment]
Yes ro shouls work
