### ISSUE TITLE
Nginx revers proxy Header upgrade

### ISSUE THREAD

**Issue by prilly-dev** [nextcloud/all-in-one#3588]
there are some IOS issues related to passing a upgrade header to the client in cases the backend server is h2 compatible and nignx revers proxy is forced to http1.1, backend will try to upgrade this connection to h2 by applying a upgrade header that is now passed to the client, in cases where websocket is used with ios devices aka nextcloud talk this will fail.

by using the map 

map $http_upgrade $connection_upgrade {
	default upgrade;
        ''      close;
}

		# Websocket
		proxy_http_version 1.1;
        	proxy_set_header Upgrade $http_upgrade;
        	proxy_set_header Connection $connection_upgrade;

You are not mitigating the problem.

this config should be removed and replaced with

	### header upgrade issue on IOS devices ###
	### https://megamorf.gitlab.io/2019/08/27/safari-nsposixerrordomain-100-error-with-nginx-and-apache.html ###
	proxy_hide_header Upgrade;

as long as the backedn server is h2 compliant and the proxy pass module in nginx is only http1.1 this error will not be correct handled.

also upgrade header is a hop on header and should not be proxied at all!

**Comment by prilly-dev** [comment]
see here: https://trac.nginx.org/nginx/ticket/915

**Comment by szaimen** [comment]
Hi, I am confused. So this is actually a bug in nginx/ios and we need to add this as workaround to our docs?

**Comment by Zoey2936** [comment]
doing so would break websocket...

**Comment by prilly-dev** [comment]
its sufficient to add this line of code to mitigate the issue: keep the map and the upgrade connection, that would be correct to handle websocket upgrade.

please see here: https://megamorf.gitlab.io/2019/08/27/safari-nsposixerrordomain-100-error-with-nginx-and-apache.html

adding this line:
proxy_hide_header Upgrade;

should take care of the upgrade h2 header that safari and ios handles very strict

**Comment by Zoey2936** [comment]
you can't set and hide a header at the same time

**Comment by prilly-dev** [comment]
> you can't set and hide a header at the same time

Yes you can, there are different directions for set and hide, set header is headers applied to the proxyed connection. While hide is the respons

**Comment by Zoey2936** [comment]
> > you can't set and hide a header at the same time
> 
> Yes you can, there are different directions for set and hide, set header is headers applied to the proxyed connection. While hide is the respons

Sorry, you are right, you can use both at the same time, but I can't confirm this problem in safari and I don't see a reason why a web server needs a workaround to fix a problem of safari. But that is discussable.

**Comment by prilly-dev** [comment]
> > > you can't set and hide a header at the same time
> > 
> > 
> > Yes you can, there are different directions for set and hide, set header is headers applied to the proxyed connection. While hide is the respons
> 
> Sorry, you are right, you can use both at the same time, but I can't confirm this problem in safari and I don't see a reason why a web server needs a workaround to fix a problem of safari. But that is discussable.

If you google around a little with this one liner and nextcloud you will find multiple post about this issue. 

The reson i need this is becouse i have a nginx revers proxy in front of apache with nextcloud, apache is h2 ready and also serves ssl only, nginx is also ssl. 

With the default nextcloud config and a revers proxy in front you will face issues with the talk client on apple devices. This one liner fixes this. As i said apple wil terminate when it get the upgrade h2 header ment for the proxymodule that nginx will pass to the client, using hide removes this header.

The source of this issue is that nginx proxymodule is only http1.1 capable so apache will try to upgrade this connection to h2 with this header, this header should no be passed on to the client. Client to proxy connection is already h2 so apple clients will terminate the connection upon reciving this header

**Comment by Zoey2936** [comment]
even if this is still and issue of apple and just a workaround, I would say just create a PR adding this to the apache, nginx and nginx-proxy-manager reverse-proxy.md

**Comment by prilly-dev** [comment]
Iam not using your code, i just stumbled across this while looking for redirect for well-known card dav. I noticed this and felt like give a heads up.

https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_hide_header

If you see here many headers are removed default, upgrade is currently debated about beeing added. But some uses cases make that non trivial, so for this case you need to manualy hide this header. Anyway there are no usescases that make this a problem, as again the right behaviour is to not pass on hop on headers

**Comment by prilly-dev** [comment]
According to rfc 2616, the HTTP/1.1 spec treats the following headers as hop-by-hop by default: Keep-Alive, Transfer-Encoding, TE, Connection, Trailer, Upgrade, Proxy-Authorization and Proxy-Authenticate. When encountering these headers in a request, a compliant proxy should process or action whatever it is these headers are indicating, and not forward them on to the next hop.

**Comment by FlattusBlastus** [comment]
So the NPM Custom location should have this text?
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Port $server_port;
proxy_set_header X-Forwarded-Scheme $scheme;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Accept-Encoding "";
proxy_set_header Host $host;
proxy_hide_header Upgrade;

![image](https://github.com/nextcloud/all-in-one/assets/78336592/03d9659c-408b-4b46-a9f1-b8caf4993bd1)

**Comment by FlattusBlastus** [comment]
I volunteer to write the updated instructions

**Comment by szaimen** [comment]
> I volunteer to write the updated instructions

cool, then go ahead :)

**Comment by Zoey2936** [comment]
I've added this to my NPMplus to test, but that broke websockets. So strongly against adding this, see conf here: https://github.com/ZoeyVid/NPMplus/blob/f4a07d44a79ac485a99289382f740397c85b2af3/rootfs/usr/local/nginx/conf/conf.d/include/proxy.conf#L13 and https://github.com/ZoeyVid/NPMplus/blob/fa43fc2daa6769b9a03cab2b9903b2832b817638/rootfs/usr/local/nginx/conf/nginx.conf#L71

**Comment by prilly-dev** [comment]
There are a lot of talk about this problem, i can see that other have reported that this breaks websocket in multiple other projects also.

what version of nginx are you using? what service is using websocket? do you use internal or other signaling servers for talk?

**Comment by szaimen** [comment]
> I've added this to my NPMplus to test, but that broke websockets. So strongly against adding this, see conf here: [ZoeyVid/NPMplus@`f4a07d4`/rootfs/usr/local/nginx/conf/conf.d/include/proxy.conf#L13](https://github.com/ZoeyVid/NPMplus/blob/f4a07d44a79ac485a99289382f740397c85b2af3/rootfs/usr/local/nginx/conf/conf.d/include/proxy.conf#L13) and [ZoeyVid/NPMplus@`fa43fc2`/rootfs/usr/local/nginx/conf/nginx.conf#L71](https://github.com/ZoeyVid/NPMplus/blob/fa43fc2daa6769b9a03cab2b9903b2832b817638/rootfs/usr/local/nginx/conf/nginx.conf#L71) and [ZoeyVid/NPMplus@`fa43fc2`/backend/templates/proxy_host.conf#L40](https://github.com/ZoeyVid/NPMplus/blob/fa43fc2daa6769b9a03cab2b9903b2832b817638/backend/templates/proxy_host.conf#L40)

Thanks for testing! Closing then
