### ISSUE TITLE
Clarify backup systems

### ISSUE THREAD

**Issue by ph00lt0** [nextcloud/all-in-one#36]
Nextcloud now has a backup system (https://github.com/nextcloud/backup) I wonder how this relates to the Borg implementation in AIO?

I think it would be wise to have one solution for backups and make that work well across all implementations of nextcloud. This would also make migrations easier and more reliable.

**Comment by szaimen** [comment]
Hello, you can simply install the backup app through the store and configure it easily yourself.
See https://apps.nextcloud.com/apps/backup
So you can easily use both solutions.
Cheers!

**Comment by ph00lt0** [comment]
@szaimen i am mentioning it because i don't think it is a good idea to add more complexity/variety in this area. It adds only more maintenance work across projects. Some standardization would be better.

**Comment by szaimen** [comment]
So here my answer:

>  The most basic reason was that if your Nextcloud instance is broken, you willl not be able to restore it to the state before until you've fixed your instance if you are only using the backup app, as far as I understood it. 
That's actually something that the borg solution is capable of!

> Also we don't run into any timeoutissues, the tool is already well proven, we can map a path outside the container into the backup container for easy storing on external drives, it doesn't run as the same user like the nextcloud but as root instead, etc.

**Comment by szaimen** [comment]
Personally, I don't think that it's bad to have those two options because the borg one is more reliable but only supports local backup and the nextcloud backup app supports all kinds of remote backups if you need that. So they complement each other pretty well, imho. :)

**Comment by ph00lt0** [comment]
> So here my answer:
> 
> > The most basic reason was that if your Nextcloud instance is broken, you willl not be able to restore it to the state before until you've fixed your instance if you are only using the backup app, as far as I understood it.
> > That's actually something that the borg solution is capable of!
> 
> > Also we don't run into any timeoutissues, the tool is already well proven, we can map a path outside the container into the backup container for easy storing on external drives, it doesn't run as the same user like the nextcloud but as root instead, etc.
> 
> Is that reason enough? ;)

Your explanation makes sense. Although I think if you break your instance this badly if might be better to reinstall and recover from there.  I am mostly afraid that all these options are going to confuse people. 

Borg surely is an awesome project and way to backup, that's actually how I have been doing it myself for long time already.Not sure why you say borg can only be done locally? I have this setup to run with remote storage.

**Comment by szaimen** [comment]
> Your explanation makes sense. Although I think if you break your instance this badly if might be better to reinstall and recover from there. 

Maybe yes but if you only have to make one click I think it is much easier and faster than having to reinstall everything ;)

> I am mostly afraid that all these options are going to confuse people.

I don't think so but I am open to add some more explanation to the interface or docs if this should happen. :)

> Borg surely is an awesome project and way to backup, that's actually how I have been doing it myself for long time already.Not sure why you say borg can only be done locally? I have this setup to run with remote storage.

Its simply like this because we've implemented it this way :)

Allowing to configure a remote backup for borg would double the solutions that are available in this regard (what I think you wanted to prevent) and would make the interface much more complex for configuration, etc. That's why we only allow local backups :)

**Comment by szaimen** [comment]
> > Your explanation makes sense. Although I think if you break your instance this badly if might be better to reinstall and recover from there.
>
> Maybe yes but if you only have to make one click for restoring, I think it is much easier and faster than having to reinstall everything ;)

Feel free to try it out yourself:
- Start the containers the first time
- verify that Nextcloud works (by logging in)
- click on Create Backup in the aio interface
- start the containers again
- run: `sudo docker exec --user root -it nextcloud-aio-nextcloud rm -rf / and sudo docker exec -it --user root nextcloud-aio-database rm -rf /*`
- now nextcloud and the databas should be completely empty as you've just deleted everything (you can verify that of course)
- now open the aio interface again and click on `restore last backup`, wait a bit until thats done and click on `start containers` again. Now you should see that everything is completely restore and functional again :)

**Comment by ph00lt0** [comment]
@szaimen Yeah might be good to clarify that Borg backups here are only local restore points here in the readme. And indeed i don't think there should be another remote option :) 

Also in the readme we could clarify why this borg option adds value compared the other app-based local backup option. I am starting a PR with proposal.
