### ISSUE TITLE
[Bug]: Unable to rename files on S3 and more

### ISSUE THREAD

**Issue by dee-kryvenko** [nextcloud/all-in-one#3662]
I wanted to bring up attention to the https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/326 and also related https://github.com/nextcloud/fulltextsearch_elasticsearch/issues/270 in this repository. Based on responses and activities so far, it looks to me this is not seen as a critical issue, not in https://github.com/nextcloud/server/issues/41209 it looks like. Elasticsearch deemed to be "optional" component, and I guess it is in certain types of installations - that's why I wanted to bring attention to this issue here in the AIO repository.

As it stands right now, out of the box, installed as AIO - NC is broken. Feel free to close this issue, this is really only meant to bring attention to the issue on the elasticsearch repo.

**Comment by szaimen** [comment]
Hi, there is indeed nothing we can do in AIO to fix this
