### ISSUE TITLE
Logged out of Nextcloud on a regular basis

### ISSUE THREAD

**Issue by KenBW2** [nextcloud/all-in-one#3674]
### Steps to reproduce
1. Log in to Nextcloud
2. Come back after an as yet indeterminate time. It seems random but it's probably dependent on the last access
3. See the login page

### Expected behavior

Once I'm logged in, I should stay logged in forever

### Actual behavior

I end up being faced with the login page on a roughly daily basis

When I try to log in, the _first time_ it doesn't matter what I enter as the password - it just loads the login screen again with no error

### Host OS

Ubuntu

#### Nextcloud AIO version

Manual install compose.yml

Nextcloud Hub 5 (27.0.2)

#### Other valuable info 

Cookies are valid for 15 days:

![cookies](https://github.com/nextcloud/all-in-one/assets/366540/d5fdae93-f658-46f4-beb0-3e7195070f3e)

No values for session configs

```
$ sudo docker exec --user www-data -it nextcloud-1 php occ config:system:get session_keepalive
$ sudo docker exec --user www-data -it nextcloud-1 php occ config:system:get session_lifetime
$ sudo docker exec --user www-data -it nextcloud-1 php occ config:system:get remember_login_cookie_lifetime

```

The default 1440 for `session.gc_maxlifetime`

```
45d6a22374d4:/var/www/html$ php -i | grep gc_maxlifetime
session.gc_maxlifetime => 1440 => 1440
```

**Comment by szaimen** [comment]
Will be answered in https://github.com/nextcloud/all-in-one/discussions/3673

**Comment by KenBW2** [comment]
Interestingly a different laptop which has been in suspend for a number of days, overlapping the above, was logged in as soon as I returned to it this evening

**Comment by KenBW2** [comment]
@szaimen Can I have this ticket reopened? I've had this happen twice today

Nothing in the Nextcloud Logging page. I'm happy to peruse other logs

**Comment by szaimen** [comment]
See https://github.com/nextcloud/all-in-one/discussions/3673#discussioncomment-7477965
