### ISSUE TITLE
Notify Push container can't start. notify_push does not have execution permissions.

### ISSUE THREAD

**Issue by dvino** [nextcloud/all-in-one#3714]
### Steps to reproduce
1. Install AIO
2. Start containers

### Expected behavior 
Notify Push container can`t start

``` bash
docker ps
```
```
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS                          PORTS
         NAMES
.......

7849dd0a4d45   nextcloud/aio-notify-push:latest           "/start.sh"              3 minutes ago   Restarting (0) 57 seconds ago
         nextcloud-aio-notify-push
.......
```
### Host OS 
qemu VM 
x86_64  Ubuntu 22.04.3

#### Nextcloud AIO version 
Nextcloud AIO v7.5.1

#### Current channel 
latest
#### Other valuable info 

logs nextcloud-aio-notify-push:
```
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
/start.sh: line 51: /nextcloud/custom_apps/notify_push/bin/x86_64/notify_push: Permission denied
/start.sh: line 51: /nextcloud/custom_apps/notify_push/bin/x86_64/notify_push: Permission denied
```
`notify_push` does not have execution permissions.
``` bash
docker run -it --rm --volume nextcloud_aio_nextcloud:/var/www/html:rw alpine sh -c "ls -l /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push"
```
```
-rw-r--r--    1 xfs      xfs       22581232 Nov 10 01:02 /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push
```

When I set the execution permissions, the container started up fine.
``` bash
docker run -it --rm --volume nextcloud_aio_nextcloud:/var/www/html:rw alpine sh -c "chmod +x /var/www/html/custom_apps/notify_push/bin/x86_64/notify_push"
```

**Comment by Zoey2936** [comment]
see https://github.com/nextcloud/all-in-one/pull/3707

**Comment by szaimen** [comment]
This is now fixed with 7.7.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by dvino** [comment]
Thank you! It works great

**Comment by jospoortvliet** [comment]
yeah, switching to Beta works for me as well! Nice work.

**Comment by JoseRamirezMoreno** [comment]
Solved it as follows:

1. sudo docker exec -it nextcloud-aio-nextcloud /bin/bash
2. cd /var/www/html/custom_apps/notify_push/bin/x86_64
3. chmod +x notify_push
