### ISSUE TITLE
Clamav support

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#376]
Just in order to separate this from the other ticket https://github.com/nextcloud/all-in-one/issues/78

docs: https://docs.clamav.net/manual/Installing/Docker.html

For later: https://www.sitepoint.com/detect-html-form-changes/

**Comment by marcatsmci** [comment]
Great, thanks !

**Comment by szaimen** [comment]
So I suppose it works for you? :D

**Comment by marcatsmci** [comment]
`Not Checked. No matching rules. Please check antivirus rules. File: 664 Account: admin Path: /admin/files/700-Dev/LR/Appli mobile Logistique/Images-doc/Oldies/LR Logistique V1.apk`

I think so ;-)
