### ISSUE TITLE
can't get localAI to work... 

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/all-in-one#3767]
running AIO 7.7 beta, but had the same issue with previous version.

```rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:36041: connect: connection refused``` is the error I see in the log in ```/api/docker/logs?id=nextcloud-aio-local-ai```

UI gives this error:
![Screenshot_20231118_001114](https://github.com/nextcloud/all-in-one/assets/551757/4213024f-e743-4c0c-aaec-f1c93f7d356c)

Tried a few models - gpt4all-j, ourobouros, llama2-chat, no luck.

Full log:
```
:
model name	: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
CPU:    AVX    found OK
CPU:    AVX2   found OK
CPU: no AVX512 found
nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9001: Name or service not known
Waiting for nextcloud to start
nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9001: Name or service not known
Waiting for nextcloud to start
nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9001: Name or service not known
Waiting for nextcloud to start
Waiting for nextcloud to start
Waiting for nextcloud to start
Waiting for nextcloud to start
Waiting for nextcloud to start
Waiting for nextcloud to start
Waiting for nextcloud to start
Waiting for nextcloud to start
Waiting for nextcloud to start
++ nproc
+ THREADS=4
+ export THREADS
+ set +x
[90m12:06AM[0m [32mINF[0m Starting LocalAI using 4 threads, with models path: /models
[90m12:06AM[0m [32mINF[0m LocalAI version: v1.30.0 (274ace289823a8bacb7b4987b5c961b62d5eee99)

 ┌───────────────────────────────────────────────────┐ 
 │                   Fiber v2.49.2                   │ 
 │               http://127.0.0.1:8080               │ 
 │       (bound on host 0.0.0.0 and port 8080)       │ 
 │                                                   │ 
 │ Handlers ............ 70  Processes ........... 1 │ 
 │ Prefork ....... Disabled  PID ................ 39 │ 
 └───────────────────────────────────────────────────┘ 

rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:38469: connect: connection refused"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:36041: connect: connection refused"
```

In my server log, I see a ton of these, not sure if they are related:
```
[PHP] Error: Undefined variable $notificationActionLabel at /var/www/html/custom_apps/assistant/lib/Listener/TaskFailedListener.php#46

at 2023-11-17T23:12:21+00:00
```

**Comment by szaimen** [comment]
> ```
> rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:38469: connect: connection refused"
> rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:36041: connect: connection refused"
> ```

I found this: https://github.com/mudler/LocalAI/issues/771



> [PHP] Error: Undefined variable $notificationActionLabel at /var/www/html/custom_apps/assistant/lib/Listener/TaskFailedListener.php#46

Please report this upstream

**Comment by szaimen** [comment]
Maybe this helps?
https://github.com/nextcloud/all-in-one/discussions/3623#discussioncomment-7416240

**Comment by jospoortvliet** [comment]
Tnx. So the hard question is what's the cause - could be memory, could be failed hardware acceleration or other things. 

> Maybe this helps? [#3623 (comment)](https://github.com/nextcloud/all-in-one/discussions/3623#discussioncomment-7416240)

It seems, somehow, eitehr an update or just more fiddling, but it works... WHOOOOH
