### ISSUE TITLE
Link to login to AIO interface is missing after update

### ISSUE THREAD

**Issue by ChojinDSL** [nextcloud/all-in-one#3772]
It seems that after the most recent unstable update, the link to the AIO interface is missing when you go to Administration Settings -> Overview.

I'm tracking the unstable branch of nextcloud-aio.

**Comment by szaimen** [comment]
Hi, can you post a screenshot of what ou are seeing?

**Comment by szaimen** [comment]
Hi, can you post the nextcloud container logs here please?

**Comment by ChojinDSL** [comment]
The issue seems to have been resolved with a master container update.
