### ISSUE TITLE
AIO Interface cleanup 

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#381]
I think it would be great if the AIO Interface page is cleaned up to focus only on very important aspects, e.g. like a Dashboard.

Some zones to simplified (in my opinion) :

- initial NC credentials : to put behind a button (security enhancement in case of screenshot)
- you can change your AIO password below: behind a button (security enhancement in case of screenshot)
- same for near all the description of borgbackup

**Comment by szaimen** [comment]
Good suggestion, thanks!
