### ISSUE TITLE
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException

### ISSUE THREAD

**Issue by wgzhao** [nextcloud/all-in-one#397]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. docker pull nextcloud/all-in-one:latest
2. docker run -it --rm   --name nextcloud-aio-mastercontainer  -p 10080:80 -p 18080:8080 -p 10443:8443 --volume /var/run/docker.sock:/var/run/docker.sock:ro  --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config nextcloud/all-in-one:latest
3.

### Expected behaviour 
It works
### Actual behaviour 
Got the following error message:

```
Fatal error: Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/v1.41/containers/nextcloud-aio-borgbackup/json in /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:210
Stack trace:
#0 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Middleware.php(63): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/ClientTrait.php(44): GuzzleHttp\Client->request('GET', 'http://localhos...', Array)
#14 /var/www/docker-aio/php/src/Docker/DockerActionManager.php(58): GuzzleHttp\Client->get('http://localhos...')
#15 /var/www/docker-aio/php/src/Container/Container.php(91): AIO\Docker\DockerActionManager->GetContainerRunningState(Object(AIO\Container\Container))
#16 /var/www/docker-aio/php/src/ContainerDefinitionFetcher.php(156): AIO\Container\Container->GetRunningState()
#17 /var/www/docker-aio/php/src/ContainerDefinitionFetcher.php(32): AIO\ContainerDefinitionFetcher->FetchDefinition()
#18 /var/www/docker-aio/php/src/Cron/cron.php(19): AIO\ContainerDefinitionFetcher->GetContainerById('nextcloud-aio-n...')
#19 {main}
```
Use browser open https://localhost:18080, get the following error message:

```
Slim Application Error
The application could not run because of the following error:

Details
Type: GuzzleHttp\Exception\ConnectException
Code: 0
Message: cURL error 7: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://localhost/v1.41/containers/nextcloud-aio-borgbackup/json
File: /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php
Line: 210
```
---

**Comment by DrShivang** [comment]
got the same error while using custom apache port passed through env var.

**Comment by szaimen** [comment]
Which OS?

**Comment by wgzhao** [comment]
macOS 12.1 intel

**Comment by szaimen** [comment]
Did you see https://github.com/nextcloud/all-in-one#how-to-run-it-on-macos?

**Comment by wgzhao** [comment]
Yes，I notice that. But in my macOS, there is not `/var/run/docker.sock.raw`

**Comment by szaimen** [comment]
> Yes，I notice that. But in my macOS, there is not `/var/run/docker.sock.raw`

cc @juliushaertl do you have any idea if there are multiple ways to install docker on macOS?

**Comment by wgzhao** [comment]
It's magic!
The  `/var/run/docker.sock.raw` does not exists ,but I use  `--volume /var/run/docker.sock.raw:/var/run/docker.sock:ro`, it works!

I go the future test

**Comment by szaimen** [comment]
> The `/var/run/docker.sock.raw` does not exists

It may only exist inside the VM that docker is running on macOS ;)

**Comment by DrShivang** [comment]
> Which OS?

HassOS -- Home Assistant OS

**Comment by szaimen** [comment]
> HassOS -- Home Assistant OS

Never heard of that. Is this based on Linux?

**Comment by DrShivang** [comment]
> > HassOS -- Home Assistant OS
> 
> Never heard of that. Is this based on Linux?
Yes, using Buildroot, it only happens when I use a custom apache port

https://github.com/home-assistant/operating-system

**Comment by szaimen** [comment]
> Details
> Type: GuzzleHttp\Exception\ServerException
> Code: 500
> Message: Server error: POST http://localhost/v1.41/containers/nextcloud-aio-domaincheck/start resulted in a 500 Internal Server Error response: {"message":"driver failed programming external connectivity on endpoint nextcloud-aio-domaincheck (4c726da366534cd29c58a (truncated...)
> File: /var/www/docker-aio/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php
> Line: 113

Okay, that points towards an already used port on the host OS. Please follow the reverse proxy documentation. Thanks!
