### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Tomptez** [nextcloud/all-in-one#40]
I think adding a bit of documentation or some sort of FAQ to the Readme would be very helpful for both users and people who are wondering if this fits their use case. This is particular so because the target audience for this (if I understood correctly) is people with less knowledge than your typical system administrator.

Things that I'd like to see:

- How to update to a new version of nextcloud?
- Is it possible to run occ?
- If not, how do you restore from backup? (is it even possible? Maybe related to #39)

Maybe others have more suggestions

**Comment by szaimen** [comment]
> * If not, how do you restore from backup?

It is possible to restore the last backup currently

**Comment by szaimen** [comment]
> * Is it possible to run occ?

definitely, will add some docs about this
basically like this: `docker exec -it nextcloud-aio-nextcloud php occ your-command`

**Comment by Tomptez** [comment]
> > * If not, how do you restore from backup?
> It is possible to restore the last backup currently
@szaimen:
More specifically I was wondering how you would [restore an instance from scratch](https://github.com/nextcloud/backup#restoring-my-nextcloud-from-scratch) but I assume you would just follow the steps using OCC?

Thanks a lot, I think including these questions in an FAQ would be great!

**Comment by szaimen** [comment]
> More specifically I was wondering how you would [restore an instance from scratch](https://github.com/nextcloud/backup#restoring-my-nextcloud-from-scratch) but I assume you would just follow the steps using OCC?

Yes, using occ should be sufficient :)

**Comment by szaimen** [comment]
done with #48
