### ISSUE TITLE
Increase Nextcloud HPB limit?

### ISSUE THREAD

**Issue by muellerm01** [nextcloud/all-in-one#400]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Software
Install Nextcloud AIO 0.8 like documented

Hardware:
Azure North Europe Standard D4as v4 (2 vcpus, 8 GiB Arbeitsspeicher)
8 Gbit download (measured)
1,8 Gbit upload (measured)

Steps:
1. start a meeting with allowed guestes
2. the 7th person will take a little bit longer to join
3. the 8th person is not able to join the meeting

### Expected behaviour 
Nextcloud talk participant limit should be releated to CPU, RAM and upload/download speed

### Actual behaviour 
CPU runs on 0,5 cores
RAM 2,5 GB used
Upload/Download ~20Mbit
and participant limit is between 7 and 8

---

#### Nextcloud AIO version 
AIO 0.8
#### Current channel 
latest channel

**Comment by szaimen** [comment]
Hi, thanks for your report. I fear though that there is not much we can do here because we install everything based on the docs.

Feel free to read the following docs though: https://github.com/nextcloud/spreed#how-to-have-the-maximum-number-of-participants-in-a-call

**Comment by szaimen** [comment]
Also it seems like your cpu is pretty limitied. Feel free to try to increase the cpu count

**Comment by muellerm01** [comment]
OK, sorry I thought HPB was part of AIO because it is configured.
I requested your sales team but think the minimum user count is around 100 to get enterpise support and search for a solution below that. Let´s see what i will get from them.

I also tried it with a larger CPU, but that doesn't seem to change anything.

I think in the range of 50 participants and an on premise installation. But I could not find a purchasable solution so far. 

Hosting is not an option for me. 
Then I could just take teams.

**Comment by szaimen** [comment]
> OK, sorry I thought HPB was part of AIO because it is configured.

yes, the HPB is part of AIO.

**Comment by szaimen** [comment]
It seems like it is just not scaling as well as promised...

**Comment by szaimen** [comment]
> But than HPB with a limit of 7-8 thems to be confusing.

yes, it is

**Comment by muellerm01** [comment]
Is something configured incorrectly?

**Comment by szaimen** [comment]
Noth that I am aware of.

**Comment by szaimen** [comment]
You can have a look yourself: https://github.com/nextcloud/all-in-one/blob/main/Containers/talk/start.sh

**Comment by szaimen** [comment]
Maybe this is the problem for you?
https://github.com/nextcloud/all-in-one/blob/8fedcb48109a62e794eb4ae6a5ae258ae43c4ef8/Containers/talk/start.sh#L55

**Comment by szaimen** [comment]
feel free to adjust that number in the container and try again.

**Comment by muellerm01** [comment]
I looked, but I only know the documentation from others and not what is recommended. 

Hm ok good point, I'll try that.

**Comment by szaimen** [comment]
Feel free to report back if adjusting this number makes it work.

**Comment by szaimen** [comment]
We can then adjust the number if it works for you.

**Comment by szaimen** [comment]
I'll reopen this until then :)

**Comment by szaimen** [comment]
Sidenote: after you applied that change you probably need to restart the container to make the new setting work.

**Comment by szaimen** [comment]
Or lets go the other way around. I'll increase the value and you can test it with the next release.

**Comment by muellerm01** [comment]
I tryed docker stop <container id>
docker copy <container id>:/usr/bin/start.sh start.sh
changed connectionsperhost = 40
docker cp start.sh <container id>:/usr/bin/start.sh
docker restart <container id>

But nothing changed, the limit is still between 7 and 8

**Comment by muellerm01** [comment]
the janus log looks like a crash loop but hard to read

**Comment by szaimen** [comment]
What is the output of `cat /etc/signaling/server.conf` after a restart?

**Comment by szaimen** [comment]
> the janus log looks like a crash loop but hard to read

Interesting! Can you share the logs?

**Comment by muellerm01** [comment]
connectionsperhost = 40

**Comment by szaimen** [comment]
> connectionsperhost = 40

Hm...

**Comment by muellerm01** [comment]
[log-part-janus.log](https://github.com/nextcloud/all-in-one/files/8304968/log-part-janus.log)

**Comment by muellerm01** [comment]
I also tryed to disconnect user 7 and 8 and than reconnect again 8 before 7
the last user is always the one with the problem

**Comment by szaimen** [comment]
> I also tryed to disconnect user 7 and 8 and than reconnect again 8 before 7
> the last user is always the one with the problem

So there seems to be a hard limit at 7-8 somehow...

**Comment by muellerm01** [comment]
Hm I have a HPB running with these sources and docker-compose, it looks like this is not limited to 7-8

**Comment by szaimen** [comment]
> Hm I have a HPB running with these sources and docker-compose, it looks like this is not limited to 7-8

So then it is probably a configuration issue, right.

**Comment by muellerm01** [comment]
I used this guide for configuration https://markus-blog.de/index.php/2020/07/30/how-to-install-nextcloud-talk-high-performance-backend-with-stun-turnserver-on-ubuntu/

**Comment by szaimen** [comment]
Thanks! At first glance it looks comparable. I'll adjust our config to match this guide a bit better.

**Comment by muellerm01** [comment]
thx but can´t say what is different hm everything is splitted in 4 container

**Comment by szaimen** [comment]
Hey, I just published a new talk container. Feel free to try that one out and report back. :)

**Comment by muellerm01** [comment]
Hm, has not changed the behavior.

**Comment by szaimen** [comment]
Hm...
