### ISSUE TITLE
Clean up the log files

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#401]
How can the log files be cleaned up in Nextcloud AIO? I'm slowly losing track and can't keep up with the reports for the individual apps.

Possible inclusion in the documentation?

**Comment by szaimen** [comment]
which logfile?

**Comment by R7JANV1** [comment]
nextcloud logs which can be found under the logging tab

**Comment by szaimen** [comment]
currently it is configured so that a restart of your containers will delete the old logs...

**Comment by szaimen** [comment]
I'll not document this though since this might be changed in the future.
