### ISSUE TITLE
Scheduled updates for AIO

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#407]
Scheduled updates for AIO releases. But also the feature that Nextcloud Apps can be updated automatically and or scheduled.

**Comment by szaimen** [comment]
will come with https://github.com/nextcloud/all-in-one/issues/47

**Comment by R7JANV1** [comment]
Both functions? That Nextcloud apps are updated automatically? And that AIO is updated automatically?

**Comment by szaimen** [comment]
yes

**Comment by R7JANV1** [comment]
I love it!
