### ISSUE TITLE
Redis is constantly told to be starting in AIO interface with error in the redis container logs

### ISSUE THREAD

**Issue by AlphaCraft9658** [nextcloud/all-in-one#4096]
### Steps to reproduce
1. Just launch the latest Nextcloud AIO with Nextcloud 28 and check the status and logs of the redis container
2. Try to log in, if it fails, it is a general bug and not related to my setup

### Expected behavior 
It should start properly
### Actual behavior 
It doesn't fully start and gives this error:

`Memory overcommit is disabled but necessary for safe operation
See https://github.com/nextcloud/all-in-one/discussions/1731 how to enable overcommit
7:C 22 Jan 2024 07:21:14.639 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.`

Additionally, I'm unable to log into nextcloud. It tells me that there is a temporary error. I have checked that it isn't caused by Authentik, which I have set up recently. No kind of login works. I think it might be related to this issue with redis.

### Host OS 
Ubuntu-Server with Docker

#### Nextcloud AIO version 
7.10.0
#### Current channel 
latest

**Comment by AlphaCraft9658** [comment]
Oh wait. That _is_ related to my Authentik setup. What domain paths do Nextcloud and the mastercontainer use to communicate? I likely need to add exceptions for the authentication to make this work.

**Comment by AlphaCraft9658** [comment]
Now it suddenly works again? I'm seriously confused.

**Comment by szaimen** [comment]
> Redis is constantly told to be starting in AIO interface

Do you have ipv6 enabled for the internal nextcloud-aio docker network? If so, you are most likely running into this: https://github.com/nextcloud/all-in-one/discussions/2557. One workaround would be disabling ipv6-support again for the network.

**Comment by szaimen** [comment]
Tracking things further in https://github.com/nextcloud/all-in-one/issues/4092
