### ISSUE TITLE
Suppress Apache Version + PHP-Version in HTTP-Header....

### ISSUE THREAD

**Issue by markthebro** [nextcloud/all-in-one#4126]
### Is your feature request related to a problem? Please describe. 
Since applications can't be updated always on-time, for any reason, some security-related parts should be optimized.
E.g. suppressing all version banners or anything similar through the public web should be suppressed by default.

### Describe the solution you'd like
It would be great if no versions of any software will be part of the HTTP-Response-Header.
E..g. for Apache ServerSignature Off / ServerTokens Prod could be applied per default.
Same for PHP (expose_php = off).

### Describe alternatives you've considered

If this feature request can't be applied per default, it would be great / nice to configure those settings additionally....for security enthusiasts ;-)

### Additional context

Well,  not related to this subject / topic, but the same (suppressing version string / version banner) when opening the start-page of nextcloud would be nice as well - so that a person from outside won't get any version string / version banner back. 
E.g. https://scan.nextcloud.com/

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/.github/blob/master/SECURITY.md
