### ISSUE TITLE
Switching the Docker installation

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#413]
I have a question,
I have docker.io installed and Nextcloud AIO running on it. Now I noticed that docker.io is an outdated version of Doker and I want to switch to the installation method curl -fsSL get.docker.com | sudo sh (as described in the documentation). Is this somehow easy to implement? And would it work if I backup via Borck Backup in the AIO interface and then set up again and then restore the backup?

**Comment by szaimen** [comment]
As long as the docker.io version works, I guess it should be fine and you don't nee to use the recommended way to install docker then.

**Comment by R7JANV1** [comment]
And would it work if I backup via Borck Backup in the AIO interface and then set up again (with the recommended way) and then restore the backup?
Or does the backup also restore the docker.io?

**Comment by szaimen** [comment]
> And would it work if I backup via Borck Backup in the AIO interface and then set up again (with the recommended way) and then restore the backup?

That would work but restoring on a new instance is currently not implemented. See https://github.com/nextcloud/all-in-one/issues/38 for that

**Comment by R7JANV1** [comment]
Yes I know, I am already waiting anxiously for it.

**Comment by szaimen** [comment]
It was implemented and released with v0.9.0
