### ISSUE TITLE
collabora not working after restart without visiting settings page

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#424]
### to reproduce

1. activate collabora option in aio
2. start containers
3. click on any document like docx or odt

### expected
4. document gets opened with collabora

### reality
4. document gets downloaded

---

@juliushaertl could you have a look? I guess it is because we don't run `occ richdocuments:activate-config` which is not possible though as the apache container is not running at that moment and is itself waiting for the php process to become available.
See https://github.com/nextcloud/all-in-one/blob/3eede90e867e2967ea971d6ed0259445f7d18ab7/Containers/nextcloud/entrypoint.sh#L288-L289

**Comment by szaimen** [comment]
Okay, seems like running `php occ config:app:set richdocuments public_wopi_url --value="https://$NC_DOMAIN/" should make it work. @juliushaertl can you confirm? :)

**Comment by szaimen** [comment]
I'll try that :)

**Comment by szaimen** [comment]
It still does not seem to work. :/

@juliushaertl do you have ideas how to solve that? :)

**Comment by juliushaertl** [comment]
Yes, currently the Nextcloud server caches the response from the Collabora Online server and also the failure attempt quite heavily. Probably something we should try to improve in richdocuments.

We generally do not want to request too often, but in an error case, like a temporarily unavailable server (or re-enabled) after an upgrade we should do this more heavily. I'll see I can push a quick improvement for that, but some caching would still be needed to avoid performing heavy requests basically with every page load.

However even with a lower cache time there might still be a small timeframe (e.g. 1 minute) where Nextcloud has not detected yet that Collabora is running now, that is why if possible I'd still recommend to run the `occ richdocuments:activate-config` after the Collabora container has started.

**Comment by juliushaertl** [comment]
As discussed, tracking this in https://github.com/nextcloud/richdocuments/issues/2124 for further improvements as this might be a bit more work than just reducing the timeout to handle it properly.

**Comment by szaimen** [comment]
At first sight it still does not seems to work :/
![image](https://user-images.githubusercontent.com/42591237/162042965-69726e0d-f625-4ce2-a93e-8449ed9c2273.png)
The activate config command seem to work correctly though:
```
System config value allow_local_remote_servers set to boolean true
Config value wopi_url for app richdocuments set to http://nextcloud-aio-collabora:9980/
Config value public_wopi_url for app richdocuments set to https://nc.mydomain.com/
```

**Comment by szaimen** [comment]
Here are the error browser logs:
![image](https://user-images.githubusercontent.com/42591237/162043813-ff9c4145-9118-4a4a-a198-3b343684176e.png)
It seems to refer to this line:
![image](https://user-images.githubusercontent.com/42591237/162043981-cfc87c24-9514-4fdc-a8c5-c68c41f488dd.png)

---

Nothing In the nextcloud logs

---

![image](https://user-images.githubusercontent.com/42591237/162044104-390dcc55-1ea0-42d1-bccd-c2166d3952ad.png)

After clicking on the save button it seems to work though.

**Comment by szaimen** [comment]
@juliushaertl do you think this still might be due to collabora not being finished with the initial start when we try to connect?
Though shouldn't the activate config command in that case return that it wasn't able to connect?

**Comment by szaimen** [comment]
It seems like I was too early: even after the check in the settings is green, opening a document still does not workand fails with the same error. So this unfortunately does not seem to work :/

@juliushaertl so I guess there is no way around usign the valid domain again and adding a script that activates the config later on after the webserver was started, right?
