### ISSUE TITLE
investigate why imaginary produces black-white thumbnails with alpine3.19

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#4258]
See https://github.com/nextcloud/all-in-one/issues/4239 and https://github.com/nextcloud/all-in-one/pull/4253

Possibly it was caused by malfunctioning docker hub during upgrade... Hopefully https://github.com/nextcloud/all-in-one/pull/4256 prevents such things in the future

Needs to be investigated latest ahen 3.18 gets out of support: https://alpinelinux.org/releases/ in 2025-05-09

**Comment by Zoey2936** [comment]
the docker golang images based on alpine v3.18 aren't updated anymore (latest version 1.22.3, newest 1.22.4)

**Comment by szaimen** [comment]
> the docker golang images based on alpine v3.18 aren't updated anymore (latest version 1.22.3, newest 1.22.4)

I see, so we need to investigate on the topic then soon I guess...

**Comment by Zoey2936** [comment]
Maybe it works again with alpine v3.20?

**Comment by szaimen** [comment]
Yeah we can try
