### ISSUE TITLE
Images rendered unusable after AIO update.

### ISSUE THREAD

**Issue by Byter3** [nextcloud/all-in-one#4281]
Nextcloud AIO v7.12.1

Uploaded picture no matter the file type rendered as a black and white mess.
![kép](https://github.com/nextcloud/all-in-one/assets/48226954/9ae9c299-3a32-466a-a607-40d173e8d8fc)

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/all-in-one/issues/4239#issuecomment-1959249773

**Comment by Byter3** [comment]
> Hi, see [#4239 (comment)](https://github.com/nextcloud/all-in-one/issues/4239#issuecomment-1959249773)

Didn't see. Sorry!
