### ISSUE TITLE
Documented method for changing domain is incomplete

### ISSUE THREAD

**Issue by xyhhx** [nextcloud/all-in-one#4335]
### Steps to reproduce
1. Install Nextcloud AIO container on a domain
2. Follow the [documented procedure](https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-change-the-domain) to change the domain
3. Try to use some apps

### Expected behavior 

All apps should use the new domain for any scenario

### Actual behavior 

Some apps (for example Talk) have more configuration to change, and use the old domain.

### Host OS 

Ubuntu server 23.10

#### Nextcloud AIO version 

28.0.3

#### Current channel 

Latest

#### Other valuable info 

Dumping the postgres database and grepping it returned ~12 results. Most are translations, some are from Talk, and a few I didn't discern where they're from

**Comment by xyhhx** [comment]
grepping the postgres dump for the old domain returns the following:

```
95      1709250396      30      file_created    admin   admin   files   created_self    [{"100":"\\/Talk"}]             []      /Talk   https://old-domain.com/apps/files/?dir=/        files   100
spreed  stun_servers    ["old-domain.com:3478"] 2       f
call_summary_bot        secret_[redacted]       {"id":"[redacted]","secret":"[redacted]","backend":"https:\\/\\/old-domain.com\\/"}     2       f
theming url     https://old-domain.com  2       f
1       docker_aio      AIO Docker Socket Proxy docker-install  http    nextcloud-aio-docker-socket-proxy:2375  {"net":"nextcloud-aio","nextcloud_url":"https:\\/\\/old-domain.com","haproxy_password":null,"gpu":false}
1       Call summary    https://old-domain.com/ocs/v2.php/apps/call_summary_bot/api/v1/bot/en   [redacted]      Call summary (British English) - The call summary bot posts an overview message after the call listing all participants and outlining tasks     [redacted]      0       \N      \N      1       3
2       Protokoll       https://old-domain.com/ocs/v2.php/apps/call_summary_bot/api/v1/bot/de   [redacted]      Protokoll (Deutsch (Persönlich: Du)) - Der Anruf-Zusammenfassungs-Bot veröffentlicht nach der Unterhaltung eine Übersichtsnachricht, in der alle Teilnehmenden und die Aufgaben aufgeführt sind [redacted] 0\N      \N      1       3
3       Resumen de la llamada   https://old-domain.com/ocs/v2.php/apps/call_summary_bot/api/v1/bot/es   [redacted]      Resumen de la llamada (Español (España)) - El bot de resumen de llamada publica un mensaje de visión general listando a todos los participantes y delineando tareas     [redacted]      0       \N \N       1       3
4       Résumé de l'appel       https://old-domain.com/ocs/v2.php/apps/call_summary_bot/api/v1/bot/fr   [redacted]      Résumé de l'appel (Français) - Le robot chargé de résumer l'appel publie un message de synthèse après l'appel, énumérant tous les participants et décrivant les tâches à accomplir.     [redacted] 0\N      \N      1       3
5       ملخص المكالمة   https://old-domain.com/ocs/v2.php/apps/call_summary_bot/api/v1/bot/ar   [redacted]      ملخص المكالمة (اللغة العربية) - يقوم روبوت "ملخص المكالمة"بنشر رسالة عامة بعد المكالمة يسرد فيها جميع المشاركين و يحدد المهام   [redacted]      0       \N      \N      1       3
6       Resumo da chamada       https://old-domain.com/ocs/v2.php/apps/call_summary_bot/api/v1/bot/pt_BR        [redacted]      Resumo da chamada (Português Brasileiro) - O bot de resumo da chamada publica uma mensagem de visão geral após a chamada, listando todos os participantes e descrevendo as tarefas      [redacted]  0       \N      \N      1       3
7       Çağrı özeti     https://old-domain.com/ocs/v2.php/apps/call_summary_bot/api/v1/bot/tr   [redacted]      Çağrı özeti (Türkçe) - Çağrı özeti botu, çağrıdan sonra tüm katılımcıları listeleyen ve görevleri özetleyen bir özet iletisi gönderir.  [redacted]      0       \N      \N      1       3
8       通话摘要        https://old-domain.com/ocs/v2.php/apps/call_summary_bot/api/v1/bot/zh_CN        [redacted]      通话摘要 (简体中文) - 通话摘要机器人会在通话结束后发布一条概述信息，列出所有与会者并概述各项任务        [redacted]      0       \N      \N      1       3
```

**Comment by xyhhx** [comment]
here are some queries i'm trying in order to remediate it:

```sql
# find occurances of $oldDomain in oc_appconfig
select * from oc_appconfig where configvalue like '%$oldDomain%';

# update stun servers
update oc_appconfig (configvalue) set (configvalue='["$newDomain:3478"]') where configkey = 'stun_servers' and appid = 'spreed';

# update call summary bot secret
update oc_appconfig set configvalue='{"id":"xxx","secret":"xxx","backend":"https:\/\/$newDomain\/"}' where configkey = 'secret_xxx' and appid = 'call_summary_bot';

# update theming
update oc_appconfig set configvalue='https://$newDomain' where configkey = 'url' and appid = 'theming';
```

i don't know if the call summary bot query would work, if the secret is derived from the backend somehow

**Comment by xyhhx** [comment]
i'm gonna use my instance for a bit and see if everything works as expected. if so, i'll contribute a PR

**Comment by xyhhx** [comment]
the call summary bot is throwing 401 errors. presumably because of the secret replacement mentioned earlier.

i tried to disable and remove, then download and enable it, but that didn't work

**Comment by xyhhx** [comment]
> the call summary bot is throwing 401 errors. presumably because of the secret replacement mentioned earlier.
> 
> i tried to disable and remove, then download and enable it, but that didn't work

this isn't making any difference. summaries are working

**Comment by szaimen** [comment]
Just to mention what to do when updating the documentation. Instead of tinkering with the database, one should open the correct settings and adjust it there:

> ```sql
> # update stun servers
> update oc_appconfig (configvalue) set (configvalue='["$newDomain:3478"]') where configkey = 'stun_servers' and appid = 'spreed';
> ```

This should be adjusted in `https://your-nc-domain.com/settings/admin/talk`

> ```sql
> # update call summary bot secret
> update oc_appconfig set configvalue='{"id":"xxx","secret":"xxx","backend":"https:\/\/$newDomain\/"}' where configkey = 'secret_xxx' and appid = 'call_summary_bot';
> ```

This should probably also be adjusted in `https://your-nc-domain.com/settings/admin/talk`

> ```sql
> # obviously the 'xxx' above should reflect the actual values in your table
> 
> # update theming
> update oc_appconfig set configvalue='https://$newDomain' where configkey = 'url' and appid = 'theming';
> ```

This should be adjusted in `https://your-nc-domain.com/settings/admin/theming`

> ```sql
> update oc_ex_apps_daemons set deploy_config = replace(deploy_config, '$oldDomain','$newDomain');
> ```

This should probably be adjusted in `https://your-nc-domain.com/settings/admin/app_api`

**Comment by xyhhx** [comment]
Hm, I'm not sure I agree. Firstly, it's hard to describe what to do in a way that will surely find every occurrence: an admin would have to go through every app and check every field in order to effectively find them all, and this sound very prone to human error

Furthermore, the documentation is directed at a server admin anyway, and already advises tampering with the configuration files inside containers. 

Maybe we can suggest both options? Something along the lines of:

> If you are comfortable with managing database and writing basic SQL, you can do the following: 
> [...]
>
> If you aren't comfortable working directly on tables' values, you can also go through each apps' settings in the Administration Settings of your instance and replace any values you find.  Common examples include:
> - `https://your-nc-domain.com/settings/admin/talk`
> - `https://your-nc-domain.com/settings/admin/theming`
> - `https://your-nc-domain.com/settings/admin/app_api`
>
> But you should check every field of every app to make sure.

**Comment by szaimen** [comment]
Sorry but the risk of inexperienced people breaking something in the database is simply to high. 

So it should be done via the webinterface or via occ command if possible.

**Comment by xyhhx** [comment]
I have been trying to think of a way to describe this in a way that makes sense but everything just sounds ridiculous ("go through every field in every app in administration settings and replace them all"?).

If you don't look through the database there's no way to reliably find every occurrence, and string replacement is more reliable and less error prone than typing it out manually using either `occ` or the web interface.

Would you be open to me opening another PR that actually adds the feature to the AIO interface?

**Comment by xyhhx** [comment]
Anyway, for anybody who finds this issue, I create [a gist](https://gist.github.com/xyhhx/a98274274daefc7aa574b9e966229adf) with the steps.
