### ISSUE TITLE
Add "Default Phone Region" to config.php

### ISSUE THREAD

**Issue by OliverPifferi** [nextcloud/all-in-one#44]
**Security & setup warnings displays the "missing default phone region" after initial install**

This can, of course, be added by changing the config.php in the specific "nextcloud/aio-nextcloud:latest"-container but maybe this parameter can also be implemented somehow, giving the user the change to adapt this value to match the user's personal needs?

**Comment by szaimen** [comment]
Hi, you can simply set it yourself by running the following command: 
`sudo docker exec -it nextcloud-aio-nextcloud php occ config:system:set default_phone_region --value="yourvalue"`

**Comment by OliverPifferi** [comment]
Hey, thanks for the feedback - helps in the meantime! Additionally, I did already and directly add the entry to the config.php inside the container.
