### ISSUE TITLE
Numerals 2-9 Are Rejected in Additional Backup Directory File Paths

### ISSUE THREAD

**Issue by Tally** [nextcloud/all-in-one#4410]
### Steps to reproduce
1. Enter a file path with a numeral 2-9 in it into the "Back up additional directories ..." text field of the AIO configuration page.
2. Submit this field.
3. Verify that all characters were in fact permitted.

### Expected behavior 
File path would be accepted as a valid target for backing up.
### Actual behavior 
Error message stating "You entered unallowed characters!" appears.

### Host OS 
Raspbian Bookworm

#### Nextcloud AIO version 
v7.13.1
#### Current channel 
latest
#### Other valuable info 
![AIO - Brave 3_20_2024 00_58_20](https://github.com/nextcloud/all-in-one/assets/5515952/bdfc7cd7-7040-475b-be5a-d5685be5e3b6)

**Comment by Zoey2936** [comment]
https://github.com/nextcloud/all-in-one/blob/172330b93806843c9fc2efecaca1fa12664d5425/php/src/Data/ConfigurationManager.php#L745 can confirm

**Comment by szaimen** [comment]
Seems ro be a typo. Can someone please open a pr?

**Comment by Zoey2936** [comment]
see #4411

**Comment by szaimen** [comment]
This is now fixed with v8.1.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
