### ISSUE TITLE
Minor typo in restore from backup page

### ISSUE THREAD

**Issue by airplane-flight** [nextcloud/all-in-one#4428]
When restoring a backup there is a minor typo on the page. "Please not that the current AIO password will be kept and the AIO password not restored from backup" should likely read "Please note that the current AIO password will be kept and the AIO password will not be restored from backup"
![image](https://github.com/nextcloud/all-in-one/assets/7052108/e6667f3d-5ec5-4fab-8ced-078ad7b1f237)

**Comment by szaimen** [comment]
PRs to improve this are welcome :)
