### ISSUE TITLE
Fulltextsearch Index Failing

### ISSUE THREAD

**Issue by FlattusBlastus** [nextcloud/all-in-one#4463]
### Steps to reproduce
1. New AIO Instance
2. docker exec --user www-data -it nextcloud-aio-nextcloud php occ fulltextsearch:index

### Expected behavior 
Happy search underway text
### Actual behavior 
PHP Fatal error:  Declaration of Elastic\Elasticsearch\Response\Elasticsearch::withStatus(int $code, string $reasonPhrase = ''): Psr\Http\Message\ResponseInterface must be compatible with Psr\Http\Message\ResponseInterface::withStatus($code, $reasonPhrase = '') in /var/www/html/custom_apps/fulltextsearch_elasticsearch/vendor/elasticsearch/elasticsearch/src/Traits/MessageResponseTrait.php on line 87

### Host OS 
Windows 11
#### Nextcloud AIO version 
8.0.0
#### Current channel 
Develop

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/nextcloud/fulltextsearch_elasticsearch/issues

**Comment by FlattusBlastus** [comment]
This was actually caused by Carnet. Bug reported appropriately. Thanks!
