### ISSUE TITLE
feed back after update to aIo v8

### ISSUE THREAD

**Issue by punkyard** [nextcloud/all-in-one#4464]
after latest update, I got this error in log right after restart

Error	core	
DbalException
An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR: zero-length delimited identifier at or near """" LINE 1: ...") AS "current_user_votes", coalesce(shares.type, "") AS use... ^
Error while running background job (class: OCA\Polls\Cron\AutoReminderCron, arguments: )

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/nextcloud/polls/issues
