### ISSUE TITLE
ClamAV broken when updating to nextcloud 28 from 27

### ISSUE THREAD

**Issue by Sabering1** [nextcloud/all-in-one#4466]
### Steps to reproduce
1. Update to nextcloud 28 from 27
2. ClamAV will not be found and will halt the NextCloud main
3. After a while NextCloud will start but ClamAV will not

### Expected behavior 
All containers start with no issue

### Actual behavior 
ClamAV is broken

### Host OS 
Debian Gnu/Linux 12

#### Nextcloud AIO version 
8
#### Current channel 
Latest
#### Other valuable info 

Failed to start clamd
Starting Freshclamd
Starting ClamAV

or clamd not found yet, retrying (0/90) ...ClamAV update process started at Fri Mar 29 13:57:20 2024
daily.cld database is up-to-date (version: 27229, sigs: 2057112, f-level: 90, builder: raynman)
main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
bytecode.cld database is up-to-date (version: 335, sigs: 86, f-level: 90, builder: raynman)
LibClamAV Error: Can't load /var/lib/clamav/main.cvd: Can't verify database integrity
LibClamAV Error: cli_loaddbdir: error loading database /var/lib/clamav/main.cvd
ERROR: Fri Mar 29 13:57:27 2024 -> Can't verify database integrity

or clamd not found yet, retrying (1/90) ...
or clamd not found yet, retrying (2/90) ...
or clamd not found yet, retrying (3/90) ...
or clamd not found yet, retrying (4/90) ...
or clamd not found yet, retrying (5/90) ...
or clamd not found yet, retrying (6/90) ...
or clamd not found yet, retrying (7/90) ...
or clamd not found yet, retrying (8/90) ...
or clamd not found yet, retrying (9/90) ...
or clamd not found yet, retrying (10/90) ...
or clamd not found yet, retrying (11/90) ...
or clamd not found yet, retrying (12/90) ...
or clamd not found yet, retrying (13/90) ...
or clamd not found yet, retrying (14/90) ...
or clamd not found yet, retrying (15/90) ...
or clamd not found yet, retrying (16/90) ...
or clamd not found yet, retrying (17/90) ...
or clamd not found yet, retrying (18/90) ...
or clamd not found yet, retrying (19/90) ...
or clamd not found yet, retrying (20/90) ...
or clamd not found yet, retrying (21/90) ...
or clamd not found yet, retrying (22/90) ...
or clamd not found yet, retrying (23/90) ...
or clamd not found yet, retrying (24/90) ...
or clamd not found yet, retrying (25/90) ...
or clamd not found yet, retrying (26/90) ...
or clamd not found yet, retrying (27/90) ...
or clamd not found yet, retrying (28/90) ...
or clamd not found yet, retrying (29/90) ...
or clamd not found yet, retrying (30/90) ...
or clamd not found yet, retrying (31/90) ...
or clamd not found yet, retrying (32/90) ...
or clamd not found yet, retrying (33/90) ...
or clamd not found yet, retrying (34/90) ...
or clamd not found yet, retrying (35/90) ...
or clamd not found yet, retrying (36/90) ...
or clamd not found yet, retrying (37/90) ...
or clamd not found yet, retrying (38/90) ...
or clamd not found yet, retrying (39/90) ...
or clamd not found yet, retrying (40/90) ...
or clamd not found yet, retrying (41/90) ...
or clamd not found yet, retrying (42/90) ...
or clamd not found yet, retrying (43/90) ...
or clamd not found yet, retrying (44/90) ...
or clamd not found yet, retrying (45/90) ...
or clamd not found yet, retrying (46/90) ...
or clamd not found yet, retrying (47/90) ...
or clamd not found yet, retrying (48/90) ...
or clamd not found yet, retrying (49/90) ...
or clamd not found yet, retrying (50/90) ...
or clamd not found yet, retrying (51/90) ...
or clamd not found yet, retrying (52/90) ...
or clamd not found yet, retrying (53/90) ...
or clamd not found yet, retrying (54/90) ...
or clamd not found yet, retrying (55/90) ...
or clamd not found yet, retrying (56/90) ...
or clamd not found yet, retrying (57/90) ...
or clamd not found yet, retrying (58/90) ...
or clamd not found yet, retrying (59/90) ...
or clamd not found yet, retrying (60/90) ...
or clamd not found yet, retrying (61/90) ...
or clamd not found yet, retrying (62/90) ...
or clamd not found yet, retrying (63/90) ...
or clamd not found yet, retrying (64/90) ...
or clamd not found yet, retrying (65/90) ...
or clamd not found yet, retrying (66/90) ...
or clamd not found yet, retrying (67/90) ...
or clamd not found yet, retrying (68/90) ...
or clamd not found yet, retrying (69/90) ...
or clamd not found yet, retrying (70/90) ...
or clamd not found yet, retrying (71/90) ...
or clamd not found yet, retrying (72/90) ...
or clamd not found yet, retrying (73/90) ...
or clamd not found yet, retrying (74/90) ...
or clamd not found yet, retrying (75/90) ...
or clamd not found yet, retrying (76/90) ...
or clamd not found yet, retrying (77/90) ...
or clamd not found yet, retrying (78/90) ...
or clamd not found yet, retrying (79/90) ...
or clamd not found yet, retrying (80/90) ...
or clamd not found yet, retrying (81/90) ...
or clamd not found yet, retrying (82/90) ...
or clamd not found yet, retrying (83/90) ...
or clamd not found yet, retrying (84/90) ...
or clamd not found yet, retrying (85/90) ...
or clamd not found yet, retrying (86/90) ...
or clamd not found yet, retrying (87/90) ...
or clamd not found yet, retrying (88/90) ...
or clamd not found yet, retrying (89/90) ...
or clamd not found yet, retrying (90/90) ...
Failed to start clamd
Starting Freshclamd
Starting ClamAV

or clamd not found yet, retrying (0/90) ...ClamAV update process started at Fri Mar 29 13:58:52 2024
daily.cld database is up-to-date (version: 27229, sigs: 2057112, f-level: 90, builder: raynman)
main.cvd database is up-to-date (version: 62, sigs: 6647427, f-level: 90, builder: sigmgr)
bytecode.cld database is up-to-date (version: 335, sigs: 86, f-level: 90, builder: raynman)
LibClamAV Error: Can't load /var/lib/clamav/main.cvd: Can't verify database integrity
LibClamAV Error: cli_loaddbdir: error loading database /var/lib/clamav/main.cvd
ERROR: Fri Mar 29 13:58:59 2024 -> Can't verify database integrity

**Comment by leuedaniel** [comment]
How is your setup in nextcloud? Also like that?:
![image](https://github.com/nextcloud/all-in-one/assets/44936305/0aa23ce8-18d6-402e-be89-c702535f378a)

**Comment by Sabering1** [comment]
Yea, even logs display it
![image](https://github.com/nextcloud/all-in-one/assets/39810634/e5861df5-8de7-478e-83f3-2d11be76a49c)

**Comment by conloos** [comment]
Hi all,

i have the same issue. The setup checked and like the Screenshot.

Full output of the Error Message:

![Screenshot_20240330_112551](https://github.com/nextcloud/all-in-one/assets/524257/b3060a70-b2ba-466d-9616-6d5212a0ff05)

**Comment by ShapeShifter499** [comment]
I'm seeing the same issue here, the clamav container isn't starting for some reason

**Comment by johndoejai** [comment]
[https://github.com/nextcloud/files_antivirus/issues/305](url)
@szaimen does nextcloud aio configures a memory limit for the clamav container?

**Comment by szaimen** [comment]
Hi, I cannot reproduce this on my test instance. It works correctly without any problem. 

Maybe all of you actually do not have enough RAM or the clamav services were not available so that the database could not be checked?
