### ISSUE TITLE
Make OnlyOffice work behind NGINX Proxy Manager

### ISSUE THREAD

**Issue by foxhoundv** [nextcloud/all-in-one#447]
### How to use GitHub
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Is your feature request related to a problem? Please describe. 

Not really a problem but an optional setup for those that use NGINX Proxy Manager.

### Describe the solution you'd like

I use NGINX Proxy Manager because I am a very visual person and I can understand things better with a visualization. So I have documentation to possibly add for those that want to use NGINX PM.

### Additional context

Setup your router to properly forward the ports needed. Add a Proxy Host that looks like the following...
![01 - Proxy Host - Details](https://user-images.githubusercontent.com/16512250/161135343-7e373b05-ada6-463b-8e51-4aac6bb7787a.png)

Then under that Proxy Host, go to the Custom Locations and add the following information...
![02 - Proxy Host - Custom Locations](https://user-images.githubusercontent.com/16512250/161136600-2c056d45-83b4-44d2-b991-1ade8b340c45.png)

The following setting from the NGINX settings provided wouldn't work: proxy_set_header Connection $connection_upgrade;

So far I am trying to get OnlyOffice to work properly but am having no luck. In the Nextcloud Settings page it seems like everything works but when I try to create a Document or Spreadsheet, it won't connect to the file.

**Comment by szaimen** [comment]
Some question from my side:
Does setting the host value specifically for the onlyoffice path to onlyoffice make it work?

Did not test this logic:
```
location /onlyoffice {
proxy_set_header Host $host/onlyoffice;
}
```

**Comment by foxhoundv** [comment]
> Some question from my side: Does setting the host value specifically for the onlyoffice path to onlyoffice make it work?
> 
> Did not test this logic:
> 
> ```
> location /onlyoffice {
> proxy_set_header Host $host/onlyoffice;
> }
> ```

I will try and see.

**Comment by foxhoundv** [comment]
So I did a fresh reinstall and now I do not have the nextcloud-aio-domaincheck container (I believe that was the name) So I had to try some different settings.
![T2 - 01 - Proxy Host - Details](https://user-images.githubusercontent.com/16512250/166605189-4c9b13b2-7a6c-4dce-be3c-793dbc2258fd.png)
![T2 - 02 - Proxy Host - Custom Locations](https://user-images.githubusercontent.com/16512250/166605194-7bcf4535-3b20-4ebd-b45f-2ac4444c323c.png)
It doesn't work... although I wonder about what port should be designated, especially since no ports are exposed.

**Comment by 2020Sanoj** [comment]
![grafik](https://user-images.githubusercontent.com/75573284/167483793-cddf89ea-9b00-49c8-9287-0c97513717e6.png)
![grafik](https://user-images.githubusercontent.com/75573284/167483816-7daa2ab4-086b-4470-b388-56e09450ab7b.png)
![grafik](https://user-images.githubusercontent.com/75573284/167483841-65891e33-46ae-458d-95d6-095a822dde98.png)
![grafik](https://user-images.githubusercontent.com/75573284/167483860-b881c510-d96d-46f8-af1d-ac91a5ef590a.png)
For me ONLYOFFICE and everything other works fine with this configuration (I run Nginx Proxy Manager with network mode host, so I can access the Nextcloud over 127.0.0.1)

**Comment by szaimen** [comment]
@2020Sanoj am I allowed to add the screenshots that you provided to the reverse proxy documentation? :)
(nginx-proxy-manager is still missing)

**Comment by 2020Sanoj** [comment]
Yes, but for this, as I said the Nginx Proxy Manager need to be launched with network host in the docker compose file / docker run command

**Comment by szaimen** [comment]
Thanks! will add this note :)

**Comment by szaimen** [comment]
1.2.1 stable is released. Can you please try if it works now?
