### ISSUE TITLE
"No disk space left on server" after updating to AIO 8.1.0

### ISSUE THREAD

**Issue by Stooovie** [nextcloud/all-in-one#4500]
Immediately after updating to 8.1.0, I get "No disk space left on server" upon opening any Collabora document. Fine prior to update. 100 GB left on drive. No files added or changed since the update. Cannot use Collabore or open any document.

### Host OS 

Proxmox LXC

#### Nextcloud AIO version 
8.1.0

#### Current channel 
Latest

#### Other valuable info 
Nothing in logs.

It's strangely difficult to determine free space with AIO NC. The LXC has 300 GB reserved, NC app said 190 out of 195 GB used, after deleting 20 GB of files, it says 170 out of 173 GB used (????). But the problem is new, I haven't seen it ever.

Please help.

**Comment by szaimen** [comment]
This is getting handled in https://help.nextcloud.com/t/no-disk-space-left-on-server-after-updating-to-aio-8-1-0/187260
