### ISSUE TITLE
Add documentation about possible NAT configuration to allow containers to reach themselves through their public domain name

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/all-in-one#4519]
### Is your feature request related to a problem? Please describe. 

I have two VMs in my setup. One is hosting AIO.
One is hosting router, NAT, and RP.

When setting up AIO (in RP mode), the network check always failed. After analysis, I discovered that:
- from internet, I can access NC components check (signaling-standalone/api/v1/welcome for Talk, or /hosting/discovery for Collabora)
- from inside a container, I could never curl these URLs. Network failure.

There is some configuration to do on the NAT side to allow port forwarding back onto the same network. See:
https://www.netfilter.org/documentation/HOWTO/NAT-HOWTO-10.html

### Describe the solution you'd like

Add the above to the AIO documentation

### Describe alternatives you've considered

-/-

**Comment by szaimen** [comment]
Added via https://github.com/nextcloud/all-in-one/discussions/5006
