### ISSUE TITLE
Docker network gateway needs to be a trusted proxy in the config.php

### ISSUE THREAD

**Issue by Zoey2936** [nextcloud/all-in-one#4528]
### Steps to reproduce
1. Use AIO in reverse proxy mode (with NPMplus)
2. trigger failed login
3. see docker network gateway as IP

How to fix:
- add IP of docker network gateway to trusted_proxies in the config.php (should maybe be added to the entrypoint.sh/start.sh of the nextcloud container)

### Expected behavior 
log real ip

### Actual behavior 
logs IP of docker network gateway

### Host OS 
Debian 12.5

#### Nextcloud AIO version 
v8.1.0

#### Current channel 
beta

#### Other valuable info 
without IP of the docker gateway and then with it added to the trusted_proxies array in the config.php file
![grafik](https://github.com/nextcloud/all-in-one/assets/75573284/a69f996a-5abe-431d-8b3b-7d0364c9a71d)

**Comment by Zoey2936** [comment]
`ip r | grep default | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+\.1"` this command outputs the IP of the gateway

**Comment by szaimen** [comment]
Does https://github.com/nextcloud/all-in-one/discussions/2045 help?

**Comment by Zoey2936** [comment]
As I wrote whithelisting the gateway IP helps, but I think this IP should be always whithelisted

**Comment by Zoey2936** [comment]
should I open a PR?

**Comment by szaimen** [comment]
Yes, that would be great, thanks :)
