### ISSUE TITLE
Add information to not use @ or : in password (helm values.yaml)

### ISSUE THREAD

**Issue by yannik-b** [nextcloud/all-in-one#4567]
### Is your feature request related to a problem? Please describe. 

I had multiple issues with "unique and good" passwords in the values.yaml when these contain special characters as @ or : as they are interpreted in postgresql URI.

### Describe the solution you'd like

Add a information in values.yaml above all the passwords to not use such symbols as @ and : in secrets.

### Describe alternatives you've considered

- Escape those characters before building the PostgreSQL or redis connection URIs
- Provide a good error notice. Something better than "DATABASE_URL environment variable malformed" when I don't have to provide any DATABASE_URL env variable in values.yaml

**Comment by szaimen** [comment]
Hey, would you mind opening a PR that documents this? Thanks a lot in advance! :)

**Comment by yannik-b** [comment]
Will do this tomorrow
