### ISSUE TITLE
Username is not shown in Activity comments mention (only "{mention1}")

### ISSUE THREAD

**Issue by n3ur0m4n** [nextcloud/all-in-one#4605]
### Steps to reproduce
1. Open details for a file (ex. Nextcloud Manual.pdf)
2. Under the Activity tab add a new comment with @user for mention
3. In the comments list the user is visible, but under the main Activity tab, the comment show "{mention1}" and the mentioned user is not visible 

#### Other valuable info 

![image](https://github.com/nextcloud/all-in-one/assets/16403996/6b32b337-0132-46c7-a253-776abe688722)

![image](https://github.com/nextcloud/all-in-one/assets/16403996/79f6f95d-c77a-4651-8fd9-77f3fe4a22a4)

**Comment by szaimen** [comment]
Hi, please open an issue here if there shouldnt be one already: https://github.com/nextcloud/server/issues
