### ISSUE TITLE
Bug on Notes app version 4.10.0

### ISSUE THREAD

**Issue by souovan** [nextcloud/all-in-one#4614]
### Steps to reproduce
1. Access Notes application
2. Try to create new or delete an existing one

### Expected behavior 
The application should create and exibihit the new note or delete the existing one

### Actual behavior 
Nothing happens in both cases, making it necessary to forcefully refresh the page to show the change

### Host OS 
Running on:
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

#### Nextcloud AIO version 
Nextcloud AIO v8.2.0

#### Current channel 
latest

#### Other valuable info 
In some tests i got the below behavior:

[![asciicast](https://asciinema.org/a/7t0hzjUJi1avgLopd5D4a9Jvo.svg)](https://asciinema.org/a/7t0hzjUJi1avgLopd5D4a9Jvo)

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/nextcloud/notes
