### ISSUE TITLE
Errors in logs: Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by bennyslbs** [nextcloud/all-in-one#4626]
### Steps to reproduce
1. Have a running Nextcloud AIO, installed months ago, auto-upgraded
2. View Logs in Admin-web interface
3. Tried to fix via running this command, but didn't help.
   `sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ maintenance:repair`

### Expected behavior 
No errors expected

### Actual behavior 
A lot of log entries as this - new for each 35 minutes:
` file_put_contents(/mnt/ncdata/appdata_************/bookmarks/cache/CACHEDIR.TAG): Failed to open stream: No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#339`

### Host OS 
Debian 12

#### Nextcloud AIO version 
Nextcloud AIO v8.2.1

#### Current channel 
latest

**Comment by szaimen** [comment]
Hi, please open an issue here: https://github.com/nextcloud/bookmarks
