### ISSUE TITLE
Second user cannot login through webdav

### ISSUE THREAD

**Issue by Joly0** [nextcloud/all-in-one#4704]
I have a user that is unable to login using webdav and only sees this error:
![Screenshot_2024-05-23-17-55-56-64_0e489ec226af3f5e7c9b5690cc6e2ad0.jpg](https://github.com/nextcloud/all-in-one/assets/13993216/5e4082a8-ab0d-4a4e-9853-d9615a1df091)

The same account can login from the webui and the app, but not through webdav. My user can login without any issues, although both have exactly the same permissions.

### Steps to reproduce
1. I have no idea how to reproduce this

### Expected behavior 
user should be able to login
### Actual behavior 
user isnt able to login

### Host OS 
Unraid

#### Nextcloud AIO version 
v8.2.1
#### Current channel 
Latest

**Comment by szaimen** [comment]
Hi, please ask this at https://help.nextcloud.com
