### ISSUE TITLE
SKIP_DOMAIN_VALIDATION=true with manual install

### ISSUE THREAD

**Issue by PhysicsIsAwesome** [nextcloud/all-in-one#4716]
I could not find a way to use SKIP_DOMAIN_VALIDATION=true in case of a reverse proxy with DNS challenge for the manual install method without using the master container. Is there a way to do this?

**Comment by Zoey2936** [comment]
There is no domain check in manual install, so you can't skip something which doesn't exist

**Comment by PhysicsIsAwesome** [comment]
I see. Thank you.

Then something must be wrong with my reverse proxy config.
