### ISSUE TITLE
Nextcloud on path instead of subdomain

### ISSUE THREAD

**Issue by UltraBlackLinux** [nextcloud/all-in-one#4717]
### Is your feature request related to a problem? Please describe. 

I don't like hosting things on subdomains. It's more work and it's ugly. In my opinion the same server should always use paths instead of subdomains for different services.
As I wanted to set up the nextcloud AIO image today, after my previous non-aio nextcloud instance imploded on an upgrade and rendered the database unusable, I was immediately greeted with a request to enter a domain, which didn't accept any paths

### Describe the solution you'd like

Allow paths, e.g. `domain.com/cloud` instead of `cloud.domain.com`

### Describe alternatives you've considered

There is no alternative I'm happy with

### Additional context

it worked on the community edition nextcloud image, so I don't see why it wouldn't work on the AIO image

**Comment by Zoey2936** [comment]
There were already discussions/issues about this and no, it won't be added since you can use a subdomain. If you need further reasons, just search for the PRs/Issues/Discussions

**Comment by UltraBlackLinux** [comment]
tragic...
