### ISSUE TITLE
SSL Error / Own fault

### ISSUE THREAD

**Issue by krauthaus** [nextcloud/all-in-one#473]
Last night I tried to save a snap instance, it was a night full of horror.

I really lukentgus project since it made the hole setup process very easy. I can enter wit the local IP and over my domain.ltd:8443 the air center welcomes me. But the nextcloud instance itself just shows a SSL Error.

Since the logs seem to whisper me that I was too excessive with new SSL certs letsencrypt put me on the list.

Will this resolve itself when my jailtime is over or should I restart the hole install/Backup to fresh install?

thx for the help!

**Comment by szaimen** [comment]
There is nothing that you can do when you reached the letsencrypt limit then waiting. You could retry with a different domain though.
