### ISSUE TITLE
User Creation Process

### ISSUE THREAD

**Issue by lukasmatourek** [nextcloud/all-in-one#4781]
### Steps to reproduce
1. Log In as admin
2. Go to Users and click Create User
3. Fill some fields, username at least.
4. Click out of the dialog window, so it will close
5. Try to create the same user again.
6. Finish the creation properly, you should get error message on top right corner that the user with this username already exists but the new user is created anyway so no big deal.

### Expected behavior 
The message that user already exists should not be displayed as you did not finish the creation process and closed the dialog accidentally

### Actual behavior 
The error message that user was already created is displaying.

### Host OS 
Ubuntu Linux 22.04.4 LTS

#### Nextcloud AIO version 
Used Docker image 20240606_075829-latest

#### Other valuable info 
I would disable closing the dialog window when user clicks out of the dialog. It is annoying behaviour of many applications that you have work in progress and accidentally na click out of dialog and the work is gone. It is not big deal, just idea for improvement.

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/nextcloud/server/issues

**Comment by lukasmatourek** [comment]
> Hi, please report this to https://github.com/nextcloud/server/issues

Hello, I did. Thanks.
