### ISSUE TITLE
403 Forbidden on Public Shares

### ISSUE THREAD

**Issue by tijnsc** [nextcloud/all-in-one#4841]
### Steps to reproduce
1. Update to Nextcloud AIO v9.0.1
2. Create a new public share for any folder or file
3. Visit the share link in any browser

### Expected behavior 
I should be able to access the files in the shared public folder

### Actual behavior 
I get a 403 Forbidden page, the url is rewritten to https://cloud.hostname.org/login/selectchallenge?redirect_url=XXXXXXXX

### Host OS 
Ubuntu Server 22.04.4 LTS

#### Nextcloud AIO version 
v9.0.1

#### Current channel 
latest

#### Other valuable info 
![Screenshot 2024-06-18 130827](https://github.com/nextcloud/all-in-one/assets/26672538/4188d4e5-0a42-4308-b245-2c8d16c2e4c5)

**Comment by szaimen** [comment]
Hi, please open an issue here: https://github.com/nextcloud/server/issues
Thanks!

**Comment by tijnsc** [comment]
Thank you, I assumed this was an Apache configuration issue, so I opened it here.
I have opened a new issue at https://github.com/nextcloud/server/issues/45949
