### ISSUE TITLE
Files not visible for users on desktop or mobile

### ISSUE THREAD

**Issue by tailsec** [nextcloud/all-in-one#4869]
### Steps to reproduce
1. Upload files to user directory (e.g. X:\nc_datadir\<username>\files\Photos)
2. Run `sudo -u www-data php occ files:scan <username>` on the nextcloud container to index new files
3. Output confirms the new files were indexed 
4. Logging in as user and viewing Files > All Files now shows no files, whereas previously it showed the files prior to the upload
5. Viewing Photos > All Media or Photos > Folders shows the files and folders which were uploaded and indexed
6. Double-checking the server drive, the files and folders are all still there and intact.

### Expected behavior 

The files and folders should also show up under All Files.

### Actual behavior 

Users can no longer see the files that were visible prior to the upload, or the files which were uploaded. Viewing the All Files location on both Desktop and Mobile shows a blank page - "No files in here. Upload some content or sync with your devices!"

### Host OS 

Windows 11 running the all-in-one install on Docker Desktop. Docker Engine v26.1.4 and Docker Desktop 4.31.1 (153621) both latest available versions at this time

#### Nextcloud AIO version

Nextcloud AIO v9.0.1

#### Current channel

latest

#### Other valuable info 

![image](https://github.com/nextcloud/all-in-one/assets/126639182/34cba0d2-798c-40c5-9ab7-4aec0012a629)

Images are still visible in the Media folder (black boxes added for privacy):
![image](https://github.com/nextcloud/all-in-one/assets/126639182/72bbee74-a640-4f4f-8998-91a9c40324f7)

**Comment by szaimen** [comment]
Hi, please post this at https://help.nextcloud.com
