### ISSUE TITLE
NPM-PLUS issues with it going to sleep possibly

### ISSUE THREAD

**Issue by Sabering1** [nextcloud/all-in-one#4877]
### Steps to reproduce
1. Install AIO the normal way except add community container npmplus.
2. After the process has been complete use nextcloud as normal
3. Here the bug will appear

### Expected behavior 
When i enter my subdomain name that's connected to nextcloud it should load it with no issues

### Actual behavior 
All browsers will report a TLS error and the nextcloud instance will not be accessible, however after reloading the page it works out fine

### Host OS 
Debian latest

#### Nextcloud AIO version 
Latest

#### Current channel 
Latest

**Comment by Zoey2936** [comment]
Can you please op a discussion here: https://github.com/ZoeyVid/NPMplus/discussions/new?category=q-a please also say if you run a local instance and what exact tls error you are talking about

**Comment by Sabering1** [comment]
sure one second

**Comment by Sabering1** [comment]
I use nextcloud docker and community container called NPMplus, when everything is set up it works just fine, but after a while if its inactive i belive, it will bug out and the next time i try to load my nextcloud instance it will report a TLS error (not sure will attach a screenshot when it happens again), this will not happen with any other subdomains/services i have set up, which leads me to belive that maybe nextcloud stops working somehow? or that npm will go to sleep and stop listening on that port? i dont know i will provide the logs when it happens again.

I am running on a home server with static ip and all ports opened correctly and i can confirm that they are not blocked by my isp

**Comment by Sabering1** [comment]
[WARN  tini (7)] Tini is not running as PID 1 and isn't registered as a child subreaper.
Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/README.md' -> '/data/etc/modsecurity/crs-plugins/README.md'
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/empty-after.conf' -> '/data/etc/modsecurity/crs-plugins/empty-after.conf'
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/empty-before.conf' -> '/data/etc/modsecurity/crs-plugins/empty-before.conf'
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/empty-config.conf' -> '/data/etc/modsecurity/crs-plugins/empty-config.conf'
no DEFAULT_CERT_ID set, using dummycerts.
Working on file: /data/nginx/custom/events.conf
Working on file: /data/nginx/custom/http.conf
Working on file: /data/nginx/custom/http_top.conf
Working on file: /data/nginx/custom/root.conf
Working on file: /data/nginx/custom/server_dead.conf
Working on file: /data/nginx/custom/server_proxy.conf
Working on file: /data/nginx/custom/server_redirect.conf
Working on file: /data/nginx/custom/server_stream.conf
Working on file: /data/nginx/custom/server_stream_tcp.conf
Working on file: /data/nginx/custom/server_stream_udp.conf
Working on file: /data/nginx/custom/stream.conf
Working on file: /data/nginx/custom/stream_top.conf
Working on file: /data/nginx/default.conf
Working on file: /data/nginx/ip_ranges.conf
Working on file: /data/nginx/proxy_host/1.conf
Working on file: /data/nginx/proxy_host/10.conf
Working on file: /data/nginx/proxy_host/2.conf
Working on file: /data/nginx/proxy_host/3.conf
Working on file: /data/nginx/proxy_host/9.conf
Success.

-------------------------------------
 _ _  ___  __ __       _
| \ || . \|  \  \ ___ | | _ _  ___
|   ||  _/|     || . \| || | |[_-[
|_\_||_|  |_|_|_||  _/|_| \__|/__/
                 |_|
-------------------------------------
Version:  2.11.2+22fa2f0
Date:     Sat Jun 22 18:24:52 CEST 2024
User:     root
PUID:     0
User ID:  0
PGID:     0
Group ID: 0
-------------------------------------

nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found for certificate "/data/tls/dummycert.pem"

**Comment by Sabering1** [comment]
nextcloud shows also this : Some headers are not set correctly on your instance - The `X-XSS-Protection` HTTP header does not contain `1; mode=block`. This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.

**Comment by Zoey2936** [comment]
I will handle this in https://github.com/ZoeyVid/NPMplus/discussions/901
