### ISSUE TITLE
change IPv6 Documentation

### ISSUE THREAD

**Issue by Zoey2936** [nextcloud/all-in-one#4887]
Docker has changed how ipv6 is configured by default with v27.0.1: https://github.com/moby/moby/releases/tag/v27.0.1, we should change the documentation

**Comment by szaimen** [comment]
Thanks for the heads-up! PRs are welcome if you have time :)

**Comment by Zoey2936** [comment]
so what changed in practice in the daemon.json:
 - experimental can be removed
 - ip6tables can be removed (it is enabled by default)
 - ipv6 and fixed-cidr-v6 can be removed if ipv6 is not needed for the default bridge network (not used by AIO) - see: https://github.com/moby/moby/issues/47990
 => changes in daemon.json are not needed anymore

what changed for the network creation (requires newest docker deamon, cli and compose) - portainer currently not supported (because compose version is too old):
 - ipam and all suboptions can be removed
 - if `"default-network-opts":{"bridge":{"com.docker.network.enable_ipv6":"true"}}` is set in daemon.json, then the networks doesn't need to be created at all, because ipv6 will be enabled for all new networks
 => ipam and suboptions can be removed and if `"default-network-opts":{"bridge":{"com.docker.network.enable_ipv6":"true"}}` is set then no network needs to be manually created

**Comment by szaimen** [comment]
Thanks Zoey! This feels so much nicer now 🤗
