### ISSUE TITLE
Collabora changes are lost after the nightly backup

### ISSUE THREAD

**Issue by Roman991** [nextcloud/all-in-one#4896]
I dont know if its more related to AIO or to collabora

After the daily backup (with instance restart) changes to a collabora ods file are lost.

### Steps to reproduce
1. Create a ods file
2. Make some changes by multiple users (the changes are visible and saved)
3. Wait the daily bak + restart
4. Go back to file and all changes are lost

### Host OS 
Proxmox 8 > LXC debian 12 > Docker 26.1

#### Nextcloud AIO version 
9.0.1

**Comment by szaimen** [comment]
Hi, please open an issue for that at https://github.com/nextcloud/richdocuments/issues. Thanks!
