### ISSUE TITLE
Feature: Multi Tenant Support

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/all-in-one#49]
Multi Tenant Support would be a huge plus.

For example we could have several instances of nextcloud on one server

cloud.somedomain.com
cloud.anotherdomain.com
etc

Allow these domains to be added to the AIO WebUI

**Comment by szaimen** [comment]
Sry but we are not going to add this at least in the foreseeable future. 
Feel free to investigate yourself how this could be done :)
