### ISSUE TITLE
nextcloud admin account repeatedly disabled

### ISSUE THREAD

**Issue by Liziloo** [nextcloud/all-in-one#4906]
### Steps to reproduce
1. login to nextcloud as admin
2. wait a few hours or a day
3. try to log back in, admin account disabled 

### Expected behavior 
Should be able to log in to nextcloud as admin

### Actual behavior 
The nextcloud admin account is disabled after several hours despite no unsuccessful login attempts. Logs show admin as having tried to log in in the middle of the night, despite no such behavior on human end, and no corroborating evidence of traffic incoming to website

### Host OS 
Open Media Vault docker container

#### Nextcloud AIO version 
29.0.1.1

#### Current channel 
Apparently can't access the interface either -- "slim application error"

**Comment by szaimen** [comment]
Hi, please post this at https://help.nextcloud.com thanks!
