### ISSUE TITLE
OpenWrt image pull failure: failed to register layer: lsetxattr security.capability /usr/bin/caddy: operation not supported

### ISSUE THREAD

**Issue by zhengliw** [nextcloud/all-in-one#4907]
### Steps to reproduce
1. Use https://github.com/nextcloud/all-in-one/blob/main/compose.yaml to define docker-compose file...
2. docker compose up
3. Initial image pull fails with error

### Expected behavior 
Image downloads successfully and container starts up

### Actual behavior 
failed to register layer: lsetxattr security.capability /usr/bin/caddy: operation not supported

### Host OS 
OpenWrt 23.05.3, Docker 26.1.0  
using Docker Compose

#### Nextcloud AIO version 
not related

#### Current channel 
nextcloud/all-in-one:latest

#### Other valuable info 
Based on my research, my guess would be that something is trying to access xattr related functionality although OpenWrt doesn't include these in the default kernel. Maybe we could identify the component that's using it...

This is a snippet around the end....
```
   ✔ 4abcf2066143 Already exists                                           0.0s 
   ✔ 64d2971301bc Pull complete                                            1.0s 
   ✔ cc6eca4f1862 Pull complete                                            1.0s 
   ✔ b5d35b189a56 Pull complete                                            1.0s 
   ✔ e4edc397ae5a Pull complete                                            1.3s 
   ✔ 61392208410a Pull complete                                            1.3s 
   ✔ bee5804676fa Pull complete                                            3.2s 
   ✔ 51b55d7a64eb Pull complete                                            3.2s 
   ✔ 1de2bd55d517 Pull complete                                            6.6s 
   ✔ a326e5f4c37a Pull complete                                            6.6s 
   ⠿ d630d07ded49 Extracting       14.64MB/14.64...                        9.8s 
   ✔ a4242c1aebc5 Download complete                                        7.4s 
   ✔ 79c7df51942c Download complete                                        7.0s 
   ✔ 3302431a828c Download complete                                        7.9s 
   ✔ f52aa223cc7a Download complete                                        7.8s 
   ✔ 32420f8e2209 Download complete                                        8.2s 
   ✔ 930390356495 Download complete                                        8.4s 
   ✔ 267204048c7c Download complete                                        8.6s 
failed to register layer: lsetxattr security.capability /usr/bin/caddy: operation not supported
```

**Comment by szaimen** [comment]
> failed to register layer: lsetxattr security.capability

Hi, I found this: https://www.google.com/search?q=failed%20to%20register%20layer%3A%20lsetxattr%20security.capability
