### ISSUE TITLE
Cannot upload files larger than 100 MB via share link because of ClamAV

### ISSUE THREAD

**Issue by saytamkenorh** [nextcloud/all-in-one#4918]
### Steps to reproduce
1. Verify that logged in user can upload files larger than 100 MB through the Files app via the New button
2. Create a folder with a "File Drop" share link or a share link with modify rights
3. Try to upload a file larger than 100 MB using the link (it does not matter if the link is opened in the same browser window or in an anonymous window where a Nextcloud user is not logged in)

### Expected behavior 
File uploads without any problems.

### Actual behavior 
File does not upload. The user sees a message that an unknown error occurred.

**An error also appears in the Event Log:**

`BadRequest
Expected filesize of 325033371 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 134111232 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.`

When I changed the files_antivirus av_stream_max_length setting via occ to the equivalent of 300 MB, the upload works fine but another error appears in the event log:
`Failed to write a chunk. Check if Stream Length matches StreamMaxLength in anti virus daemon settings.`
I should probably also change the settings in the /etc/clamav/clamd.conf file but this would require modifying the ClamAV container. **Nevertheless, it is certain that the antivirus somehow blocks the file upload.**

### Host OS 
Debian 12.5

#### Nextcloud AIO version 
v8.3.0

#### Current channel 
latest

#### Other valuable info 
Running behind a nginx reverse proxy

**Comment by szaimen** [comment]
Hi, thanks for you report! I'll probably have a look next week.

**Comment by szaimen** [comment]
Looks like I can reproduce this

**Comment by saytamkenorh** [comment]
@szaimen Thank you for the fix!

**Comment by szaimen** [comment]
This is now released with v9.2.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by saytamkenorh** [comment]
@szaimen So I have installed the beta on my homelab server and I can confirm that with ClamAV enabled uploading files via a share link works now seamlessly out of the box. I was able to upload a ~1GB and a ~4GB file.

However, I found a warning in the ClamAV log:
`LibClamAV Warning: Max file-size was set to 10737418240 bytes. Unfortunately, scanning files greater than 2147483647 bytes (2 GiB - 1) is not supported.`
So I tried setting the Stream Length and Max File size in Nextcloud AV settings to "2147483647" and uploading both files smaller than 2GB and larger than 2GB via a share link still worked without any problems. With lower values I sometimes experienced the problem why I originally opened this issue.

I was not able to modify the clamd.conf file though. Nevertheless, if it worked even with the clamd.conf file modified, it would be maybe best to set both parameters to 2147483647 to get rid of the warning.

**Comment by szaimen** [comment]
> However, I found a warning in the ClamAV log: `LibClamAV Warning: Max file-size was set to 10737418240 bytes. Unfortunately, scanning files greater than 2147483647 bytes (2 GiB - 1) is not supported.` So I tried setting the Stream Length and Max File size in Nextcloud AV settings to "2147483647" and uploading both files smaller than 2GB and larger than 2GB via a share link still worked without any problems. With lower values I sometimes experienced the problem why I originally opened this issue.
> 
> I was not able to modify the clamd.conf file though. Nevertheless, if it worked even with the clamd.conf file modified, it would be maybe best to set both parameters to 2147483647 to get rid of the warning.

I fear this is a hard-limit then: Apparently uploading any file that is bigger than 2 GiB via public link will fail if clamav is enabled, right?

**Comment by saytamkenorh** [comment]
@szaimen
Sorry, my mistake, I was not clear enough. What I essentially ended up with is:

- ClamAV is enabled on my instance
- Both limits in the AV settings in Nextcloud GUI administration are set to 2147483647
- Uploading of files of any size through the public link surprisingly **does** still work
    - I tried uploading a 2.3 GB ZIP and a 3.2 ZIP file with videos and before the file was uploaded completely the CPU usage spiked because of a clamd process so the file was probably successfully checked somehow
- However, setting the values in the administration to something lower than 2147483647 causes that the uploads (more or less often) fail

**Comment by szaimen** [comment]
Okay but setting it to something higher than 2147483647, will this only trigger this warning and disable scanning or does it still work? In my testing at least it worked, so I would risk this warning because our implementation is technically correct...

**Comment by saytamkenorh** [comment]
Yes, it works without any problems even if the warning is present.

Okay, that is a fair point. It is probably better to keep it at 10 GB like it is now then.
