### ISSUE TITLE
Core error | flooded with "ValueError" error while running background job

### ISSUE THREAD

**Issue by carsten-re** [nextcloud/all-in-one#4928]
Seeing this error several times:
Error - core:

ValueError
Path cannot be empty
Error while running background job OC\FilesMetadata\Job\UpdateSingleMetadata  (id: 3468, arguments: ["carsten",10456])

### Steps to reproduce
1. not sure, logfile is flooded with such errors.

### Expected behavior
At least steps to solve it.

### Actual behavior
One issue I see is, that Photo App is not showing new pictures in the preview.

### Host OS
Debian 12 LXC

#### Nextcloud AIO version
Nextcloud AIO v9.1.0

#### Current channel
latest

**Comment by szaimen** [comment]
Hi, please open an issue for this here: https://github.com/nextcloud/server if it is not already reported
