### ISSUE TITLE
Talk push notifications are not working

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#496]
I think this might be related to AIO as it seems to work on non-AIO instances.

https://github.com/nextcloud/talk-android/issues/1921

**Comment by szaimen** [comment]
sorry, I cannot reproduce. Just tried and it works here.

---

I suppose you are not running AIO behind a nginx reverse proxy? https://github.com/nextcloud/all-in-one/issues/491

Also, push notifications only work if you installed the Nextcloud Talk app from the Google Play store...
