### ISSUE TITLE
Caldav not working on osx

### ISSUE THREAD

**Issue by e4242** [nextcloud/all-in-one#5014]
### Steps to reproduce
1. Step up nextcloud with SSO
2. Create an app password
3. Navigate to the calendar app and click on "Copy iOS/macOS CalDAV address"
4. Go to the default calendar app in OSX and choose add Caldav account
5. Fill in the user, username and password from step 2

### Expected result
Calendar events showing up on local computer

### Actual results
Constantly getting the same error: Your calendar couldn’t be refreshed. The request for account “ADDRESS” failed.

### Notes
All steps from the guide were followed. Https, no self-signed certificates, .well-known/caldav, etc.

**Comment by szaimen** [comment]
Hi, please open an issue for this at https://github.com/nextcloud/server
