### ISSUE TITLE
Provide Vim Keybindings For Text Editing

### ISSUE THREAD

**Issue by andynameistaken** [nextcloud/all-in-one#5020]
Hi,
I just started to use Nextcloud AIO and I found editing text files cumbersome (Notes, Collectives). I am very used to Vim editor (as some of us are I guess) and it just feels like step backwards.

If you ever find it worthwhile please add an option for enabling Vim keybindings (and maybe emacs so those folks would be happy too)

**Comment by blueholocron** [comment]
This project is focused on installation and management of Nextcloud. Perhaps filing in issue in the [text](https://github.com/nextcloud/text) or [notes](https://github.com/nextcloud/notes) repository would be more productive?
