### ISSUE TITLE
After automatic update without backup beforehand database container fails to start

### ISSUE THREAD

**Issue by NiklasReisser** [nextcloud/all-in-one#5045]
Hi, 

after updating my nextcloud instance, I am unable to bring it back online again. 
Thanks in advance for any help & support!

Kind regards

Niklas

### Steps to reproduce
1. I followed https://github.com/nextcloud/all-in-one#how-to-enable-automatic-updates-without-creating-a-backup-beforehand

### Expected behavior 

nextcloud should be up and running again

### Actual behavior 

The apache, nextcloud, database and notify-push containers remain in state "starting"

The cause the database container being stuck in a reboot loop, with the log below. The other containers are "just" waiting for the database

```
2024-07-26T09:26:32.651127026Z Unable to restore the database because the database dump is missing.
2024-07-26T09:26:33.197662313Z Unable to restore the database because the database dump is missing.
2024-07-26T09:26:33.665916939Z Unable to restore the database because the database dump is missing.
2024-07-26T09:33:19.988073491Z Unable to restore the database because the database dump is missing.
... <continues endlessly> ...
```

### Host OS 

docker / ubuntu 23.10

#### Nextcloud AIO version 

v9.3.0 (after the update. Unfortunately I don't recall the previous version)

#### Current channel 

latest

#### Other valuable info 

1. I followed this instructions because I have a separate backup solution in place.
2. nextcloud-apache is not avalailable at the assigned port (11000) as well. Stopping the containers only works via AIO-WebGui, calling `docker exec --env STOP_CONTAINERS=1 nextcloud-aio-mastercontainer /daily-backup.sh` causes endless `Waiting for apache to become available` messages

**Comment by szaimen** [comment]
Hi, please restore a backup from before the update to recover from this situation.
