### ISSUE TITLE
Large file upload chunking issue on Firefox

### ISSUE THREAD

**Issue by BLovegrove** [nextcloud/all-in-one#5049]
### Steps to reproduce
1. Create  fresh AIO instance on unraid under a fresh NGINX Proxy Manager install, using all instructions provided in the AIO repo
2. Optionally, change PHP ram size, timeout, and file upload size but this has made no effect even as high as 80G
3. Log in to nextcloud and upload a file >10G in size through the web interface using firefox (fresh install, no extensions). For some reason, it seems to work fine on Chrome from my limited testing.

### Expected behavior
File should, after some time, upload

### Actual behavior
I get an 'unknown error' UI popup, and checking dev console reveals a few lines of error and nothing else.
Screenshots taken in order of appearance in the dev console in the last section of this report.

Sometimes, the upload gets right to the end and then fails with a single error in the log (again, showing as unknown in the NC UI popup) saying the chunks couldn't be reassembled, reason: rejected

### Host OS
Unraid

#### Nextcloud AIO version
Hub 8 (29.0.4)

#### Current channel
Latest

#### Other valuable info
I can take more screenshots, recordings, or get more log info as needed I'm just not 100% sure how much is needed and where from.
I'm completely at my whits end and have tried everything i can think of so far. Would *really* appreciate some help.

Dev console errors:
![image](https://github.com/user-attachments/assets/028c6f30-746b-4301-81ff-3a663e6c53d0)
![image](https://github.com/user-attachments/assets/796c3d21-7fef-455a-8dc5-408807f82b69)
![image](https://github.com/user-attachments/assets/fe8c6e48-de5c-4dc5-85c4-6816d84ea55d)
![image](https://github.com/user-attachments/assets/f9c4bb9f-b179-4778-8e6b-66d54023e120)

These popped up in the nextcloud log around the same time:
![image](https://github.com/user-attachments/assets/ff6a89d0-48e8-45fc-974e-c934688c8796)

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/nextcloud/server
