### ISSUE TITLE
Windows CMD AIO cannot download container. Incorrect username or password??? 

### ISSUE THREAD

**Issue by memece3** [nextcloud/all-in-one#5058]
### Steps to reproduce
1.Install Docker Desktop
2. Copy and paste code from github/nextcloud/all-in-one for windows
3. Press enter. recieve error:  
C:\Users\memec>docker run ^
More? --init ^
More? --sig-proxy=false ^
More? --name nextcloud-aio-mastercontainer ^
More? --restart always ^
More? --publish 80:80 ^
More? --publish 8080:8080 ^
More? --publish 8443:8443 ^
More? --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config ^
More? --volume //var/run/docker.sock:/var/run/docker.sock:ro ^
More? nextcloud/all-in-one:latest
Unable to find image 'nextcloud/all-in-one:latest' locally
docker: Error response from daemon: Head "https://registry-1.docker.io/v2/nextcloud/all-in-one/manifests/latest": unauthorized: incorrect username or password.
See 'docker run --help'.

C:\Users\memec>
### Expected behavior 
should install nextcloud and go to the next step. I installed this once. It worked perfect except the login would not accept the long pass phrase so i uninstalled and started again.
### Actual behavior 
after I installed Docker Desktop without error and paste the code from github, it just comes up with the error

### Host OS 

Windows 11 Pro

**Comment by szaimen** [comment]
Hi, this will be handled in https://github.com/nextcloud/all-in-one/discussions/5056
