### ISSUE TITLE
Add whiteboard container for nc30

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#5063]
As option to the aio interface. See https://github.com/nextcloud/whiteboard/pull/82 and https://github.com/nextcloud/all-in-one/pull/378 as reference

FYI @juliushaertl

**Comment by juliushaertl** [comment]
Relevant occ commands to automate configuration are in the apps readme, caddy config can be adapted from https://socket.io/docs/v3/reverse-proxy/#caddy-2

**Comment by szaimen** [comment]
- Needs https://github.com/nextcloud/whiteboard/pull/90; add redis connectivity then

**Comment by szaimen** [comment]
- Needs at least 1 pre-release or a stable release that I can use like e.g. v0.0.1-beta or something: https://github.com/nextcloud/whiteboard/pkgs/container/whiteboard

**Comment by juliushaertl** [comment]
Sorry for the delay @szaimen 

https://github.com/nextcloud-releases/whiteboard/pkgs/container/whiteboard/272546293?tag=v1.0.0-rc.1
https://github.com/nextcloud-releases/whiteboard/releases/tag/v1.0.0-rc.1

**Comment by szaimen** [comment]
> https://github.com/nextcloud-releases/whiteboard/pkgs/container/whiteboard/272546293?tag=v1.0.0-rc.1

@juliushaertl looks like the package is private or not reachable for me?

**Comment by juliushaertl** [comment]
Changed the visibility, can you check that one?

https://github.com/nextcloud-releases/whiteboard/pkgs/container/whiteboard/272548458?tag=v1.0.0-rc.1

**Comment by szaimen** [comment]
yes, can see it 👍

**Comment by Zoey2936** [comment]
also possible, but then the upstream Dockerfile needs changes:
1. it uses multiple run steps which makes it bigger then it needs (also I recommend clean-modules to remove bnot needed files from the node_modules folder)
2. the docker image is not very strictly tagged, can be used, but I think it is not the best way
3. tzdata is missing
4. healthcheck is missing
5. them CMD would not even work at this moment:
https://github.com/nextcloud/whiteboard/blob/2e5014eff779a72d2e5dc2db220d50b0732200d2/Dockerfile#L27
file does not exist: https://github.com/nextcloud/whiteboard/tree/v1.0.0-rc.1/websocket_server
instead it should be npm run server:start or node websocket_server/main.js
https://github.com/nextcloud/whiteboard/blob/2e5014eff779a72d2e5dc2db220d50b0732200d2/package.json#L16

**Comment by szaimen** [comment]
@juliushaertl FYI ⬆️

**Comment by Zoey2936** [comment]
Í can also open a PR at https://github.com/nextcloud/whiteboard

**Comment by szaimen** [comment]
Sounds good, thanks for the offer :)

**Comment by juliushaertl** [comment]
Definitely, a pr there is much appreciated

**Comment by Zoey2936** [comment]
see https://github.com/nextcloud/whiteboard/pull/145

**Comment by juliushaertl** [comment]
Merged and released as 1.0.0-rc.2, thanks again @Zoey2936

**Comment by szaimen** [comment]
@juliushaertl I am wondering if we should rather wait for https://github.com/nextcloud/whiteboard/issues/119 and not implement the container additionally in AIO as the app_api is already part of AIO.

**Comment by szaimen** [comment]
However users of https://github.com/nextcloud/all-in-one/tree/main/nextcloud-aio-helm-chart would then not be able to easily run it...

**Comment by juliushaertl** [comment]
For now https://github.com/nextcloud/whiteboard/issues/119 will have performance penalty as there is only a way to proxy requests through a PHP endpoint, so at least in the first iteration there is no websocket connection just polling. I think running the separate container is still the better approach.

**Comment by szaimen** [comment]
All right. Will add it then to aio directly 👍
