### ISSUE TITLE
Manual Install README error and missing information

### ISSUE THREAD

**Issue by CoderTobi** [nextcloud/all-in-one#5079]
### Is your feature request related to a problem? Please describe. 

I think there is a slight error in this read me file:
[all-in-one/manual-install/readme.md](https://github.com/nextcloud/all-in-one/tree/main/manual-install)
at [this](https://github.com/nextcloud/all-in-one/tree/main/manual-install#docker-profiles) paragraph.
It says to use `docker-compose` which I think does not support the profiles Feature. Because I am getting this error:
```
ERROR: The Compose file './compose.yaml' is invalid because:
services.nextcloud-aio-nextcloud.depends_on contains unsupported option: 'required'
services.nextcloud-aio-apache.depends_on contains unsupported option: 'required'
```
It works simply fine with `docker compose`. Note the missing `-`. One uses the standalone binary and one the plugin.

Additionally, I noticed that using the manual install the apache container starts trying to do the ACME challenge which surprised me as it didn't seem to be documented anywhere, that it just does that.

### Describe the solution you'd like

Replace `docker-compose` with `docker compose` and add a note about how the ACME challenge works with the manual install or just how to handle https by caddy or other proxies.

**Comment by szaimen** [comment]
Hi, thanks for the report! The commands are going to be adjusted with https://github.com/nextcloud/all-in-one/pull/5085.

---

> add a note about how the ACME challenge works with the manual install or just how to handle https by caddy or other proxies.

As for that, it is indirectly documented via https://github.com/nextcloud/all-in-one/blob/89d2dd7287c19597b6a3c694b0648aea60bf1b16/manual-install/sample.conf#L24.

If you want to run it behind your own RP, you need to adjust this variable and then you can basically use the same config like here: https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#1-configure-the-reverse-proxy
