### ISSUE TITLE
AIO Borgbackup stuck on "Creating archive"

### ISSUE THREAD

**Issue by Felitendo** [nextcloud/all-in-one#5087]
### Steps to reproduce
1. Start a Backup via the AIO Interface
2. Look in Logs of nextcloud-aio-borgbackup
3. See the Error below

### Expected behavior
It should create the Backup and the Archive

### Actual behavior
It is stuck on this:

```
Performing backup...
Starting the backup...
Creating archive at "/mnt/borgbackup/borg::20240802_152255-nextcloud-aio"

```

### Host OS
Debian 12

#### Nextcloud AIO version
v9.4.1

#### Current channel
beta

#### Other valuable info
Logs:

```
2024-08-02T15:22:55.603354704Z Performing backup...
2024-08-02T15:22:55.603787039Z Starting the backup...
2024-08-02T15:22:57.134198369Z Creating archive at "/mnt/borgbackup/borg::20240802_152255-nextcloud-aio"
```

**Comment by Felitendo** [comment]
I just delete the /mnt/backup Folder most of the time, but that's not a really good solution for obvious reasons

**Comment by szaimen** [comment]
Hi, I fear I cannot reproduce this on my test server. So I suspect that this is caused by something AIo is not in control over. E.g. an external drive. However I'll leave this open for now since apparently more people run into this recently...

**Comment by Felitendo** [comment]
Hey, I've had this prblem for years now. I suggest it has to do with my System, even though I'm just using a VPS with no external drive. Welp, I'm just going to delete /mnt/backup then

**Comment by Felitendo** [comment]
Thanks for answering so quickly though :)

**Comment by szaimen** [comment]
Which OS are you using?

**Comment by Felitendo** [comment]
Linux Debian 12

**Comment by szaimen** [comment]
Okay... can you post the output of `sudo docker info` here?

**Comment by Felitendo** [comment]
Client: Docker Engine - Community
 Version:    27.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 38
  Running: 31
  Paused: 0
  Stopped: 7
 Images: 46
 Server Version: 27.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-22-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.62GiB
 Name: rs-zap466398-2
 ID: d1eed8dd-b5a0-4fd4-9293-4d80d858ae8a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by Felitendo** [comment]
I guess that's a skill issue on my part then :/
