### ISSUE TITLE
If a user's quota is 0 B, they can't see the contents of folders shared with them.

### ISSUE THREAD

**Issue by Hyperspeed1313** [nextcloud/all-in-one#5088]
### Steps to reproduce
1. Create user with quota of 0 bytes (e.g. by using Guests add-on)
2. Share a folder containing files with that user
3. Log in as that user and attempt to access the shared folder
4. See nothing inside it

### Expected behavior 
User should see files within the shared folder

### Actual behavior 
User sees nothing. Interface says the folder is empty.

### Host OS 
Debian 12 Bookworm (inside Proxmox VE LXC)

#### Nextcloud AIO version 
v9.3.0

#### Current channel 
latest

#### Other valuable info 
By raising the quota to 100 MB and waiting a bit, then resharing the folder because changing the quota removed all shares to that user for some reason, I was able to restore the ability to view the shared folder's contents.

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/nextcloud/server/issues. Thanks!
