### ISSUE TITLE
Internal Server Error after Updates

### ISSUE THREAD

**Issue by norbjert** [nextcloud/all-in-one#5149]
### Steps to reproduce
1. Start and update the nextcloud-AIO after not using it for 2 months
2. Update all the containers
3. Log in with correct credentials

### Expected behavior 
The usual nextcloud welcome page opens

### Actual behavior 
"Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
"

### Host OS 
Raspian (on a RPi5)

#### Nextcloud AIO version 
Nextcloud AIO v9.4.1

#### Other valuable info 
![image](https://github.com/user-attachments/assets/c136785c-4b81-4f99-80ea-406feb40f24d)

Logs from the AIO Container: (none of the other container had any)
![image](https://github.com/user-attachments/assets/25a92139-5d9d-4cae-955c-c6d08f677491)

Also note that the login interface is fine, and if you enter incorrect creds it promtly rejects them. The timestamps from the Slim\Exception\HttpNotFoundException correlate with successful login attempts/requests to open the default starting page

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/all-in-one/discussions/5141#discussioncomment-10364959
