### ISSUE TITLE
163 Email cannot be used 

### ISSUE THREAD

**Issue by auxpd** [nextcloud/all-in-one#5165]
I also have this problem and it cannot be used when using the 163 mailbox.
{message: "mailbox 32 is not cached", type: "OCA\Mail\Exception\MailboxNotCachedException"}

ServiceException
Can not get messages from mailbox INBOX: Could not open mailbox "INBOX".

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/nextcloud/mail/issues
