### ISSUE TITLE
Fails to start when port 443 in use.

### ISSUE THREAD

**Issue by Timmmy** [nextcloud/all-in-one#52]
Container nextcloud-aio-domaincheck fails to start if port 443 is already in use on the host.
Any way to map this to another port?

**Comment by szaimen** [comment]
Sry but port 443 is required. See https://github.com/nextcloud/all-in-one#which-ports-are-mandatory-to-be-open

**Comment by Timmmy** [comment]
Ok, but be aware that this will prevent the container from running on a lot of NAS devices and configurations as they often already bind to 443

**Comment by szaimen** [comment]
Thanks for the feedback! Unfortunately port 443 or 80 are a requirement to get a valid certificate out of the box so this is likely nothing we can solve on our own. Having a way to get a valid certificate using another port would be exciting but there is none, as far as we know. See https://letsencrypt.org/docs/challenge-types/
