### ISSUE TITLE
aio-onlyoffice: Unable to change file size limitation (maxDownloadBytes)

### ISSUE THREAD

**Issue by jejbq** [nextcloud/all-in-one#5212]
### Steps to reproduce
1.  Install Nextcloud AIO
2. Enable OnlyOffice with << "isOnlyofficeEnabled": 1 >> in volumes/nextcloud_aio_mastercontainer/data/configuration.json
3. Upload a 233.2 MB PPTX in Nextcloud
4. Try to open the PPTX via OnlyOffice

### Expected behavior

- Be able to open and modify a 233.2 MB PPTX in OnlyOffice
- Be able to set a max file size via the Nextcloud AIO Admin web settings for OnlyOffice App <nextcloud-aio>/settings/admin/onlyoffice.
- Be able to fine tune OnlyOffice configuration via local.json or default.json in volumes/nextcloud_aio_onlyoffice or somewhere else

### Actual behavior

- Unable to open the PPTX in OnlyOffice

**The file size exceeds the limitation set for your server.**
**Please contact your Document Server administrator for details.**

**Press "OK" to return to document list.**
<OK>

### Workaround

I implemented a workaround but it's not persistent. This increase the max file size from 100M to 1G:
```
docker exec -it -w /etc/onlyoffice/documentserver $(docker ps --filter name=nextcloud-aio-onlyoffice -q) bash -c 'sed -i -e "s/104857600/1073741824/" default.json; supervisorctl restart all'
```

Based on
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/354#issuecomment-824678415

#### Host OS

Debian 12

#### Output of `sudo docker info`

Client: Docker Engine - Community
 Version:    27.1.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 17
  Running: 13
  Paused: 0
  Stopped: 4
 Images: 19
 Server Version: 27.1.2

#### Docker run command or docker-compose file that you used

The one launched by Nextcloud AIO Master Container

#### Other valuable info

nextcloud/aio-onlyoffice:latest (8 weeks ago, a94390b52086)
Please note that nextcloud/aio-onlyoffice:latest is derived directly from onlyoffice/documentserver:8.1.1.2
https://github.com/nextcloud/all-in-one/blob/main/Containers/onlyoffice/Dockerfile

Same issue reported to OnlyOffice DocumentServer 
https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/770

**Comment by szaimen** [comment]
Lets track this in https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/770

**Comment by jejbq** [comment]
> Lets track this in https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/770

This ticket is currently marked as "invalid" by them 
because you are maintaining your own docker image nextcloud/aio-onlyoffice
so if you close this ticket... nobody cares?!

Can you implement this?
Set a max file size via the Nextcloud AIO Admin web settings for OnlyOffice App <nextcloud-aio>/settings/admin/onlyoffice
so if they implement Docker config parameter ONLYOFFICE_MAX_DOWNLOAD_BYTES you will need to modify Nextcloud AIO "portainer"-like MasterContainer to pass a higher value. 

It will not help because nextcloud-aio does not mount docker volumes in following locations to persist config changes
- /etc/nginx/includes for ds-common.conf
- /etc/onlyoffice/documentserver for local.json and default.json

**Comment by szaimen** [comment]
As you saw, we are using their image. So if they expose this as a setting it will be available directly also in AIO.
We have no interest to further customize their image. You could maybe ask them to increase the default.
