### ISSUE TITLE
Collabora issue

### ISSUE THREAD

**Issue by piotr-sikora-v** [nextcloud/all-in-one#5255]
Hi
there was a bug in collabora fixed here: https://github.com/CollaboraOnline/online/issues/9948

But in Nextcloud AIO still exist, so some people have issue: https://github.com/nextcloud/all-in-one/discussions/5188
https://github.com/nextcloud/richdocuments/issues/4026

Can  you update version in of Collabora in Nextcloud-AIO?

Thanks in advanced

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/all-in-one/discussions/5188#discussioncomment-10633137
