### ISSUE TITLE
NC30: backup failes

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/all-in-one#5256]
After the update to NC and AIO 9.5.1 Beta the daily backup fail:

Logs
2024-09-13T04:01:24.420844894Z The .ocdata file is missing in Nextcloud datadir which means it is invalid!
2024-09-13T04:01:24.420928923Z Is the drive where the datadir is located on still mounted?

Thanks!

**Comment by szaimen** [comment]
Thanks for the report. Already on my radar with https://github.com/nextcloud/all-in-one/pull/5250

**Comment by ifedan-ed** [comment]
same here

**Comment by Rimos911** [comment]
same 

2024-09-15T10:08:34.612584234Z The .ocdata file is missing in Nextcloud datadir which means it is invalid!
2024-09-15T10:08:34.612657698Z Is the drive where the datadir is located on still mounted?

**Comment by br4yd** [comment]
Ah so it is a bug with the current version and should be fixed by an update but not something on my end? Already was confused because I didn't switch datadir's.

**Comment by Rimos911** [comment]
Is there a workaround to fix this or should we just wait for the patch? When will the update be released?

**Comment by szaimen** [comment]
It will be fixed in the next update. Until then a workaround is to create an .ocdata file inside the datadir.

**Comment by br4yd** [comment]
> It will be fixed in the next update. Until then a workaround is to create an .ocdata file inside the datadir.

Just an empty one? So `touch .ocdata`?

**Comment by szaimen** [comment]
Yes

**Comment by Rimos911** [comment]
where ist the "datadir" located - or do you mean the /nextcloud/ folder?

**Comment by br4yd** [comment]
@Rimos911 it is the directory specified in your Docker Compose file for AIO. There should be an environment variable with the path there.

**Comment by lukasig** [comment]
Same problem here with nextcloud-AIO running in docker, but I'm a bit of a noob. Can anyone give an example of terminal commands that can create the .ocdata file inside the datadir?
Thanks

**Comment by szaimen** [comment]
`sudo docker exec --user www-data -it nextcloud-aio-nextcloud touch /mnt/ncdata/.ocdata`

**Comment by amjedsaleel** [comment]
I am facing the same issue while trying to take the backup.

**Comment by szaimen** [comment]
See the command above for a temporary fix

**Comment by gael1980** [comment]
Meme problème depuis la migration vers NC30

**Comment by szaimen** [comment]
This is now fixed with v9.6.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by jakobroehrl** [comment]
Thanks for the quick fix, works well, tested. :)
