### ISSUE TITLE
About #323

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#526]
#323 

unfortunately does not work. 

Command:
-e NEXTCLOUD_MOUNT="/mnt/backup/"

Error message: 
-e: command not found

**Comment by szaimen** [comment]
https://github.com/nextcloud/all-in-one#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
![image](https://user-images.githubusercontent.com/42591237/164973225-6a3ddac1-a41b-470e-9d31-8e737625ef32.png)

**Comment by R7JANV1** [comment]
how can i achieve this?

**Comment by szaimen** [comment]
stop the mastercontainer, delete it and start it again with this additional environmental variable...

**Comment by R7JANV1** [comment]
where can I find the recommended procedure to start the master container again?😅

**Comment by szaimen** [comment]
I am nice today:
sudo docker stop nextcloud-aio-mastercontainer
sudo docker rm nextcloud-aio-mastercontainer
and then 
![image](https://user-images.githubusercontent.com/42591237/164973901-4e173f33-b80d-4335-8e62-579e6fb36b4a.png)
plus adding this environmental variable to the command (it must be inserted before the last line)

**Comment by R7JANV1** [comment]
many many thanks!
