### ISSUE TITLE
AIO not serving up-to-date Nextcloud image 

### ISSUE THREAD

**Issue by troed** [nextcloud/all-in-one#5267]
### Steps to reproduce
1. Use AIO
2. Update to latest master container
3. Notice the version of Nextcloud is behind the latest

### Expected behavior
AIO being the preferred installation method should contain the latest version of Nextcloud, especially when the communication around that version being that it contains security fixes.

### Actual behavior
When Nextcloud's official Mastodon account communicated version 29.0.7 being available, AIO was on 29.0.4. One day later AIO was updated, but the version of Nextcloud is still only 29.0.6.

#### Host OS
Linux

#### Docker run command or docker-compose file that you used
services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed

#### Other valuable info 

https://ioc.exchange/deck/@troed/113129642997707469

**Comment by szaimen** [comment]
Hi, the 29.0.7 update will be available with the next aio update: https://github.com/nextcloud/all-in-one/pull/5259
