### ISSUE TITLE
Calendar app never initialises completed - constant spinning on calendars

### ISSUE THREAD

**Issue by mikebakke** [nextcloud/all-in-one#5276]
### Steps to reproduce
1. download and enable calendar app from store
2. select calendar from application bar

### Expected behavior 
Calendar should load and allow entries

### Actual behavior 
The calendar entries on the sidebar just show constant spinning - if I try to enter an appointment the dialog works as expected but the entry is never displayed after clicking save

### Other information
The app used to work - this is a mature instance. I have an identical instance for a different domain which works correctly. Same host environment, same NC level (29.0.6). After noticing the spinning, I tried to disable/remove/add but the spinning remains. Everything else works fine

Exec into instance and issue OCC looks fine:
128beb82b29b:/var/www/html# sudo -u www-data php occ dav:list-calendars mike

Warning: Failed to set memory limit to 0 bytes (Current memory usage is 2097152 bytes) in Unknown on line 0
The current PHP memory limit is below the recommended value of 512MB.
+--------------+--------------+-----------------------+---------------------+----------+
| uri          | displayname  | owner's userid        | owner's displayname | writable |
+--------------+--------------+-----------------------+---------------------+----------+
| appointments | Appointments | principals/users/mike | Mike                |  ✓       |
| tasks        | Tasks        | principals/users/mike | Mike                |  ✓       |
| personal     | Personal     | principals/users/mike | Mike                |  ✓       |
+--------------+--------------+-----------------------+---------------------+----------+

I am sure this is not a "global" AIO bug - must be related to my instance, really looking for ideas to avoid having to re-install everything from scratch...

**Comment by mikebakke** [comment]
Logs etc:
![2024-09-17 08 35 53 aio b3lt3r com c796da9d6c17](https://github.com/user-attachments/assets/79e144a4-8328-4a9c-ab6c-b46273158c84)
![2024-09-17 08 34 23 aio b3lt3r com 534a4766df63](https://github.com/user-attachments/assets/9ef40ee6-48eb-4f02-bd32-f8acb352aca6)

**Comment by mikebakke** [comment]
[nextcloud.log](https://github.com/user-attachments/files/17024910/nextcloud.log)

**Comment by mikebakke** [comment]
[nextcloud1.log](https://github.com/user-attachments/files/17024953/nextcloud1.log)

**Comment by szaimen** [comment]
Hi, please open a bug report for this at https://github.com/nextcloud/calendar/issues. Thanks!

**Comment by mikebakke** [comment]
I will indeed - just had a quick look there and seem multiple similar issues open for many years so not optimistic.

Before heading off I did a comparison between the working and failing instance looking in the browser console. In the working I see no errors when the calendar is selected. In the failing instance I see 404 which seem to be complaining about the WEBDAV server - is this from plugin or core?
calendar home scanned Array(5) Array(1) Array(0)
/remote.php/dav/calendars/mike/personal/:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:612  Error
    at o.onreadystatechange (dist.js:2:17483)
(anonymous) @ index.js:612

If I select the webdav link from the settings on working side and open a browser I get a sign-in dialog as expected, doing the same on failing side I get:
nternal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: 192.168.100.6
    Request ID: OQsgkCk3TZSpNdXJljF

and the log shows:

Error | remote | Forbidden Requested uri (/remote.php/dav?) is out of base uri (/remote.php/dav/)
-- | -- | --

In both instances the URL used is https://domain.com/remote.php/dav

This seems to me that webdav is not configured correctly in the failing side but appreciate your view if core or plugin

Many thanks
