### ISSUE TITLE
Convert Readme to Github Wiki

### ISSUE THREAD

**Issue by Joly0** [nextcloud/all-in-one#5278]
### Is your feature request related to a problem? Please describe. 

Currently, everything really important for nextcloud-aio is found in the readme, which makes finding a solution not so easy, because the size grew quite large and there are alot of different topics now all in the same file.
### Describe the solution you'd like

Remove everything that belongs into a wiki (so nearly everything under https://github.com/nextcloud/all-in-one?tab=readme-ov-file#faq) and create a github wiki for all the different topics.
### Describe alternatives you've considered

Different .md files for the different topics in a "docs" folder

**Comment by Zoey2936** [comment]
You may read here: https://github.com/nextcloud/all-in-one/discussions/826

**Comment by Joly0** [comment]
Thanks, didnt see that

**Comment by szaimen** [comment]
> #826

Indeed, lets continue there
