### ISSUE TITLE
Issue with Loading App Updates - "Could not load app discover section"

### ISSUE THREAD

**Issue by vawaver** [nextcloud/all-in-one#5316]
**Subject:** Issue with Loading App Updates - "Could not load app discover section" on Nextcloud AIO 9.5.1 (29.0.6)

Hello,

I am using Nextcloud AIO version 9.5.1 (29.0.6) running on a server with 15 GB RAM and a 12-core CPU, using Ubuntu server 24.04. When I try to access the Apps section, the list of app updates doesn't load, and I receive the error message: "Could not load app discover section."

To resolve this issue, I have already recreated all the Docker containers, but this did not help.

Does anyone have suggestions on how to fix this issue? 
Any guidance would be greatly appreciated.

![discover-section-issue](https://github.com/user-attachments/assets/9b980ecd-c9e5-472c-9e35-e428374215ae)

**Comment by szaimen** [comment]
Hi, see https://help.nextcloud.com/t/discover-section-of-the-app-store-not-working/204688
