### ISSUE TITLE
collabora: uncompressed request fails 

### ISSUE THREAD

**Issue by leon1995** [nextcloud/all-in-one#5352]
when making an uncompressed request to a translation library of collabora, in my example `/browser/d5ebff5/l10n/help-de.json` and `/browser/d5ebff5/l10n/uno/de-override.json` it fails with `transfer closed with outstanding read data remaining`
https://github.com/ZoeyVid/NPMplus/discussions/1127#discussioncomment-10801456

### Steps to reproduce
1. https://github.com/ZoeyVid/NPMplus/discussions/1127#discussioncomment-10801450

### Expected behavior 
should work uncompressed

### Actual behavior 
connection is closed

#### Host OS 
debian12

#### Output of `sudo docker info`
[see related forum post](https://help.nextcloud.com/t/translation-of-languages-takes-ages-to-load/205128)

#### Other valuable info 
https://github.com/ZoeyVid/NPMplus/discussions/1127

**Comment by Zoey2936** [comment]
And this is the error caddy throws:
```
2024/10/01 08:19:57.185 ERROR   http.handlers.reverse_proxy     reading from backend    {"error": "unexpected EOF"}
2024/10/01 08:19:57.187 ERROR   http.handlers.reverse_proxy     aborting with incomplete response       {"upstream": "127.0.0.1:9980", "duration": 0.002892976, "request": {"remote_ip": "::1", "remote_port": "54630", "client_ip": "::1", "proto": "HTTP/2.0", "method": "GET", "host": "localhost", "uri": "/browser/d5ebff5/l10n/help-de.json", "headers": {"X-Forwarded-Proto": ["https"], "X-Forwarded-Host": ["localhost"], "User-Agent": ["curl/8.10.1-DEV"], "Accept": ["*/*"], "X-Forwarded-For": ["::1"]}, "tls": {"resumed": false, "version": 772, "cipher_suite": 4865, "proto": "h2", "server_name": "localhost"}}, "error": "reading: unexpected EOF"}
```

**Comment by szaimen** [comment]
Hi, thanks for the report!

> The error seems to be collabora

Shouldn't this then rather be reported to collabora? I am not sure how we can improve AIO to fix this?

**Comment by Zoey2936** [comment]
I think collabora should be correct yes, but temporary we could configure to just respond with {}, like the broken request would do compressed, so the client loads faster

**Comment by szaimen** [comment]
I see. Honestly, I am not a huge fan of adding temporary workarounds that might end up being there for a long time or causing issues on itself. So in my opinion, the best and fastest way fixing this correctly is to create an issue at  https://github.com/CollaboraOnline/online/

**Comment by leon1995** [comment]
I submitted an issue in collabora https://github.com/CollaboraOnline/online/issues/10157

**Comment by szaimen** [comment]
> I submitted an issue in collabora [CollaboraOnline/online#10157](https://github.com/CollaboraOnline/online/issues/10157)

Thanks! Lets continue there then
