### ISSUE TITLE
Add option to exclude data files from backups

### ISSUE THREAD

**Issue by chriswoope** [nextcloud/all-in-one#537]
It would be nice to be able to easily exclude data from backups (and reinclude it).

Data can be huge, and might already be backed up with other means, and including it in backups can dramatically increase the size of backups, potentially to more than the available disk space.

Also, currently automatic updates are tied to backups, so not being able to exclude data from backups might make it impossible for someone to use the backup feature and thus also make it impossible for them to use automatic updates.

**Comment by szaimen** [comment]
Hello, please see the discussion in https://github.com/nextcloud/all-in-one/discussions/428#discussioncomment-2496070
Thanks!

**Comment by szaimen** [comment]
I don't see the point. When you have a backup solution in place just use that. We don't require to use the built-in one :)

**Comment by szaimen** [comment]
You are right. Automatic updates are bound to backups. You did not say that in your message so that was not clear to me :)

**Comment by szaimen** [comment]
However restoring the instance from backup (using the aio interface) when using these tags will not work as expected. That is one of the reason why I think using these tags is not a good idea
