### ISSUE TITLE
Save changes button not showing when initially enabling Whiteboard container

### ISSUE THREAD

**Issue by rvjr** [nextcloud/all-in-one#5378]
### Steps to reproduce
1. Update AOI from 9.5.1 to 9.6.0 (no Whiteboard container yet)
2. Stop Containers
3. Tick 'Whiteboard' in 'Optional Containers'

### Expected behavior

Save button should show.

### Actual behavior

Save button didn't show up. I had to disable/enable other container checkboxes, then the button appeared and I could save and install 'Whiteboard' this way.

![Image](https://github.com/user-attachments/assets/71e0e7a3-ae8b-4446-9926-b2d5fc6894bb)

### Other information
Host OS: Debian 11.2

Disabling 'Whiteboard' now that it is installed seems to show the 'Save' button now.

**Comment by szaimen** [comment]
Hi, this is a cache issue. Clearing the browser cache should make it work. We have a fix in https://github.com/nextcloud/all-in-one/pull/5379

**Comment by szaimen** [comment]
This is now fixed with v9.7.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
