### ISSUE TITLE
it is not possible to open files from federation shares (pdf, png, office documents)

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/all-in-one#5381]
### Steps to reproduce
1. Share a group folder on the source server
2. accept the share on the target server
3. navigate to the shared directory
4. try to open a document - nothing happens

### Expected behavior 

document should be opened 

### Actual behavior 

stalls

### Other information

Nextcloud AIO v9.6.0

#### Host OS 
Linux version 6.8.0-45-generic (buildd@lcy02-amd64-115) (x86_64-linux-gnu-gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0, GNU ld (GNU Binutils for Ubuntu) 2.42) #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024

#### Output of `sudo docker info`
Client: Docker Engine - Community
 Version:    27.1.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 15
  Running: 13
  Paused: 0
  Stopped: 2
 Images: 29
 Server Version: 27.1.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-45-generic
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.25GiB
 Name: nc-aio
 ID: c1aa57b2-9ab5-4b61-a67f-ff2a830f4b96
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by Maximilian-Maag** [comment]
I can't reproduce this error with the above mentiod settings.
After testing this failure on a remote server everything worked fine. It seams to me network config is interfering some how.

**Comment by ferdiga** [comment]
{"reqId":"0pk2ZWGVMcfYY3ehxkLz","level":3,"time":"2024-10-05T18:31:06+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"gass","app":"richdocuments","method":"POST","url":"/apps/richdocuments/token","message":"Failed to generate token for file","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","version":"29.0.7.1","exception":{"Exception":"Exception","Message":"Unable to determine collabora URL of remote server https://nxyyyyy.your-storageshare.de - Remote is not a trusted server","Code":0,"Trace":

appartently there is an issue with the trusted server

both sides have the other serve configured as trusted.

whereas one has a green dot - the other a brown "box"  - if this is of any significance - but certainly not explained

![Image](https://github.com/user-attachments/assets/a98db5b0-2133-4863-b4fe-1dec8d2b262f)

**Comment by ferdiga** [comment]
BTW the document is in a shared group folder

**Comment by unfixa1** [comment]
Make sure there are no problems with the network configuration, volume mounting, etc. of the Docker container. You can try restarting the Docker service or container.
Or it is recommended that you use[ Servbay](servbay.com) to replace Docker to deploy the development environment. Servbay has fewer bugs.

**Comment by ferdiga** [comment]
It's a Hetzner issue
opening documents on federates shares on 2 Hetzner NC Services does not work , where as opening the document on the source server(s) work

**Comment by szaimen** [comment]
> It's a Hetzner issue

All right. Then how should we fix this in AIO? Please report this to https://github.com/nextcloud/server/issues
