### ISSUE TITLE
Error, when setting "TALK_PORT" env variable

### ISSUE THREAD

**Issue by HeldvonKosmos** [nextcloud/all-in-one#5386]
I need to modify the talk_port, because my reverseproxy doesn't support the default port (3478) for udp.

I have already tried to change it inside the aio-talk docker container, but can't get root permissions and the filesystem is readonly.

So when i change the TALK_PORT to a different one i got this error log 

"Message: Could not start container nextcloud-aio-talk: Server error: `POST http://127.0.0.1/v1.41/containers/nextcloud-aio-talk/start` resulted in a `500 Internal Server Error` response:
{"message":"driver failed programming external connectivity on endpoint nextcloud-aio-talk (923f17854a9d6a0dfd252827c66f (truncated...)
File: /var/www/docker-aio/php/src/Docker/DockerActionManager.php"

I think it is not necessary to modify the internal port of the talk container.

"  nextcloud-aio-talk:
    image: nextcloud/aio-talk:latest
    init: true
    ports:
      - ${TALK_PORT}:${TALK_PORT}/tcp
      - ${TALK_PORT}:${TALK_PORT}/udp"

I think the internal port can be leaved as default and the outside port can be changeable.

Or does nextcloud use the internal port of talk container inside the docker network?

Thanks in advance!

Jonas

**Comment by szaimen** [comment]
Hi, please post the docker-compose file or docker run command that you used here and also post the output of `sudo netstat -tulpn` here. Thanks!

**Comment by HeldvonKosmos** [comment]
Hi, i wanted to change the port of talk container, but it wasn't necessery.
The problem was that Traefik can't listen on the talk containers default port from the outside.
But i will try my luck further on with this:
https://hub.docker.com/r/strukturag/nextcloud-spreed-signaling
I use self signed certificates with Traefik, because it will be used in the intranet.
