### ISSUE TITLE
NC 29 Web files app inaccessible and client stuck at syncing changes

### ISSUE THREAD

**Issue by romi1996** [nextcloud/all-in-one#5452]
### Steps to reproduce
1. Prepare few thousand files to folder in nextcloud client
2. Restart NC AIO, including wsl --shutdown command
3. Wait for sync and eventually it will stuck and make files app web inaccessible, other function work normally

### Expected behavior 
Should work normally
### Actual behavior 
Client stuck, web files app inaccessible, can only resolved for short time when shut down wsl and restart.

#### Host OS 
Windows 10 x64 Docker Desktop
Operating System: Linux 5.15.133.1-microsoft-standard-WSL2 x86_64
CPU: Intel(R) Xeon(R) CPU E5-2696 v3 @ 2.30GHz (36 threads)
Memory: 15.57 GB
Server time: Mon Oct 21 18:13:25 +07 2024
Uptime: 0 hours, 32 minutes, 21 seconds

#### Output of `sudo docker info`
Client:
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.32
    Path:     /usr/local/lib/docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.24
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /usr/local/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.2.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.9.3
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout
WARNING: Plugin "/usr/local/lib/docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 22
  Running: 17
  Paused: 0
  Stopped: 5
 Images: 37
 Server Version: 26.1.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 36
 Total Memory: 15.57GiB
 Name: docker-desktop
 ID: c9cc6fd4-daf0-4fe7-9907-afa9bb74cfd6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///var/run/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile

#### Docker run command or docker-compose file that you used
docker run ^
--init ^
--sig-proxy=false ^
--name nextcloud-aio-mastercontainer ^
--restart always ^
--publish 80:80 ^
--publish 8080:8080 ^
--publish 8443:8443 ^
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config ^
--volume //var/run/docker.sock:/var/run/docker.sock:ro ^
--env SKIP_DOMAIN_VALIDATION=true ^
--env NEXTCLOUD_MEMORY_LIMIT=2048M ^
--env PHP_MEMORY_LIMIT=2048M ^
--env NEXTCLOUD_DATADIR="/run/desktop/mnt/host/e/" ^
--env NEXTCLOUD_MOUNT="/run/desktop/mnt/host/" ^
--env NEXTCLOUD_ENABLE_DRI_DEVICE=true ^
nextcloud/all-in-one:latest
#### Other valuable info 
- Docker desktop runs as Administrator
- Run behind nginx proxy (non tunnel)
- Load average very high
- While having problems, the CPU no load, and memory still free
- Currently bypassed throttle
- No error or fatal registered from possible known source
![Image](https://github.com/user-attachments/assets/777cfb57-0819-446b-9899-3e6ea0ccaf95)
![Image](https://github.com/user-attachments/assets/5c73840b-4f01-4810-bdf6-231ded1299c2)
![Image](https://github.com/user-attachments/assets/53ac9e5e-7198-445e-a8c4-dc6dec0a19e3)

**Comment by szaimen** [comment]
Hi, please open a thread for this at https://help.nextcloud.com/. Thanks!
