### ISSUE TITLE
add a fast lane for the Nextcloud container

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#546]
listen on the update server. when a new version is published there trigger a commit that updates the nc version, builds new containers and updates only the Nc container directly to latest.
Maybe there should be a way to only publish the changes since the latest release. Possibly untested changes should not be released then.

**Comment by szaimen** [comment]
so basically the simplest but maybe also a hacky way would be triggering a bot upon a new release that uses the currently latest nextcloud container, substitutes the Nextcloud archive inside the image and pushes it to dev, beta and latest.

**Comment by marcatsmci** [comment]
Maybe wait for a few days before push on latest to give time to check is there are not to many bugs in the NC new container ?

**Comment by marcatsmci** [comment]
> This is not about pushing major Nextcloud update to latest but instead for minor Nextcloud updates :)

I think so ;-) But even in little upgrades there are troubles, sometimes...

**Comment by szaimen** [comment]
okay, good point. will discuss this with my colleagues.

**Comment by szaimen** [comment]
the idea was canceled. It will be handled differently.
