### ISSUE TITLE
Refactor compose.yaml to include config for caddy

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#5469]
Refactor compose.yaml to include config for caddy

**Comment by szaimen** [comment]
@Zoey2936 I've never worked with inline configs in docker compose yaml. Do you know how that works?

**Comment by szaimen** [comment]
Maybe @flll has some knowledge about this as well?

**Comment by flll** [comment]
Simply uncommenting everything and making it inline won't ensure proper functionality. It's better to prepare various compose.yml files for different cases, such as deploying directly to the host port, high-performance setups, lightweight setups, Tailscale setups, etc.
Alternatively, you could develop a new tool that generates a compose.yml file automatically by asking questions in a shell script to determine the intended use.

**Comment by szaimen** [comment]
> Simply uncommenting everything and making it inline won't ensure proper functionality.

I agree.

We currently describe the recommended caddy deployment in the compose.yaml. I would like to update it to also have inline config: https://github.com/nextcloud/all-in-one/blob/997b986dfe25c2ce59105760658d901f975b8f1a/compose.yaml#L36-L48 and  maybe also switch to docker volumes for the different caddy configs so that it works most of the time.



> It's better to prepare various compose.yml files for different cases, such as deploying directly to the host port, high-performance setups, lightweight setups, Tailscale setups, etc.
> Alternatively, you could develop a new tool that generates a compose.yml file automatically by asking questions in a shell script to determine the intended use.

I fear both options are out of scope for AIO itself due to the additional maintenance burden, however the community is of course free to do whatever they want 😉

**Comment by flll** [comment]
> We currently describe the recommended caddy deployment in the compose.yaml. I would like to update it to also have inline config

I think it would be better to just include a URL to a guide for building a reverse proxy. If we leave it as is for inline use, people might misunderstand and think it will work as-is. It might be better to simply remove the Caddy section for clarity.

---

> additional maintenance burden

You're right. Instead of using a shell script, it might be better to include a complete compose.yml in the reverse proxy guide, making it easier to reference.
