### ISSUE TITLE
Let workflow_pdf_converter  work in Nextcloud AIO

### ISSUE THREAD

**Issue by mcwimh** [nextcloud/all-in-one#5526]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

I really would like this feature to work in the Nextcloud AIO.
I think because Collabora is in a seperate docker container, that's the reason it doesn't work, because there is no connection with LibreOffice

**Which Nextcloud Version are you currently using:** (see administration page)

Nextcloud 30.0.1

**Is your feature request related to a problem? Please describe.**

The problem is that it's not working yet.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by szaimen** [comment]
Okay, I give up. As apparently combining https://github.com/nextcloud/workflow_pdf_converter?tab=readme-ov-file#nextcloud-pdf-converter-app with https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-add-os-packages-permanently-to-the-nextcloud-container is not easy enough for people. I'll add the binary by default.

**Comment by szaimen** [comment]
This is now released with v9.9.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
