### ISSUE TITLE
Cannot restore from remote BorgBackup

### ISSUE THREAD

**Issue by michaelfliegner** [nextcloud/all-in-one#5589]
### Steps to reproduce
![image|527x500](upload://s6HCChUkgQmTSTFxfwoa6B88opJ.png)

I configured remote backup, succeed in creating a backup, but am stuck on this page. Besides no backups are selectable for restore.

Clicking the restore button anyway leads, as could be expected - to an error:
>
2024-11-13T16:09:17.449458074Z Your public ssh key for borgbackup is: 
...
2024-11-13T16:09:19.040113624Z Restoring ''...
2024-11-13T16:09:19.436010445Z usage: borg extract [-h] [--critical] [--error] ....
2024-11-13T16:09:19.436082941Z borg extract: error: argument ARCHIVE: "::": No archive specified
2024-11-13T16:09:19.461490620Z Failed to extract backup archive.
> Blockzitat

The page then displayed is misleading:
![Screenshot 2024-11-13 17.18.09|632x500](upload://iO3NOQ6effHZM80a31bGFZ004AC.png)
#### Host OS 
Ubuntu 24.04
#### Output of `sudo docker info`
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 2
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-48-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.709GiB
 Name: ubuntu
 ID: 982fcbcd-4344-455f-93d1-8c499dec1fad
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by michaelfliegner** [comment]
My fault ... : My homemade solution
took remote backups from my
**backup director y**.
No wonder AIO cannot find backups to restore  in the repository.
What's left is a missing condition on the restore button, that the restore list be non-empty.

**Comment by szaimen** [comment]
> What's left is a missing condition on the restore button, that the restore list be non-empty.

I have a different fix in mind. See https://github.com/nextcloud/all-in-one/pull/5590
