### ISSUE TITLE
NEXTCLOUD_DATADIR variable not working

### ISSUE THREAD

**Issue by hunterwinterton** [nextcloud/all-in-one#560]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Use provided docker command
2. Add -e NEXTCLOUD_DATADIR="/host_mnt/volume1/docker/nextcloud/data"

### Expected behavior 
Container should start up and use the folder I provided to store data
### Actual behavior 
You've set NEXTCLOUD_DATADIR but not to an allowed value.
The string must start with '/mnt/', '/media/' or '/host_mnt/'. E.g. '/mnt/ncdata'

### Host OS 
Synology DSM 7.1

#### Nextcloud AIO version 
latest
#### Other valuable info 
My docker command:
sudo docker run -it \
--name nextcloud-aio-mastercontainer \
--restart always \
-p 8080:8080 \
-e APACHE_PORT=11000 \
-e NEXTCLOUD_DATADIR=“/host_mnt/volume1/docker/nextcloud/data \
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
--volume /var/run/docker.sock:/var/run/docker.sock:ro \
nextcloud/all-in-one:latest

**Comment by szaimen** [comment]
Hello, the check is indeed working correctly. You have a nasty typo ín your docker run command.
This one should work:
```
sudo docker run -it
--name nextcloud-aio-mastercontainer
--restart always
-p 8080:8080
-e APACHE_PORT=11000
-e NEXTCLOUD_DATADIR="/host_mnt/volume1/docker/nextcloud/data"
--volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config
--volume /var/run/docker.sock:/var/run/docker.sock:ro
nextcloud/all-in-one:latest
```

We'll try to improve the output though so that debugging is easier.

**Comment by njakes** [comment]
I am also having trouble with this same issue. I have set the correct permissions according to the docs but it wont detect mine either.  The current line is
      `- NEXTCLOUD_DATADIR="/mnt/jacobs-media/nextcloud-aio/ncdata"`

The log output is a constant cycle of this:
You've set NEXTCLOUD_DATADIR but not to an allowed value.
The string must start with '/mnt/', '/media/' or '/host_mnt/'. E.g. '/mnt/ncdata'

I have my RAID mounted to /mnt/jacobs-media which contains all of my files for plex, audiobookshelf, photoprism and nextcloud in different folders.  Can you give some insight as to what I am doing wrong here? I use portainer for my docker setup and have tried to add the environment variables through their own settings.  That will allow the install to run normally but doesn't seems to not apply the data dir location.

**Comment by szaimen** [comment]
Debugging becomes easier as soon as https://github.com/nextcloud/all-in-one/pull/561 is released
