### ISSUE TITLE
local-ai readme update, depericated URL listed

### ISSUE THREAD

**Issue by ShapeShifter499** [nextcloud/all-in-one#5602]
### Is your feature request related to a problem? Please describe. 

No issue, just noticed that my setup of local-ai was no longer fetching a model for 'gpt4all-j'

### Describe the solution you'd like

Fix documentation

### Additional context

Per the suggested github repository in the readme for the local-ai container: https://github.com/nextcloud/all-in-one/blob/main/community-containers/local-ai/readme.md

```Note: this Repository is deprecated. The model gallery has now moved to https://github.com/mudler/LocalAI/tree/master/gallery and is configured by default in LocalAI.``` https://github.com/go-skynet/model-gallery/tree/main?tab=readme-ov-file#note-this-repository-is-deprecated-the-model-gallery-has-now-moved-to-httpsgithubcommudlerlocalaitreemastergallery-and-is-configured-by-default-in-localai

The URL suggested should be updated to the new location.

**Comment by szaimen** [comment]
Hi, thanks for the post. Would you mind crearing a PR to update the docs? :)
