### ISSUE TITLE
Increase upload file size to 16G by default

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#5611]
See https://github.com/nextcloud/server/pull/49372

**Comment by skjnldsv** [comment]
It's not a nc31 recommendation, t's been like that for years.

**Comment by szaimen** [comment]
> It's not a nc31 recommendation, it's been like that for years.

The default in aio is currently set to 10G so need to adjust it for nc31...

**Comment by szaimen** [comment]
> Then change the default to 16 for 28+ ? 😁

Why that? Isnt the setupcheck a new feature and thud only for 31?

**Comment by skjnldsv** [comment]
I'm planning to backport it.
But it doesn't matter, it's better to follow our own guidelines, the 16G was there before I added the setup check.

**Comment by szaimen** [comment]
> I'm planning to backport it. But it doesn't matter, it's better to follow our own guidelines, the 16G was there before I added the setup check.

I didnt know that 16G is our recommended default until today. So fine by me to adjust it even before nc31 ;)
See https://github.com/nextcloud/all-in-one/pull/5613

**Comment by szaimen** [comment]
This is now released with v10.1.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
