### ISSUE TITLE
Change placeholder for Borg remote Repo

### ISSUE THREAD

**Issue by hartmann-daniel** [nextcloud/all-in-one#5680]
### Steps to reproduce
1. Start a clean Nextcloud AIO Container
2. The placeholder for the Borg remote path is misleading because the ssh:// is missing.

#### Other valuable info 
I recommend to add "ssh://" to the Placeholder in File php/templates/containters.twig Line 199.

Thank you for your work on the Borg Remote project!

**Comment by szaimen** [comment]
Cc @timdiels

**Comment by timdiels** [comment]
Agreed, this should start with `ssh://`

**Comment by timdiels** [comment]
@szaimen I took the liberty of updating the labels.

**Comment by hartmann-daniel** [comment]
Thank you

**Comment by szaimen** [comment]
This is now released with v10.1.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
