### ISSUE TITLE
Doesn't work with port mapping (Apache)

### ISSUE THREAD

**Issue by Myridium** [nextcloud/all-in-one#57]
Running with
```
docker run -it --name nextcloud-aio-mastercontainer --restart always -p 97:80 -p 8097:8080 -p 8460:8443 -p 460:443 -p 3495:3478 --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config --volume /var/run/docker.sock:/var/run/docker.sock:ro nextcloud/all-in-one:latest
```
and configuring the local reverse proxy accordingly, I end up with an `Internal error (specific information not available)` when I try to access the server.

Has anyone gotten this working with Apache port mapping?

**Comment by szaimen** [comment]
Yes, unfortunately is port 443 required. See https://github.com/nextcloud/all-in-one#which-ports-are-mandatory-to-be-open
