### ISSUE TITLE
update to alpine v3.21

### ISSUE THREAD

**Issue by Zoey2936** [nextcloud/all-in-one#5706]
See: https://alpinelinux.org/posts/Alpine-3.21.0-released.html (upstream docker images are not updated yeet on 05.12.2024)
I think the update for AIO will happen with release of v3.21.1 as always. There should be no breaking changes for AIO.

**Comment by szaimen** [comment]
Actually, this time I am thinking about upgrading with .0 already because it will fix quite a lot of small annoyances. Wdyt about this idea?

**Comment by Zoey2936** [comment]
Should be fine, it doesn't seem like there are breaking changes affecting AIO

**Comment by szaimen** [comment]
This is now released with v10.2.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
