### ISSUE TITLE
Update message

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/all-in-one#572]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Create document (at the bottom of the document this message is displayed)

### Expected behavior 
nothing

### Actual behavior 
Collabora shows users update available even if AIO does not provide update. Please hide this note completely for users because they can not influence it (only the admin(s)).

#### Nextcloud AIO version 
latest

#### Current channel 
stable

#### Other valuable info 
![grafik](https://user-images.githubusercontent.com/90777102/166977663-b97b434b-d839-4e82-b362-f64e92357158.png)

**Comment by szaimen** [comment]
Hello, we will update the container with the new release.

**Comment by R7JANV1** [comment]
And remove the message completely? because the problem will occur again with the next Collabora update. The result will be confused users😅.

**Comment by szaimen** [comment]
How can we remove that message?

**Comment by R7JANV1** [comment]
Unfortunately, I have no idea. Do you have one?

**Comment by szaimen** [comment]
nope

**Comment by R7JANV1** [comment]
> Hello, we will update the container soon.

NC 24.0.1 is out when can we expect the update?

**Comment by szaimen** [comment]
I'll create an issue to track what is missing for a release.

**Comment by szaimen** [comment]
update message should be gone with 1.7.1 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
