### ISSUE TITLE
Setting environment variables for child containers

### ISSUE THREAD

**Issue by ggzengel** [nextcloud/all-in-one#5753]
If a host is compromised, a proxy server for external logging is essential.

There is a half implementation for proxy configuration like shown here: #5634 
But this is only working in nextcloud-aoi-mastercontainer or for PHP in child containers if using `proxy` in config.php.
But it should work for apk, curl and other executables in child containers.

It make no sense to commit #5093 but ignoring #3829.

I expect there are other environment variables needed for child containers.

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/all-in-one/discussions/3830#discussioncomment-7681045

**Comment by ggzengel** [comment]
This is really cheap if you don't keep this as a feature request.
I had to open the firewall now. Why?
