### ISSUE TITLE
Incompatible "NEXTCLOUD_DATADIR" option limits for macOS.

### ISSUE THREAD

**Issue by oesni** [nextcloud/all-in-one#576]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
I'm trying to install nextcloud-aio on my m1 mac mini running macOS 12.2.1
Since macOS doesn't have directory such as `/mnt` or `/media` and root is read-only by default(It is mandatory to disable macos [SIP](https://support.apple.com/en-us/HT204899) to write to `/` which is not recommended).
Hence, It is not possible to export nextcloud's data dir to host and to use external storage to save data. (I want to save my data on external storage array)

### Expected behavior 
change the default location of Nextcloud's Datadir

### Actual behavior 
Not possible on macOS.

### Host OS 
macOS 12.2.1 (Apple Silicon)

#### Nextcloud AIO version 
v1.1.0
#### Current channel 
latest-arm64
#### Other valuable info 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/19154301/167093786-a179b00f-7161-4dc0-84df-5dad360d668d.png">

**Comment by szaimen** [comment]
Which path would be needed for macos?

**Comment by szaimen** [comment]
And are you sure that allowing another location will solve this problem? If I read correctly, there is no way around disabling SIP if the program is not signed by apple...

**Comment by oesni** [comment]
Actually, It is possible to [disable SIP](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection). But anyway, If NEXTCLOUD_DATADIR accept path under the `/var` (like `/var/nextcloud-data`), there is no need to disable SIP :).
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/19154301/167097054-803e90f4-ac90-4db7-a680-942c074180c8.png">

**Comment by szaimen** [comment]
Can you post the output of `sudo ls -l /var` please?
I need to see which folders are inside by default...

**Comment by szaimen** [comment]
Also are there other paths then /var in the root directory that are writeable by default?

**Comment by oesni** [comment]
`/var`
<img width="761" alt="image" src="https://user-images.githubusercontent.com/19154301/167099344-c9fb1e0c-96cf-491c-a7ae-be3d0f9994ba.png">
`/`
<img width="912" alt="image" src="https://user-images.githubusercontent.com/19154301/167099594-0b9601c7-5fd6-4dda-808d-0210e398dcee.png">
According to [Apple](https://support.apple.com/en-us/HT204899),  `/System`, `/usr`, `/bin`, `/sbin`, `/var` and Apps that are pre-installed with OS X. 🤔(I think is doc is published at the time when SIP is introduced, So things could be changed now.)
and said third-party apps can continue to write to `/Application`, `/Library`, `/usr/local`.

Not 100% sure, but `/usr/local` or `/opt` might be the suitable path for 3rd party applications. (Cause other mac applications - like brew or macports ... - usually use that path.

**Comment by szaimen** [comment]
I see. We'll rework this to not enforce specific values anymore.
