### ISSUE TITLE
External Storage Mounts showing UTC times instead of Local Times

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/all-in-one#621]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create an External Storage Mount to a remote FTP server
2. Create a file in the External Storage mount folder
3. Observe the time on the newly created file, being UTC while all other files outside the mount are local time.

### Expected behavior 
Time of a new file should match the local timezone

### Actual behavior 
Time of a new file is stored as UTC

### Host OS 
Ubuntu 20.04

#### Nextcloud AIO version 
1.1.0

#### Current channel 
Current

#### Other valuable info 
The timestamp on the FTP server matches the correct time and the timezone on the FTP server is set to local time zone
The timezone where AIO is set to the correct timezone

**Comment by szaimen** [comment]
I supppose this will need a lot of work because the only way I could think of how to make it work is by providing an input field for this where the user can enter your timezone in the AIO interface.

**Comment by johnnyq** [comment]
@szaimen This may be due to the docker containers using UTC as the timezone maybe linking the docker containers to the host /etc/timezone would be an easier solution?

**Comment by szaimen** [comment]
> This may be due to the docker containers using UTC as the timezone maybe linking the docker containers to the host /etc/timezone

Yes, I think so as well but this is not a solution for auto-deployments where you probably do not want to change the timezone via command line but instead via the aio interface...

**Comment by johnnyq** [comment]
that makes sense I do like the idea having it available via the web UI

**Comment by szaimen** [comment]
Somethin like this is probably useful: https://timezonedb.com/download

**Comment by szaimen** [comment]
needs tzdata:
- nextcloud
- clamav
- collabora

**Comment by szaimen** [comment]
Hello, this is now released with 1.3.0 Beta. Feel free to try it out and report back! Thank you! :)
See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
