### ISSUE TITLE
Fix password copy for Firefox

### ISSUE THREAD

**Issue by tovrstra** [nextcloud/all-in-one#638]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Follow setup and install instructions for v1.2.0 (on Rocky Linux 8.5)
2. Enter hostname and wait for containers to be installed
3. Try to log in with initial admin credentials

### Expected behavior 

Login works

### Actual behavior 

Login failes with message "Wrong username or password."

### Host OS 

Rocky Linux

#### Nextcloud AIO version 

v1.2.0

#### Current channel 

latest

#### Other valuable info 

Similar to #419. Workaround suggested by @Lockness-Ko works:

```bash
sudo docker exec -it nextcloud-aio-nextcloud php occ user:resetpassword admin
```

The initial password was a long hexadecimal string. Is that the expected behavior?

**Comment by Kirk1984** [comment]
When i copied the password there was a space at the end.

**Comment by szaimen** [comment]
> Login failes with message "Wrong username or password."

I cannot reproduce this.

Can you please share the password here (since you seem to already have changed it)

And please also run `sudo docker inspect nextcloud-aio-nextcloud | grep ADMIN_PASSWORD` and post the output here. Thanks!

**Comment by tovrstra** [comment]
FYI, It's a known bug in Firefox, which has been around for eight years... https://bugzilla.mozilla.org/show_bug.cgi?id=1017407

**Comment by Kirk1984** [comment]
> FYI, It's a known bug in Firefox, which has been around for eight years... https://bugzilla.mozilla.org/show_bug.cgi?id=1017407

Thanks for info! Thats unfortunate.

**Comment by szaimen** [comment]
> There is a way to prevent this from happening, by changing the relevant bit of the HTML from
> 
> ```
>        Initial Nextcloud password: <b>199e58f92c0bf617144ae051ebe98f76f63c025f32070d20</b>
>                                                     <br><br>
>                                                 <a href="https://whatever.org" ...
> ```
> 
> into
> 
> ```
>        Initial Nextcloud password: <b>199e58f92c0bf617144ae051ebe98f76f63c025f32070d20</b><br><br><a href="https://whatever.org" ...
> ```
> 
> That is, by eliminating whitespace in the page source, double-clicking will not invisibly select it.

All right. Is this the only workaround that works?

**Comment by szaimen** [comment]
Okay, the suggested js fix looks crazy so I will rather see how to improve the html structure...
