### ISSUE TITLE
Nextcloud 24 release

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#669]
### What is missing for the Nextcloud 24 release?

- [x] at least the first point release is out
- [x] current target is 24.0.3

### Which apps are missing?
- [x] files_antivirus
- [x] nextcloud-aio (increase the max-version number and see if it works)
- [x] release of https://github.com/nextcloud/suspicious_login/issues/643
- [ ] release of https://github.com/nextcloud/talk_matterbridge/issues/69
- [x] maybe release of https://github.com/nextcloud/maps/issues/732
- [x] release of v1.1.1 of https://apps.nextcloud.com/apps/backup

### other things:
- [x] https://github.com/nextcloud/server/issues/32367
- [x] https://github.com/nextcloud/server/issues/32286
- [x] https://github.com/nextcloud/server/issues/32512
- [x] https://github.com/nextcloud/server/issues/32518
- [x] https://github.com/nextcloud/server/issues/32514
- [x] https://github.com/nextcloud/photos/issues/1111
- [x] https://github.com/nextcloud/photos/pull/1118

**Comment by devnoname120** [comment]
@szaimen What's missing to upgrade the docker image to v24? I'm interested in this fix: https://github.com/nextcloud/server/pull/31141

**Comment by szaimen** [comment]
It was backported to NC23 so should be already included in AIO...

**Comment by szaimen** [comment]
This is now released with 1.7.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
