### ISSUE TITLE
Wrong redirect from Nextcloud settings to aio if the aio is behind reverse proxy

### ISSUE THREAD

**Issue by 2020Sanoj** [nextcloud/all-in-one#673]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. set up Nextcloud AIO & set up Reverse Proxy over Nginx Proxy Manager (works)
2. set up a reverse proxy with https for the aio interface (to port 8080)
3. open the aio interface over the reverse proxy
4. start the conatiner
5. open nextcloud
6. open from the nextcloud settings the aio interface
7. you will get send to https://aio.domain:8000, so it places the correct domain and set the protocol to https, but it adds a port, which is not need and since the port is only open to localhost, it will time out, if I manually copy the URL and remove the port it works

### Expected behavior 
- It redirects to https://aio.domain:port (or no port if the port would be 443)

### Actual behavior 
- It redirects to https://aio.domain:8000

### Host OS 
- Debian 11

#### Nextcloud AIO version 
v1.2.1

#### Current channel 
beta

#### Other valuable info 
- removing :8000 in /var/lib/docker/volumes/nextcloud_aio_mastercontainer/_data/data/configuration.json, does not help because after a restart :8000 is added again

**Comment by szaimen** [comment]
Hello, does this help?
![Screenshot_20220519-184043_Brave](https://user-images.githubusercontent.com/42591237/169353437-993bb326-a3e8-4b5f-ab53-039ef1f9b6a8.png)

**Comment by 2020Sanoj** [comment]
No, I tested changing the domain, this worked, so in the mastercontainer configuration.json was the new domain and also on the Nextcloud overview, after restarting all containers over the aio interface from this domain on port 443. But the port :8000 was still in the config and in the url of the button in the Nextcloud overview, so both got the new domain, but kept the port :8000, but I've never opened the aio interface over port 8000

**Comment by szaimen** [comment]
Do I understand correctly that you are running the AIO interface behind a reverse proxy?

**Comment by 2020Sanoj** [comment]
Yes, also Behind the Nginx Proxy Manager

**Comment by szaimen** [comment]
All right. Let me investigate

**Comment by szaimen** [comment]
Before I try some workarrounds here, can you please add this `proxy_set_header X-Forwarded-Port 443;` under the custom nginx section and try to follow my provided steps again?

**Comment by 2020Sanoj** [comment]
Adding `proxy_set_header X-Forwarded-Port 443;` didn't help, but I've tried without a reverse proxy and there it changed the port, I've also tried to add `proxy_set_header X-Forwarded-Port 443;` directly into the nginx location block, but this also don't help

**Comment by szaimen** [comment]
Okay thanks for trying. I guess we need to add a hack then in the codebase for now...

The logic will work like this: if port 8000 is discocered by the function, we will change the port 443.

**Comment by 2020Sanoj** [comment]
Yes, this seems to be the best solution,
I've tried to add this header directly into my nginx proxy manager fork, I use, but it still does not work
https://github.com/SanCraftDev/nginx-proxy-manager/commit/70f9f27697427f731c9e7f05bac3b9055f2918ad
https://github.com/SanCraftDev/nginx-proxy-manager/commit/dc7fb272bc3735a7efe5d3c6c6edc2973dfac984

**Comment by szaimen** [comment]
Hello, this is now released with 1.3.0 Beta. Feel free to try it out and report back! Thank you! :)
See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

**Comment by 2020Sanoj** [comment]
> Hello, this is now released with 1.3.0 Beta. Feel free to try it out and report back! Thank you! :) See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel

Hello, thank I've updated this second straight after I got the notification about the new release and everything is now working, it opens the aio on port 443 from the nextcloud admin overview. Thanks!
