### ISSUE TITLE
Allow to back up additional, custom directories

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#695]
- https://github.com/nextcloud/all-in-one/blob/3beba0e1a89c6a7837248afb5bc50f64aa56a688/Containers/borgbackup/backupscript.sh#L134
- https://github.com/nextcloud/all-in-one/blob/3beba0e1a89c6a7837248afb5bc50f64aa56a688/Containers/borgbackup/start.sh#L40
- https://github.com/nextcloud/all-in-one/blob/3beba0e1a89c6a7837248afb5bc50f64aa56a688/Containers/borgbackup/backupscript.sh#L166-L168
- https://github.com/nextcloud/vm/blob/a6a69671801fb413f0ea0d7e546c9380ee40581a/not-supported/borgbackup.sh#L504-L511
- https://github.com/nextcloud/vm/blob/a6a69671801fb413f0ea0d7e546c9380ee40581a/not-supported/borgbackup.sh#L525-L526
- allow everything except root. (but give good example like /mnt/drive or so...)
- How could multiple be allowed? (via new line)
- Say that this is only supported on linux?
- make it available via GUI?
- say that these will not be automatically restored upon restore, implement a check that it is not allowed to be equal to ncdatadir and/or backupdir?
- say that only one mount will be backed up
- even volumea could be allowed...

**Comment by R7JANV1** [comment]
Great! That's what I'm looking for.

Possibly interesting for offshore backup!?

**Comment by szaimen** [comment]
> Possibly interesting for offshore backup!?

No, this is only about the daily backup.

**Comment by szaimen** [comment]
This is now released with v2.0.0 Beta. Testing and feedback is welcome! See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel
