### ISSUE TITLE
Does not work when DNS name also points to IPv6 AAAA record

### ISSUE THREAD

**Issue by gurubert** [nextcloud/all-in-one#705]
When the DNS name for the new instance has an A and an AAAA record the setup does not work.

It looks like the nextcloud-aio-domaincheck container is not able to retrieve the Let's Encrypt certificate correctly.

Removing the AAAA record and starting again with the deployment works.

**Comment by szaimen** [comment]
Hello, what was the error message for you?

**Comment by gurubert** [comment]
The browser was not able to establish a secure connection as the server was not presenting any certificate at all.

**Comment by gurubert** [comment]
Ah, sorry. To be more specific: The AIO process went through until all containers have been started.

I was presented with the fresh admin credentials and tried to open the NextCloud web interface on port 443. The certificate for this connection was missing.

**Comment by szaimen** [comment]
All right. Can you post the apache contauner logs here?

**Comment by gurubert** [comment]
Sorry, these have already been removed.

**Comment by szaimen** [comment]
I fear without them it is not possible to debug this...

**Comment by szaimen** [comment]
No, that did not work but you should be able to enable ipv6 support by following https://docs.docker.com/config/daemon/ipv6/. Then creating a new aio instance should probably be able to support ipv6...

**Comment by gurubert** [comment]
Maybe this should be an entry in the FAQ that IPv6 is not supported by default.
