### ISSUE TITLE
Internal network does block inbound and outbound connections

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#715]
See https://github.com/portainer/portainer/pull/4514/files

**Comment by szaimen** [comment]
For anyone that is affected by this. You can fix this by:
1. Stopping all containers from the aio interface
2. Run `sudo docker container prune`
3. Run `sudo docker network disconnect nextcloud-aio nextcloud-aio-mastercontainer`
4. Run `sudo docker network rm nextcloud-aio`
5. Run `sudo docker network create nextcloud-aio`
6. Start all container again from the AIO interface

**Comment by apbarratt** [comment]
<img width="1680" alt="Screenshot 2022-05-26 at 12 02 23" src="https://user-images.githubusercontent.com/642320/170475720-d9975ba6-2548-40fd-8c16-d81cb27f14bb.png">

Clicking the `Start and enable containers` button does nothing and nothing appears in the network or console tabs when doing so either.
