### ISSUE TITLE
Move/Import from existing Nextcloud

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/all-in-one#73]
Hey there,

we do have an existing nextcloud instance. It could be interesting for us to switch to AIO, since we would then profit from the talk high performance backend.

I now wonder, how we would move our existing data (files/calendars/deck/talk and more) and also our https://apps.nextcloud.com/apps/user_sql implementation. Is there something specific? Can you lead the way and maybe also add a few lines to your documentation?

Best

**Comment by szaimen** [comment]
Hello, thanks for your interest in this project!

An import of an existing Nextcloud is unfortunately not easily doable as it involves many steps and is additonally also very hard to automate. 

I could try to start a PR with some steps. Are you interested in this? 

I am not sure if you will be able to use the user_sql app though as you will need to make sure that the nextcloud container is able to communicate with the external database. Or did you store the user infos in the same table that Nextcloud uses? Also, I fear you will only be able to migrate from an instance that already uses postgresql or you migrate to that beforehand and do a database export that that you can use for importing here.

Please tell me if you are still interested then! :)

**Comment by happyreacer** [comment]
> Hey there,
> 
> we do have an existing nextcloud instance. It could be interesting for us to switch to AIO, since we would then profit from the talk high performance backend.
> 
> I now wonder, how we would move our existing data (files/calendars/deck/talk and more) and also our https://apps.nextcloud.com/apps/user_sql implementation. Is there something specific? Can you lead the way and maybe also add a few lines to your documentation?
> 
> Best

That would be super. However, I fear that this is not so easy, as already described. 
A good start would be to include the "data" directory of an existing Nextcloud instance in the nextcloud-aio.

**Comment by szaimen** [comment]
I've just added some documentation on this in #85.
Feel free to try that out. Feedback is welcome! :)
See https://github.com/nextcloud/all-in-one/blob/main/migration.md

**Comment by Tomptez** [comment]
@szaimen This is great! Does this method support encrypted data? Would be great to clarify that in the document.

**Comment by szaimen** [comment]
After thinking about this a bit longer, I think you should be able to use the user_sql app also with AIO. Added some docs on this: https://github.com/nextcloud/all-in-one#user_sql
