### ISSUE TITLE
won't run on Mac OS Docker Desktop

### ISSUE THREAD

**Issue by mas0nwest** [nextcloud/all-in-one#732]
used --volume /var/run/docker.sock.raw:/var/run/docker.sock:ro for Mac OS but getting "docker: invalid reference format"

more info:
Am on Mac OS 10.15.7 Catalina, Docker desktop 4.8.2, Engine 20.10.14
My steps:

install via curl -fsSL get.docker.com | sudo sh got an error and to download docker desktop
installed docker desktop via website (and changed disk image location to my external raid system)
used "sudo docker run -it \ --name nextcloud-aio-mastercontainer \ --restart always \ -p 80:80 \ -p 8080:8080 \ -p 8443:8443 \ --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \ --volume /var/run/docker.sock.raw:/var/run/docker.sock:ro \ nextcloud/all-in-one:latest" and get error docker: invalid reference format.
See 'docker run --help'

**Comment by mas0nwest** [comment]
Am on Mac OS 10.15.7 Catalina, Docker desktop 4.8.2, Engine 20.10.14
My steps:
1. install via curl -fsSL get.docker.com | sudo sh got an error and to download docker desktop
2. installed docker desktop via website (and changed disk image location to my external raid system)
3. used "sudo docker run -it \ --name nextcloud-aio-mastercontainer \ --restart always \ -p 80:80 \ -p 8080:8080 \ -p 8443:8443 \ --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \ --volume /var/run/docker.sock.raw:/var/run/docker.sock:ro \ nextcloud/all-in-one:latest" and get error docker: invalid reference format.
See 'docker run --help'

**Comment by mas0nwest** [comment]
> Can you try:
> 
> ```
> # For x64 CPUs:
> sudo docker run -it \
> --name nextcloud-aio-mastercontainer \
> --restart always \
> -p 80:80 \
> -p 8080:8080 \
> -p 8443:8443 \
> --volume nextcloud_aio_mastercontainer:/mnt/docker-aio-config \
> --volume /var/run/docker.sock.raw:/var/run/docker.sock:ro \
> nextcloud/all-in-one:latest
> ```

Awesome,this fixed it! What did you change?

**Comment by szaimen** [comment]
> Awesome,this fixed it! What did you change

Nothing. You just used the wrong command.
