### ISSUE TITLE
Please add security header Permissions-Policy

### ISSUE THREAD

**Issue by MatejKovacic** [nextcloud/all-in-one#733]
Please add security header `Permissions-Policy`. More about that here:
https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/

also, please consider sending `Referrer-Policy "strict-origin"` security header.

**Comment by szaimen** [comment]
This needs to be implemented in Nextcloud itself. Please report this to https://github.com/nextcloud/server. Thanks!

**Comment by MatejKovacic** [comment]
OK, did that: https://github.com/nextcloud/server/issues/32607

Hope someone will listen. :)
