### ISSUE TITLE
Only use the talk docker image

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/all-in-one#74]
Hi, 
would it be possible to use only the talk HPB docker?
And setup the nextcloud, collabora myself?
Thanks a lot!

**Comment by szaimen** [comment]
Hi there, in theory, yes. 
See https://github.com/nextcloud/all-in-one/blob/c203ad65ef32531ae700a9b2cfce6fcf7d7103ee/php/containers.json#L162-L186
https://github.com/nextcloud/all-in-one/blob/c203ad65ef32531ae700a9b2cfce6fcf7d7103ee/Containers/nextcloud/entrypoint.sh#L250-L262
But it is not guaranteed that the internal config will not change anymore in the future.

**Comment by szaimen** [comment]
Please close this issue if it answers your question. Thanks! :)
