### ISSUE TITLE
Update notification spam

### ISSUE THREAD

**Issue by 2020Sanoj** [nextcloud/all-in-one#753]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. wait for an aio update
2. wait for update notifications

### Expected behavior 
one notification
### Actual behavior 
many notifications

### Host OS 
debian 11

#### Nextcloud AIO version 
v1.3.0
#### Current channel 
beta
#### Other valuable info 
![grafik](https://user-images.githubusercontent.com/75573284/170776393-ddd53138-8e97-4b37-9e25-c835f9d9d7ba.png)

**Comment by szaimen** [comment]
Thanks for the report! Can you please post the output of `sudo docker exec -it nextcloud-aio-nextcloud php /var/www/html/occ user:list`?

**Comment by 2020Sanoj** [comment]
```
  - David: David *** ***
  - Jonlp00: *** ***
  - Sanoj: Jonas L***
  - Theo: Theo ***
```

**Comment by 2020Sanoj** [comment]
Just a note, all 14 notifications are about the aio containers, so two notifications per aio container

**Comment by szaimen** [comment]
Hi, can you maybe post the mastercontainer logs of when this problem happens? This will help understanding why this happens. Thank you! :)

**Comment by 2020Sanoj** [comment]
Yes, when the next update gets released

**Comment by szaimen** [comment]
I think I found the problem. Will be fixed in 759.
