### ISSUE TITLE
Unchanged container name gives "using a different name is not supported" error

### ISSUE THREAD

**Issue by philipdistefano** [nextcloud/all-in-one#767]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Minimally edit docker-compose.yml (container name unchanged)
2. use docker compose up -d
3. Receive error in logs "It seems like you did not give the mastercontainer volume the correct name?
Using a different name is not supported!" and container continuously restarts

### Expected behavior 
Container should start successfully without error.

### Actual behavior 
docker compose logs nextcloud-aio-mastercontainer shows the follow error log:

Trying to fix docker.sock permissions internally...
Creating docker group internally with id 998
It seems like you did not give the mastercontainer volume the correct name?
Using a different name is not supported!
It seems like you did not give the mastercontainer volume the correct name?
Using a different name is not supported!
It seems like you did not give the mastercontainer volume the correct name?
Using a different name is not supported!
It seems like you did not give the mastercontainer volume the correct name?
Using a different name is not supported!
It seems like you did not give the mastercontainer volume the correct name?
Using a different name is not supported!
It seems like you did not give the mastercontainer volume the correct name?
Using a different name is not supported!
It seems like you did not give the mastercontainer volume the correct name?
Using a different name is not supported!

### Host OS 
Ubuntu 20.04.1 LTS

#### Nextcloud AIO version 
latest

#### Current channel 
Error during container setup, cannot retrieve this data

#### Other valuable info 
Screenshot of my docker-compose.yml file:
![nc_aio_error](https://user-images.githubusercontent.com/103964399/171050663-f9ea2342-cfc5-499e-a66b-016d549e8e53.PNG)

**Comment by szaimen** [comment]
Yes, this is indeed simply not supported

**Comment by philipdistefano** [comment]
What isn’t supported? I didn’t change the container name.

**Comment by philipdistefano** [comment]
> Yes, this is indeed simply not supported

What isn’t supported? I didn’t change the container name.

**Comment by szaimen** [comment]
Not using a volume

**Comment by philipdistefano** [comment]
> Not using a volume

Do you mean the NEXTCLOUD_MOUNT variable?

If so, I just uncommented it and pointed it to /media on my host, and the same error occurs.

**Comment by szaimen** [comment]
No, I mean where /mnt/docker-aio-config gets mounted. It needs to be mounted inside the nextcloud_aio_mastercontainer volume.

**Comment by philipdistefano** [comment]
> No, I mean where /mnt/docker-aio-config gets mounted. It needs to be mounted inside the nextcloud_aio_mastercontainer volume.

Would you mind elaborating?  I copied this straight from the example docker-compose.yml located at https://github.com/nextcloud/all-in-one/blob/main/docker-compose.yml.

**Comment by szaimen** [comment]
basicaly this line is not allowed to be changed:
https://github.com/nextcloud/all-in-one/blob/7ba10559fd11bf083acbc7e833d90882562766c4/docker-compose.yml#L13

**Comment by szaimen** [comment]
clear enough?

**Comment by philipdistefano** [comment]
Oooooh, yes!  Thank you, it works now.  Appreciate the help and quick responses!
