### ISSUE TITLE
increase the PHP OPcache cache buffer

### ISSUE THREAD

**Issue by twwd** [nextcloud/all-in-one#772]
I'm using the latest Nextcloud all-in-one and Nextcloud warns me on the page _Administration_ → _Overview_, that

> * The PHP OPcache module is not properly configured. See the [documentation ↗](https://docs.nextcloud.com/server/23/go.php?to=admin-php-opcache) for more information.
>    * The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply opcache.interned_strings_buffer to your PHP configuration with a value higher than 16.

![Screenshot Admin Overview Opcache Warning](https://user-images.githubusercontent.com/8222565/171219126-11522aa1-b477-4305-8a51-6948f58ef743.png)

So probably the value [here](https://github.com/nextcloud/all-in-one/blob/main/Containers/nextcloud/Dockerfile#L88) should be increased. But to which one? The [docs](https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#enable-php-opcache) specify no value for this config.

**Comment by szaimen** [comment]
Cc @MichaIng should we try to increase it to 32 or is this not recommended?

Maybe we should indeed not show the warning anymore if a certain threshold is reached?

**Comment by MichaIng** [comment]
See my comment on the PR: https://github.com/nextcloud/all-in-one/pull/791#issuecomment-1154065135

Sorry for being too late 😅 .
