### ISSUE TITLE
documentation - docker from get.docker.com vs. distribution package source

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/all-in-one#80]
In README.md i found that the user can (must) install Docker from get.docker.com .
Is this ever the correct way? 

If not perhaps the documentation can be optimized for beginners, experts, ....

**Comment by szaimen** [comment]
Hi there 👋,

Installing docker from get.docker.com has the following reasons:
1. having one command that works on almost all distributions
2. not having to document the exact command for all distributions (kind of the same like point 1)
3. Making sure that everyone runs at least docker api version 1.41 which we need internally: https://github.com/nextcloud/all-in-one/blob/9ee27cb7633b3931a2d7ebc6eabb5a0a35ad1c65/php/src/Docker/DockerActionManager.php#L21

Do you think we should document the reasons behind this in the FAQ section?

**Comment by devnull4242** [comment]
Thank you. If possible i use software direct from my distribution.
But because of version 1.41 it is no option.
The perhaps the documentation must not been changed.

**Comment by szaimen** [comment]
Thanks for your feedback!
