### ISSUE TITLE
Ways to adujst: data-directory / logging / https required

### ISSUE THREAD

**Issue by biggoof1** [nextcloud/all-in-one#81]
Hi there,

just some questions to check, if nextcloud aio can be adjusted to my scenario.
First of all, thank you so much for this initiative. This really helps normal users to set up an optimized nextcloud environment.
It in general includes exactly what I was looking for.
Some adjustments would have to be done by me to be able to run it in my environment.
Are there switches for that already or planned for the future?

1. Nextcloud data directory
    Nextcloud aio is to run on a SSD whereas the data is to be stored on a large HDD. Therefore I would have to adjust the data directory for the nextcloud container (residing outside of the container). 
   Is there a way to change the directory yet? Manual interaction with the container would be lost after an upgrade using the master container, I assume.
2. Keep http instead of https for internal networks (reverse proxy)
    I use a reverse proxy. Concerning this topic there seems to be sth going on already. But for testing I didn´t want to allow access from the internet. So the server is not accessible for the certificate generation. In that case the setup using aio will fail. Is there any way around that at the moment?
3. Adjust logging for fail2ban setup
   Using the reverse proxy to control access to the network the reverse proxy hosts the fail2ban instance.
   Therefore I would have to delegate the nextcloud log to the reverse proxy (rsyslog).
   Is there a way to accomplish this setup already?

Thanks for your help and once again thanks for your work!!

Greetings,
Christian

**Comment by szaimen** [comment]
Hello, thanks for your interest in this project!

I'll try to answer your questions:
regarding 1.: You can move your files to a different drive by moving the whole docker lib to a different drive. I'll add some docs on this.

regarding 2.: We'll make it possible to run this behind a reverse proxy sometime in the future. See https://github.com/nextcloud/all-in-one/issues/72

regarding 3.: I don't think that we'll add support for this but feel free configure your AIO Nextcloud to log to rsyslog instead. Maybe that already works?

**Comment by szaimen** [comment]
> * regarding 1.: You can move your files to a different drive by moving the whole docker lib to a different drive. I'll add some docs on this.

Added with https://github.com/nextcloud/all-in-one/pull/84.

**Comment by szaimen** [comment]
I'll close this now since everything is answered/solved/tracked in another issue.
