### ISSUE TITLE
Make collabora work behind Apache and Nginx

### ISSUE THREAD

**Issue by charredchar** [nextcloud/all-in-one#834]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install Nextcloud AIO following the steps in `readme.md`. Enable the Collabora container from the AIO Interface.
2. Open any .docx or .odt file.

### Expected behavior 
Collarbora/Nextcloud Office loads the file in the browser

### Actual behavior 
I receive an error, "Document Loading failed. Failed to load Nextcloud Office - please try again later"

### Host OS 
Ubuntu Server 20.04 in a Windows Server Hyper-V VM.

#### Nextcloud AIO version 
Nextcloud AIO v1.4.0

#### Current channel 
Latest, attempted Beta with the same results.

#### Other valuable info 
I am currently running Nextcloud through an Apache Reverse Proxy located on another VM. I followed the setup under `reverse-proxy.md`  including the VirtualHosts and startup command. Everything except for Collabora works perfectly as expected.
I wouldn't mind testing without a reverse proxy at all, using just the server IP, for testing but I couldn't get through the AIO setup without a domain entered.
I've tried it in Edge, Chrome and Firefox. Adblock disabled.

AIO Apache Log; https://pastebin.com/7VNKQw29
AIO Nextcloud Log; https://pastebin.com/NcnBpz4C
Chrome Console while loading file; https://pastebin.com/YRxkR55L
AIO Collabora log is too large for Pastebin.

**Comment by szaimen** [comment]
@Cr0iX am I correct that you are running AIO behind Apache? If yes, is it possible for you to reproduce this issue?

**Comment by Cr0iX** [comment]
> @Cr0iX am I correct that you are running AIO behind Apache? If yes, is it possible for you to reproduce this issue?

I have just tried to run nextcloud-aio with collabora instead of onlyoffice, and i can confirm that the error "Document loading failed" is back. I've tried both .odt and .docx, and both have the same error.

Pulling the updates to see if stuff changes.
Still same error with latest docker versions.

**Comment by szaimen** [comment]
I see. Thanks for providing the log!

Can you check if adding `ProxyPreserveHost On` makes it work? 
Thank you!

**Comment by Cr0iX** [comment]
It doesn't. I already had that in my config.

**Comment by szaimen** [comment]
Thanks! No idea how to work around this then...

**Comment by szaimen** [comment]
Yan you send your browser console logs when opening the document?

**Comment by szaimen** [comment]
I see @charredchar already provided this info...

**Comment by szaimen** [comment]
It seems like simply websockets do not work as intended...

**Comment by crocobc** [comment]
Hi there, just for information maybe it can help..

I had same error on Collabora at fresh install. The ONLY way i make it work is with a TRUE certificate (no self-signed...)

Maybe you can test is you use self-signed certificate.

I used true certificate (letsencrypt) with reverse proxy (haproxy) in another VM like you.

Regards

**Comment by szaimen** [comment]
No, we only use certificates from letsencrypt here so this should not be the problem...

**Comment by szaimen** [comment]
Somehow the websocket connection seems to fail. This seems to be caused by collabora not sending the `upgrade websocket` header nor the `connection upgrade` variable. But I may be wrong here since this would probably mean that it would fail behind other reverse proxies, too...

**Comment by charredchar** [comment]
> I see. Thanks for providing the log!
> 
> Can you check if adding `ProxyPreserveHost On` makes it work? Thank you!

I have this enabled already as well, as it is part of the config on the `reverse-proxy.md` doc.



> Hi there, just for information maybe it can help..
> 
> I had same error on Collabora at fresh install. The ONLY way i make it work is with a TRUE certificate (no self-signed...)
> 
> Maybe you can test is you use self-signed certificate.
> 
> I used true certificate (letsencrypt) with reverse proxy (haproxy) in another VM like you.
> 
> Regards

I have true certificates using LetsEncrypt with all subdomains through my Apache reverse proxy. I don't know what Nextcloud might be doing on the backend though as attempting to connect to IP:Port just forwards to my domain address anyway.

Should Collabora be accessible through IP:Port as well? I can not seem to access it.

**Comment by szaimen** [comment]
> Should Collabora be accessible through IP:Port as well? I can not seem to access it.

No it shouldn'. It should just work without any additional work hich is not the case because something does not work as expected with the apache reverse proxy documentation. 

However curently not sure what to change to make it work.

**Comment by bentwnghk** [comment]
In order for Collabora to work behind Apache, it has to be in a separate (sub)domain and with its own configuration in Apache reverse proxy. So, if you access your Nextcloud server at "xyz.com", you need to point Collabora to "sub.xyz.com" and configure a separate virtual host in Apache.

```
<VirtualHost *:443>
    ServerName sub.xyz.com
    SSLEngine on
    SSLCertificateFile [path to your ssl cert]
    SSLCertificateChainFile [path to your ssl chain file]
    SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
    SSLCipherSuite EECDH+CHACHA20:EECDH+AES
    AllowEncodedSlashes NoDecode
    SSLProxyEngine On
    SSLProxyVerify None
    SSLProxyCheckPeerCN Off
    SSLProxyCheckPeerName Off
    ProxyPreserveHost On
    ProxyPass           /browser http://[your nextcloud ip address]:11000/browser retry=0
    ProxyPassReverse    /browser http://[your nextcloud ip address]:11000/browser
    ProxyPass           /hosting/discovery http://[your nextcloud ip address]:11000/hosting/discovery retry=0
    ProxyPassReverse    /hosting/discovery http://[your nextcloud ip address]:11000/hosting/discovery
    ProxyPass           /hosting/capabilities http://[your nextcloud ip address]:11000/hosting/capabilities retry=0
    ProxyPassReverse    /hosting/capabilities http://[your nextcloud ip address]:11000/hosting/capabilities
    ProxyPassMatch "/cool/(.*)/ws$" ws://[your nextcloud ip address]:11000/cool/$1/ws nocanon
    ProxyPass   /cool/adminws ws://[your nextcloud ip address]:11000/cool/adminws
    ProxyPass           /cool http://[your nextcloud ip address]:11000/cool
    ProxyPassReverse    /cool http://[your nextcloud ip address]:11000/cool
</VirtualHost>
```


And don't forget to go to Nextcloud Settings > Nextcloud Office, and change the URL of Collabora Online server to "https://sub.xyz.com/"

The only issue left is, the URL you enter in Nextcloud Settings will fall back to "https://xyz.com/" when the dockers restart (if you have configured automatic backup and updates).

Any chance this issue could be solved?

**Comment by bentwnghk** [comment]
I was just trying to share how I got it to work. It would be perfect if a subdomain is not needed, as this would solve the issue I mentioned above :-)

**Comment by SamuXzX** [comment]
What can we provide to try to identify the problem?

**Comment by szaimen** [comment]
> What can we provide to try to identify the problem?

You can try to improve the reverse proxy documentation for Apache that makes Collabora that is bundled within AIO work.

**Comment by SamuXzX** [comment]
Do you confirm that you referred to this guide to set up a Collabora docker container?
[https://collabora-online-for-nextcloud.readthedocs.io/en/latest/install/](https://collabora-online-for-nextcloud.readthedocs.io/en/latest/install/)

**Comment by szaimen** [comment]
Seems like there is now a problem with Nginx, too. We could try to downgrade the collabora container and see if it fixes the issue. Do you remember with which AIO version it worked the last time?

**Comment by szaimen** [comment]
If I remember cotrectly, it used to work before the aio 1.4.0 update which included a collabora upgrade. I'll try to verify this week if using the `21.11.4.2.1` image works. If yes I will see if it is possible to downgrade.

**Comment by ckauhaus** [comment]
Any news on this? I have the same problem here, and I cannot get Collabora working on AIO at all :-(

**Comment by karlemilnikka** [comment]
Just to chime in (in case it helps with the troubleshooting). I ran three test-installs of the AIO, and Collabora worked just as it should every time. After restarting the servers however, I just got the error message “Document Loading failed” when trying to open or create a new document. Everything looked like it should be working from both the Settings pages and Nextcloud AIO container overview.

**Comment by karlemilnikka** [comment]
Please ignore my [previous comment](https://github.com/nextcloud/all-in-one/issues/834#issuecomment-1215450676). My issue is not related. My issue only occurs when I install Nextcloud AIO with IPv6 enabled, not running with IPv4 exclusively. I’ll create a ticket with more information regarding this if I find a solution or what’s causing it.

**Comment by albert-gee** [comment]
Collabora has changed their settings, here is the solution: https://help.nextcloud.com/t/solved-another-failed-to-load-collabora-online-please-try-again-later-problem/111473/39?u=esmailelbob
Can it be applied to AIO?

**Comment by szaimen** [comment]
> https://help.nextcloud.com/t/solved-another-failed-to-load-collabora-online-please-try-again-later-problem/111473/39?u=esmailelbob

This is already applied and working with all documented reverse proxies except Apache. I haven't figured out a way what needs to be changed in the Apache reverse proxy config in order to make it work. Your help in doing so is very welcome!

**Comment by SamuXzX** [comment]
We can't improve the config if we don't know what's the problem. We need some logs

**Comment by szaimen** [comment]
So, I made multiple attempts to find a working Apache config for this but everytime it fails to establish the websocket connection. I'll see together with @juliushaertl if we find the reason and a solution to this.

**Comment by Heggeg** [comment]
i have nextcloud-aio running behind nginx-proxy-manager with lets encrypt certificate. 

I also have the problem in the admin settings that nextcloud thinks it can't connect to the Collabora Online server.

As soon as I adjust the URL to access it without reverse proxy the settings turn green. (http://IP:11000) But it still does not work after you press save the settings are red again and it complains that different protocols are used. (http/https)

**Comment by TheManchineel** [comment]
This is still a problem for me, on NGINX as well. The issue concerning NGINX has been closed for some reason. Any guidance?

**Comment by szaimen** [comment]
> NGINX as well.

Ah interesting! I didn't know.

**Comment by TheManchineel** [comment]
Sample request in browser console:

```GET wss://example.com/cool/https://example.com/index.php/apps/richdocuments/wopi/files/73_och226abshji?access_token=XXXX&access_token_ttl=0&permission=edit/ws?WOPISrc=https://example.com/index.php/apps/richdocuments/wopi/files/73_och226abshji&compat=/ws```

returns HTTP status code 400 (bad request)

**Comment by Zoey2936** [comment]
That's interesting, I run it behind my fork of the Nginx-Proxy-Manager and here collabora is working without problems.

**Comment by szaimen** [comment]
to everyone that has problems with it: is everyone that has problems with it not running the reverse proxy on the same server?

**Comment by TheManchineel** [comment]
@szaimen I'm using Unraid so you're not "supposed" to run a RP on the host. Nextcloud AIO is on the host's own Docker daemon (thus it's running bare-metal), while the reverse proxy is an NGINX instance running on an Ubuntu 22.04 VM (KVM). I'm using the host's IP for the reverse proxy upstream server, which the VM accesses over the virtio network bridge (both VM and host have an IP in the same subnet, I'm using a single NIC).

**Comment by Cr0iX** [comment]
@szaimen I'm running it on the same vm. Apache reverse proxy on host and nextcloud in docker

**Comment by Nackophilz** [comment]
Same here 

NextCloud AIO is behind Nginx Proxy Manager, all work well instead off Collabora, am unable to connect the app with NextCloud Office config page :/

**Comment by szaimen** [comment]
Hello, I finally found a way to fix it for Apache! The documentation was redone with https://github.com/nextcloud/all-in-one/pull/1236 and I could verify that it works with Apache now.
See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md#apache. As for nginx or npm, please open a new issue for that. Thanks!

**Comment by Zoey2936** [comment]
Maybe change this line: https://github.com/nextcloud/all-in-one/blob/0bbae775c625e8f42169495cc4b468951b458611/reverse-proxy.md?plain=1#L24 ?

**Comment by szaimen** [comment]
good idea. will remove the issue from the doc
