### ISSUE TITLE
Document how to run multiple instances

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#854]
Usual way: add multiple vms, install aio in each one ij reverse prox mode, use a reverse proxy in front.

---

Maybe possible: add multiple users, install docker rootless for each, install aio for each of them in reverse proxy mode, use a reverse proxy in front.
- [x] needs https://github.com/nextcloud/all-in-one/issues/734 to work correctly
- [x] todo: maybe reorder steps: e.g. create as many users as you need instances, install docker rootless in specific way, create one user that runs the reverse proxy, install aio in specific way...
- [x] should document `loginctl enable-linger USERNAME` in the docker rootless documentation so that systemd user files get executed/started automatically upon reboot

**Comment by szaimen** [comment]
Okay, seems like this should indeed work.

Basically:
1. install docker rootles on your normal account (privileged ports do not need to be exposed)
2. install aio in reverse proxy mode (8080:8080 and apache_port=11000 and talk_port=3478).
3. create an additional normal account with adduser...
4. logout
5. login with the new user
6. install docker rootless for that account (privileged ports do not need to be exposed)
7. install aio in reverse proxy mode but use e.g. 8081:8080 and apache_port=11001 and talk_port=3479
8. set up a a reverse proxy e.g. with an additional user and additional docker rootless install but expose privileged ports
9. add an entry to the reverse proxy for each instance and point to the correct apache_port.
10. enter the domain for each aio instance and you should be ready to go.

If you want further instances, you can add them by simply adding further users with docker rootless installs and increasing the used port for the aio interface and apache_port and talk_port.

Obviously backups must be done to different locations and permissions set correctly and if Nextcloud_datadir or nextcloud_mount is adjusted, the same.

**Comment by szaimen** [comment]
Here a screenshot: 
![image](https://user-images.githubusercontent.com/42591237/175183696-426284bd-f53e-4981-b893-c075c47adfde.png)

**Comment by Kirk1984** [comment]
Too early and too fast ;)

Thats awesome! Should i test this or is this a done deal? My pi is still up for testing.

**Comment by szaimen** [comment]
> Thats awesome! Should i test this or is this a done deal? My pi is still up for testing.

I already verified that it works but feel free to do so as well :)

Note that talk will not work for both at the same time currently as changing the port is currently not possible: https://github.com/nextcloud/all-in-one/issues/734

**Comment by johnnyq** [comment]
Fantastic! I will test this as well. This will be nice as I don't have to have a separate VM for each instance of Nextcloud and waste another public IP address.

Really looking forward to this thanks again @szaimen

**Comment by szaimen** [comment]
For everyone interested, I just created https://github.com/nextcloud/all-in-one/blob/enh/854/multiple-aio-instances/multiple-instances.md. Feedback is welcome! :)

**Comment by Kirk1984** [comment]
So the thing is this: i wanted to test this. But then i discovered home assistant can control my smartfan. And now my 4gb and 8gb rpis are in production. And my 2gb will most likely not handle 2 instances. I will try it out in a VM tomorrow (if virtualbox allows it).
