### ISSUE TITLE
Auto Update AIO

### ISSUE THREAD

**Issue by jeremyoha450** [nextcloud/all-in-one#860]
Hi there

how can i setup auto update, so dont have to do it manually.

regards

**Comment by 2020Sanoj** [comment]
Just enabled the daily backup, while backing up, it will update

**Comment by jeremyoha450** [comment]
how and where do i do it?

**Comment by szaimen** [comment]
Here:

![signal-2022-06-01-00-34-19-268](https://user-images.githubusercontent.com/42591237/175494376-5344d042-318a-48ad-a8d0-3ccd20f26ba5.jpg)
