### ISSUE TITLE
AIO interface access

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#88]
After full install with valid tld & certs following the readme, the button "Open Nextcloud AIO Interface" proposes wrong URL : 

https://localhost:8000/api/auth/getlogin?token=xxxxxxxx

I can access the Interface with this link : 

https://ip-of-the-server:8080/containers

I think there are 2 wrong defaults : 

1. wrong port
2. wrong ip

Maybe I missed something ?

Thank you for this work which makes the complete installation of Nextcloud much easier and secure !
BR,
Marc

**Comment by szaimen** [comment]
Hello, thanks for your bugreport! This will be fixed with #89
