### ISSUE TITLE
Apache Container does not switch to running state

### ISSUE THREAD

**Issue by 2020Sanoj** [nextcloud/all-in-one#888]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Start Nextcloud AIO
2. Apache Container is always marked as starting
3. Nextcloud AIO can be used and apache and caddy are running
4. Apache Container is still marked as starting

### Expected behavior 
Nextcloud Apache Container is marked as running
### Actual behavior 
Nextcloud Apache Container is marked as starting

### Host OS 
Debian 11.3

#### Nextcloud AIO version 
v1.5.0

#### Current channel 
Beta
#### Other valuable info 
![grafik](https://user-images.githubusercontent.com/75573284/177180802-446ac06b-7d52-4b25-aa70-c823a0bda904.png)

```log
nc: getaddrinfo for host "nextcloud-aio-nextcloud" port 9000: Name or service not known
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
Waiting for Nextcloud to start...
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using fd00:dead:beef:c0:0:242:ac11:9. Set the 'ServerName' directive globally to suppress this message
{"level":"info","ts":1656946587.3192754,"msg":"using provided configuration","config_file":"/Caddyfile","config_adapter":""}
{"level":"warn","ts":1656946587.320852,"msg":"Caddyfile input is not formatted; run the 'caddy fmt' command to fix inconsistencies","adapter":"caddyfile","file":"/Caddyfile","line":2}
{"level":"info","ts":1656946587.3218882,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"warn","ts":1656946587.3222327,"logger":"http","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
{"level":"info","ts":1656946587.3223414,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0005ef2d0"}
{"level":"info","ts":1656946587.3231206,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/mnt/data/caddy"}
{"level":"info","ts":1656946587.3231692,"logger":"tls","msg":"finished cleaning storage units"}
{"level":"info","ts":1656946587.3233283,"msg":"autosaved config (load with --resume flag)","file":"/var/www/.config/caddy/autosave.json"}
{"level":"info","ts":1656946587.3233378,"msg":"serving initial configuration"}
```

**Comment by szaimen** [comment]
Hi, is it possible that the iptables may block the mastercontainer from communicating internally with the apache container?

If yes, we probably need to adjust the iptables command to be a bit more specific...

**Comment by szaimen** [comment]
I am refering to this: https://github.com/nextcloud/all-in-one/pulls

**Comment by 2020Sanoj** [comment]
This could be possible, I will remove the iptables rule and test it, but just a short question how does the mastercontainer check if the apache container is running?

**Comment by szaimen** [comment]
> just a short question how does the mastercontainer check if the apache container is running?

It checks if the port is internally reachable...

**Comment by szaimen** [comment]
> Yes, removing this firewall rule fixed it

Great! So the rule needs to be adjusted...

**Comment by szaimen** [comment]
Honestly, I dislike adding yet another environmental variable for ip-bindings for the apache container but @wabberz has a point that this is the much cleaner approach...

**Comment by szaimen** [comment]
See https://github.com/nextcloud/all-in-one/issues/889
