### ISSUE TITLE
caddy aborting with incomplete response

### ISSUE THREAD

**Issue by AetherCollective** [nextcloud/all-in-one#895]
Trying to migrate from one nextcloud instance to another, copying a bunch of media files to my nextcloud via Rclone, and I keep getting this error:

nextcloud-aio-apache.log:
```
{"level":"error","ts":1657153365.3401353,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"http2: stream closed"}
```

Nextcloud > Settings > Admin > Logging:
```
[no app in context] Error: Expected filesize of 11340736302 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 10962067456 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.

PUT /remote.php/dav/files/Emily/Shared/Movies/sample1.mkv
from 172.17.0.1 by Emily at 2022-07-07T00:45:58+00:00
```

rclone received this response:
```
2022-07-06 03:05:32 ERROR : Shared/Movies: error reading destination directory: couldn't list files: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>408 Request Timeout</title>
</head><body>
<h1>Request Timeout</h1>
<p>Server timeout waiting for the HTTP request from the client.</p>
<hr>
<address>Apache/2.4.53 (Debian) Server at emilyloveapp Port 8000</address>
</body></html>: 408 Request Timeout
```

**Comment by szaimen** [comment]
Hi, 

are you running AIO behind a reverse proxy and after what time does the timeout appear?

**Comment by EmilyLove26** [comment]
No I am not. I just port fowarded the ports and it worked as-is.

As for when, usually after transferring a large file

**Comment by szaimen** [comment]
Okay and does this timeout appear after approx. 1h?

**Comment by EmilyLove26** [comment]
I haven't been watching that carefully. It's a batch process that has been running for a few weeks and it just occasionally does this so tbh I'm not really sure when or what is triggering it

**Comment by EmilyLove26** [comment]
Any ideas?

**Comment by szaimen** [comment]
My idea is that the process is running into a timeout when trying to upload a very large file and it reaches the php timeout of 1h...

**Comment by szaimen** [comment]
I've created https://github.com/nextcloud/all-in-one/discussions/901 for a possible enhancement in the future.

**Comment by EmilyLove26** [comment]
One of the biggest problems is it takes forever for a sync to start. Multiple hours for 30753 folders and 245897 files. During the process where it tries to figure out if files have changed on the server, I get these timeouts even then

**Comment by szaimen** [comment]
I fear this is rather a desktop client bug then...

**Comment by EmilyLove26** [comment]
How can I verify rather it is client or server sided? What would you recommend?

**Comment by szaimen** [comment]
> I fear this is rather a desktop client bug then...

See e.g.https://github.com/nextcloud/desktop/issues/4424

**Comment by EmilyLove26** [comment]
Just to be clear, I'm not using virtual files
