### ISSUE TITLE
files_antivirus : RuntimeException: The antivirus executable could not be found at /usr/bin/clamscan

### ISSUE THREAD

**Issue by marcatsmci** [nextcloud/all-in-one#90]
Nextcloud AIO latest.

I have Clamav on my server and have installed **Antivirus for files** into AIO but the executable is not available for AIO...

Any way to run ClamAV in AIO ?

Thanks,
Marc

**Comment by szaimen** [comment]
Hello, clamav as optional addon will be adddeed with https://github.com/nextcloud/all-in-one/issues/78.

**Comment by marcatsmci** [comment]
> Hello, clamav as optional addon will be adddeed with #78.

Oops, sorry !
