### ISSUE TITLE
document how to run it with Portainer

### ISSUE THREAD

**Issue by szaimen** [nextcloud/all-in-one#934]
See https://github.com/nextcloud/all-in-one/discussions/932#discussioncomment-3140707

**Comment by R7JANV1** [comment]
Thank you very much! As a container or as a stack? (As a container would be great because then several AIOs can be operated more easily in parallel)

**Comment by szaimen** [comment]
As a stack. Multiple containers in one portainer installation does not work either way.

**Comment by R7JANV1** [comment]
> As a stack. Multiple AIO containers in one portainer installation does not work either way.
> 
> See [#854 (comment)](https://github.com/nextcloud/all-in-one/issues/854#issuecomment-1163802727)

Why won't that work? If I create two AIO containers and map the ports differently, shouldn't it work?

**Comment by 2020Sanoj** [comment]
> > As a stack. Multiple AIO containers in one portainer installation does not work either way.
> > See [#854 (comment)](https://github.com/nextcloud/all-in-one/issues/854#issuecomment-1163802727)
> 
> Why won't that work? If I create two AIO containers and map the ports differently, shouldn't it work?

No, because the two AIO containers would use the same docker volumes, which are static created through the docker socket and master container.

**Comment by R7JANV1** [comment]
Oh well, that makes sense, thanks!
