### ISSUE TITLE
Database dump import is not run for migration

### ISSUE THREAD

**Issue by eonrider** [nextcloud/all-in-one#964]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Follow migration instructions (https://github.com/nextcloud/all-in-one/blob/main/migration.md)
2. Try to log in as previously existing user.
3. Get told that the login doesn't work.

### Expected behavior 
I should be able to log in as one of the users that existed in the database I migrated from.

### Actual behavior 
I believe the database dump import is being skipped which leads to my login not succeeding. 

### Host OS 
Raspberry Pi OS Lite (64-bit)

#### Nextcloud AIO version 
Nextcloud AIO v1.5.0

#### Current channel 
`latest-arm64`

#### Other valuable info 
I did some debugging by stepping into the live database container. I suspect this is happening due to this line:
```
( ! [ -f "$DATADIR/PG_VERSION" ] && ( [ -f "$DUMP_FILE" ] || [ -f "$DUMP_DIR/export.failed" ] )
```
https://github.com/nextcloud/all-in-one/blob/v1.5.0/Containers/postgresql/start.sh#L32
File `PG_VERSION` exists so the predicate is false. `PG_MAJOR` and `PC_VERSION` are both `14` in my case.

**Comment by szaimen** [comment]
Did you run `sudo rm -r /var/lib/docker/volumes/nextcloud_aio_database/_data/*` in order to trigger the import?

And can you post the database container logs after the failed import?

**Comment by eonrider** [comment]
Thanks for pointing me to that line. I actually did get an error while running that:
```
rm: cannot remove '/var/lib/docker/volumes/nextcloud_aio_database/_data/*': No such file or directory
```

I deleted all the files and directories one by one and got the database dump import to start. Thanks!
