### ISSUE TITLE
postgres FATAL:  remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by GUNT0815** [nextcloud/all-in-one#966]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. run nextcloud-aio
2. produce some traffic on nextcloud e.g. by uploading 1000 small files
3. sudo docker logs -f nextcloud-aio-database -> will show "FATAL:  remaining connection slots are reserved for non-replication superuser connections"
4. connection to db is lost 

### Expected behavior 
nextcloud-aio can handle all necessary connections to the db

### Actual behavior 
see above 3 and 4

#### Nextcloud AIO version 

latest = [Nextcloud Hub II](https://nextcloud.com/) (23.0.6)

#### Current channel 

stable

#### Other valuable info 

![grafik](https://user-images.githubusercontent.com/66719836/180253392-a5dc5aaa-0cba-4a38-ab94-d6eb9f943848.png)

**Comment by szaimen** [comment]
Hi, thanks for your report! Did this happen after upgrading to the latest release or already before?

**Comment by GUNT0815** [comment]
I am using a fresh installation from scratch - no update has been run so far.

**Comment by MerlinB** [comment]
I am not able to replicate this anymore after rebooting my system with which I accessed nextcloud (not the server). No problem on other devices either. Maybe it was the frontend that spawned to many requests to the server?

**Comment by GUNT0815** [comment]
I did a reboot of the machine and restart of the containers and the error keeps occuring on heavy file transfers. I think this error is received from postgres and we need a different configruation of the db in nextcloud-aio re/ the max_connections allowed ...

**Comment by szaimen** [comment]
Honestly Nextcloud should simply not spawn as many database connections so this is likely a bug. Upgrading to NC24 may resolve this.

**Comment by GUNT0815** [comment]
One additional information from today:

- preview generation is running in the backgroud (manualy triggered) and paperbin for calendar entries is triggered to be emptied
- message in nextcloud protocol: "Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "nextcloud-aio-database" (172.26.0.4), port 5432 failed: FATAL: sorry, too many clients already"

IMHO I think in the standard configuration is to narrow for nextcloud.aio and you should think about a changed configuration of postgresql.

**Comment by szaimen** [comment]
I see so the preview generation may be the missing puzzle piece here...

However we will still try to upgrade to nc24 first and if the issue still exists afterwards we will try to increase the max connections value.

**Comment by szaimen** [comment]
Hi, please upgrade to 1.7.0 Beta and report back if it fixes the issue. See https://github.com/nextcloud/all-in-one#how-to-switch-the-channel If not, we will need to adjust the database config going forward. Thanks!

**Comment by MerlinB** [comment]
Updating seems to have fixed it for me.
