### ISSUE TITLE
Don't update the containers for the sake of updating

### ISSUE THREAD

**Issue by rekcodocker** [nextcloud/all-in-one#976]
Most recent update was minor version bumps and documentation upgrades.
Please.

Whenever there is an update, all client software starts mentioning this, on all devices. Every day. 

An update means the system is offline for a while, and every update is not 100% risk free either.

I would appreciate updates when they really fix or improve something. Quite often they feel just like a mid-development upgrade.

**Comment by szaimen** [comment]
If you would have read the changelog you would have seen that we indeed update the dependencies inside the containers regularly. So publishing them regularly is needed and no way around it. I also do not see why you complain about this. You should be lucky that this project is as good maintained. Also if you do not want to update manually, simply enable daily backups which also updates all your containers automatically.

**Comment by szaimen** [comment]
Also you may read this artice: https://about.gitlab.com/blog/2016/07/21/release-early-release-often/
